### ISSUE TITLE
Thorin-Oakenpants you become too soft.

### ISSUE THREAD

**Issue by Angelus35** [ghacksuserjs/ghacks-user.js#106]
Sorry dude, but I have to say it. Since the beginning of this year, I began to notice that you are remove (disabling) some important pref. I think it's all due to the fact that you're trying to please both the one and the other. But you can not play on both sides, otherwise both will suffer. Hardening (privacy and security) should be for you in the first place. You become too soft. In the end, you will ruin everything for what it was created.

**Comment by crssi** [comment]
@Angelus35, can you list those "some important pref" that were disabled?

**Comment by Thorin-Oakenpants** [comment]
Please remember that this is a "medium" (but I always try to err on the side of security, privacy, anti-FP in that order) TEMPLATE. It's actually *almost* a pretty damn hardened version (I do not see it as middle-of-the-road at all). Read around the comments in places like reddit FWIW, or use google, and loads of people saying this is too hard, breaks too much stuff. People moaning about TP/SB being turned off (in favor of uBo), people complaining that they suddenly can't log in on sites etc. People bitching about their urlbar doorhangers, and so on. However, that is irrelevant when you consider than since day one it can been called a template.

Consider that this "medium" branch (which takes some site breakage into account), is actually, in many ways *more hardened* than so called *hardened* versions. Example, cookies denied out of the box. PB mode not used out of the box, which enables users to flick open one off PB mode windows - which is actually even more private than starting in PB mode.

It is a TEMPLATE. As said in the readme (future branches), and in numerous comments here, and on ghacks, we plan on released a "lite/relaxed" version as well as an uber-hardened version.

There are 454 prefs (excluding deprecated, personal section & parrot prefs) in 291 numbered items - getting these so everyone is happy is impossible in this branch. This is subjective, it's not a case black and white. Even if it were, there are still trade-offs to be judged.

Part of the reason for this project is to educate and make it easier for people to get into using this or similar setups. I can easily make this *HARD*, but then no-one would use it.

If you have an issue about any particular prefs being dropped or made inactive, then by all means speak up. Create an issue such as "What did you disable pref xxx.yyy.zzz?" instead of insulting me. I'd rather you were part of a solution, than a problem.

**Comment by crssi** [comment]
@Thorin-Oakenpants, please, don't trigger to provocations as this one. It takes energy, which could be spent somewhere else.
@Angelus35 took one minute to freshly create account at github with a single post almost obvious targeted to insult you without any grounds,
I was asking a guy with a one-liner question, to which I am 99% sure, he/she doesn't have an answer, to avoid your time being spend wrongly. ;)

**Comment by Thorin-Oakenpants** [comment]
Reply was the for benefit of all readers. Am tempted to mark this as invalid and close it, but, alas, I am not the dark insect overlord I always wanted to be ... it's true, I am soft :cry: :princess: 

I promise to be a total bitch in future :fist_oncoming:
