### ISSUE TITLE
replace google's geo API key with Mozilla's one

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#110]
I see no harm in doing this (yes, we would need to amend the timeout as well, forgot about that). It does not affect those who disable geo, but helps those who may turn it on (eg in their custom js - this is template, right, and knowledge is power). There is NO downside to doing this AFAIK.

If I get a clear majority of 100% and 3 billion upvotes, then I will assume it's OK to add this to the js

see https://github.com/ghacksuserjs/ghacks-user.js/commit/553d1aedde2818f0fa529fa33ad8c2bde29ffedf for all the details

**Comment by earthlng** [comment]
First of all sorry for my harsh words over there. It's not personal and I hope you understand that.

I have a feeling that you may think the recent post from a throwaway account calling you soft could have been me. It wasn't me! You'll have no way of knowing for sure and will have to take my word for it, but what you _do_ know is that I've criticized you often enough and not in uncertain terms either. I absolutely despise people who create throwaway's to upvote their own comments and other shit like that. And let me tell you, I would never ever do that because it's fucking shady IMHO.
If I have something to say to you I'll do so with this account. I do have one other older account on github but have not used it since I've created this one, nor do I plan to.
Someone recently impersonated me on your original ghacks article, and although I would have posted almost (if not exactly) the same comment, it wasn't me who wrote that and it really pissed me off.

Now back to the issue at hand. If the pref change ever does make it to stable then there's no need to change it in the user.js. All the Geolocation prefs are nicely grouped together and if someone feels that they want to enable one, then they should hopefully be smart enough to also reset some or all of the other ones.
It's a template and this template does (and should IMHO) disable Geolocation. The rest is up to the users.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/1b73cb828ebb5ad38b0aea5b41b7b6a780994413
