### ISSUE TITLE
font.system.whitelist

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#111]
What about `font.system.whitelist`?
Does it make any sense to add?

I have stumbled on some TBB pages for the following (fonts on Win7):
`user_pref("font.system.whitelist", "Arial, Arial Black, Calibri, Cambria, Cambria Math, Comic Sans MS, Consolas, Courier, Courier New, Georgia, Helvetica, Impact, Lucida Console, Lucida Sans Unicode, Microsoft Sans Serif, MS Gothic, MS PGothic, MS Sans Serif, MS Serif, Palatino Linotype, Segoe Print, Segoe Script, Segoe UI, Segoe UI Light, Segoe UI Semibold, Segoe UI Symbol, Tahoma, Times, Times New Roman, Trebuchet MS, Verdana, Wingdings, Aharoni, Andalus, Angsana New, AngsanaUPC, Aparajita, Arabic Typesetting, Batang, BatangChe, Browallia New, BrowalliaUPC, Candara, Constantia, Corbel, Cordia New, CordiaUPC, DaunPenh, David, DFKai-SB, DilleniaUPC, DokChampa, Dotum, DotumChe, Ebrima, EucrosiaUPC, Euphemia, FangSong, Fixedsys, FrankRuehl, FreesiaUPC, Gabriola, Gautami, Gisha, Gulim, GulimChe, Gungsuh, GungsuhChe, HELV, IrisUPC, Iskoola Pota, JasmineUPC, KaiTi, Kalinga, Kartika, Khmer UI, KodchiangUPC, Kokila, Lao UI, Latha, Leelawadee, Levenim MT, LilyUPC, Malgun Gothic, Mangal, Marlett, Meiryo, Meiryo UI, Microsoft Himalaya, Microsoft JhengHei, Microsoft New Tai Lue, Microsoft PhagsPa, Microsoft Tai Le, Microsoft Uighur, Microsoft YaHei, Microsoft Yi Baiti, MingLiU, MingLiU_HKSCS, MingLiU_HKSCS-ExtB, MingLiU-ExtB, Miriam, Miriam Fixed, Modern, Mongolian Baiti, MoolBoran, MS Mincho, MS PMincho, MS UI Gothic, MV Boli, Narkisim, NSimSun, Nyala, Plantagenet Cherokee, PMingLiU, PMingLiU-ExtB, Raavi, Rod, Roman, Sakkal Majalla, Script, Shonar Bangla, Shruti, SimHei, Simplified Arabic, Simplified Arabic Fixed, SimSun, SimSun-ExtB, Small Fonts, Sylfaen, System, Terminal, Traditional Arabic, Tunga, Utsaah, Vani, Vijaya, Vrinda");`

**Comment by Thorin-Oakenpants** [comment]
IMO, this is a waste of time. Linux vs Mac vs Windows lists will/may cause problems. And everyone will use their own list or whatever. Filling this in will most likely lead to a high entropy FP. It will take a large number of users with an enforced list ( see https://bugzilla.mozilla.org/show_bug.cgi?id=1336208 proposes bundling fonts for use and using this pref ). It also gets tricky with non-Latin/non-Western characters/languages I think.

Just use the user.js `browser.display.use_document_fonts` = 0 (1401).

IF and WHEN tor uplift does bundle fonts and set an enforced whitelist, then that would be the way to go instead of the above pref. It would then allow the web to be displayed as designed (rather than limited to a few fonts), and would also hide you in a large subset of FF users. Personally, I do not have ANY issues with limiting fonts. The web looks perfectly nice to me with my tiny set of 3.

**Comment by Thorin-Oakenpants** [comment]
Sheeshus ... I even wrote that in the js

```js
 * [NOTE] Creating your own probably highly-unique whitelist will raise your entropy. If
 * you block sites choosing fonts in 1401, this preference is irrelevant. In future,
 * privacy.resistFingerprinting (see 2699) may cover this, and 1401 can be relaxed.
```
