### ISSUE TITLE
extensions.shield-recipe-client.enabled (?) True or False

### ISSUE THREAD

**Issue by GitCurious** [ghacksuserjs/ghacks-user.js#116]
I didn`t find a reference to this pref in the user.js

extensions.shield-recipe-client.enabled

Defaults to TRUE here, appears to be some kind of tracking/feedback mechanism.
https://wiki.mozilla.org/Firefox/Shield/Shield_Studies

Just wondering if it needs to be set to false, whether another preference disables it or if it`s redundant ?

I`m not technically minded about these matters so was just curious about the setting state.

**Comment by earthlng** [comment]
Hi, I don't have that pref in about:config. I guess that's because nothing installs automatically in my FF.
Afaik if you allow automatic app updates  then system addons (including the shield one you mention, I assume) are updated/installed automatically also.
If you don't want to participate in the shield study then yes, set that pref to false, ideally in a user.js file because the shield addon could reset the pref otherwise, and next time around the pref would be true again.

**Comment by GitCurious** [comment]
Thanks Earthlng

I couldn`t find the system addon xpi responsible (I do usually delete them though)

I set it false anyway, just to be sure.

**Comment by earthlng** [comment]
You're welcome :)

> I couldn`t find the system addon xpi responsible

from the site you linked:
> Shield Studies live for a fixed period and **are uninstalled by the system** at the end date or after the specified elapsed time

**Comment by Atavic** [comment]
Shield Recipe Client [removes itself](https://github.com/pyllyukko/user.js/issues/319#issuecomment-310661285) automagically.

**Comment by Atavic** [comment]
#16 https://addons.mozilla.org/en-US/firefox/shield_study_16

**Comment by Atavic** [comment]
[shield_study_16](https://addons.mozilla.org/en-US/firefox/shield_study_16)
