### ISSUE TITLE
How do you update your user.js

### ISSUE THREAD

**Issue by verlain3** [ghacksuserjs/ghacks-user.js#124]
Do you download the most recent user.js and replace everytime a new commit is made?

How does one use the most recent user.js without downloading and apply our own user preferences changes to it everytime (i have like 10 lines tweaked from your original user.js file, in order to not break some websites i use)? Not possible, right?

**Comment by Thorin-Oakenpants** [comment]
Well, TBH, MY own user.js - I have two, I have a working copy and my live one. I do changes in my working copy and then commit them to here. I use a diff program to merge locally. My copy is actually identical to the live master. So I'm not much help, sorry.

People can use a fork and let github spot all the differences. Or earthlng suggested ways to merge this with a non ghacks.js one: see https://github.com/ghacksuserjs/ghacks-user.js/issues/65#issuecomment-290703628

**Comment by Thorin-Oakenpants** [comment]
Or like atomGit does at 12bytes - use the user.js AS IS but append your own overwrites at the end - this seems easier

**Comment by verlain3** [comment]
And those at the end will be in use, instead of the duplicated ones at the sections they're in?

**Comment by Thorin-Oakenpants** [comment]
Yes. If a pref is listed twice, the last one is applied last (see https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview/#what-is-it-what-does-it-do-and-why-would-i-want-one ) - it is parsed in order

So you could use the user.js as is and anything you want to overwrite add to the end as an active preference with the different value

```js
[line 1005]
/* 2404: disable JS storing data permanently ***/
user_pref("dom.indexedDB.enabled", false);
...

[line 1800]
/* start verlain overwrite prefs ***/
user_pref("dom.indexedDB.enabled", true); //2404
```

**Comment by earthlng** [comment]
Instead of adding your own changes at the end of this user.js you can also create a `preferences` folder in your profile directory and move the latest user.js from here in there and then have a user.js with your own prefs in the main profile dir. The .js preferences files under preferences can have any name you want so you could rename it to ghacks-user.js for example. That way you don't have to edit your own file every time you get a new copy from here. The user.js in the main folder is always applied last and overwrites all the prefs applied from (multiple) js files under preferences.
But *all* files in the preferences dir are applied in (I assume) alphabetical order, so make sure you don't put multiple copies of this (or any other) user.js in there

**Comment by verlain3** [comment]
Thanks for the replies, the tips definitely help. Just updated to the most recent commit and so far so good with.

This can be closed now. :)

**Comment by RoxKilly** [comment]
@earthlng thanks that was a great tip. I'll be using that myself.

**Comment by Thorin-Oakenpants** [comment]
it should be added to a wiki item

**Comment by RoxKilly** [comment]
I ran into a block trying to implement @earthlng 's approach to update `v53` to `v54`: There are settings in `ghacks-user.js` that I want to replace with the browser default. 

* When I know that default, it's easy enough, I can just write it into my `user.js`, and it will overwrite whatever `ghacks-user.js` set (now located in `preferences` folder).

* When I don't know the default, I'm stuck: what I did in the past is just comment out the line so nothing would be set. With the approach mentioned here though, `ghacks-user.js` is not touched, and all customization is done in a separate `user.js`. What to put there since I don't know the default?  The only thing I can think of is to start the browser with a clean profile and look up the value for each of these prefs in `about:config` to find out the default. Seems cumbersome but is there a smarter way?

**Comment by Thorin-Oakenpants** [comment]
What happens if you right click and reset in your current profile - that should give you the right value. No need to try a new profile. If the value disappears (and it also defaults to a string), then it's likely hidden. The only way to deal with those is to comment it out

**Comment by RoxKilly** [comment]
right click + reset shows default value, or blank for a previously hidden pref

**Comment by bonbonboi** [comment]
right click + reset sets default value ... according to who? where from FF get that default value?

**Comment by Thorin-Oakenpants** [comment]
^^ in about:config, when you select and right-click on a preference, there is a menu option to reset (it will be disabled if the value is already at default)

**Comment by bonbonboi** [comment]
> ^^ in about:config, when you select and right-click on a preference, there is a menu option to reset (it will be disabled if the value is already at default)

- Ok how FF knows what was the default value in the first place, what file FF reads to know that?

**Comment by RoxKilly** [comment]
Default values are hardcoded in software. It's the value you would have if you did a fresh install of the browser on a new system.

**Comment by bonbonboi** [comment]
> Default values are hardcoded in software. It's the value you would have if you did a fresh install of the browser on a new system.
- I see, got something to know about, if the user.js introduced a new pref, would that appear on about:config? or about:config about what Mozilla wants the user to see, so still they're some other hidden prefs somewhere else,,

**Comment by RoxKilly** [comment]
Yes it will appear.

**Comment by bonbonboi** [comment]
> Yes it will appear.
- I see, thanks

**Comment by earthlng** [comment]
> how FF knows what was the default value in the first place, what file FF reads to know that?

see [here](https://github.com/earthlng/FFprefs-diffs) at the end of the README, I listed all the preferences files and the order in which they are applied. For example if a pref exists in file 1 (greprefs.js) and in file 9, then the value from 9 will overwrite the value from file 1
