### ISSUE TITLE
dom.maxHardwareConcurrency

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#127]
Note that in [1360039](https://bugzilla.mozilla.org/show_bug.cgi?id=1360039) FF55+ will spoof **navigator**.hardwareConcurrency as 2  (They went with 2 as per Firefox's own [metrics](https://metrics.mozilla.com/firefox-hardware-report/)). This will happen under `privacy.resistFingerprinting` . Tor currently uses a value of 1, and [1333933](https://bugzilla.mozilla.org/show_bug.cgi?id=1333933), also under resistFingerprinting, will flip a ton of prefs, including this one (I am sure it will fall into line with a value of 2)

```js
/* 2514: spoof number of CPU cores (also see 2699f) (FF48+)
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1008453
 * [2] https://trac.torproject.org/projects/tor/ticket/21675 ***/
user_pref("dom.maxHardwareConcurrency", 2);
```

My only concern is that "spoofing" content is fine, but does this affect "chrome calls" - eg, will it limit FF itself to use only 2 cores? AFAIK this is OK (My default value is 16 on WIndows, I have 4 cores btw)

> RuntimeService::ClampedHardwareConcurrency() is only called from Navigator.cpp and WorkerNavigator.cpp. I don't see any browser chrome code calling navigator.hardwareConcurrency today

Anyone see any issues with adding this?

**Comment by earthlng** [comment]
We discussed that already [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/33)
IMO we should not add this and wait till FF55 spoofs it with `privacy.resistFingerprinting;true`

**Comment by Thorin-Oakenpants** [comment]
^^ "wontfix: at this stage" - that was back when I had a lot to do getting this baby up and running here. There is a difference between dom* and navigator* spoofing, AFAIK.

**Comment by earthlng** [comment]
I'm not sure spoofing alone would do any good and nobody answered KOLANICH's question "have you found a suitable way to overcome https://github.com/oftn-oswg/core-estimator ?"
It seems that sites can still estimate the number of cores even with spoofing. Setting the dom pref would prevent that but it would probably also limit FF's performance.
If you want to add it I don't mind adding it as inactive ie commented out, but personally I'm not going to use it because I don't care if the rare few sites I allow JS on could know my number of cores, because I think a majority of computers worldwide will have the same number of cores as my own machine. And once FF55 spoofs it, simply getting the value from the dom would not give a site the correct number of cores if they don't also use the core-estimator trick. But since we also have (service)workers disabled anyway there's nothing they can do to get the correct # of cores.

**Comment by Thorin-Oakenpants** [comment]
Yeah, I think inactive might be best. I bust reading thru https://bugzilla.mozilla.org/show_bug.cgi?id=1008453 and related links and I'm not convinced that this pref DOESNT affect ff core performance (ps, don't be sidetracked by workers since we block those)

**Comment by Thorin-Oakenpants** [comment]
> But since we also have (service)workers disabled anyway there's nothing they can do to get the correct # of cores.

But workers is covered: "ClampedHardwareConcurrency() is only called from Navigator.cpp and WorkerNavigator.cpp."

**Comment by earthlng** [comment]
Yes it's covered but only for spoofing. It seems that the estimator trick doesn't care about that value and tries higher numbers of workers regardless. I also doubt that sites really use that trick to fingerprint because it's only an estimate and not very reliable. They maybe *are* using the number of cores as given back by the DOM as one bit of FP information but once that is spoofed I think we're gucci.
And setting the dom pref does not just spoof it, it effectively limits the use of more cores, and I assume that applies to FF as well. So yeah, I'm not a fan of adding this.

**Comment by Thorin-Oakenpants** [comment]
Now I'm not sure. I think I might add it as active and await any fallback. If it's good enough for TBB, I'm sure they've covered performance. Still intrigued as to why bugzilla 1333933 wants to flip the pref with resistFP when resistFP already has a built in spoof under 1360039 which does not use the pref. Maybe it's oversight, and 1360039 makes dom.maxHardwareConcurrency redundant.

There's a big difference between the ability of sites to estimate the number of CPU cores with high accuracy (eg thru polyfill) and DIRECTLY EXPOSING it. Why make life easy - reduce attack surface when possible.

**Comment by Thorin-Oakenpants** [comment]
OK, so all I need to know then to make a decision of whether its active or inactive is does the DOM pref affect core chrome performance. We know the spoof NAVIGATOR value does not.

**Comment by Thorin-Oakenpants** [comment]
OK ... convinced this limits core performance, and will impact e10s - so will modify description and add to js as inactive

**Comment by earthlng** [comment]
> and DIRECTLY EXPOSING it

yeah but FF55 with resistFP won't expose it anymore.

> We know the spoof NAVIGATOR value does not.

Do we though? Even the mozilla guys don't seem to be sure about that:

> I don't see any browser chrome code calling navigator.hardwareConcurrency **today**, but it would be affected by privacy.resistFingerprinting **if it did**. It looks like RuntimeService.cpp **could check** if it is called by chrome code.

I don't know what they mean by "could check" - does it mean "maybe it checks but I'm not sure" or "we could add a check to see if it's called by chrome code" ??

**Comment by Thorin-Oakenpants** [comment]
```js
/* 2514: spoof number of CPU cores (also see 2699f) (FF48+)
 * [WARNING] *may* affect core chrome/Firefox performance
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1008453
 * [2] https://trac.torproject.org/projects/tor/ticket/21675
 * [3] https://trac.torproject.org/projects/tor/ticket/22127
 * [4] https://html.spec.whatwg.org/multipage/workers.html#navigator.hardwareconcurrency ***/
   // user_pref("dom.maxHardwareConcurrency", 2);
```

and

```js
/* 2699f: spoof navigator.hardwareConcurrency as 2 (FF55+)
 * This spoof does not affect core chrome/Firefox calls
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1360039 ***/
```

**Comment by Thorin-Oakenpants** [comment]
^^ will change does not to maybe

**Comment by earthlng** [comment]
2514 does not spoof, it limits it, doesn't it?

**Comment by Thorin-Oakenpants** [comment]
good point - TBB use the word spoof, but it really does limit IMO (but I am not sure) , i.e it limits content (ignore workers). The question is does it LIMIT firefox core chrome performance - and no one seems to know, and it;s too risky what with e10s. That second tor ticket links talks about a sliding scale.

**Comment by Thorin-Oakenpants** [comment]
see new draft
