### ISSUE TITLE
disable freceny?

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#128]
from @Atavic 

> Info on GlobalFrecency [entries](https://wiki.mozilla.org/User:Sspitzer/GlobalFrecency) & a Wilders [post](https://www.wilderssecurity.com/threads/firefox-31-released.366329/page-2#post-2395461) tells how to disable:
```
 browser.cache.frecency_experiment -1
```

**Comment by Thorin-Oakenpants** [comment]
Personally, I don't want to go here. People either want suggestions or they don't (in which case they kill the whole thing). I think freceny is good for those people - the algorithm helps ensure the most relevant items. Plus it would be another thing to maintain - do you know how many times mozilla tweak and f*k with the urlbar? Answer: all. the. time.

**Comment by Atavic** [comment]
1st link:

```
// the (maximum) number of the recent visits to sample when calculating frecency

pref("browser.frecency.numVisits", 10);
```

Seems to affect the urlbar list.

**Comment by earthlng** [comment]
That one pref that he quoted has to do with some **cache** half-life experiments and nothing to do with the `places.frecency.*` prefs. The user.js already clears history on shutdown by default and we shouldn't mess with people's bookmarks IMHO, so no need to go there.

**Comment by Thorin-Oakenpants** [comment]
`browser.frecency.numVisits` doesn't exist anymore Atavic (that link is from 2008, so much has changed since then). And now I've had a chance to read TheWindBringeth's comments, what earthlng said is true.

I really do not want to mess with this. IF someone has one-or-more suggestion types on for keyword search engines, and IF that someone has maxRichResults at 0 to hide suggestions, and IF that person clears history as per the user.js, then it's not too often something will show.

Messing with the relevancy of bookmarks, typed urls, clicked links etc - all those weight and bonus and type points - I am sure I could kill frecency, but it's really not necessary. A hardened browser can just flat out kill suggestions, and that's what matters.

**Comment by Thorin-Oakenpants** [comment]
Thanks Atavic. I know you were not suggesting we actually do this, just adding some info in that other thread. It was worth a look. Closing as WONTFIX

**Comment by earthlng** [comment]
frecency (frequency + recency)

**Comment by Atavic** [comment]
Did some search and  ```browser.cache.frecency_experiment -1``` does not disable anything.

> if at -1, no experiment is run and we use the preferred value for frecency (6h)
See: bugzilla 986728

So I keep a low fingerprint with:

```browser.cache.frecency_experiment 4
*.frecency.*Bonus 0
*.frecency.*Weight 1
*.frecency.*Cutoff 1```

*browser.cache.frecency_half_life_hours 6* is a decay-time, an high value means *low recency*.
*frecency_experiment 4* above means *low frequency*.

**Comment by earthlng** [comment]
`browser.cache.frecency_experiment` is a dead pref since FF59. It's even listed in the user.js under 9999

**Comment by earthlng** [comment]
> how did you learn this?

I must have searched for it on DXR and noticed it's not used anymore.
The 3 places you linked are the pref **definitions**. That's why I wrote "dead pref": the pref still exists but the code that used it was removed, they just forgot to remove the pref.
Since it was removed in FF59 you have to go back to esr52 on DXR to see what it looked like when it was still used. compare
https://dxr.mozilla.org/mozilla-esr52/search?q=frecency_experiment and 
https://dxr.mozilla.org/mozilla-esr60/search?q=frecency_experiment

**Comment by earthlng** [comment]
^^ FYI from that point on it's easy to find the relevant bugzilla by 
- clicking the [file where the pref was last used in esr52](https://dxr.mozilla.org/mozilla-esr52/source/netwerk/cache2/CacheObserver.cpp#206)
- in the navigation on the right click on log
- change to ["tip"](https://hg.mozilla.org/releases/mozilla-esr52/log/tip/netwerk/cache2/CacheObserver.cpp)
- copy the most recent commit id since they're unique, in this case d6f37cd67e82
- replace esr52 in the URL to esr60
- ctrl+f and search for the commit id

in this case there were only 9 changes to that file since esr52 and the most recent change is "Remove the HTTP cache half-live experiment". It's not always that easy but you get the idea

**Comment by Atavic** [comment]
On some forks this entry is active.

**Comment by grauenwolfe** [comment]
@earthlng Thanks for breaking it down. Your thoroughness and follow-through is pretty damn inspiring.

**Comment by earthlng** [comment]
@grauenwolfe you're welcome. Thanks for the compliment!
