### ISSUE TITLE
Add-ons/extensions section of the wiki

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#132]
In the Add-ons section of the wiki:

 - The title uses "Add ons" instead of "Add-ons" (missing the hyphen).  Although since Add-ons are pretty much gone, you might want to change it to "Extensions".
 - "QuickJava" is listed as "Quick Java".  Also might want to mention that it can block WebRTC.
 - For extensions in the "Do not bother recommending these..." section, it would be useful to add to the wiki why you are not recommended each of them.

**Comment by Atavic** [comment]
Point 3: [Ghostery](https://github.com/ghacksuserjs/ghacks-user.js/issues/4#issuecomment-280851393) tracks [users data](https://github.com/gorhill/uBlock/issues/902#issuecomment-153615037).

[Privacy Badger](https://github.com/privacytoolsIO/privacytools.io/issues/121#issuecomment-279521871) is less aggressive than [uBlock Origin](https://github.com/gorhill/uBlock/issues/642).
Gorhill's Wiki prove it's also less effective in overall blocking.

UAControl and related User-Agent JS Fixer are ignored simply because this repository doesn't want any spoofing. 

Disconnect has blacklists and those can be integrated into uBo.

**Comment by Thorin-Oakenpants** [comment]
> The title uses "Add ons" instead of "Add-ons" (missing the hyphen)

Github does that, it strips the hyphen out
