### ISSUE TITLE
browser.zoom.siteSpecific

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#135]
Obviously JS can detect object positions etc and thus if you use a site specific zoom it can raise entropy. It's one of Arthur's items in https://bugzilla.mozilla.org/show_bug.cgi?id=1333933

http://kb.mozillazine.org/Browser.zoom.siteSpecific (old unreliable reference - need to check if behaviour has since been changed)
- True: remember the zoom level on a per-site basis. (Default)
- False: The zoom level should be applied on the current tab only. 

AFAIK, and we need to test, it does NOT stop someone zooming (is it only currrent tab, does the zoom stick in the current tab between domains? etc), but at least on a revisit (new session, new tab/window) the zoom will be reset to default - imagine being at  67% zoom across dozens of sites, or always at 90%. Most users will be at 100% almost all the time.

I think we should include this. Just not sure if active pref at false, or inactive at false (and left for the uber-hardened version). Personally, on a desktop and dealing with sites predominantly geared for smaller devices, I use site zoom a fair bit (maybe 30 regular sites), so that sucks for convenience. But closing down a FP'ing vector is always good.

Class, discuss!

**Comment by earthlng** [comment]
True: stores the zoomlevel under siteSettings and if set for a site in a normal window, it will also set the same zoom level if you open the site in PB but not vice-versa.
False:
* it does NOT stop someone zooming
* is only current tab
* does the zoom stick in the current tab between domains? yes
* on a revisit (new session, new tab/window) the zoom will be reset to default
* also works exactly the same way in a Private window, ie it "remembers" the zoomlevel across domains for the current tab only

I never change the zoom level but if I did, I would reset it to 100% before closing the tab so this pref doesn't matter to me. Since we don't clear siteSettings on shutdown mostly because we want to remember site-specific cookie settings, and since this is a potential FP issue, I think setting the pref as active is probably best.

**Comment by earthlng** [comment]
But a case can also be made for keeping it inactive, namely because user's already set site-specific zoom levels will no longer be honored, and I'm also okay with adding it as inactive.

**Comment by Thorin-Oakenpants** [comment]
The reason I don't clear site settings is things like cookie exceptions, exceptions to all those things listed under permissions etc, zoom specifics - it would be incredibly annoying to wipe potentially years of someone's accumulated exceptions etc (people should have backups anyway). But yeah, this is not the issue

From a usability perspective, I would find this incredibly annoying and tedious. I don't mind doing a quick ctrl+/- on a few (30+) sites, but it would be nice for a pref to make it change back to 100% when the domain changes. The only other thing for me is my speed-dial. I have the dials as small as allowed, and zoom is at 67%. I'd go out of my mind if it was an ugly 100% (I have 12 tabs and up to 66 dials per tab before a vertical scroll bar appears - and some of those tabs are close to that). I could switch to list view, but I am so used to my visual clues and positions of sites. On that basis, personally, I would have this inactive. But its not about me. ME ME ME .. 

I feel if it was active (i.e we forced it to deviate from the default), we'd get tons of complaints about it. Left inactive in this branch, but used in an uber-hardened one seems more prudent. I also don't think it's widely used since there is so much more lower hanging fruit in the FP garden.

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1369357

**Comment by Thorin-Oakenpants** [comment]
zoom levels affect screen res: note, I am using privacy.resistFingerprinting and my inner window at 100% is 1366x768.

http://browserspy.dk/screen.php
- at 100% = 1366x768
- at 90% = 1525x858 etc

We should also look at `layout.css.devPixelsPerPx` => "1.0" which controls the default zoom level [note "-1.0" is the default value and will adhere to system settings]

**Comment by Thorin-Oakenpants** [comment]
I am going to make this active (it's going to happen anyway under privacy.resistFingerprinting, which will not be using any prefs, but will be "hardcoded" AFAIK).

:+1:  or nits

```js
/* 2515: disable site specific zoom preferences and set default zoom at 100%
 * Zoom levels affect screen res and are highly fingerprintable. This does not stop you using
 * zoom, it will just not use/remember any site specific settings. Zoom levels on new sessions,
 * tabs and windows are reset to default, otherwise the current tab retains the current zoom. ***/
user_pref("browser.zoom.siteSpecific", false);
user_pref("layout.css.devPixelsPerPx", "1.0");
```

**Comment by earthlng** [comment]
Is it necessary to include devPixelsPerPx? Fe if set to 1.1 it also changes the textsize in the menu bar and the tab titles and everything else. If I zoom on a page it doesn't change that pref either. I'm not against including it but that pref would be the "and set the default zoom at 100%" in the title right, which is simply incorrect. ie afaik there's no pref to set the default zoom to 100%.

> Zoom levels on new tabs and new windows are reset to default, otherwise the current tab retains the current zoom

Otherwise? I think "and only" or so would be better

and regarding the FPing it's only a problem if you reload a site/load a new site while being zoomed in or out, or I guess if JS is allowed it may be possible to detect it without a (re)load. Otherwise afaik sites can not detect it. But yeah I don't think we need to mention that.

**Comment by Thorin-Oakenpants** [comment]
Yeah, a site can detect element positions, mouse positions etc, so a page reload is not strictly necessary - try zooming and see what happens at [w3school](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_event_mouse_clientxy) - that is click on a certain letter .. zoooooom .. click again on the same letter - bang, you've been nailed son, and it's not even easter!

This pref should be to disable zooming contents entirely. As it is, if this is false, it leaves you open to not reverting back to 100% when changing domains IF you had a different value. If the value is true, then it leaves you susceptible to using a few specific site zooms, even if you didn't mean to keep that zoom. Either way, neither is bulletproof. But since it's going to be enforce, we might as well do the same.

I tried a couple of "site zoom" web extensions - they sucked donkeys balls. One went ballistic with CPU and couldn't handle chrome:// (which I overcame anyway). I'm fine with no site specific zoom anyway - except my speed dial which I fixed (see above edit).

Ahh, I got that px thing wrong. That's UI, as you said. Sweeet, we can drop that. "otherwise"=>"and only" = tick

**Comment by earthlng** [comment]
that site doesn't do jack without JS. On sites where you block JS, once the page is loaded you can zoom in or out as much as you want and the site can't detect that at all (afaik!). That's what I was trying to say :)

**Comment by Thorin-Oakenpants** [comment]
I always look at it from the worst case scenario. IF u allow JS and IF u allow XSS and IF u allow this and that .. THEN ... what's the worst that can happen. Step 1 is to always reduce the attack surface (eg no JS/XSS), then harden the attack surface (spoof, block) and then there's always OpSec

Anyway, you said JS xD

>> or I guess if JS is allowed it may be possible to detect it without a (re)load
