### ISSUE TITLE
How to automaticly add to exception list for the auto deleteion of cookies

### ISSUE THREAD

**Issue by HarleyGodfrey** [ghacksuserjs/ghacks-user.js#1479]
Hey!

I was wondering if there is a way to add exceptions to the "auto delete cookies on closure" using a config file or command? I am setting up a script for automated deployment which installs arkenfox's user.js, some UI changes and extension installs. The auto deletion of all cookies is a pain to setup after as there are quite a few for me to add. 

I really hope I explained this clearly enough? And if not I am happy to elaborate. First time logging any sort of ticket here so I hope I am following the guide lines properly?

Thanks,
Harley Godfrey

**Comment by Thorin-Oakenpants** [comment]
site exceptions are stored in permissions.sqlite. IDK how feasible it is to write to it (while FF is closed) to add what you want (without damaging existing entries), or to replace it with a generic starting sqlite with all your entries (for initial deployment)

I have modified the sqlite file myself in testing profiles: removing entries, modifying them (not adding them) - while FF is closed - but there are some entries for moz-extensions in there: e.g. `moz-extension://e0cc77c6-3785-BLAH-BLAH-SOMETHING---`  - the good news is at least that is the Manifest ID, not the random Internal UUID

Try it. It looks doable once per profile. i.e create a profile, add your extensions, add site exceptions, close, save the permissions.sqlite as a master, try it in a new profile.

Otherwise, this is really out of scope for arkenfox, so closing - but let us know how you got on
