### ISSUE TITLE
FF uniqueness

### ISSUE THREAD

**Issue by bonbonboi** [ghacksuserjs/ghacks-user.js#150]
How could I minimize the uniqueness at (https://amiunique.org)?
how come I got <0.1% About 
User agent 	<0.1% 	"Mozilla/5.0 (Windows NT 6.1; rv:54.0) Gecko/20100101 Firefox/54.0"
 Screen resolution 	less than <0.1% 	"1366x687x24" WTF am I the only one on the Earth got that  Screen resolution!

**Comment by Forsaked** [comment]
You can spoof your user-agent with the part `2697: USER AGENT (UA) SPOOFING` in the user.js.
A current list with the most used user-agents can be found here: [https://techblog.willshouse.com/2012/01/03/most-common-user-agents/](https://techblog.willshouse.com/2012/01/03/most-common-user-agents/)
The screen resolution spoofing part can be found under `2699: privacy.resistFingerprinting` in the user.js.

**Comment by Thorin-Oakenpants** [comment]
Well then, change your inner window sizes to reflect a better resolution. It will be done for you in FF55 - rounded to 100s, but you can override it with a maxwidth and maxheight. I use 1366x768 - see https://metrics.mozilla.com/firefox-hardware-report/ (the idea is you should be in the biggest set for Firefox, not the biggest set overall, although they are probably the same, who cares - you only need to care about your subset)

Look, I'm not going to type up and write about fingerprinting and entropy etc, because it would take a book. Spoofing currently is a waste of time and raises entropy if sites implement a little basic JS digging. Spoofing will happen under resistFingerprinting in FF56 and will round to the nearest multiple of 10 etc. This will be enforced as thus garner a much larger set of users who cannot change it (eg just like Tor Browser Bundle only reports the latest rounded ESR) - i.e large numbers forced to use the same settings.

Those tests are biased and skewed. Of course you will only have a small percentage of users on FF 54, because its only been out a few days. It's meaningless. You'll also find, by its very nature and the nature of its users, that figures are not real world - eg the percentage of FF users will be much higher than real life, because most people who care about tracking wouldn't be using Chrome for example.

Another really skewed figure is the number of users who have DNT (do not track) eg see Panopticlick. Mozilla's own figures indicate about 20% turn on DNT. DNT *must* be off by default (otherwise the advert networks would not agree to it), and only I guess 20% turn it on. But privacy conscious people, those who test themselves at Panopticlick, would be likely to activate this feature (whether it helps or not is not the point, the point is that it is one bit for entropy). Panopticlick indicates (or indicated) that it was about 50/50. That is a massive skew from 20%.

The data from these tests is also tainted with old results, as seen by your FF version. AmIUnique if I recall correctly, can let you choose a time period, such as this week, today, this month - which would be more relative, but a smaller data set.

**Comment by RoxKilly** [comment]
Small correction to:
> DNT must be off by default (otherwise the advert networks would not agree to it)

If memory serves, this isn't quite right. The consensus was that DNT should be *unset* by default in UI implementations; neither *On*, nor *Off*, like an unset radio button.

In practice of course, this probably meant that the *DNT* header was not sent, so I guess in practical terms, *unset* has the same effect as *Off*.  Come to think of it, it has the same effect as *On* (advertisers don't care).

**Comment by Thorin-Oakenpants** [comment]
> Come to think of it, it has the same effect as On (advertisers don't care).

Exactly, high praise for EFF, but ultimately it's the :middle_finger: to advertising

**Comment by bonbonboi** [comment]
So you telling that if I want more about those stuff  I better go and use Tor Browser which is made for anonymity in the first place..

**Comment by crssi** [comment]
Now ex FBI 1st head sad not so long ago: Anonymity on Internet? There is no such thing.

**Comment by Thorin-Oakenpants** [comment]
> So you telling that if I want more about those stuff I better go and use Tor Browser which is made for anonymity in the first place.. fair enough.

Wot?

The TBB is designed for anonymity, correct. It is especially hardened in ways that Firefox isn't and can't be, through code patches etc. It also masks your IP via TOR. It also has downsides - the exit node for example is a risk, as are honeypots, the speeds can be terrible, and more. It's also not foolproof - the human factor is critical, because people lack the craft. And it's pretty rare - example, catching a bomb hoaxer at an american university by looking at logged traffic at that university and filtering down tot he one student using tor at the time. Another example - DPR traffic monitored when he posted on silk road coincided with his TOR traffic, which was enough to nab him.

**You use the right tool for the right job***. If you fear state surveillance, then use TOR (on tails, etc) .. hell, use TOR over VPN .. daisy chain three VPNS (its not hard) .. but at the end of the day, most people f**k up over OpSec. But if your objective is to just stop all that creepy company and corporate tracking, then a "hardened" Firefox is fine.

You beat fingerprinting by reducing the attack surface as much as possible .. AND thru OpSec, end of story. Use the right tools, use the right methods.

**Comment by Atavic** [comment]
> "Mozilla/5.0 (Windows NT 6.1; rv:54.0) Gecko/20100101 Firefox/54.0"

Most Win 7 users haven't upgraded, you can get a[ 2.3% popularity](https://techblog.willshouse.com/2012/01/03/most-common-user-agents/) with:

`	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0`

> "1366x687x24"

Do you have two taskbars? That choice with no hideable taskbar makes you unique.

**Comment by crssi** [comment]
I am sure you are all aware that even TOR is broken. If you follow the latest stuff (which is not new) with a lot (and I mean a lot) of home routers are p0wned by 3 letters agencies. In that case they can match source and with an exit traffic.

**Comment by Atavic** [comment]
Sad but true, at least we can sometimes put an open source OS on them. And then follow the bug tracker.

**Comment by bonbonboi** [comment]
> Do you have two taskbars? That choice with no hideable taskbar makes you unique.
What taskbars!

> Now ex FBI 1st head sad not so long ago: Anonymity on Internet? There is no such thing.
I agree, but don't forget about recent Ransomwares, they coudlnt trace back who owns the real thing, bitcoins address oh that anonymous somehow, Wikileaks based on OR, such publishing leaked docs which is sent anonymously.

> I am sure you are all aware that even TOR is broken. If you follow the latest stuff (which is not new) with a lot (and I mean a lot) of home routers are p0wned by 3 letters agencies. In that case they can match source and an exit traffic.
- If that true why still Tor Browser releases new versions till now and updating its client!

**Comment by earthlng** [comment]
> What taskbars!

Toolbars -> Menu Bar, Bookmarks Toolbar, etc

> If that true why still Tor Browser releases new versions till now and updating its client!

You can use TBB *not* from home for example

> a lot (and I mean a lot) of home routers are p0wned by 3 letters agencies

... not **all** home routers either

**Comment by Atavic** [comment]
[tor-fingerprint](https://github.com/jonaslejon/tor-fingerprint) with inner width query.

**Comment by earthlng** [comment]
> with inner width query

where exactly is that query?

**Comment by Atavic** [comment]
Search for: inner

tor-fingerprint.js @ line 89: `document.getElementById("fingerprint").innerHTML = fingerprint;`

**Comment by earthlng** [comment]
line number? it has no inner width query anywhere

**Comment by Atavic** [comment]
Seems like it's for document tables (I thought was for screen width).
