### ISSUE TITLE
maps.google.com accuracy

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#152]
After a long time I have opened maps.google.com.
Last time it misses my location for 10k miles, which is good.
Today it pinpointed me to several hundred meters.

Anyone same result?

**Comment by RoxKilly** [comment]
How do you get `map.google.com` to show what it thinks is your location? When I load it, no location is pre-selected. All of North America is shown.

**Comment by Thorin-Oakenpants** [comment]
Are you using WiFi? Because google has mapped the entire universe's wifi names etc, so yur f**ked mate

**Comment by crssi** [comment]
No wifi, latest user.js and FF 54.
Last time I got also all of North America.

**Comment by Thorin-Oakenpants** [comment]
I just let google maps thru NS, uBo and uM .. and all I got was a lousy t-shirt .. seriously, it just guessed the middle of my country

**Comment by RoxKilly** [comment]
@crssi are you browsing on a smartphone/tablet with GPS enabled? Alternatively, maybe you've granted the site some permission (click the "i" icon to the left of the URL bar to see site permissions.

**Comment by Thorin-Oakenpants** [comment]
@crssi Has google even been given your address? Do u have an android phone (and google account for the play store) and even if location awareness was off, it knows your wifi. So u have any remnant of google info in your browser? They're really sneaky those google engineers. I once let my mate on my wifi with his smartphone, and suddenly all my google searches (in the footer) offered to search relative to my town rather than the usual country - I watched it change in real time.

**Comment by crssi** [comment]
I am back with a clean install of FF54, clean profile with latest user.js,
No granted permissions, browsing on Windows 10. No WiFi.
Results are the same. Very accurate position.
But your idea make sense. Maybe a kid with Android is a leaker (for sure he is) and google mapped our current external IP with his data. Nasty.

**Comment by bonbonboi** [comment]
Dude it's geoip any web site knows your location by looking up your ip, so simple task.

**Comment by crssi** [comment]
^^ Not exactly and always.

**Comment by Thorin-Oakenpants** [comment]
> Dude it's geoip any web site knows your location by looking up your ip, so simple task.

Not to within a few hundred meters.

**Comment by Atavic** [comment]
^ That's definitely GPS.

**Comment by bonbonboi** [comment]
What kind of Internet connection is on your computer?

**Comment by Thorin-Oakenpants** [comment]
I can't be arsed looking, but is google maps using ip6 .... oooh scary .. mac addresses. Change ya mac address crssi and see what happens

**Comment by crssi** [comment]
I am not using IPv6... MITM is too easy to make.
Tried out now over company "proxy" and now I get a 100 miles vicinity.
So I could easily assume that is what you have mentioned some mobile device on my network is leaking GPS position tied to our home IP address.... which is DSL spread around a 50 miles radius.
Thank you all

**Comment by bonbonboi** [comment]
> I am not using IPv6... MITM is too easy to make.
Tried out now over company "proxy" and now I get a 100 miles vicinity.
So I could easily assume that is what you have mentioned some mobile device on my network is leaking GPS position tied to our home IP address.... which is DSL spread around a 50 miles radius.
Thank you all
* Good, at least you'd get your pizza delivered very hot in no time..

**Comment by crssi** [comment]
lol... true for hot pizza.

Thank you guys for brainstorming

@Thorin-Oakenpants  Fell free to close this topic since I don't dare to do it myself. :).

**Comment by Thorin-Oakenpants** [comment]
> @Thorin-Oakenpants  Fell free to close this topic since I don't dare to do it myself. :). 

Why? What's the worst that could happen? Will you explode or your ears fall off? Will Liam Neeson find you and kill you? Will Trump post a tweet about how sad bigly and yuge something is? Or would I just reopen it if I felt it needed to stay open?

**Comment by Thorin-Oakenpants** [comment]
Google uses [BSSID](https://en.wikipedia.org/wiki/Service_set_(802.11_network)#Basic_service_set_identification_.28BSSID.29) information from your WLAN Access Point to get an approximation of where you are located, even with GPS and WiFi turned off.

> Google and others like Apple and Skyhook build a Database which links WLAN BSSIDs to a geographic location. A BSSID is like the MAC address of a access point that gets broadcasted by that access point. It is therefore "public viewable" if the BSSID broadcast is enabled, which is the default for most access points. The BSSID operates on a lower layer as the IP stack, you don't even have to be connected to an access point to receive these broadcasts.

So, essentially, when you ARE using WiFi and GPS, Google's database of BSSIDs is updated with a geographic location associated with that BSSID, as you've assumed. In your case, your AP is sending beacons advertising its BSSID, and because it is already in Google's database, Google Maps knows where you are based on the location of that AP.

So it's not that the ISP is giving Google the location of their routers, it's that your phone has already helped to build a database of the Access Points around you, and Google uses this data for geolocation.

Sadly, even if you get a new router and keep any and all Android devices away from it, **they will still be able to approximate your location based on the cell towers your phone connects with (or maybe even your neighbor's AP!), but it won't be nearly as accurate.**

---
Although turning off this "feature" (GPS/location etc) on your phone (and other devices) seems like the best way to prevent your BSSID from being added to the database, this isn't necessarily the case. You've got other people's phones, the phones of passers-by, and even Google's own Street View cars to contend with

---
As I said in comment 3
> Because google has mapped the entire universe's wifi names etc, so yur f**ked mate

**Comment by Thorin-Oakenpants** [comment]
Oh yeah, even with no WiFi or GPS, you still have cellular data turned on. That means that the phone is in communication with the local cell towers. Android uses cell tower geolocation to estimate your current location. If you're in a larger populated area, like a city, your phone will usually get signals from more than one cell tower. So picture the intersection of overlapping slices from tower A, tower B, tower C, and tower D. The intersections define a smaller and smaller area. Google a giant database(s) of all this - tower IDs, positions mapped with GPS, signal strength, etc - they've mapped universe

https://developers.google.com/maps/documentation/geolocation/intro <-- tip of the iceberg

The Play Store has some hideous shit as well, but lets not go there

Hide/protect yourself all you like, they only need to connect two dots

**Comment by bonbonboi** [comment]
So in the end, that's the present life, we have to accept it as it is. Google/ M$/ FB etc...  uses latest technology to use/sell intelligence information, so deal with it.

**Comment by RoxKilly** [comment]
To Google's credit, it does seek your permission to do some of this dirty. Every time I enable my GPS radio, I see [this popup](https://forums.androidcentral.com/samsung-galaxy-s4/788316-improve-location-accuracy.html) and press "*Disagree*"

**Comment by Thorin-Oakenpants** [comment]
Just wait until they have your face in their databases and the world becomes one giant [surveillance advertising platform](https://www.techdirt.com/articles/20170616/08400337606/facial-recognition-software-brings-personalized-ads-to-supermarket.shtml) .. and you just *know* google will own all that .. I'd stick a bucket on my head and become Lord Buckethead, except that would make me stand out more... and the name is [already taken](https://en.wikipedia.org/wiki/Lord_Buckethead)

**Comment by Atavic** [comment]
> So in the end, that's the present life.
Until the 90s the world progressed without cellular phone.

> To Google's credit, it does seek your permission to do some of this dirty. 
There's no differece, as they got and store the data

**Comment by crssi** [comment]
But Lord-BucketheadOpants for sure isn't taken. :)

**Comment by bonbonboi** [comment]
> Until the 90s the world progressed without cellular phone.

- After that the cold wars begun, every world leader wants to know more about the enemies with ease and comfort, unlike before 90s the spying was going in persons, so when you implement technology, you save a lot of money and human resources, plus you may save your own peoples' lives in minimizing the risk of being caught/killed for being a spy, imagine how it's cool when you sit on your chair, turn on  your terminal, look up for any person, you get their personal info, locations, lifestyle etc..  that's a f*ckin' insane power in your hands. That's where the Information Technology is heading... Hunting persons down with no or most least risks as possible in order to stay on the leading chair.

**Comment by Atavic** [comment]
I don't care about what the world leaders want to know and I won't abide to anything related to any kind of "leading chair".

**Comment by bonbonboi** [comment]
We all hear how most people is ranting every now and then about the privacy by saying" I have nothing to hide" that statement leads to give the leaders more and more power over people. Imagine that you're the only one who do care about your own privacy, but you're a part of something else, eg. home, building,  neighborhood, street, area, city, if you're surrounded with idiots who don't care about their privacy, that going to effect you, their stupidity  breaks your privacy on spot.

**Comment by Gitoffthelawn** [comment]
As soon as technology became powerful enough to harm people, evildoers harnessed it's power to kill or oppress people.

Read about the role of technology in the Holocost.

For example, search for "IBM's role in the holocaust".

Also read about the Japanese internment camps in the United States during World War II, and the role technology played.

Anyone who is accepting of intrusive technology must be ignorant of history.

**Comment by bonbonboi** [comment]
> As soon as technology became powerful enough to harm people, evildoers harnessed it's power to kill or oppress people.

Read about the role of technology in the Holocost.

For example, search for "IBM's role in the holocaust".

Also read about the Japanese internment camps in the United States during World War II, and the role technology played.

Anyone who is accepting of intrusive technology must be ignorant of history.

It's already out there

**Comment by Atavic** [comment]
Timely release: https://wikileaks.org/vault7/document/Elsa_User_Manual/page-8/#pagination

**Comment by bonbonboi** [comment]
> Timely release: https://wikileaks.org/vault7/document/Elsa_User_Manual/page-8/#pagination

Aaagh let's disconnect and rest in peace :(
