### ISSUE TITLE
material.angular.io site broken can't figure out why

### ISSUE THREAD

**Issue by RoxKilly** [ghacksuserjs/ghacks-user.js#156]
With a fresh profile (no extension), and the default `user.js v54` on Firefox 54.0, I am unable to load [material.angular.io](https://material.angular.io/).  With a default config (no user.js), the website loads well.

I can't figure out which setting(s) are breaking the site. Any advice would be welcome.

**Comment by bonbonboi** [comment]
It works while FF in Safe Mode, thus it's add-ons related issue.

**Comment by bonbonboi** [comment]
After looking into my own add-ons I found out "CanvasBlocker" is the issue with your web site.

**Comment by Thorin-Oakenpants** [comment]
Nilla FF55 with the user.js as is, in order to get the site to display (rather than just a tiny blue nav bar across the top), you need to allow cookies (info icon in urlbar>right arrow>more information>permissions>cookies> uncheck it and change from default block to allow. After that everything displays and shows and works (eg side menu under components)

I am not in a container or PB mode, and FF says there is no cookie - but wait, I am in FPI, so maybe it's hidden/protected - will edit this post to report back on that aspect (I can see cookies just fine in my main FF and I have FPI on). I also suspect the cookie setting affects local storage (I am not an expert but these two always seems to be tied in addons etc). IDK.

**Comment by Thorin-Oakenpants** [comment]
^^ I turned of FPI and it still shows no cookie :)

I installed Canvas Blocker
- In "Block readout API" mode everything worked
- In "Fake readout mode" nothing was displayed, completely blank window
- In "Ask for readout API permission", when I clicked OK when prompted after loading the site, it then proceeded to display absolutely nothing

Note: I cleared the cache between tests

**Comment by bonbonboi** [comment]
So what was the conclusion?

**Comment by bonbonboi** [comment]
At CanvasBlocker's options I put "material.angular.io" in the "white list" and everything worked.
All my tests while using the ghacks-user.js
plus that dump site needs JavaScript and cookies to be enabled, that's really a lot of demands. even I don't know what that web site is, I'm just testing blindly...

**Comment by Thorin-Oakenpants** [comment]
The conclusion is whatever @RoxKilly wants to do, and then this ticket can be closed. The site needs "cookies" permissions (which is why the default user.js breaks it, that's all). I suspect Roxkilly will whitelist the site in canvas blocker (assuming that it is being used), until the add-on becomes obsolete (tor uplift will prompt for canvas, hopefully a per site permissions setting).

**Comment by RoxKilly** [comment]
Thanks guys. @bonbonboi I do use CanvasBlocker but I knew something in the `user.js` was causing breakage since as I said in my OP, the breakage would occur on a fresh profile (no addons). @Thorin-Oakenpants  note about cookies makes sense.  My problem is resolved.

**Comment by bonbonboi** [comment]
>  I knew something in the user.js was causing breakage 

what's it?

**Comment by Thorin-Oakenpants** [comment]
```js
/* 2701: disable cookies on all sites [SETUP]
... ***/
user_pref("network.cookie.cookieBehavior", 2);
```

**Comment by bonbonboi** [comment]
I see, I'm using Cookie Controller add-on, so helpful and easy in managing cookies stuff.. I'm using LastPass that add-ons needs some care more than anything else. e.g. to save its cookies, we need extra sub-domains to be in the exception list:
- helpdesk.lastpass.com
- lastpass.com
- loglogin.lastpass.com (hidden, couldn't be controlled by Cookie Controller, needs to be added manually)
- pollserver.lastpass.com (hidden, couldn't be controlled by Cookie Controller, needs to be added manually)
