### ISSUE TITLE
proposed change to all user.js documentation regarding editing

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#158]
in my [user.js](https://github.com/atomGit/Firefox-user.js/blob/master/user.js) i have included a section at the bottom for people to add their changes rather than edit the default prefs

i might suggest doing the same here as this will make updating the file far easier - the user will not have to sift through the entire file and re-edit the defaults

here's what mine looks like if you want to use it...

```
/*
 * =========================
 * BEGIN USER CUSTOMIZATIONS
 * =========================
*/

/*
 * any changes you make to this file should be made in your custom preferences section here between "BEGIN USER CUSTOMIZATIONS" and "END USER CUSTOMIZATIONS"
 *
 * insert your own custom preferences below and uncomment the troubleshooting preferences (ghacks_user.js.parrot)
 *
 * test for syntax errors in your code by entering 'about:config' in the browser address bar, then searching for the preference 'ghacks_user.js.parrot', the value of which should be whatever you set it to below (currently "user settings loaded") if there are no errors in your code
 *
 * for example, if you wanted to change the preference "browser.tabs.warnOnClose" to "true" to receive a warning when you close the browser with multiple tabs still open, then you would copy the preference from above and paste it here, without the two leading comment slashes of course...
*/
//user_pref("browser.tabs.warnOnClose", true);  // optionally, you could write a description here of what this preference is for

// troubleshooting preference below - if you mess up your code the value of this preference will be "syntax error @ BEGIN USER CUSTOMIZATIONS" when you check it in 'about:config' - uncomment to use
//user_pref("ghacks_user.js.parrot", "syntax error @ BEGIN USER CUSTOMIZATIONS");

// add your preferences here between the two troubleshooting preferences

// troubleshooting preference below - if there are no errors in your code, the value of this preference will be - "user settings loaded" when you check it in 'about:config' - uncomment to use
//user_pref("ghacks_user.js.parrot", "user settings loaded");

/*
 * =======================
 * END USER CUSTOMIZATIONS
 * =======================
*/
```

**Comment by earthlng** [comment]
Have you seen [this](https://github.com/ghacksuserjs/ghacks-user.js/issues/124#issuecomment-303085803)? That way users have to do a lot less editing.

**Comment by atomGit** [comment]
thanks for that! i was wondering if FF could load multiple pref files - dang - nice!

**Comment by Thorin-Oakenpants** [comment]
Hang on .. not so fast @atomGit .. I'm thinking of doing something here

**Comment by RoxKilly** [comment]
As it stands, the limitation with both this and @earthlng 's recommendation is that there is no easy way to replace a `ghacks-user.js` value with whatever the default is when we don't know that default. I currently just comment out the line, but that obviously cannot be done if we segment all our modifications to the end of the file

Would be nice if FF implemented a token that can be supplied as the value to `user_pref()` to instruct the browser to use whatever the browser-default is.
```
user_pref("browser.tabs.warnOnClose", %%DEFAULT_VAL%%)
```
/just_venting

**Comment by earthlng** [comment]
> there is no easy way to replace a ghacks-user.js value with whatever the default is when we don't know that default

You should be able to find the default value on DXR. Any prefs in particular that you have trouble finding the default value for?

**Comment by RoxKilly** [comment]
@earthlng not at this time. I've been commenting out the lines I want to skip.  What's DXR?

**Comment by Thorin-Oakenpants** [comment]
DXR = https://dxr.mozilla.org/mozilla-central/source/ . Note you can change source etc etc. Search for things such as preference names, burrow into the code/comments

After #124 [How do you update your user.js] I added an item to the wiki sticky that earthlngs solution should be in the wiki - maybe as "1.5 Maintenance" or "1.5 Keeping up to date" where we can outline the two methods (add to end, use separate files). However, I am personally against these methods because they are too "flawed" IMO (although I am not a user who just wants to download a file every 6 weeks).

There are several downsides to overwriting: forcing a "user set" (i.e from prefs.js) value
1. Mozilla can never enforce a changed default - this is especially important for items such as security measures that are now deemed OK to turn on/off, and what if the meanings behind the values change and the default changes, such as happened with `1260: disable or limit SHA-1` (5 values). What about changes to strings such as blocklists/exceptions etc. You won't pick up on the changes. What about a simple boolean - now your default will be at odds with both ghacks js AND mozilla - well done!
2. Mozilla can't remove a deprecated item (compared to it being commented out and reset, it would fall off automatically).
3. Knowing the default value - looking them up in about:config isn't so bad, and values may differ between builds (eg linux vs windows, esr etc). Looking them up on DXR is an even bigger PITA, and again, point 1, values may change.

I am a big fan of just commenting them out and resetting in about:config. So the problem IMO is knowing WHAT you had commented out. You can still have a section at the end or separate file where you add your own stuff, or override both the ghacks value and the default - but you can also add a list of the prefs to disable - if it's 10 items, it just means 10 items to comment out each release.

```js
/* ROXKILLY's OVERRIDES ***/
user_pref("privacy.sanitize.timeSpan", 4); // default = 1, ghacks = 0

/* ROXKILLY's DISABLED ITEMS
2402   dom.event.clipboardevents.enabled
2404   dom.indexedDB.enabled
2301   dom.workers.enabled
 ***/
```

So when Roxkilly replaces the user.js, he also whips open his other js at the same time and quickly re-comments out those items - search/scroll/ add two slashes. Bit of a PITA maybe. But it's the only way I see to be 100% "correct"

Obviously there are other ways to pick up on changes and merge, or watch commits etc - but let's not go there :)

**Comment by earthlng** [comment]
PSA: apparently what I described [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/124#issuecomment-303085803) doesn't really work reliably (anymore?). It works for adding new prefs but overwriting existing prefs doesn't work at all. I kinda feel bad for providing false information, but not too bad because none of you apparently tested it either xD
sorry guys, back to adding the custom changes at the end of the user.js it is :-1:

**Comment by earthlng** [comment]
^^ if you place this user.js in the profile folder and your custom.js in the "preferences" folder it still works

**Comment by atomGit** [comment]
confirmed - works fine for me - i tested it yesterday and again just now by defaulting a pref that's set in /preferences/*.js and restarting

**Comment by earthlng** [comment]
so you have the ghacks user.js in the preferences folder and your custom user.js in the main profile folder and it works for you, or what? I tested it in my latest ESR and it didn't work that way, maybe it still (or again) works in FF54 (?)

**Comment by Thorin-Oakenpants** [comment]
Works for me on FF54 portable.

profile/user.js
user_pref("testing123", "user.js value");
restarted, checked value = tick

profiles/preferences/override.js
user_pref("testing123", "override.js value");
restarted, checked value = tick, overrode

**Comment by Thorin-Oakenpants** [comment]
> The user.js in the main folder is always applied last and overwrites all the prefs applied from (multiple) js files under preferences

So did you get this back to front?

**Comment by earthlng** [comment]
lol, what was the value then? "override.js value" I'm sure, right?
But that was not what I described in my comment. I thought user.js always comes last and would overwrite everything else. I also tried to put both files in preferences and the zzz.js didn't overwrite aaa.js either.

**Comment by Thorin-Oakenpants** [comment]
> lol, what was the value then? 

Exactly as described. the string value "user.js value" was what was originally applied via profile/user.js. When I then introduced a profile/preferences/override.js, and restarted, the string value was replaced by the one in override.js - namely "override.js value".

I know that's not what you said, hence the subsequent post. Where did you get this info about the profile user.js being applied last?

**Comment by earthlng** [comment]
> Where did you get this info about the profile user.js being applied last?

Oh now you ask, huh? xD
IDK but it's in the freakin main profile folder. It also doesn't make any sense to me that zzz.js does not overwrite aaa.js. Confusing AF

https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences
> 3. Load user pref files, first prefs.js, then user.js

I can't even find any official infos about the possibility of having a "preferences" folder, at all.

Yeah sorry guys, I know that makes me the Fake News peddler around here, once again xD
I will make use of my right to remain silent from now on ;)

**Comment by Thorin-Oakenpants** [comment]
I was just there, been reading for 5 minutes

> The administrator may add an all-companyname.js preference file (install_directory/browser/defaults/preferences/all-companyname.js).  This will be parsed last during the preference loading process.

It makes sense for the non "user.js" to get parsed last. Was going to say I think I will test without the preferences folder.

**Comment by Thorin-Oakenpants** [comment]
lulz

> Note: because of abuse of user.js preferences, support for user.js may be removed in a future version of Firefox.

**Comment by atomGit** [comment]
> so you have the ghacks user.js in the preferences folder and your custom user.js in the main profile folder and it works for you, or what?

the other way around - /profile/user.js (ghacks) and /profile/preferences/atom.js - the latter overwrites the values of the former, as it should

FF v54

**Comment by Thorin-Oakenpants** [comment]
^^ same at atomGit - /profile/user.js (ghacks) and /profile/preferences/darkinsectoverlord.js (with overrides that get applied last)

**Comment by Thorin-Oakenpants** [comment]
**Dread Pirate Pants**: [Pants takes both goblets and turns away from Earthlng so he can not see to which directory he adds the iocane] All right. Where is the poison? The battle of wits has begun. It ends when you decide and we both restart Firefox, and find out who is right...and who is dead. 

**Earthlng**: Now, a clever man would put the poison into his own custom js, because he would know that only a great fool would reach for what he was given. I am not a great fool, so I can clearly not choose the user.js in front of you. But you must have known I was not a great fool, you would have counted on it, so I can clearly not choose the custom.js in preferences.

**Dread Pirate Pants**: You've made your decision then?

**Earthlng**: Not remotely. Because iocane comes from Australia, as everyone knows, and Australia is entirely peopled with criminals, and criminals are used to having people not trust them, as you are not trusted by me, so I can clearly not choose the user.js in profile/.

**Dread Pirate Pants**: Truly, you have a dizzying intellect.

**Earthlng**: WAIT TILL I GET GOING! Where was I?

**Dread Pirate Pants**: Australia.

**Earthlng**: Yes, Australia. And you must have suspected I would have known the powder's origin, so I can clearly not choose the custom.js in /preferences/.

**Dread Pirate Pants**: You're just stalling now.

**Earthlng**: You'd like to think that, wouldn't you? You've beaten my giant, which means you're exceptionally strong, so you could've put the poison in your own user.js in /profile/, trusting on your strength to save you, so I can clearly not choose the js in front of you. But, you've also bested my Spaniard, which means you must have studied, and in studying you must have learned that man is mortal, so you would have put the poison as far from yourself as possible, so I can clearly not choose the custom js in the longer directory path of /preferences/. 

**Dread Pirate Pants**: You're trying to trick me into giving away something. It won't work

**Comment by crssi** [comment]
FF is processing user.js in main folder first and then everything in the preferences subfolder, but I didn't test yet the order, since I am using only one file.
First time that I have used this, was when @earthlng mentioned some time ago, maybe when FF v49,  and it was so already back then. Back then I have noticed its reversed order than mentioned, but I have forgotten to mention it for general knowledge. :(

**Comment by Thorin-Oakenpants** [comment]
[1.5 Keeping Up To Date](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.5-Keeping-Up-To-Date)

first draft up ready for all you nit picking bastards. When it's done, we can maybe add something to the user.js in the top section

**Comment by Thorin-Oakenpants** [comment]
@RoxKilly Does this answer you question on what to do with prefs you do not know the default value for?

**Comment by Thorin-Oakenpants** [comment]
Note: I changed the path to the Troubleshooting page. It had a colon it in when all the others did not

was `1.4: Troubleshooting` - now `1.4 Troubleshooting`. This changes the url - I fixed it in three places in the wiki and 5 or 6 places in comments in the repo comments. Think I got them all

**Comment by Thorin-Oakenpants** [comment]
earthlng wrote
> https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences
>> 3. Load user pref files, first prefs.js, then user.js

That's the LOAD order. If you read down it says
> Preference conflicts are resolved in favor of the last entry

Example given
- Load prefs, then config, then user.js
- Conflict: for example, user.js takes precedence over prefs.js

So now I know how you misread that and got it arse about face. I'll let you off this time xD

**Comment by RoxKilly** [comment]
@Thorin-Oakenpants  nice write-up. The update is a high-maintenance kludge but I don't see any way around it until someone with a very particular set of skills creates a tool that can parse the old `user.js`, the new `user.js`, and the `override.js` to produce a new `override.js`.  Even then, given that settings must be reset from within about:config to undo changes, we're a long way from anything user-friendly.

> Does this answer your question on what to do with prefs you do not know the default value for?

Oh, yeah -- you did answer my question

**Comment by earthlng** [comment]
> Even then, given that settings must be reset from within about:config to undo changes

you can also remove them from prefs.js instead which can easily be done with a script

**Comment by Thorin-Oakenpants** [comment]
Its more than that really. You have to comment them out *and* reset them (either in prefs.js or via about:config).

I like RoxKilly's idea for a default variable - maybe someone could file a bug - it should be fairly trivial IMO - as the code parses each `*pref`, if the value is `%%DEFAULT_VAL%%` then remove the item from `prefs.js`. Just need some rules - eg clarify how this works with lock_pref

**Comment by Thorin-Oakenpants** [comment]
Just throwing this out there... re lite & hardened versions... because there are so few changes, rather than maintain another branch, I was going to simply create two topics and list the items to change. Now I think it's easier to just provide two extra js files (to stick in `profile/preferences`). Certainly can do for hardened (because we will basically only make more settings active) - but would be trickier and more maintenance with a lite version (but we can look up defaults)

eg
```js
/*** This hardened.js works in conjunction with the ghacks user.js. <and add instructions> ***/
/** This js disables saving any persistent data, blah blah blah ***/

user_pref("browser.formfill.enable", false); // 0860
user_pref("browser.formfill.saveHttpsForms", false); // 0861
user_pref("places.history.enabled", false); // 0862
user_pref("signon.rememberSignons", false); //0901
user_pref("permissions.memory_only", true); // 1005
user_pref("security.ssl.require_safe_negotiation", true); // 1201

// etc
```

We would need to test how to control in which order preferences/*.js get loaded (and thus in reverse applied last), so that an override.js will still work (eg if alphabetical, then "lite" and "hardened" come before "override")

That seems simple to me.
- Add `user.js` to `/profile/` (applied first)
- [Optional] add `hardened.js` or `lite.js` to `/preferences/` (which is applied next)
- Add `override.js` to `/preferences/` for personal final tweaks (applied last)

**Comment by earthlng** [comment]
I'm willing to give it a shot to create such a tool but I'm not sure what users expect it to do exactly.
I already have a script that detects changes in 2 user.js files, which I use to create the changelogs.
It detects all the following categories of changes.

* removed or deprecated in new user.js
==> keep them around with the old value?
* new
==> what to do with those?
  * one thing is to remove a "future-proof" pref from OR.js (if the value matches!) since it's now in the user.js, 
  * for the rest show a list to notify the user about the new prefs? or comment them out in the new user.js?
* new but inactive
==> just show them to the user, minus the ones already in the OR.js?
* activated
==> keep commented out?
* activated + changed the value
==> ???
* commented out
==> keep active? ie copy them to OR.js as active?
* commented out + changed the value
==> keep active with old value? ie copy to OR.js with old value
* changed value
==> keep old value? ie copy to OR.js with old value

OR.js = override.js

I would make it so that the new user.js and the prefs.js would only get modified after confirmation in a prompt. fe. "Do you want to comment out these prefs? ..." or "Do you want to remove the following prefs from prefs.js?"
activated (+ changed value) are the tricky ones. Probably need user intervention.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/34d0054d9569a712238f24c7f7c7ed2251c813b4
