### ISSUE TITLE
Memory settings 

### ISSUE THREAD

**Issue by bonbonboi** [ghacksuserjs/ghacks-user.js#160]
Not going to go through ghacks-user.js line by line for now, is there any memory settings changed there? I notice FF uses more memory than before, and getting heavy after sometimes. Could it be add-ons memory leak, I've no idea for now

**Comment by earthlng** [comment]
no "memory settings" per se but cache is disabled by default. Can't think of anything else from the top of my head that could cause increased memory usage.

**Comment by bonbonboi** [comment]
I think it could be something prevent FF to use swap page, instead its continue filling up ram
I remember that happened that time when I used Tor browser hardened version, even later its developers commented about that thing, I hope ghacks-user.js got nothing to do with that, also the FF private window is heavier than I used to feel before ghacks-user.js.. any way I'll investigate the root of that thing, would post again later..

**Comment by Thorin-Oakenpants** [comment]
There's really nothing in the user.js that should affect core performance except
- the e10s section which is inactive and there as a FYI
- disk cache which IMO should have no affect if you have plenty of RAM and don't have 100's of tabs open
- GPU / hardware acceleration << if you disable and reset the two prefs under 2508. I would also go to the settings "Options>Advanced>General>Use hardware acceleration when available" and toggle this off and back on to make sure that anything OS specific gets picked up

**Comment by bonbonboi** [comment]
What's the propose of e10 section?

**Comment by Atavic** [comment]
It's under 1100 section.

**Comment by bonbonboi** [comment]
A lot of graphics related settings are disabled , webgl 2d 3d etc.. I doubt if FF still that usable, I'm facing difficulties  with cookies and lastpass, feeling like to go back to use vanilla FF with some slight tweaks..

**Comment by 2glops** [comment]
Cookies are disabled by default, thus logins are problematic. 
You have to either edit the user.js or install a cookie manager.

**Comment by bonbonboi** [comment]
> Cookies are disabled by default, thus logins are problematic You have to either edit the user.js or install a cookie manager.

I know that, I turned everything off, I exit FF, launched it again my cookies in the exception list keeps get deleted...

**Comment by Thorin-Oakenpants** [comment]
@bonbonboi 

Try a brand new profile and add the user.js. Excluding video performance (gpu/hardware acceleration will make a difference), there really is NOTHING that will cripple/ruin FF's performance. Your problems are more likely to be with extensions - you have already (I think) mentioned decentraleyes being slow (or maybe that was someone else). I'm not having any of these problems - default user.js and I have decentraleyes. Going to close this ticket.

---
As for your cookies problem, try removing all the entries: about:preferences#privacy
- Exceptions
  * remove the entries for allowed or whatever you have in there - make a list first for later
- Show Cookies
  * Remove them all

Now go to each site you wanted the exception and click on the info icon in the urlbar>right arrow>more information>Permissions tab> Set Cookies - uncheck use default and tick "Allow" or "Allow for Session".

I have the same issue with Cookie Controller. Items added via CC work fine, items added manually are not respected by CC. CC of course has an extra setting (Allow first party only).

I do not know why your cookies seem to be messed up, but if you're like me - I have about 20 entries for cookies since everything is blocked by default, so it should be easy to make a quick list, clear it, wipe cookies, re-add exceptions.
