### ISSUE TITLE
FYI: Tor Browser Security Slider prefs

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#161]
Tor Browser 7.0.1

### Low Security:
```js
user_pref("media.webaudio.enabled", true);
```

### Mid Security:
```js
user_pref("extensions.torbutton.security_slider", 2);
user_pref("gfx.font_rendering.opentype_svg.enabled", false);
user_pref("javascript.options.baselinejit", false);
user_pref("javascript.options.ion", false);
user_pref("javascript.options.native_regexp", false);
user_pref("mathml.disabled", true);
user_pref("media.webaudio.enabled", false);
user_pref("noscript.forbidMedia", true);
user_pref("noscript.global", false);
user_pref("noscript.globalHttpsWhitelist", true);
```

### High Security:

**all the prefs from Mid Security plus the following changes:**
```js
user_pref("extensions.torbutton.security_slider", 1);
user_pref("noscript.forbidFonts", true);
user_pref("noscript.globalHttpsWhitelist", false);
user_pref("svg.in-content.enabled", false);
```

Apart from the NoScript & TBB-only prefs, the only pref we don't have in the user.js is
`user_pref("javascript.options.native_regexp", false);`

**Comment by Thorin-Oakenpants** [comment]
Hah .. I was actually going to grab default and various slider pref.js files and compare them at some stage. The question above is what changes with the meta setting extensions.torbutton.security_slider

**Comment by Thorin-Oakenpants** [comment]
### Low Security
- `media.webaudio.enabled` - does not exist in FF (DXR shows a single test)

### Mid Security
- `gfx.font_rendering.opentype_svg.enabed` - 1403
- `javascript.options.ion` + `javascript.options.baselinejit` - 2421 (INACTIVE)
- `mathml.disabled` - 2663

### High Security
- `svg.in-content.enabled` - does not exist in FF, nothing in DXR
   * The pref is 2671 `svg.disabled` which is INACTIVE

A hardened js could include the SVG, Baseline JIT and ION. The last two were problematic (I tried it for 6 months, caused weird odd behavior and performance issues ), and of course in-content SVG would break lots since SVG is common, hence they are inactive in our default.

I've looked in depth before at TBB. Followed every release & notes/tickets, followed tickets, checked prefs - its where a lot of the js content originally came from when I compiled it. I still think they're missing things - eg in v 7.0 they disabled social items, but completely missed the hidden master pref (unless they changed its value behind the scenes).

**Comment by Thorin-Oakenpants** [comment]
FYI: https://trac.torproject.org/projects/tor/ticket/13612

Here's Arthur's patch: https://github.com/arthuredelstein/tor-browser/commit/13612 - I do not see a `user_pref("social.enabled", false); // (hidden pref)`

**Comment by Thorin-Oakenpants** [comment]
`javascript.options.native_regexp`

Could add this as inactive at 2419. 2420=asmjs, 2421=baselinejit+ion. But would need some more info on why it's a threat

**Comment by Thorin-Oakenpants** [comment]
!bump @earthlng - can we decide on `javascript.options.native_regexp` ? If its not needed then lets close this. At some stage, maybe after the first TBB based on ESR59, we should do a full diff - check all their default values

**Comment by earthlng** [comment]
> would need some more info on why it's a threat

**Comment by Thorin-Oakenpants** [comment]
https://trac.torproject.org/projects/tor/ticket/21865

**Comment by Thorin-Oakenpants** [comment]
> It turns out that the JIT *.content prefs are gone for a while now. This happened in https://bugzilla.mozilla.org/show_bug.cgi?id=939562 and the patch updates the security slider to take this into account. We got the tip to include `javascript.options.native_regexp` as well.

What tip? Why disable the regex one only at the top level of the slider? :headspin:

**Comment by Thorin-Oakenpants** [comment]
[DXR](https://dxr.mozilla.org/mozilla-central/search?q=javascript.options.native_regexp&redirect=false) 
Its disabled on Android, other than that I can't follow how this is used. The tor ticket (currently last comment) says _"If the idea is to disable JIT entirely..."_ so I think that was their goal, not that it is a security risk, i.e ey added this to cover their asses. Also the first comment says _"So since ESR31 we have just been switching off optimizations which don't exist. Unbelievable :)"_ - is he saying that these are dead prefs?

`2420` **asmjs** - disabled works well
`2421` **baselinejit+ion** - disabled caused issues - lots of things, just weird behavior eg comboboxes not responding, mega downloads failing. I ran with it myself for 6 months. In the end we made it inactive

Not that there aren't security issues: https://github.com/tunz/js-vuln-db - handy page of javascript CVEs. Here's the regexp ones
- [CVE-2016-1669](https://bugs.chromium.org/p/chromium/issues/detail?id=606115)
- [CVE-2016-1688](https://bugs.chromium.org/p/chromium/issues/detail?id=604897)

I do not think adding `javascript.options.native_regexp` will achieve anything (for us). It will probably break loads of stuff IMO. Its all way over my head and I cannot find anything else about it. Tried looking on CVE and got a headache.

At most we could do a little revamp of 2400's (currently 17 items with large gaps in numbering) and get these three JIT items (2420+2421+the new one) in order - noting that baseline+ion + regexp are for uber hardened at your own risk (there must be a reason TBB disabled it).

**Comment by earthlng** [comment]
> is he saying that these are dead prefs?

No, I think he means the ones they had previously ie this:

> It turns out that the JIT *.content prefs are gone for a while now.

Yeah I agree let's ignore it. It's not clear at all whether the alternative (non-native-regexp?) is any safer or whatnot. They don't seem to know exactly why they disabled it either.
