### ISSUE TITLE
Contradictory settings for DNT

### ISSUE THREAD

**Issue by stebeh** [ghacksuserjs/ghacks-user.js#163]
You write "1610: ALL: disable the DNT HTTP header (this is essentially USELESS and raises entropy)"
However, setting user_pref("privacy.trackingprotection.enabled", true); causes a DNT header to be sent.
Tested with FF52 ESR against https://browserleaks.com/donottrack.

Proposal to set user_pref("privacy.trackingprotection.enabled", false); in line with what you wrote under 1610. False is also the default in FF52.

**Comment by Thorin-Oakenpants** [comment]
Interesting

DNT is a must-opt-in protocol. If you open a PB mode window (which uses TP), it does not state ANYWHERE that DNT will be used. If you take the Learn More link, on the subsequent page it mentions DNT and how to turn it on - it implies DNT is a different setting and not tied to PB mode or TP.

In my tests with Panopticlick it shows DNT is not enabled (I have TP on in both normal and PB mode, as per user.js). If I click on the browserleaks link it says I DO have DNT on.

Panopticlick
>Does your browser unblock 3rd parties that promise to honor Do Not Track? 	✗ no"

Browserleaks
> DNT	✔ True (1)
JavaScript ways to detect Do Not Track
navigator.doNotTrack	✔ True (1)
window.doNotTrack	× False (undefined)
navigator.msDoNotTrack	× False (undefined)

Maybe @fmarier can elaborate, because I certainly didn't ever agree to allowing DNT, and the settings involved can all be set from the UI. In fact if I go to about:preferences#privacy, and click on Manage your DNT settings, it pops up a modal dialogue and the option is unchecked.

FF seems to be breaking the terms of DNT as laid out by the EFF

PS:
JonDonym shows DNT is enabled
AmIUnique shows DNT is enabled

Now I'm really annoyed.

**Comment by Thorin-Oakenpants** [comment]
I am not condoning this, but if you use NS, you can still force DNT to be false - however, it needs to be thought through - it might raise your entropy (not that I think any site can detect if you use TP mode)

The real solution is for Mozilla to explain this aberrant behavior

**Comment by Thorin-Oakenpants** [comment]
In a new PB window, under Tracking Protection, there's also a [See how it works](https://www.mozilla.org/en-US/firefox/54.0.1/tracking-protection/start/) button - but in four different browsers I cannot get this page to load, it just shows five large bordered div elements with nothing in them (all protections/blocks disabled)

**Comment by earthlng** [comment]
> Ummm, I already have noscript.doNotTrack.enabled -> false, so it still leaks navigator.* it seems

what does navigator.* have to do with DNT?

> JonDonym shows DNT is enabled
AmIUnique shows DNT is enabled

You don't need testsites to check for the DNT header. FF's Network Monitor shows you the Headers

**Comment by Thorin-Oakenpants** [comment]
@earthlng I know I can see the headers :) When I said navigator* I was referring to the browserleaks result (see below). Back when I was testing the two DNT prefs (one is obsolete) I had trouble getting it to work and it was compounded by NS having a setting as well. That is, it seems NS overrode the FF setting (I would disable DNT but it would show as enabled on test sites, and I assume vice versa). IDK, it was ages ago, and I thought this sh*t was behind us, only to find that Panopticlick has lied to me all this time, and now so too is the setting displayed in preferences, and I have been opted in without my permission.

> navigator.doNotTrack ✔ True (1)
window.doNotTrack × False (undefined)
navigator.msDoNotTrack × False (undefined)

**Comment by earthlng** [comment]
see, I told you not to enable TP xD
a simple userscript + an addon to strip the header is enough to opt you out again though.

navigator.doNotTrack is set to "unspecified" when DNT is disabled

**Comment by earthlng** [comment]
...or just go with it and enable the DNT pref as well

**Comment by Gitoffthelawn** [comment]
I think a few sites honor DNT, so even though it's "honor-based", it's not all bad in and of itself.

The question is what percentage of Firefox users are sending a DNT line as part of their HTTP/S request headers.  That way, you can determine whether or not disabling DNT in the header increases or decreases entropy.

**Comment by Atavic** [comment]
We discussed DNT [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/4#issuecomment-280860992), by scrolling down you see Pants results on Panopticlick, Am I Unique and Browserprint where roughly half the users have DNT disabled.

**Comment by Thorin-Oakenpants** [comment]
In terms of FP, DNT enabled is bad. The (small) datasets (approx 50/50) from those test sites are skewed (and now I think Panopticlick's method is flawed). See my comments in Atavic's link above. I cannot find the source(s) but I have read several times now that Mozilla's telemetry showed approx 20% of users had DNT, which is much more realistic. **This however, is not the question** (if you think it is, then the answer is we do not want DNT)

The question is why is TP enabling DNT when it is opt-in and 1. There is nothing anywhere in the UI or relevant links that says DNT will be enabled and 2) the checkbox in preferences still states DNT is off.

FF needs to EITHER
- 1) Make the DNT checkbox status display actual behavior and 2) Explicitly state that TP enables this pref and control the checkbox accordingly - stop hiding the pref behind a popup (it's TWO LINES per god's sake) and put in front and center underneath the TP choices
OR
- Stop flipping DNT with TP preferences

Who do we complain to?

**Comment by Thorin-Oakenpants** [comment]
FYI and OT:
- Here is DNT stats from 2011: Approx 5% - https://blog.mozilla.org/metrics/2011/09/08/understanding-dnt-adoption-within-firefox/
- Here is an independent study 2011: Approx 6% - https://gigaom.com/2011/08/12/419-new-study-shows-use-of-do-not-track-is-on-the-rise/

^ Early days, compounded by the fact that 40% of users were still on FF versions that did not have DNT

- 2013 - https://blog.mozilla.org/netpolicy/2013/05/03/mozillas-new-do-not-track-dashboard-firefox-users-continue-to-seek-out-and-enable-dnt/ .. but the metric dashboard no longer exists
  * DNT adoption in the U.S. Firefox user base is approximately 17 percent. Globally, the average is around 11 percent.

Interesting but its not today's metrics or with user's perceptions today about advertisers. So in 2 years it went from 5 or 6% to 11%. The growth rate probably declined. I still think 20% is about right.

But it's a moot point. Within FF users, default off is well, the default (and no way has FF achieved a 50% opt-in success rate on this), and the only reason to enable it would be when it's enforced (eg by tor uplilft - and they don't want a bar of it, and neither do we)

**Comment by RoxKilly** [comment]
@Thorin-Oakenpants [wrote](https://github.com/ghacksuserjs/ghacks-user.js/issues/163#issuecomment-312837601):

> if I go to about:preferences#privacy, and click on Manage your DNT settings, it pops up a modal dialogue and the option is unchecked - so FF is lying to me.

FF is not lying to you. You just misread an (admittedly) ambiguously worded dialog.  Take another look:

![24](https://user-images.githubusercontent.com/12346501/27850316-c7cffd7c-6121-11e7-9b2f-5cbd78720ba7.png)

* Checking the box instructs FF to always send DNT, even when Tracking Protection is off
* Underneath the checkbox is a note that FF **will** send DNT **whenever** Tracking Protection is on

This is why you find that DNT is set when Tracking Protection is enabled.  FF tells you so.

@Thorin-Oakenpants  [wrote](https://github.com/ghacksuserjs/ghacks-user.js/issues/163#issuecomment-312837601):

> DNT is a must-opt-in protocol...FF seems to be breaking the terms of DNT

A (good) argument can be made that when the user opts into Tracking Protection (which he must do since it's disabled by default), she is opting into the option to disable tracking, hence into DNT. I don't think FF broke the spirit of DNT (I didn't read the technical requirements of the UI)

**Comment by Thorin-Oakenpants** [comment]
Ahhh. Thanks @RoxKilly . This smacks a little of [Dark Patterns](https://darkpatterns.org/). Its not mentioned on the links anywhere or in the relevant areas (eg where you **actually** turn TP on or off), ONLY in a popup buried clicks deep, and even then it caught me out (my fault, the wording is technically correct - I still stand by the fact that is TP is always on, this checkbox should be automatically checked). Maybe the prefs UI overhaul will fix this (hiding the option another click deep)

@earthlng 
> a simple userscript + an addon to strip the header is enough to opt you out again though

Where is this user script, and where is this Web Extension. I would like to keep TP always, but add the info/link to always block DNT.

As for the user.js, I think I'll do as @stebeh suggested and add the reason why

**Comment by Thorin-Oakenpants** [comment]
DNT as a FP is binary (essentially one bit at 50/50), but tracking protection actually protects against far more accurate tracking mechanisms. DNT can be implemented web wide, but TP only covers a very small part of the internet. Another factor is TP is on by default for PB mode, and PB mode is detectable, so no DNT disabled in PB mode would make you more unique. That doesn't mean we should not try to deal with DNT.

For most people, enabling TP across all windows far outweighs the chance of DNT helping FPing. So, it's a trade-off. But if you have uBo etc, TP kicking in is very rare.

I'm stil confused as to what to do here. There are sufficiently huge numbers of FF users (at 20% it would be 80-100 million?) with DNT that the FPing is almost a moot point.

**Comment by Thorin-Oakenpants** [comment]
nits anyone?

```js
/* 1610: ALL: disable the DNT HTTP header, which is essentially USELESS
 * It is voluntary and most ad networks do not honor it. DNT is *NOT* how you stop being data mined.
 * Don't encourage a setting that gives any legitimacy to 3rd parties being in control of your privacy.
 * Sending a DNT header *highly likely* raises entropy, especially in standard windows.
 * [SETTING] Options>Privacy>Use Tracking Protecting>manage your Do Not Track settings
 * [NOTE] DNT is enforced with TP (see 0420) regardless of this pref (eg in default PB Mode)
 * [NOTE] If you use NoScript MAKE SURE to set the pref noscript.doNotTrack.enabled to match ***/
user_pref("privacy.donottrackheader.enabled", false);
```
^^ fixed setting info (it must have changed recently), plus better info

```js
/* 0420: enable Tracking Protection in all windows
 * [NOTE] TP sends DNT headers regardless of the DNT pref (see 1610)
 * [1] https://wiki.mozilla.org/Security/Tracking_protection
 * [2] https://support.mozilla.org/en-US/kb/tracking-protection-firefox ***/
   // user_pref("privacy.trackingprotection.enabled", true); // default false
   // user_pref("privacy.trackingprotection.pbmode.enabled", true);  // default true
```
^^^ no change to the values, just make it all inactive - so by default end users stay at defaults which is probably the best mix

**Comment by Thorin-Oakenpants** [comment]
Wow .. look at all the ad companies committed to honoring DNT - http://donottrack.us/implementations (may be outdated a little, there's no date - I expect many of these have since dropped DNT and no new ones come on board)

[2014 article](http://www.computerworld.com/article/2489727/data-privacy/internet--do-not-track--system-is-in-shatters.html)
> But maybe the list should be empty. "There is no such thing as Do Not Track right now," said Mike Zaneis, executive vice president, public policy, and general counsel at the Interactive Advertising Bureau. "It's a gimmicky marketing term," he said

^^ that's approx 2+ years or so after DNT was launched/ramped up (a Feb 2012 pledge from tech/advert companies at the white house - DNT itself is older). It hasn't gotten any better. It's a complete waste of bandwidth :) It doesn't even stop the tracking and retention of data - it doesn't even stop the adverts.

:middle_finger: to all adverts

**Comment by fmarier** [comment]
> You misread the checkbox as giving you the option to enable or disable DNT, when it's actually giving you the option to enable it always or only when TP is on.

That confusing dialog / set of options has hopefully been made clearer in Nightly:

![tracking-prefs-nightly](https://user-images.githubusercontent.com/167821/27882271-8db049c2-61bb-11e7-9f21-44d824c630f7.png)

> A (good) argument can be made that when the user opts into Tracking Protection (which he must do since it's disabled by default), she is opting into the option to disable tracking, hence into DNT. I don't think FF broke the spirit of DNT. Indeed I think it would be exceedingly confusing to ask the average user to separately:
>
> - opt into tracking protection setting
> - opt into do-not-track setting

@RoxKilly nailed it. The two options confused our users who thought they were protected from tracking when they enabled DNT but not TP.

When it comes to the spirit of DNT, the spec says that ["the signal sent must reflect the user's preference"](https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html#determining). If a user chooses to go into Private Browsing or enables TP, then we argue that they have expressed a preference against being tracked.

> I'm stil confused as to what to do here. There are sufficiently huge numbers of FF users (at 20% it would be 80-100 million?) with DNT that the FPing is almost a moot point.

Firefox telemetry shows that [17% of Nightly 56 users have DNT enabled](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2017-07-04&keys=__none__!__none__!__none__&max_channel_version=nightly%252F56&measure=DNT_USAGE&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2017-06-13&table=1&trim=1&use_submission_date=0) (it's lower in Beta). But that's severely undercounting the signal since it's sent by default whenever users use Private Browsing (because TP is enabled there) and we don't collect telemetry for Private Browsing.

**Comment by Gitoffthelawn** [comment]
@fmarier That's a huge improvement! 👍 

It would be beneficial to have a "Never" option for the "Send websites a Do Not Track signal..." option.

Alternatively, it likely would make more sense (and improve the UX) if the options for "Send websites a Do Not Track signal..." simply paralleled those for the "Use Tracking Protection..." option:

   1. Always
   2. Only in private windows
   3. Never

**Comment by fmarier** [comment]
> It would be beneficial to have a "Never" option for the "Send websites a Do Not Track signal..." option.

The only option is to also disable TP. The reason is that the Disconnect list relies on the [EFF's DNT policy](https://www.eff.org/dnt-policy).

If a tracker complies with it (none of them do at the moment except for [a test domain we control](https://github.com/mozilla-services/shavar-prod-lists/blob/ce41e57e1c9e8cbf6bb2eb4b7645ca45e376c196/disconnect-blacklist.json#L52-L57)) then they get removed from the Disconnect list. This means that if you were to enable TP but disable DNT, you could be tracked by trackers who would otherwise comply with DNT (i.e. don't track you) had you sent them the DNT signal.

**Comment by earthlng** [comment]
Thanks for that info @fmarier. Good to know. But doesn't that also mean that mozilla will never enable TP (+ therefore DNT) by default in non-private windows because you require the user to Opt-In for DNT?

**Comment by Thorin-Oakenpants** [comment]
As far as I'm concerned, DNT is a binary option that adds to entropy and offers ZERO in return. It should be dropped altogether :) What really annoys me is that if a company adheres to it, they are removed from TP. WTF? The company will still serve you adverts. Just as well no-one signed up or else TP would be useless as well.

**Comment by fmarier** [comment]
> But doesn't that also mean that mozilla will never enable TP (+ therefore DNT) by default in non-private windows because you require the user to Opt-In for DNT?

So far we've always talked about TP being opt-in in normal mode, not opt-out like it is in Private Browsing.

> The company will still serve you adverts. Just as well no-one signed up or else TP would be useless as well.

TP is meant to block trackers, not all ads. If the web moved from behavioural ads to non-tracking ads, that would be a huge improvement from a privacy point of view.

And there will always be uBlock Origin & friends for those who want to block all of the ads.

**Comment by Thorin-Oakenpants** [comment]
It would be interesting to see what percentages of nightly users are using
- resistFingerprinting
- FPI
but I have no idea how to drive that metrics dashboard
