### ISSUE TITLE
Outlook Web App: "something went wrong"

### ISSUE THREAD

**Issue by passboltUser** [ghacksuserjs/ghacks-user.js#180]
Hi,
I created a fresh new Firefox profile and put your master `users.js` (no additional plugins), started FF, went to an Outlook Web App site and I get:
![exchange](https://user-images.githubusercontent.com/29798595/28561258-f05e336a-711d-11e7-8ab5-b97aa1c6cedb.png)
Which setting do I need to change so that Outlook Web App is working? (except of course not to use proprietary M$ products)

**Comment by crssi** [comment]
Indexdb

I dont have access at this time to check more informative

On 25 Jul 2017, at 09:48, passboltUser <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I created a fresh new Firefox profile and put your master users.js, started FF, went to a Outlook Web App site and I get:
[exchange]<https://user-images.githubusercontent.com/29798595/28561258-f05e336a-711d-11e7-8ab5-b97aa1c6cedb.png>
Which setting do I need to change so that Outlook Web App is working? (except of course not to use proprietary M$ products)

-

**Comment by crssi** [comment]
2404

On 25 Jul 2017, at 09:48, passboltUser <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I created a fresh new Firefox profile and put your master users.js, started FF, went to a Outlook Web App site and I get:
[exchange]<https://user-images.githubusercontent.com/29798595/28561258-f05e336a-711d-11e7-8ab5-b97aa1c6cedb.png>
Which setting do I need to change so that Outlook Web App is working? (except of course not to use proprietary M$ products)

-

**Comment by passboltUser** [comment]
Thanks.
