### ISSUE TITLE
About 2697: USER AGENT (UA) SPOOFING

### ISSUE THREAD

**Issue by rebrovov** [ghacksuserjs/ghacks-user.js#193]
Maybe it's time to change ESR 45 to ESR 52?

**Comment by Thorin-Oakenpants** [comment]
Did you mean for the user.js to update the values in the 2697 section? Btw, you don't spoof as ESR, you just spoof the version.

If you are using Firefox stable, then come next release you will be spoofed across a large number of navigator variables, exactly the same across a large subset of firefox users, and it is enforced. Its under the privacy.resistFingerprinting pref. It does not use the 2697 prefs, but hardcodes them - hopefully it will also patch some of the "leaks" in navigator onjects.

The version number is to round down to the nearest multiple of 10, no need to worry about when major ESRs come out - the code will last for years.

Otherwise, ~~we~~ I do not condone spoofing, because you leak if someone wants to dig, and all that does is raise entropy. It works for privacy.resistFingrprinting because it is enforced and a large subset.

**Comment by Thorin-Oakenpants** [comment]
Sorry, @rebrovov  - did I come across as a bit blunt? Not meant that way. Did my answer satisfy you? Are you on stable and able to use resistFingerprinting ?

**Comment by rebrovov** [comment]
Everything is normal. I found out what I wanted and closed the topic. :)
