### ISSUE TITLE
Is it possible to achieve "You not have unique fingerprints" on panopticlick.eff.org ?

### ISSUE THREAD

**Issue by rebrovov** [ghacksuserjs/ghacks-user.js#195]
Is it possible to achieve "You not have unique fingerprints" on test panopticlick.eff.org ? The maximum I reached "You have nearly-unique fingerprints".

**Comment by Thorin-Oakenpants** [comment]
Absolutely.

Visit the site in your exact same browser config from 20 different IP addresses

**Comment by rebrovov** [comment]
Without changing country ip.

**Comment by Thorin-Oakenpants** [comment]
^^ read my edit in last post

**Comment by 2glops** [comment]
We can't defeat FP, there are too much possibilities for identification.
The best thing which can be achieved is to know our enemies/threats and from there use the more efficient tools. That will make hard times for them to FP you is they really want to.
For Panopticlik (and similar sites), I don't bother too much because their user-base for tests is quite small. The main goal is to identify what is leaking.

**Comment by Thorin-Oakenpants** [comment]
▲▲ what @2glops said, but mine ▼▼ is much better :smiley: Off the top of my head, so its a bit disjointed (I can't write for crap)

Ant-Fingerprinting is really really really hard. Its complex. And there's often no right or wrong answer, and it often depends on other factors - eg who are you trying to defeat.

### Test results are bullshit

First up, these online tests for "uniqueness" are skewed. They are NOT real world in almost every facet. They are visited by privacy conscious people, so the percentages will tend to be a LOT higher. And while fairly impressive, their datasets are not that huge - in fact they are tiny. They are also accumulated over a long period (think browser version numbers), and a lot of data (probably most of it) is from repeat visitors re-checking things with slight tweaks (which in itself, drives the percentages WAY too high). To be fair, amiunique allows you to pull a time range.

example: amiunique says (for me)
> 45.05 % of observed browsers are Firefox, as yours.
> 0.08 % of observed browsers are Firefox 55.0, as yours.
> 6.59 % of observed browsers have UTC0 as their timezone, as yours.

Note: I just upgraded to 55. 54 is shown as 1.55%.

In the real world, Firefox users account for approx 6% overall, just over 12% for desktop. This is a reflection of the real world that Firefox definitely has more privacy built into it than say chrome, and that's its users are more into this stuff on a percentage basis.

If we were to to do some math and say that at 45%, the figure is skewed by a multiplier of approx 7.5 (using 6% as market share). If we then logically extend that to the percentage of say FF54 users (which they say is 1.55%) .. then the proposed real world figure would be more like 0.2 % (that zero point 2). But this is nonsense. Mozilla's own metrics (on around 100 million users) show that FF users are quick to upgrade and something like 80% are on stable. In other words if you are on stable right now (ignoring the 6 weekly upgrade cycle in flux), you would be approx 80% of 12% = 9.6%. If we narrow that down to desktop users, it's more like 4.8% (rough figures). Then we narrow it down by OS .. etc.

These online estimates are a bit of a joke. I could give you a dozen examples. You need to take these test results with a grain of salt, is all I'm saying

### Fingerprinting

Fingerprinting is a collection of data points. The key to beating it in some fashion is to be the same as a significant number of users across a range of values. Each FP data point provides entropy. You want to lower entropy (more on that later). If everyone in the world returned "en-US" as their language, then it would carry an entropy of 1 and be useless for fingerprinting. But because browsers can specify hundreds of languages, the actual entropy is a reflection of real world usage, so it exceeds 1.

A UNIQUE value means you're nailed, on a single value - such as canvas fingerprinting (the odds of a collision are zero to none).

You can attack FPing in two ways. Lower entropy, or raise entropy. Sounds weird right. Take the case of canvas FPing - you can block it (return null or don't reply) or spoof it (lets say the world decided to always return 0000000000000000000000). Or you could *always* return a different value every time it is asked - that is, you hide in the noise.

Another way is to reduce the attack surface (basically don't reply). Examples are disabling access to various APIs (such as network connection info), or plugins, or fonts, and the list goes on. But note that this too is a value.

### You can't beat it

Lets ignore IPs, and referers, and also just focus on the end points (you and the website(s) - some may be 3rd party) - i.e ignore sniffers etc, assume you are on https. HELL, lets assume you are TOR and honeypots do not exist. Let's even ignore cookies and all the various storages that can be reaccessed by first party sites. You're still f**ked. Lets even ignore going to the same site and just purely focusing on this question - can the same FP'ing script on two different sites link your two visits (assuming a global player buys all the data)?

There are literally hundreds of FPing attack points, and most you cannot block or spoof. As fast as some of these are mitigated, more pop up with new web technologies and APIs and so on - tech moves so fast. It has taken four or five years so far for spoofing your user agent and navigator objects properly, and until 56 lands and I test it, it's still not done. And that's just ONE item.

As I said earlier, FPing is really really really complex. When you get it wrong, you create bits and raise entropy. And almost everyone gets it wrong (including me). Lets say you spoof your OS as Windows, but you're really on Linux. If someone does a simple test using a CSS line-height JS query they now KNOW you are on Linux. Congrats, you are now HIGHLY unique because the combo of "On Linux but returns Windows" is very very very small. You were better off saying you were on Linux - thousands of times better off.

And that's just on ONE item. Think how bad it gets with just the 12 or 15 items on these test sites. Now double, triple the things that could be checked for. Browser feature detection and dozens of other things can unmask your LIES. Bad boy! You are toast! We're all toast.

### Well fuuuuuck! How do we beat it.

A combination of things, and this is an oversimplification (people write books on this stuff)
- Reduce the attack surface (disable shit). Not just prefs such as Gamepad API etc, but Javascript, XSS connections etc
- Spoof/Lower entropy  (or raise entropy eg in the case of canvas)
- OpSec

And I will not write an essay on OpSec, sorry.

**Comment by Thorin-Oakenpants** [comment]
Geeze, I wrote all that and misread the question. I have no idea why I read that as amiunique.

> Is it possible to achieve "You not have unique fingerprints" on test panopticlick.eff.org

Yes. First of all panopticlick (since v2) uses canvas in it's calculations, so always spoofing randomly means you will always be unique. You would have to use a set value. THEN you could easily visit ten times a day from ten different IP addresses for 10 days/months/whatevr - vpns, proxies etc - using the exact same browser. Eventually, you will FOOL panopticlick that you are not unique.

All you would achieve is a falsehood, because nothing you did affected the real world

**Comment by Thorin-Oakenpants** [comment]
I also just want to say, that some of the regular commentators at [Bruce Schneier's site](https://www.schneier.com/) (and these guys are hardcore) simply do not use the internet with JS (among other things). I can't vouch for them, but I would assume for as couple that is always, but for the majority of these hard-core guys, that simply means one of their identities = basic OpSec.

Killing JS kills 95% of the FP problems.
