### ISSUE TITLE
What is "Google Key"?  Should it be neutralized?

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#197]
In *about:support*, there is an entry entitled "Google Key".  What is this?  And should we change it to not be listed as *Found*?

**Comment by fmarier** [comment]
It's built-in API key (the same for every Firefox user) that is used by Safe Browsing and Geolocation.

You can't change the key without recompiling Firefox, but you can disable geolocation or switch it to using the Mozilla Location Service.

Safe Browsing on the other hand won't work without the correct API key.

**Comment by Thorin-Oakenpants** [comment]
@fmarier about:url-classifier -> when do we move to google4?

**Comment by fmarier** [comment]
The move to `google4` is currently planned for 56.

**Comment by Gitoffthelawn** [comment]
Thanks @fmarier :)

**Comment by Thorin-Oakenpants** [comment]
@fmarier That's interesting ... Overnight my `...\profile\safebrowsing\` created a google4 directory, which is currently empty.

Most likely, probably, possibly, utterly not important: It did this somewhere between 24 and 36 hrs since I updated to 55 (I know the time stamp of the folder creation, but can't exactly pinpoint/remember my browser update - my update history is blanked, not sure how I did that), but it was certainly after 24 hrs
