### ISSUE TITLE
Randomization versus Uniformity

### ISSUE THREAD

**Issue by Atavic** [ghacksuserjs/ghacks-user.js#205]
[Mr. Pants](https://github.com/ghacksuserjs/ghacks-user.js/issues/203#issuecomment-321690794) wrote that it is far better, where possible, to lower entropy vs randomly-raising it.  Also see: [Draft](https://www.torproject.org/projects/torbrowser/design/#fingerprinting-linkability)

@laserstrike discusses the two options [here](https://intoshadows.com/browser-fingerprinting/).

I keep an eye on the randomization approach because, by uniforming, a user appeals to the lowest common denominator and allows the big actors - ad providers, cdn - to lurk into your surfing habits. I needed something to back this idea and I've found [this issue](https://github.com/easylist/easylist/commit/a4d380ad1a3b33a0fab679a1a8c5a791321622b3) where a site has been **Removed due to DMCA takedown request**.

[DMCA Request](https://github.com/github/dmca/blob/ff44d37f62d772bfec5fd4327e4a2009b9ad47aa/2017/2017-08-02-LevenLabs.md)

>The code in question attempts to circumvent copyright access controls to copyrighted content on the site listed in the title of this commit.

Surely I am pro-copyright control but I'm against browser tracking. While hoping this DMCA takedown won't be a trend in the future, I suggest using different browsers with different approaches.
I Keep a secondary browser with randomized responses, just in case.

**Comment by Atavic** [comment]
Easylist is used by uBlock origin. If that specific URL is whitelisted for appealing to a DMCA request (based on potential circumvention of copyright access) then my browser will load a flawed blacklist.

**Comment by grauenwolfe** [comment]
Saw this article earlier today and almost put my fist through my monitor. Add these two filters in uBlock's "My Filters" to cover this new mandated absurdity:

`||functionalclam.com`

`||functionalclam.com^$third-party`

**Comment by Thorin-Oakenpants** [comment]
OK, all I saw (emails) was the title and I didn't even read the contents - I want to focus on closing FF55 changes first. I just posted about the DMCA bullshittery in my soapbox before I noticed @grauenwolfe's comment. On this subject (DMCA asshattery), adding custom rules is a joke - that's like playing whack-a-mole and does not fix the underlying problem (although I appreciate the info). If you read the commit comments, the EFF have reached out to Easylist. Meanwhile there is talk of moving to gitlab or whatever to bypass this buttfuckery. Simply put, 2 attacks - EFF on the legal front which could take years, and Easylist moving (not forking, we want the lists to be beyond jurisdiction and entries re-added. THIS is not the first entry that has been removed or not added due to liability)

WTF does blocklists and DMCA have to do with "Randomization vs Uniformity" in fingerprinting? So OT it is not funny. 

As for Randomization vs Uniformity - massive topic (beyond the scope of this repo IMO) and each item needs to be assessed on it's own merits. I'm inclined to close and lock this topic :grumpy-face:

**Comment by grauenwolfe** [comment]
> On this subject (DMCA asshattery), adding custom rules is a joke - that's like playing whack-a-mole and does not fix the underlying problem (although I appreciate the info).

Yeah, only going to get worse over the years. And, no idea if those filters listed above will actually help or not... got the info from /r/Firefox. Thread goes on to say that Pete Lowe's Ad tracking list still includes them. Like to reddit thread:
https://www.reddit.com/r/firefox/comments/6t2xpl/ad_blocking_is_under_attack/?sort=new

Done with this I suppose since this isn't related to the topic even though OP brought it (glad you did).

**Comment by Atavic** [comment]
@Thorin-Oakenpants Feel free to change the title, as I can't for some reasons ( I tried with pale-moon and chromium, but no response by clicking on edit).
My point was that even a small subset of users ( that have uBlock and Easylist) got played with these kind of triicks.

**Comment by Atavic** [comment]
@Thorin-Oakenpants Feel free to change the title, as I can't for some reasons (I tried with pale-moon and chromium, but no response by clicking on edit).
My point was that even a small subset of users (that have uBlock and Easylist) got played with these kind of triicks.

**Comment by Atavic** [comment]
@Thorin-Oakenpants Feel free to change the title, as I can't for some reasons (I tried with pale-moon and chromium, but no response by clicking on edit).
My point was that even a small subset of users (that have uBlock and Easylist) got played with these kind of tricks.

**Comment by earthlng** [comment]
LOL, classic Streisand effect. Instead of having one domain "burnt" they effectively lost all of them: https://ssl.bblck.me/BarbBlock.txt

**Comment by Thorin-Oakenpants** [comment]
Streisand.Effect©™® MIke Masnick :grin: 

I updated by soap box, but I doubt anyone goes there .. so I'll just repeat it here

> Edit: https://www.techdirt.com/articles/20170813/00092137987/how-dmcas-digital-locks-provision-allowed-company-to-delete-url-adblock-lists.shtml

**Comment by Thorin-Oakenpants** [comment]
PS: I hope the EFF take em to the cleaners.

Couple of things in the comments at techdirt

1.
>  _This also seems to infringe on the 1st Amendment protected right of freedom of expression_
>> The EFF and Bunnie Huang are [suing the government](https://www.eff.org/press/releases/eff-lawsuit-takes-dmca-section-1201-research-and-technology-restrictions-violate) over exactly that.

2. [This](https://www.techdirt.com/articles/20170813/00092137987/how-dmcas-digital-locks-provision-allowed-company-to-delete-url-adblock-lists.shtml#c209) comment (part pasted below)
> My web browser is a work protected by copyright. I use an adblocker to control access to it by preventing undesirable websites from accessing it. Therefore, it's a 1201 violation to attempt to circumvent my ad blocker, and quite possibly a CFAA violation as well... right?
>
> (Any lawyers in the house who wanna take a crack at this one?)

**Comment by Thorin-Oakenpants** [comment]
Just so this issue has at least SOME content to do with the title .. some thoughts on @laserstrike 's article - [Browser Fingerprinting: A new menace on the web](https://intoshadows.com/browser-fingerprinting/)

These are just my thoughts, not knocking anyone :heart: Both methods have pros and cons, but I fear 99%+ of the peasants are doomed. Full disclosure: I am not an expert.

> So install stock Windows 7, 8 or 10 with no extra plugins. Install stock Google Chrome and do not modify it.

Zero modification (modification is mentioned in the next paragraph) means you WILL definitely be unique, even if you removed a couple of items such as audio stacks and canvas that have very high entropy. Doing nothing is not a solution, period. I think the whole point of Panopticlick version 1 was that even with just a handful of basic FP points, you were screwed anyway.

> trying to blend in requires extraordinary effort on the part of the user as they go above and beyond to tweak their system to the most common configuration only to still be fingerprinted because they forgot about that exotic graphics driver

The exact same applies to making noise. Spoofing is still spoofing (including blocking), whether it is to reduce or increase entropy. Someone trying to randomly raise noise can just as easily miss something

> not only lying but lying in a believable way

Plausibility helps, but its almost the same argument from above about all that work to reduce entropy, and you miss something. So I kinda disagree. I think plausible is given too much credit under this strategy. If you're going to go all random, then it would be trivial to be picked up at some level. Its ONE bit (but of course the spread is not 50/50), and you will be caught out.

Both arguments require large numbers to buy into it, and that will only happen in FF if for example resistFP is enforced in PB mode, given lots of press and the UI checkbox lands. Chrome on the other hand .. you must be dreaming.

As anti-FP gains traction, those who want to track will just up the game - eg browser feature detection, lots of simple tricks to determine OS. In this regard both methods then fail etc. I think its an arms race we will never win.

It'll just be a select few of us .. just kill JS, XSS, default deny everything (use a text only browser!), multiple profiles over multiple browsers over multiple VMs over daisy chained VPNs over TOR over proxies, have multiple online IDs, use appropriate OpSec .. never contaminate ... all the tools are there

**Comment by Atavic** [comment]
A few days ago a banner appeared on github, pushing to the lastest versions of firefox etc.
Now, without any 'upgrade', I can't use reactions, can't edit and can't preview.

**Comment by Thorin-Oakenpants** [comment]
@Atavic 
* So are you on 55 or 55.0.1 or 55.0.2? Its not clear to me because the timing of the relases has been whack, they even stopped upgrades for a while.
   * I am on 55 for what its worth,  have not upgraded to 55.0.1 or 55.0.2 yet). I have no issues with adding a thumbs or heart reaction, or editing or previewing. Using default user.js as is (with indexeddb override atm
* So has this JUST happened, or has it been going on for a couple of days?

Troubleshoot it. Disable uM and uBo and NS for starters for a quick test - even recreate the github cookie. It certainly is not site code, and if you didn't upgrade FF then it must be something else (could even be corruption somewhere).

I also sometimes have issues with github and found lag issues and crap due to OCSP - even lost an entire commit and my backpage action restored it but I lost the description (its the one called "Update user.js" - lulz.

My current two overrides
```js
// OVERRIDES
user_pref("security.OCSP.require", false);
user_pref("dom.indexedDB.enabled", true);
```

Good luck buddy

**Comment by crssi** [comment]
Why `user_pref("security.OCSP.require", false);`?

**Comment by Thorin-Oakenpants** [comment]
^^ As I said I have been having issues with OCSP - websites not available in FF (whatever that SEC_ERROR* is), but they load in other browsers just fine. This is because the OCSP server is unavailable. Starting happening a lot in the last 3 or 4 weeks (prior to that not an issue since ever)

**Comment by crssi** [comment]
Haven't seen those, but I have got a few times `SSL_ERROR_UNSUPPORTED_VERSION` and needed to lower the `security.tls.version.min` down to `1` temporarily... even on GoDaddy (did research and it was total legitimate).

**Comment by Thorin-Oakenpants** [comment]
GoDaddy is shite .. just sayin' .. seriously .. wasn't the metric from Zilla something like under 1%. They are also an ethically repugnant company AFAIC

**Comment by crssi** [comment]
> GoDaddy is shite... ethically repugnant company AFAIC
Can you elaborate? What is alternative of your choice?
Thx

**Comment by Thorin-Oakenpants** [comment]
^^ https://en.wikipedia.org/wiki/Godaddy#Controversies for starters

**Comment by Atavic** [comment]
My point was that even a small subset of users (that have uBlock and Easylist) got played with these kind of tricks.
