### ISSUE TITLE
security.family_safety.mode live on Linux

### ISSUE THREAD

**Issue by 2glops** [ghacksuserjs/ghacks-user.js#209]
Microsoft Family Safety cert is included in 55 LINUX version.
Default:
user_pref("security.family_safety.mode", 2);

Proposed:
/* 1220: disable Microsoft Family Safety cert [WINDOWS and LINUX]
or:
/* 1220: disable Family Safety cert (by Microsoft)

**Comment by Thorin-Oakenpants** [comment]
I'm confused. Do you mean the pref is in FF55 for Linux, or that Linux (some distros) are installing a MS cert?

**Comment by Thorin-Oakenpants** [comment]
OK .. still confused .. I don't really care about the pref being present .. I guess I should have really asked

Is the Microsoft Family Safety cert being installed on Nix machines? If not then who cares if the pref exists in a FF-LIX build, it has no meaning - or am I missing something here?

**Comment by 2glops** [comment]
The Microsoft Family Safety cert is not installed on my machine, even if the pref is set to 2
user_pref("security.family_safety.mode", 2);
You're right, the pref has no meaning for LINUX, I'll keep the pref set to "0" anyway as per the user.js.

I've just deleted all the specific WINDOWS prefs from my user.js and founded that one still present after reset to default.

**Comment by Thorin-Oakenpants** [comment]
Seems weird to have the pref in `obj-x86_64-pc-linux-gnu/dist/bin/greprefs.js` .. [DXR](https://dxr.mozilla.org/mozilla-central/search?q=security.family_safety.mode&redirect=false)  .. I can't see any reason or logic for a smelly MS MiTM being distributed with Linux (I am not a Linux person much, yet - I've had one set up for the last 18 months but have learn almost nothing in that time due to laziness).

https://dxr.mozilla.org/mozilla-central/source/obj-x86_64-pc-linux-gnu/dist/bin/greprefs.js#49 - it says it's only for windows. And here ( https://dxr.mozilla.org/mozilla-central/source/security/manager/ssl/nsNSSComponent.cpp#749 ) is checking if XP to decide what to do - if XP do A, else Win7,8*,10 do B is my best guess.

Feel free to close... I have beers to drink

**Comment by Atavic** [comment]
THose certificates have no place in Linux. They work from Win 8 onwards.
