### ISSUE TITLE
Things to watch

### ISSUE THREAD

**Issue by Theemim** [ghacksuserjs/ghacks-user.js#214]
Rewrite libpref
https://bugzilla.mozilla.org/show_bug.cgi?id=1379383

> Since all prefs are known in advance -- assuming that nobody uses prefs as an ad hoc data store, which we can rely on once 57 blocks XUL add-ons -- they should be stored in a fixed array.

> I'm a little dubious about that -- I think datareporting, Log.jsm, urlclassifier, fonts, the IDN whitelist, and some other places use computed keys (or at least created-later keys) into prefs. It's not just add-ons. Furthermore, prefs sync relies on Firefox being able to store arbitrary preferences, because we might be handed key/value pairs that were set by a future version of Firefox. [...] That might mean we build two stores: one being prefs as it is now (with app/distro/locale overlays), and one being a key-value store that's external to Gecko to which we can shunt the other kinds of consumers.

> Interesting! Thank you for the info. It sound like a key part of this will be to define exactly what a pref is.

I don't want to think about the potential downsides.  As for potential upsides, maybe user.js processing will be improved so that any/all errors are reported *and* an error condition could prevent Firefox from starting up.

**Comment by Theemim** [comment]
Usage of Differential Privacy & RAPPOR
https://groups.google.com/forum/#!topic/mozilla.governance/81gMQeMEL0w

**Comment by Thorin-Oakenpants** [comment]
Its all good to me, keep bringing things up. Can't say I understand some of them immediately, because I am so clueless :)

As for the differential privacy and opt-in vs opt-out, and using buckets, and stripping down to domains, and only counting, etc and mozilla starting to harvest some new types of data - I'm not for or against it, but I do believe we need to have discussions to keep it on the straight and narrow, but this is not the forum for that AFAIC. I do not want to get into Mozilla politics and conspiracy theories :)

The [discussion[(https://www.reddit.com/r/firefox/comments/6vapu5/firefox_planning_to_anonymously_collect_browsing/) for the most part on reddit was informative and civil and pretty much covers it. As long as we just keep track of these things via prefs etc, then we're doing our job.

**Comment by gorhill** [comment]
Regarding this data collection plan by Mozilla, I would like to understand the technical details about what happens **between** a user loading a site in his browser and the "differential privacy" database. Let's purport that the "differential privacy" database on Mozilla's server is really unusable to whoever would want to infer any bit of browsing history for a specific user.

So to whoever _knows_ the accurate answer to this, my question is:

What exactly happens between my computer and Mozilla's "differential privacy" database?

Let's posit I load `sensitive-site.com` at 00h00m00s in my Firefox browser with no VPN to mask by ISP-assigned IP address.

What exact information would leave my computer and at what time, to be sent to Mozilla's server before that information is munched into the "differential privacy" database?

Anyone knows how this will work?

**Comment by Thorin-Oakenpants** [comment]
Hey, welcome gorhill :) I'll scope it all out and get back to you with an in depth single post. My gut feeling on the data is that it would be archived locally as `eTLD, counter` and sent as a batch with all other telemetry - certainly not sent in real time. Some pings are (shutdown and update for example). I haven't ever delved into when health reports and telemetry are sent, but suspect that various prefs with datetime and duration values control all this. eg It may be sent after starting if the last send was ages ago, IDK for sure .. but I'll dig into it. Not even sure if an guid of some sort (session, browser) is bundled (I think it is) - or the receiving server knows to assign a unique group id to that batch.

With this one though, because it is a shield recipe, it may have its own little set of rules. Probably the closest would be to follow what Follow-On Searches do (it accumulates the same thing IMO - a domain and counter), or look at the Shield code ( https://dxr.mozilla.org/mozilla-central/source/browser/extensions ).

Gimme a day to idle and maybe earthlng will jump in and save me some time :grinning: 

I'm not too worried about the WHEN (it will be batch info), more concerned with the WHERE and AFTER :)  I will read this later : https://robertovitillo.com/2016/07/29/differential-privacy-for-dummies/

**Comment by Thorin-Oakenpants** [comment]
^^ they will not care about your IP, hey will include a client guid of some sort because they want to collate data per browser, nothing more

toolkit.telemetry.cachedClientID ?

**Comment by gorhill** [comment]
> they will not care about your IP ... IP does nothing for them

What I have in mind is less about Mozilla, and more about other parties which could try to make use of the data in between one's computer and the "differential privacy" database. I want to understand what is of use to such external parties.

**Comment by Atavic** [comment]
>RAPPOR permits statistics to be collected on the population of client-side strings with strong privacy guarantees for each client, and without linkability of their reports.

See [here](http://static.googleusercontent.com/media/research.google.com/en/us/pubs/archive/42852.pdf)

>The first time the RapporService is started, a client will generate and save a random 128-byte secret key, which won't change and is never transmitted to the server... The cohort that the client belongs to and the results from the above process are sent to the server.

See  [here](http://www.chromium.org/developers/design-documents/rappor) 

- https://github.com/Alexrs95/rappor

**Comment by Thorin-Oakenpants** [comment]
I'm struggling to find exact answers (but I have some). And I do not wish to pollute Theemin's `Things to Watch` issue - I will move discussion to #219

**Comment by Thorin-Oakenpants** [comment]
> BTW, think this type of issue is a good idea? Bad idea? Close if it isn't something you want me to continue.

Actually, upon reflection, just bring new items up in new issues with descriptive titles. Easy to track, discuss, find etc
