### ISSUE TITLE
firefox cares about your privacy ... right? 'Usage of Differential Privacy & RAPPOR' (not an issue)

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#219]
Usage of Differential Privacy & RAPPOR - Google Groups
https://groups.google.com/forum/#!topic/mozilla.governance/81gMQeMEL0w

**Comment by Atavic** [comment]
Closer and closer to Chrome.

**Comment by Thorin-Oakenpants** [comment]
@Atavic Blanket statements like that do nothing. If you want to parrot, go to ghacks :smile: 

1. Telemetry is a thing - it is used to better software. eg: all the quantum improvements came from crunching huge amounts of telemetry data. Making hundreds and hundreds of small improvements to make an overall significant gain. You should read the Quantum newletters, it's all rather exciting
   * OT: I remember way back in the day writing and testing around 10 different functions for returning the day of the week when passing a Date, in SQL. I would clear caches etc and run this over a query that returned over a million records - the built in MS function was the slowest. I eventually got the query down from 10 minutes to 10 seconds, just on one query alone, using tiny int and a stupid nursery rhyme. I used to live for this shit :)
2. Despite a couple of occasions (one was a experimental accidentally? pushed update) and the other the GA in about:// - Mozilla respect the telemetry settings
3. OMG .. we have telemetry settings. OK, the UI ones only control the extent of the data, we need to dig deeper, but hey - we did.
4. Data is anonymized - I trust Mozilla in this respect, but I do get concerns over `meta-data`, so...
5. Mozilla use `differential privacy`
6. This is a shield study .. OMFG .. we can disable shield studies
7. Even if we didn't disable it, it only records the domain
8. It only uses a counter - eTLD+1
9. My understanding is by looking at data gained from what happens on the top sites re performance for FF users, they can improve the browser more - i.e least effort for most usage reward, biggest bang for their buck so to speak - this is smart. To do this they need to first know what are the top sites for FF users.
10. They are open about it, they have discussions
11. The world is full of uneducated trolling dicks

I could probably make another 10 relevant points...

Look, I get it. I'm not happy about a couple of things (but I understand why they do them) - case in point, the counting of follow on searches, and the general unable to disable system add-ons from within the interface. But overall Mozilla is NOTHING like chrome/google, not as a browser and not as a company. They are poles apart.

**Comment by Thorin-Oakenpants** [comment]
@gorhill [asked](https://github.com/ghacksuserjs/ghacks-user.js/issues/214#issuecomment-324212725)

> Regarding this data collection plan by Mozilla, I would like to understand the technical details about what happens **between** a user loading a site in his browser and the "differential privacy" database. Let's purport that the "differential privacy" database on Mozilla's server is really unusable to whoever would want to infer any bit of browsing history for a specific user.
> 
> So to whoever _knows_ the accurate answer to this, my question is:
>
> What exactly happens between my computer and Mozilla's "differential privacy" database?
> 
> Let's posit I load `sensitive-site.com` at 00h00m00s in my Firefox browser with no VPN to mask by ISP-assigned IP address.
> 
> What exact information would leave my computer and at what time, to be sent to Mozilla's server before that information is munched into the "differential privacy" database?
> 
> Anyone knows how this will work?

**Comment by Thorin-Oakenpants** [comment]
* What exact information would leave my computer
   * we would have to wait to see the shield-recipe (open source), but the discussion seems to be that it would be eTLDs and a counter
* Is this data useful if mined by someone else
   * probably not, I think the world already has metrics on top sites - I do not think anyone would bother TBH in _this_ case (future cases, who knows)
* What time
   * irrelevant IMO, archived in batches, probably checked on startup, sent based on timers/intervals
* Where does it go
   * [citation needed] - to a mozilla-controlled(?) server running RAPPOR (open source), or to a 3rd party server/service (AWS, google etc), potential IP leakage
* What happens to it
   * whatever RAPPOR is meant to do (add noise AFAIK) etc -> differential privacy
   * does RAPPOR do what it says - see `memoization`. Is it truly vetted?
* What else
   * What server/database is this sent to, is a guid of some kind involved and is this stripped so there is no link between existing "anonymized" data, is the data encrypted (probably only between end points)

Some links
- Shield: https://github.com/mozilla/normandy
- Shield Recipe-Client code here - https://dxr.mozilla.org/mozilla-central/source/browser/extensions
- Simplistic article from 2014: https://www.cnet.com/news/how-google-tricks-itself-to-protect-chrome-user-privacy/
- RAPPOR - [GitHub](https://github.com/google/rappor) - [Data Flow](https://google.github.io/rappor/doc/data-flow.html) example

Conclusion: I have always blocked all telemetry. I will continue to do so and this repo will continue to do so. Because of this I have never delved too deeply behind the scenes, and I do not have to worry and don't really care, one less thing to work on or have discussions about.

But until it is set up and we see some code, and we get some answers from Mozilla, it's only an educated guess. For all I know, they could use google services, or any other third party, under their agreement to host and collect this data. Too many Q's and no answers I'm afraid.

Default-deny is all I can say. I sleep well at night too.

**Comment by earthlng** [comment]
quoting [dr_rentschler](https://www.reddit.com/r/firefox/comments/6vapu5/firefox_planning_to_anonymously_collect_browsing/dlzedsf/):

> The question is: what does Firefox want to be? Do we need a non profit foundation to offer us an alternative with the focus on performance? **No, we need it to offer an alternative with focus on VALUES**, because that is not what a commercial product can ever offer. Commercial product's highest priority is always profit. What I'm seeing is Mozillas priorities seemingly shift and that's scary.

:+1: :+1:

**Comment by Atavic** [comment]
No single client reports are sent to RAPPOR Servers, as clients reports are logged into various common pools - called [cohort](https://github.com/ghacksuserjs/ghacks-user.js/issues/214#issuecomment-324423271) - and then sent to the servers.

**Comment by Atavic** [comment]
No single client reports are sent to RAPPOR Servers, as clients reports are logged into various common pools - called [cohorts](https://github.com/ghacksuserjs/ghacks-user.js/issues/214#issuecomment-324423271) - and then sent to the servers.

**Comment by Thorin-Oakenpants** [comment]
^^ The data collated and sent from my PC from my one and only FF is transmitted *somewhere* and includes associated meta-data such as my IP (which lets say I never hide) and builds a complete history over time. As few as 10 sites can de-anonymize a person ( see https://www.techdirt.com/articles/20170803/14480037916/once-again-with-feeling-anonymized-data-isnt-really-anonymous.shtml )

> For other users, a more probabilistic approach can deanonymise them. For instance, a mere 10 URLs can be enough to uniquely identify someone – just think, for instance, of how few people there are at your company, with your bank, your hobby, your preferred newspaper and your mobile phone provider. By creating “fingerprints” from the data, it’s possible to compare it to other, more public, sources of what URLs people have visited, such as social media accounts, or public YouTube playlists.

That somewhere is a server, my data is NOT fully anonymized yet. I don't care about exactly how RAPPOR works as long as it does. If the data is manipulated in a step prior to being feed to RAPPOR to do the diff privacy step, that's fine. This is simply the process. Whether RAPPOR can eat the data RAW or needs it COOKED first doesn't mean anything (but does create yet another step to evaluate)

**Comment by Thorin-Oakenpants** [comment]
> quoting [dr_rentschler](https://www.reddit.com/r/firefox/comments/6vapu5/firefox_planning_to_anonymously_collect_browsing/dlzedsf/):

Just to play devil's advocate. I agree with that statement, but I think the motives behind it are not nefarious. There is a real culture (from the little I have read) at Mozilla among the employees about leaving no stone unturned and gaining every. single. ounce. of performance no matter how small. It's exciting (see my first post, I used to live for this shit). This has happened because of better telemetry (the proposed Book of Mozilla update includes this in its message, it's _that_ big of a deal - it is the cornerstone of Quantum etc).

IMO, this is simply an enthusiastic progression of that. I believe this proposal has been driven by the engineers. Real world data that cannot be replicated in a test lab to cover top FF user domains - it's not the domains they want so much (it really wouldn't differ from say Alexa top 1000 IMO etc), its the real world data on jank etc - the collection of the domain cannot be excluded. This is **SMART**, should have been done ages ago AFAIC - target top 5% of sites, improve 50% of users' experiences/traffic. I have no problems with this... but ...

.. but I do question the opt-out vs opt-in, whatever it becomes - because this is a different type of data collection. I do not want to use the words "slippery slope", but the WAY they are going about this starts to open doors. I do not mind their effectively Opt-Out telemetry (which doesn't fully stop it) which collects performance stats etc about the actual browser .. but this type of data is significant

Its a bit messy. Opt-in, opt-out. Shield respects the telemetry settings, but they know most people don't bother to turn it off. Moving the goalposts without an opt-in (if that's what they do) is a SHITTY move. It certainly won't help PR

**Comment by Thorin-Oakenpants** [comment]
Sheeshus .. now I have images in my head of two little firefoxes in a basement plotting [world domination](https://en.wikipedia.org/wiki/Pinky_and_the_brain)

**Comment by Atavic** [comment]
There's a *persistent UUID*: a random 128-byte secret key, stored locally.
(more on the link in my previous comment)

**Comment by Thorin-Oakenpants** [comment]
^^ which link? - they are all about RAPPOR
- http://static.googleusercontent.com/media/research.google.com/en/us/pubs/archive/42852.pdf
- http://www.chromium.org/developers/design-documents/rappor
- https://github.com/Alexrs95/rappor

I am not so concerned about RAPPOR, as about any ids (batch, session, or profile) being sent to the first receiver by **Firefox**, and how that is treated along the chain. Don't get me wrong - the server receiving the raw data, and RAPPOR itself can also add a unique id to incoming batch data - in fact it _has to_ in order to process it. I will trust the experts that RAPPOR itself is fine

**Comment by Thorin-Oakenpants** [comment]
Actually, I'm not concerned about any of this, TBH. Not into the politics of it. I understand and support opt-in, I understand the need for real data, I trust Mozilla .. but truth be told, as atomGit says in the topic, it is "not an issue" - well, not for this user.js project.

Killing all telemetry eliminates all the risks asked above. If it ever gets to the point where any outgoing connection could not be controlled by a pref (or removal of a system addon), then I would scream blue murder

gorhil gave :+1: , I can only assume he meant my supreme and effortless well-sleeping well at night knowing that it is far easier and safer to just kill it at the source.. no risk, no fuss, no work, no arguments .. sorry engineers

closing - but feel free to follow up with details as they emerge

**Comment by Atavic** [comment]
>^^ which link?

The 2nd link you posted, after **Algorithm** section.

**Comment by Thorin-Oakenpants** [comment]
^^ So in other words, part of the rappor design and process, as I said. Cheers

**Comment by Atavic** [comment]
Aye. Aye. Can servers read this Universally *unique* ID?

**Comment by Thorin-Oakenpants** [comment]
> Can servers read this Universally unique ID?

Servers can do whatever they like on their own servers (assuming the server is an end point and thus the information to be processed is no longer encrypted). As I said, the more steps, the more potential weak points. I sleep well knowing this issue is closed and I do not have to deal with it because we do not allow telemetry _at all_.
