### ISSUE TITLE
Firefox doesn't remember windows position with user.js

### ISSUE THREAD

**Issue by eggplanti** [ghacksuserjs/ghacks-user.js#220]
Hello,

since updating to Firefox 55, I encounter following problem only when I use the latest user.js alpha for Firefox 55:

When closing Firefox and opening it again, the window size is not saved. Each time I open Firefox, the window size is different.

When I don't use the user.js file, the problem doesn't happen. Firefox remembers it's latest windows position.

Is this a bug or a feature? I can't find a matching string inside the user.js file.

**Comment by earthlng** [comment]
try disabling `privacy.resistFingerprinting` and see if that helps. It's not the user.js that changed, it's FF55 that now always restores the windows to make its inner width+height 1000px when `privacy.resistFingerprinting` is set to true. I know it's not great but there's nothing we can do about it.
Alternatively you can activate the 2 prefs below privacy.resistFingerprinting to get a slightly more acceptable window size. Or go back to ESR, or learn to live with it.

**Comment by Thorin-Oakenpants** [comment]
I do not wish to rehash everything - see https://github.com/ghacksuserjs/ghacks-user.js/issues/7#issuecomment-322038553 (some comments before but particularly after) about why NEW inner windows resize to 100s/200's and why this works and why maximized is not such a good idea, and why dropping privacy.resistFingerprinting is also maybe not such a great idea (maybe for ESR 52.x since not much was implemented by then). The only workaround is to open normal and then click the maximize button (in order to get your desired state, knowing that your values are now more unique than when it opened - I am guessing it is more unique, but it certainly will be once the pref gains traction, and especially in the controlled subset of FF resistFP users )
