### ISSUE TITLE
(FF55+ on Windows) bug with RFP + spoofing timezone as UTC 0 [Bugs 1330890, 1409973]

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#230]
There seems to be a problem with `privacy.resistFingerprinting` and the UTC+0 timezone spoofing.

https://bugzilla.mozilla.org/show_bug.cgi?id=1330890#c29

Can some of you guys on FF55+ please check https://browserleaks.com/javascript and report if **toLocaleString()** returns UTC timezone or if it's bugged for you as well.
Obviously if your system's timezone is UTC+0 already you'll need to temporarily change it to something else, like a timezone in the US or Australia so it's easy to spot the difference and DST won't be an issue.

It would be nice if we could get results from MacOS and Linux users as well. Thanks

**Comment by crssi** [comment]
FF 55.0.3 x64 here... and browserleaks reports GMT+0000 (UTC), which I am not. So, all good here.

**Comment by earthlng** [comment]
@crssi thanks, are you sure that's the **toLocaleString** value?

**Comment by crssi** [comment]
Crap... you are right. toLocaleString is my correct one.
```
System Time | Thu Sep 07 2017 11:47:02 GMT+0000 (UTC)
toLocaleString | 9/7/2017, 1:47:02 PM
```

**Comment by 2glops** [comment]
FF55.0.3 Linuw

System Time	Thu Sep 07 2017 15:51:39 GMT+0000 (UTC)
toLocaleString	9/7/2017, 3:51:39 PM
toLocaleFormat	Thu Sep 7 15:51:39 2017

Good!
Time spoofed, I'm not at GMT+0000 (UTC)

**Comment by crssi** [comment]
Windows 10, FF 55.0.3 x86 and x64, with ghacksuser.js or clean profile with privacy.resistFingerprinting = True... always bad result.

**Comment by savyajha** [comment]
No problem here. FF 56.0b9 on the Mac gives me:

```
System Time | Fri Sep 08 2017 10:43:51 GMT+0000 (UTC)
toLocaleString | 9/8/2017, 10:43:51 AM
toLocaleFormat | Fri Sep  8 10:43:51 2017
```

I'm not in GMT, fyi.

**Comment by Forsaked** [comment]
It seems not to be landed in stable, since my 55.0.3 also doesn't spoof the timezone.
Gonna test the beta channel when im back home.

**Comment by Thorin-Oakenpants** [comment]
@Forsaked Is this Windows or Linux?

**Comment by Forsaked** [comment]
@Thorin-Oakenpants Windows

I am home now, result of 55.0.3:

> System Time	Fri Sep 08 2017 22:03:31 GMT+0000 (UTC)
> toLocaleString	9/9/2017, 12:03:31 AM
> toLocaleFormat	Friday, September 08, 2017 22:03:31

Checking 56+ now

**Comment by Thorin-Oakenpants** [comment]
^^ https://bugzilla.mozilla.org/show_bug.cgi?id=1330890#c36

**Comment by Forsaked** [comment]
So 56b1:

> System Time	Fri Sep 08 2017 22:18:14 GMT+0000 (UTC)
toLocaleString	9/9/2017, 12:18:14 AM
toLocaleFormat	Freitag, 8. September 2017 22:18:14

Same error.

**Comment by earthlng** [comment]
Thanks guys! :+1:

**Comment by Thorin-Oakenpants** [comment]
@Forsaked 

55: toLocaleFormat Friday, September 08, 2017 22:03:31
56: toLocaleFormat Freitag, 8. September 2017 22:18:14
  // ^^ you're lucky German spelling for September is the same

Both with RFP=true. I assume 55 was your main one with the user.js and 56 was a nilla profile - ont he same machine?. Do you see an issue that RFP can leaks locale.

For me, my beta nilla changed to 12 hrs clocks (but was still using english, just not en-US). I'm still trying to work out WHICH pref is responsible - hard to tell for me since I'm all english.

Can you load up your beta 56 and fire up the test page to reveal **Sonntag** and then one by one try these pref changes with refreshing the JS test after each one

1. intl.locale.matchOS => false  (should be false by default, if so, ignore it)
2. javascript.use_us_english_locale = true (hidden pref, you'll need to create it)
3. intl.accept_languages", "en-US, en"

I'm struggling after that. Can't see why anything else in 0200 would make an effect.

If the above fixes it so you only display EN for days/months (I think 2 might do it), that's great - BUT does not control the format - eg why I display 12 hr clock and you display 24

**Comment by Forsaked** [comment]
The FF56.0b1 was only with RFP enabled no user.js, thats why it showed the gernan language.

New test on Windows 10 Pro 15063.540


Firefox Stable 55.0.3 (Vanilla-Profile + User.js):

> System Time	Sun Sep 10 2017 11:36:23 GMT+0000 (UTC)
> toLocaleString	9/10/2017, 1:36:23 PM
> toLocaleFormat	Sunday, September 10, 2017 11:36:23


Firefox Dev Edition 56.0b10 (Vanilla-Profile + User.js):

> System Time	Sun Sep 10 2017 11:37:30 GMT+0000 (UTC)
> toLocaleString	9/10/2017, 1:37:30 PM
> toLocaleFormat	Sunday, September 10, 2017 11:37:30


Firefox Nightly 57.0a1 (Vanilla-Profile + User.js):

> System Time	Sun Sep 10 2017 11:38:51 GMT+0000 (UTC)
> toLocaleString	9/10/2017, 1:38:51 PM
> toLocaleFormat	Sunday, September 10, 2017 11:38:51

**Comment by Thorin-Oakenpants** [comment]
> The FF56.0b1 was only with RFP enabled no user.js, thats why it showed the german language

Yeah. That was my point. That RFP alone does not properly cover locale & format. Hence why I wanted you to test which pref was responsible for fixing the locale leak part. But it's OK. I worked it out. Fixing format is another story

**Comment by Thorin-Oakenpants** [comment]
FYI
- https://trac.torproject.org/projects/tor/ticket/21784
- https://trac.torproject.org/projects/tor/ticket/22125

**Comment by Thorin-Oakenpants** [comment]
Upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1409973

**Comment by Thorin-Oakenpants** [comment]
https://www.fxsitecompat.com/en-CA/docs/2017/date-prototype-tolocaleformat-has-been-removed/

**Comment by Thorin-Oakenpants** [comment]
This is listed and tracked under RFP sticky - closing

**Comment by Thorin-Oakenpants** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1409973 resolved fixed
