### ISSUE TITLE
uBo WE and retention of blocklists

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#239]
What situations cause uBo blocklists to be reset?

**Comment by Forsaked** [comment]
This only happens if the indexedDB is disabled by the user.js or PB mode.
I have set Firefox to clean everything on exit without using the PB mode or indexedDB disabled and my lists survive closing the browser.
Using eCleaner will kill the indexedDB, so you need to download and rebuild your blocklists every Firefox start.
There is nothing we can do about this except enabling the indexedDB, disabling PB mode and don't using eCleaner, until Mozilla or Gorhill changes something.

**Comment by Gitoffthelawn** [comment]
@Forsaked What's your definition of *PB mode*?

Since you have Firefox cleaning everything on exit, doesn't it delete indexedDB?

**Comment by Forsaked** [comment]
My "definition" of PB mode is `browser.privatebrowsing.autostart=true`, which prevents Firefox in using the indexedDB even if it's enabled in the prefs.
With everything i mean, everything what Firefox itself can clean up on exit: cache, cookies, downloads, formdata, history, offline Apps, sessions and site Settings.

**Comment by Gitoffthelawn** [comment]
@Forsaked Hmmm... I set up a test with `browser.privatebrowsing.autostart=false` and `dom.indexedDB.enabled=true`, and set Firefox to clean everything on exit.  When I do this, uBo loses its blocklists, and they have to be re-downloaded every time the browser starts.

Do you have a different experience?

**Comment by Forsaked** [comment]
Yes, my lists don't get cleared.

**Comment by Gitoffthelawn** [comment]
@Forsaked Thanks. When you restart the browser, and go to the ***3rd-party-filters*** tab in uBo, is the ***Update now*** button yellow?

**Comment by Forsaked** [comment]
As i told you, no.
I was using the PB mode before the native WE of uBlock landet.
Then i tried to enable the indexedDB only to find out that it is still disabled in PB mode.
So i was forced to disable PB mode and enable indexedDB.
Since then my filter lists stay and i don't need to download them every restart of Firefox, except there is an update.

**Comment by Gitoffthelawn** [comment]
@Forsaked Sounds good.  We are seeing different things.  Not sure why.  What version of Firefox are you using?

**Comment by Forsaked** [comment]
Stable, but also tested on Beta and Nightly. 
Did you still use eCleaner?

FF + PB + iDB disabled = uBO list wipe
FF + PB + iDB enabled = uBO list wipe
FF + iDB disabled = uBO list wipe
FF + iDB enabled = uBO works, no wipe

**Comment by Thorin-Oakenpants** [comment]
***PB mode does not use IDB***, so this affects extensions that use it. eg uBo. It will also affect uMatrix when it ports - as this too will use IDB for cached assets. Stylus also uses IDB (but stores the data in `profile\browser-extension-data` rather than `profile\storage` ) so I assume that Stylus also breaks in various ways in PB mode - IDK. PB mode also blocks access to cookies. PB Mode is not the magical thing people assume it is. It's very limited IMO.

~~FF + PB + iDB disabled = uBO list wipe~~ - pointless test as it's PB mode!!
~~FF + PB + iDB enabled = uBO list wipe~~ - pointless test as it's PB mode!!
FF + iDB disabled = uBO list wipe
FF + iDB enabled = uBO works, no wipe

^^ exactly as Forsaked said. uBo uses IDB and PB mode does not

> This only happens if the indexedDB is disabled by the user.js or PB mode.

^^ exactly as Forsaked said

**Comment by Thorin-Oakenpants** [comment]
@Gitoffthelawn 
>  I set up a test with browser.privatebrowsing.autostart=false and dom.indexedDB.enabled=true, and set Firefox to clean everything on exit. When I do this, uBo (WebExtensions version) loses its blocklists, and they have to be re-downloaded every time the browser starts.

autostart = false = default
IDB = true = default

- So in other words, just use a nilla profile and add uBo, update lists, close, open, check lists - I bet the IDB cache is not wiped
- You need to then test with various clear on shutdown items to see IF any of those are clearing IDB. Then try using "everything" under "clear recent history" dialog, etc.
- AFAIK nothing clears IDB via the interface or options (but I never checked in-depth)

**Comment by Gitoffthelawn** [comment]
@Forsaked Not using eCleaner.

@Thorin-Oakenpants Yes.... I'll need to do that.  I thought clearing cookies or offline website data cleared IDB (most likely the latter)... will have to do some experimentation.

**Comment by Forsaked** [comment]
@Thorin-Oakenpants Fun Fact: If indexedDB is enabled while in PB mode (which makes it inaccessible), sites which require the indexedDB like Outlook Web App and other, are working.
I think they only check if it is enabled but don't use it.

**Comment by Thorin-Oakenpants** [comment]
^^ Yeah. the pref effectively disables the API, but PB mode do it slightly differently (because it is not good to flip pref values like that - eg see RFP decided against this method). It was mentioned here https://www.wilderssecurity.com/threads/firefox-and-indexeddb.395113/ in the first post

my edit in brackets
> I've [removed write access to relevant indexedDB folder(s) - same as simulating PB mode] and haven't run into any problems on sites which make use of IndexedDB. It seems that those sites still think that IndexedDB is available although they cannot write to those folders mentioned above.

**Comment by Gitoffthelawn** [comment]
I figured out the issue.  Thanks to @Forsaked and @Thorin-Oakenpants for their assistance.

I run Firefox within a script.  (I've been meaning to share that script for a while.)  As part of its duties, the script clears out `..\storage\default` within the profile.

It turns out, uBo WE stores its data in `..\storage\default`.  'nuff said.

What's curious is that some other extensions store their data in `..\storage\permanent`.  Besides uBo, I don't know of any other extensions that store their data in `..\storage\default`.  To be clear, I'm not saying that any extensions (including uBo) are storing their data in the wrong place.

Anyone understand the difference between `..\storage\default`, `..\storage\permanent`, and `..\storage\temporary`?

**Comment by Thorin-Oakenpants** [comment]
right .. so I don't have to waste my time testing clearing IDB then - currently (AFAIK and from numerous zilla tickets) there is nothing in the UI/settings or about:config that will clear IDB, but this will change and the changes better leave extension and internal shit alone

So we can close this then?

**Comment by Thorin-Oakenpants** [comment]
> Anyone understand the difference between `..\storage\default`, `..\storage\permanent`, and `..\storage\temporary`?

Also stylus uses IDB but seems to store it elsewhere - see earlier comment. Anyone want to look up Storage API limitations etc?

**Comment by Thorin-Oakenpants** [comment]
* https://bugzilla.mozilla.org/show_bug.cgi?id=1333050 - Implement clearing of IndexedDB in browsingData API - RESOLVED FIXED 58+
* https://bugzilla.mozilla.org/show_bug.cgi?id=1047098 - 'Clear Recent History' with 'Cache' or 'Offline Website Data' doesn't clear...  - RESOLVED FIXED 58+
* https://bugzilla.mozilla.org/show_bug.cgi?id=1275599 - [meta] Add a site permission management interface - RESOLVED FIXED - FYI

**Comment by Gitoffthelawn** [comment]
> So we can close this then?

One unresolved question before we close:

Anyone understand the difference between `..\storage\default`, `..\storage\permanent`, and `..\storage\temporary`?

**Comment by Thorin-Oakenpants** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria

can we close this now?

**Comment by Gitoffthelawn** [comment]
Good find.  Thank you.  Closing now...

**Comment by Thorin-Oakenpants** [comment]
Interesting. I actually wiped everything in my permanent folder with FF closed. Restarted FF and voila, I FINALLY have a Stylus' IDB turn up (under default). Also a literal f**ktonne of console errors from one legacy addon has now disappeared. I wonder if something in `permanent/chrome` was blocking IDB - might explain why I haven't seen anything for the 5 weeks I've had it on. Spooky!

The permanent entries `chrome` auto reappeared and `indexeddb+++fx-devtools` did as well as soon as I opened devtools. Another one called `moz-safe-about+home` has not come back. In my 56 test profile that folder doesn't exist.

**Comment by Thorin-Oakenpants** [comment]
^^ as per https://github.com/ghacksuserjs/ghacks-user.js/issues/234#issuecomment-329529558

Those two sites I already have configured to allow JS, images, etc - bare minimum (not cookies) - HuffPo and Guardian, that do not need service workers to spawn idb, I still get nothing - so that's good.

This is about the third major quirk I have come across. Really considering starting a brand new clean profile in 57
