### ISSUE TITLE
Is there a way to debug which setting is breaking a page? (Open Spotify)

### ISSUE THREAD

**Issue by AtomicStryker** [ghacksuserjs/ghacks-user.js#243]
Not so much an issue as user error, probably. I am usually fairly proficient at getting my websites to work past uMatrix and uBlock Origin, but i absolutely cannot get open.spotify.com to work. It stubbornly remains on the "Enable player in your browser" message. Even if i disable both uMatrix and uBlock. Before i applied the ghacks user.js, the site worked, but that really doesn't narrow anything down.

How would i best go about figuring out how to unbreak the site?

**Comment by crssi** [comment]
I don't have account at spotify to test, but maybe workers are the problem.
Set `dom.workers.enabled` to true and try again.

**Comment by Thorin-Oakenpants** [comment]
I don't have an account at Spotify either. Usually the first sites to implement "new tech" are the major players - eg google sites, FB, instagram, twitter, outlook, etc. These major sites are also the ones they usually use cross domain logins that are in effect super cookies - so 4001 `privacy.firstparty.isolate` causes issues (for logins) - but I am sure that is not the case here - you'll logged in right?

Personally, for troublesome sites - I would just use a secondary profile or browser - rather than compromise my base main FF settings.

That said (and I cannot test since I do not have a Spotify account)
- you seem to have JS/XSS etc covered
- you seem to have login (and cookies) etc covered
- it complains about a player - so I would look at the GMP items - I did a quick google fu and there is mention of Widevine & Spotify - see `1825`
- other than that, it would be the usual suspects such as workers, service workers, indexedDB (which was disabled until recently - not sure what version you are on, but we made it inactive, so you would have to actively reset it in about:config)

Let us know how you get on

**Comment by AtomicStryker** [comment]
Wow, so much help, thank you!

It wasn't the workers, and i have indexedDB enabled (12bytes mods). Enabling 1825 and 1830 allows me to progress into the player page, yay! Now the portable FF i am using to test this is stuck with a yellow bar "Firefox is installing components needed to play the audio or video on this page. Please try again later."

**Comment by Thorin-Oakenpants** [comment]
1820 may be needed - since this covers all GMP (GMP = cdm's like widewine, and eme's, and the openh264)

In short, if you want all video/media then make all of 1820+1825+1830+1840 = inactive and reset in about:config

**Comment by AtomicStryker** [comment]
Done. It still refused to work, but then i had the bright idea to check uMatrix again and lo, there was a new request pending! IT WORKS! Thank you so much.

**Comment by Thorin-Oakenpants** [comment]
> Is there a way to debug which setting is breaking a page

Yes: https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting

**Comment by Thorin-Oakenpants** [comment]
FYI: This is why I personally am against all the DRM & EME

https://falkvinge.net/2017/09/27/with-the-world-wide-web-consortium-captured-by-the-copyright-industry-who-will-step-up-to-lead-web-development-next/

The security risks alone are horrifying - the lack of control is terrifying - and the legal mindfield is pant-shittingly chilling
