### ISSUE TITLE
prefs to disable things due to CVE's need to be reenabled

### ISSUE THREAD

**Issue by jawz101** [ghacksuserjs/ghacks-user.js#255]
The javascript.* stuff all got fixed in March 2015.  I don't know if it makes sense to completely disable something that had a temporary bug.

**Comment by Thorin-Oakenpants** [comment]
Can you been a little more specific? CVE's come and go. Just because it was fixed once, doesn't mean it stays incident free. An example is graphite (1408). This pref `gfx.font_rendering.graphite.enabled` was set as disabled in the user.js back in FF49 when it Zilla flipped it back on. And voila ... https://www.mozilla.org/security/advisories/mfsa2017-15/#CVE-2017-7778  .. another exploit almost a year later.

AFAIK, none of the "javascript" options (are we talking about section 2400?) that are currently active and disabled - cause any real issues. Ion and baseline JIT are inactive. ASMJS seems fine being disabled. The only one is WASM which is pretty new - see earthlng who shot me down in flames over that one.

CVEs in the js:
- 1408 graphite
- 2301 workers (4 of them, but we disable workers for a different reason)
- 2420 asm.js
- 2421 Ion & Baseline JIT (inactive)
- 2669 remove paths when sending URLs to PAC scripts (this is enforced at default)
- 2672 puncode

That's the entire list of what we have that have CVE's referenced.
