### ISSUE TITLE
FF57 IndexedDB allow only for uMatrix and uBlock

### ISSUE THREAD

**Issue by theDuckIsAlive** [ghacksuserjs/ghacks-user.js#260]
I'm testing FF57-Quantum on Linux.

How is that possible to enable IndexedDB **ONLY** for **uMatrix** and **uBlock** ?
Some sites are dumping a lot of junk under: ` /profile-dir/storage/default/`

something like: `https+++www.XXXXX.com^firstPartyDomain=XXXXX.com`

**Comment by 2glops** [comment]
The wiki should help:
https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.7-Setting-Extension-Permission-Exceptions

I also have a FF57-Quantum on Linux, uBo and uM works fine

**Comment by atomGit** [comment]
currently none of the WebExt's that automatically handle cookie auto-deletion are capable of deleting LocalStorage (FF WebExt. API issues are to blame i believe), but you might want to keep an eye on such extensions because, IMO, this is the best/easiest way to handle LocalStorage items

[Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) is one such ext.

also you might want to have a look at the [WebAPI Manager](https://addons.mozilla.org/en-US/firefox/addon/webapi-manager/) ext.

**Comment by Thorin-Oakenpants** [comment]
FYI: localstorage handling (by host) is fixed for FF58+ - so expect CAD etc to implement that properly in time. IndexedDB clearing was also implemented in FF57, but not by host or by time (IDK) but plans are for this to be done - it's just that there is still a lot going on with (site) permissions for Offsite Website Data (OWD = IndexedDB) and I think that is going to be dropped from the UI. There were around 30 tickets to do with IDB, about 8 are still open

**Comment by theDuckIsAlive** [comment]
This is a privacy nightmare.

Seems I have to stick around with FF56 for a  very long time.
.... will only test FF57 and jump from FF56 directly to FF58.

by now I set a perl script which get fired together with FF57.
It deletes everything in the /storage/default directory which matches `/^https?\+\+\+/`

**Comment by Thorin-Oakenpants** [comment]
FF57 already handles IndexedDB, which is also called `Offline Website Data`. IDB is the /storage/default directory you speak of. This can already be cleared manually with Clear Recent History, and also on close - Privacy & Security>History>Clear history when Firefox closes>Settings

**Comment by Thorin-Oakenpants** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1334411  - the OWD pref in site permissions will be gone with FF58 (it hasn't worked for years anyway)
