### ISSUE TITLE
tidyup: NotificationsAPI

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#262]
https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API

> As of Firefox 44, the permissions for Notifications and Push have been merged. If permission is granted for notifications, push will also be enabled

I think the user.js could do with a little tidy to make it clearer as per this comment - https://support.mozilla.org/en-US/questions/1165867#answer-981820

Break 2305 into two prefs
- 2305: dom.webnotifications.enabled = MASTER switch
- 2306: dom.webnotifications.serviceworker.enabled = control PUSH notifications
- 2307: dom.push.* = control BACKGROUND push notifications

Also, find out which one controls the site exception "Receive Notifications"

**Comment by earthlng** [comment]
IMO it's fine as it is ie. the 2 dom.webnotifications.* fit nicely together.

Either way "control PUSH notifications" is more confusing because it simply controls whether workers are allow to use webnotifications: ["Note: This feature is available in Web Workers."](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API)
... and "control BACKGROUND push notifications" is equally incorrect and confusing ie it doesn't have to be "BACKGROUND" push notifications.

Anyhow, who cares about webnotifications anyway? 👎 :)

**Comment by Thorin-Oakenpants** [comment]
> the 2 dom.webnotifications.* fit nicely together.

The whole section fits nicely together :) What's your point.

I certainly don't care about webnotifications, but that doesn't mean I don't want the correct or **complete** info shown. ATM there is nothing to show the chain of permissions. and three sets into two do not go. As for the wording "push" and "background", I used those from the link. We can reword it. Push by that link's definition meant a site tab had to be open, whereas background meant sites did not have a tab open.

The link specifically says
> There are two different preferences for notifications, a master switch, and ***one which is specific to background (web push) notifications that can appear after you leave the site which sends them***.

I will draft something shortly

**Comment by Thorin-Oakenpants** [comment]
Reason for closing: we can revisit if it needed. There is a link to the mozilla support question if anyone asks who can't read. Too much other stuff to do.
