### ISSUE TITLE
Add an option for OCSP Must-Staple

### ISSUE THREAD

**Issue by Exodion** [ghacksuserjs/ghacks-user.js#267]
Since we know that non-stapled OCSP leaks information to the CA, I thought it would be a good idea to add `user_pref("security.ssl.enable_ocsp_must_staple", true);` for completeness and increased security and privacy. The default value is true anyways.

**Comment by Thorin-Oakenpants** [comment]
@Exodion sorry for the delay. We probably left it out as it was already at true. This is more @earthlng 's area - I'm all for comprehensiveness, so why the heck not.

/* 1213: blah blah

Anyone want to write it up? Maybe find a doc link? Earthlng, what say you?

**Comment by Thorin-Oakenpants** [comment]
Thanks @Exodion . I'll discuss the PR in here, so it's all together. Not that there is necessarily anything wrong with it, but I like to understand it myself before it goes in, and its not 100% clear to me what this does with that one short line - one aim of the js is to put things in non layman terms so idiots like me can use it (even if the link does it for us, the more info in the js the better)

```js
/* 1213: require a stapled OCSP response from the CA (FF45+)
 * [1] https://blog.mozilla.org/security/2015/11/23/improving-revocation-ocsp-must-staple-and-short-lived-certificates/ ***/
user_pref("security.ssl.enable_ocsp_must_staple", true);
```

- I'd add (FF45+) as per above
- Excellent link
- maybe "enforce OSCP Must-Staple (FF54)" and then an short explanation

> When a CA adds this [TLS feature] extension to a certificate, it requires your browser to ensure a stapled OCSP response is present in the TLS handshake. If an OCSP response is not present, the connection will fail and Firefox will display a non-overridable error page

I'm confused. If the CA has the new feature, then who is not giving the stabled OCSP response? Maybe I don't follow this. Where is the cert coming from? I understand the hard fail part as the fallback rather than a soft fail, but I maybe I need a flow chart. Is their a third party in this besides the CA + the browser? I'm struggling to see when this fails (because I am a dummy!) :)

I need to head off, so will get to this tomorrow,

**Comment by earthlng** [comment]
I'm 50-50 on this. On one hand there's no reason not to add this to the user.js for completeness but on the other there are lots of other security prefs for which we don't enforce the default value either. And then there's the possibility that it confuses people about what this pref does. In fact @Exodion seems to be one of those people because in the pull request he/you titled it "require a stapled OCSP response from the CA" which is incorrect - it merely enables support for it.

If we want to add it, another nice article IMO is https://www.grc.com/revocation/ocsp-must-staple.htm.
But I also found this from May 19. 2017:
https://blog.hboeck.de/archives/886-The-Problem-with-OCSP-Stapling-and-Must-Staple-and-why-Certificate-Revocation-is-still-broken.html

> **The OCSP Stapling implementations of Apache and Nginx are broken**
> ... the biggest share of active sites on the Internet run on Apache (about 46%), followed by Nginx (about 20 %).
> ... To summarize: This is all a big mess. Both Apache and Nginx have OCSP Stapling implementations that are essentially broken. As long as you’re using either of those then enabling Must-Staple is a reliable way to shoot yourself in the foot and get into trouble. Don’t enable it if you plan to use Apache or Nginx.

If we add it then users might get a false sense of added privacy/security due to a feature that still seems to be broken and/or not very widespread. IDK, up to you Pants. Just my 2 cents

**Comment by Thorin-Oakenpants** [comment]
IDK .. I have no cents .. this is one area that always does my head in

**Comment by Atavic** [comment]
Not many servers support it. https://github.com/pyllyukko/user.js/issues/17#issuecomment-100435660

**Comment by Thorin-Oakenpants** [comment]
By all that argument then the default is true so we all have shot feet

**Comment by Thorin-Oakenpants** [comment]
OK, I follow now - 66% of servers are Apache/Nginx - so if you hit one of those that fit the OSCP Must-Staple then you've tricked yourself - how? By connecting when you shouldn't have, I assume - because hard failing wouldn't be a loss of privacy/security? :headspin:

**Comment by earthlng** [comment]
No you've not tricked yourself. The article just illustrates that back in May even if someone in charge of a webserver would want to enable OCSP stapling on those 2 webserver SWs it could result in problems for their users if a CA is temporarily down and the stapling information on the server would get fucked up, effectively stopping anyone who had Must-staple enabled in their browsers from accessing their sites.
Therefore 66% of servers out there are likely not very inclined to enable stapling in the first place. But again, that was back in May, lots could have changed in the meantime.
I just don't want to confuse people into thinking that they can "force" a server to use stapling (and must-staple on the client-side) Read the grc.com article it explains at lot of it.

**Comment by Thorin-Oakenpants** [comment]
bad use of words .. "false sense" then. So they would fail at worst (hard fail when they didn't have to) which is not a loss of security/privacy. Which makes sense because if the error was the other way round (soft fail when they should have blocked it) then I doubt the default would be true.

So I agree the value should be true, which is default. But I also think this is too confusing. Hell, I'm a genius with 25 PhD's and a goat, and it takes too much to explain the ups and downs and side effects. It's even tricky to condense it to two or three lines - and even then people would misunderstand it. So yeah .. 

I need to go .. I'll have a sleep on it

**Comment by earthlng** [comment]
"false sense of added privacy/security" as in "I use the ghacks user.js and when reading thru it I noticed that OCSP must-staple is enforced and therefore I can trust that I will **always** get connected to the right server because otherwise must-staple would detect it and stop the connection"

**Comment by Thorin-Oakenpants** [comment]
> and therefore

Which is why ~~we~~ (/s ) **I** always want to putin explanations for dumb people like me :)

**Comment by Thorin-Oakenpants** [comment]
I think we'll skip on adding this to the user.js. The default value is what we want, so no worries there. IF it ever changes, we will pick this up in our FF release diffs and we can revisit it - so that's covered. Essentially we are future-proofed and the decision really boils down to earthlng's point about confusion and a false sense of security

@Exodion Thanks for the suggestion, appreciated - I learned something :)
