### ISSUE TITLE
Feature request: extension that installs/updates ghacks-user.js

### ISSUE THREAD

**Issue by sheddup** [ghacksuserjs/ghacks-user.js#272]

**Comment by Thorin-Oakenpants** [comment]
I am not an extension developer, but this is not possible AFAIK. Pretty sure file manipulation in the profile root folder is forbidden with web extensions.

Lets say it could - then the only way to do it would be for the extension to alert the user if they click on "check for update" (this would require some mechanism on our end) and if there was it would be up to the end user to click "update" or "close".

At this point - it could be as simple as sending them to the releases page.

Or it could get complicated where the js is fetched, compares done, local file read/write etc. It also would not be possible to change about:config entries (well, 99% of them) to reset those that are made inactive (and the default value for some prefs differ by OS, not to mention by release, so that would have to be coded for because AFAIK there is no "reset" command)

It also gets complicated with users tweaking their version. There is no way code can determine in a diff if say `// ` was added by the user or a previous version. The whole thing is just not feasible, sorry.
