### ISSUE TITLE
Basilisk

### ISSUE THREAD

**Issue by grumpygeek** [ghacksuserjs/ghacks-user.js#274]
Anyone interested in setting up and maintaining a user.js version for Basilisk?

**Comment by Thorin-Oakenpants** [comment]
My initial thoughts: nah

I'm not interested myself. However, it should be easy enough for someone to create it based on the ghacks user.js (deprecated section is by FF version, new prefs (since we came here at least) always get the FF version). It would need testing/checking to see what has been stripped out. Once its been done, then it should be easy to maintain - but the more divergent basilisk becomes from FF the more of a nightmare. I'm not up to speed on basilisk - whats been stripped, what's it goals are long term. And it would require seeing what moonchild & co add for their own prefs. It's probably better suited to a dedicated repo

Anywho... it won't be me. I have enough trouble finding time just for FF stable. And I still need to do a relaxed version (either a relaxed-override.js or a branch), after a couple more section revamps and the mess with storage is sorted. And the wiki needs my attention.

Anyone is free to take our project as a starting point - I'll leave this topic open for a week while I am away, so people can see it and you can all talk about a basilisk user.js home

**Comment by Gitoffthelawn** [comment]
Where you going @Thorin-Oakenpants ?  We'll miss you! 💋

**Comment by Thorin-Oakenpants** [comment]
I can tell u Gitoffthelawn, but then I'd have to MDK <sup>1</sup> u

<sup>1</sup>MurderDeathKill : from the movie [Demolition Man](http://www.imdb.com/title/tt0106697/) (1993), also a [video game](https://en.wikipedia.org/wiki/MDK_(video_game)) (1997), also a violent street gang somewhere ...  i think u get the idea :) :kiss:
