### ISSUE TITLE
JS link not workin'

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#28]
`<a href="javascript:void(lstc_preview());">preview</a>`

it's supposed to open a new window, but instead it opens a new blank tab @ `https://[domain].org/wp-admin/options-general.php?page=lightweight-subscribe-comments`

works with a new profile, but i'll be damned if i can find what pref is responsible - i reset all 'dom.' prefs, all tab prefs, all security prefs and every other one i thought might be responsible trying to hunt this bugger down

console says: `18:19:09.848 TypeError: document.getElementById(...) is null 1 options-general.php:187:60`

**Comment by Atavic** [comment]
Similar questions on Wordpress support.

**Comment by atomGit** [comment]
the click events at w3 all work for me - i looked for another JS example that opened a new window, but didn't readily find any

**Comment by earthlng** [comment]
so what's the problem exactly? is it that it's opening a tab instead of a window? you say it's a new blank tab but then add an url. I don't get it. is it a blank tab, or that url but it should be another url? And without knowing where exactly this happens, makes it impossible to look at the code to figure out where it goes wrong.
Did you make sure it's not caused by an addon or userscript?

**Comment by Roman-Nopantski** [comment]
- first of all 3007 is set to open new windows in a new tab instead `browser.link.open_newwindow` . This is under Options>General and 3 is the default value. So let's ignore that part of it. It doesn't matter where the page is opened, the problem is the instruction on what to load is not being passed on - hence an empty page.

@atomGit (and everyone else who reads), when you log these, you need to give us reproduceable steps, the more info the better. Obviously we can't test on your word press admin page. What is the code behind the link? Does it happen elsewhere?

**Comment by earthlng** [comment]
> remove the first half of it. ... If the problem still exists, then you know it is <1400
wouldn't it be the other way around? ie. if the problem still exists without the first half, it would be >1400

**Comment by Roman-Nopantski** [comment]
Fixed. its not actually how I would test mine. I would use add, section by section, so I don't have to reset the profile folder. And given my knowledge, I would probably add the right section first pop.

**Comment by earthlng** [comment]
> I would use add, section by section

Oh, that's way better. You should use that methodology when writing the guide IMO

**Comment by Roman-Nopantski** [comment]
[Troubleshooting Wiki](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4:-Troubleshooting)

**Comment by earthlng** [comment]
@atomGit If you don't answer our questions or provide more details, we can't help and I will have to close this issue.
If you can't figure it out by yourself, go to that general-options.php page, right-click anywhere and click 'Inspect Element', and then copy the whole source code from the Inspector tab and pastebin it for us to have a look. Before you pastebin it, sanitize everything that could allow someone to hijack your session cookie, or could let someone know where that wp-admin site can be found, etc. (urls to your domain, form-parameters, etc)

**Comment by Roman-Nopantski** [comment]
@earthlng atomGit is 12bytes and is probably busy right now, he will come back to it. He's also off watch probably due to the busy first days of the repo.

Idea: We could provide a "report issue" template
```
FF version: __
Settings that are related: _
Website(s): __
Steps to reproduce: _
etc
```

I would prefer that we don't close anything until we solve the issue, and I'm even happy leaving issues like that `bug` one open until it lands. pyllyukko just closed an 15 month old ticket of 3 comments. It's no big deal to have open items to remind us. Don't get me wrong, let's be clean and tidy though.

We can set an annual date for "The Purge: earthlng" :)

**Comment by atomGit** [comment]
@Roman-Nopantski - you asked for more information, including the link source - it is:

`<a href="javascript:void(lstcPreview());">preview</a>`

also you asked: "Does it happen elsewhere?"

no, not that i've noticed

@earthlng ...

> Did you make sure it's not caused by an addon or userscript?
> What's the WP version?

i have not tested with a clean profile yet - i should have already done this, but i didn't - partly because i'm confidant it's a user.js issue, but i will test and get back on this soon - i'm busy with work just now

WP 4.7.2

the JS link code though is from the plug-in 'Lightweight Subscribe To Comments' v1.5.2

may be a couple hours yet until i can provide more info

**Comment by atomGit** [comment]
this is not a user.js issue 

very sorry to have wasted your time with this - never again

i tested with a fresh profile, importing only my current user.js and the pop-up worked as expected

**Comment by Roman-Nopantski** [comment]
> very sorry to have wasted your time with this - never again

You're not wasting our time, you're part of the team, you even publish and push and use this, so feel free to bring anything up. Good to know its not something in the js. Let us know what caused it when you find out.
