### ISSUE TITLE
Script to clean deprecated prefs from prefs.js

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#303]
Anyone interested in that kind of script, before I dig into?
If so, I can make powershell one.

Cheers

**Comment by Thorin-Oakenpants** [comment]
See #242 which I hope to do one day

**Comment by crssi** [comment]
It a bit ugly. But WTH, will be good for first post.

```powershell
if (Get-Process firefox -ErrorAction SilentlyContinue) { Write-Host 'Firefox must be closed to proceed. Exiting...'; Exit }

if (($InstalledVersion = Get-ItemProperty 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\Mozilla Firefox *', 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Mozilla Firefox *' | Sort-Object DisplayName | Select-Object @{Name='Version';Expression={$_.DisplayVersion.Split('.')[0]}}, @{Name='Name'; Expression={$_.DisplayName}}) -eq $null) { Write-Host 'No Firefox installed. Exiting...'; Exit }

Try { $ghacks_user_js = (Invoke-WebRequest -Uri https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/user.js).Content } Catch { Write-Host 'There might be no internet connection. Exiting...'; Exit }

$Section9999 = ([regex]'\/\*\*\*\s9999:.*\/\*\sEND:').Match($ghacks_user_js.Replace("`n", "°")).Value # get deprecated section
$Section9999 = ([regex]'°\/\*\sFF.*\/\*').Match($Section9999).Value # strip header and kill the parrot
$ValidVersions = @(($Section9999.Split('°') | Select-String -Pattern '^\/\S\sFF.*') | ForEach { $_ -match '^\/\S\sFF(\d{2}).*' | Out-Null; $Matches[1] })


Write-Host 'Firefox installation(s) found:'
$InstalledVersion | ForEach { "$($_.Version) : $($_.Name)" }
Write-Host ''

if ($InstalledVersion.Count -ne 1) { $Version = Read-Host -Prompt "Enter Firefox version (Default: $($InstalledVersion[0].Version); 0: Exit)" }
if ($Version -eq 0) { Exit }
if (!$Version) { $Version = $InstalledVersion[0].Version }
if ($ValidVersions -notcontains $Version) { Write-Host 'Selection input error. Exiting...'; Exit }
Write-Host "Selected version: $Version"
Write-Host ''

$DeprecatedPrefs = @($([regex]".*°\/(\*|\/)\sFF$Version(?=.*)(?(?!\/{2}\s(?:\*{3}|(\*\s){3})\/).)*\/{2}\s(?:\*{3}|(\*\s){3})\/").Match($Section9999).Value -split '°' | Select-String -Pattern 'user_pref' -SimpleMatch | ForEach { $_.ToString().Split('"')[1] })

if (!(Test-Path $env:APPDATA\Mozilla\Firefox\Profiles.ini)) { Write-Host "Profile folder can't be found. Exiting..."; Exit }
$FirefoxProfiles = @([String]::Join(' ', (Get-Content $env:APPDATA\Mozilla\Firefox\Profiles.ini)).Replace('[',"`nProfile=").Replace(']','').Trim().Split("`n") | ForEach { New-Object psobject -Property (ConvertFrom-StringData -StringData $_.Trim().Replace(' ',"`n")) })
$FirefoxProfiles = $FirefoxProfiles | where { $_.Name -ne $null -and $_.Path -ne $null} | Sort-Object Default, Name
$FirefoxProfiles | ForEach { if ($_.IsRelative) { $_.Path = "$env:APPDATA\Mozilla\Firefox\$($_.Path.Replace('/','\'))"}}
Write-Host ''

Write-Host 'Firefox profile(s) found:'
$index = 1
$FirefoxProfiles | ForEach { "$index : $($_.Name) ($($_.Path))"; $index++ }
"$index : Custom path"
Write-Host ''

Remove-Variable SelectedProfile
$SelectedProfile = (Read-Host -Prompt 'Enter profile index (Default: 1; 0: Exit)').ToString().Trim()
if (!$SelectedProfile) { $SelectedProfile = 1 }
if ($SelectedProfile -eq 0) { Exit }
Try { $SelectedProfile = [Int]$SelectedProfile } Catch { Write-Host 'Selection input error. Exiting...'; Exit }
if ($SelectedProfile -gt ($FirefoxProfiles.Count + 1)) { Write-Host 'Selection input error. Exiting...'; Exit }
Write-Host "Selected profile: $SelectedProfile"
Write-Host ''

if ($SelectedProfile -eq $FirefoxProfiles.Count + 1) { $ProfilePath = (Read-Host -Prompt 'Enter the profile path').TrimEnd('\') } else { $ProfilePath = "$($FirefoxProfiles[$SelectedProfile - 1].Path)" }

if (!(Test-Path $ProfilePath\prefs.js)) { "$ProfilePath\prefs.js could not be found. Exiting..."; Exit }
$CurrentPrefs = Get-Content $ProfilePath\prefs.js

$RemovedPrefs = $CurrentPrefs | where { $DeprecatedPrefs -contains $_.Split('"')[1] }
$NewPrefs = $CurrentPrefs | where { $DeprecatedPrefs -notcontains $_.Split('"')[1] }

if ($RemovedPrefs) {
    $TimeStamp = (Get-Date).ToString("yyyy.MM.dd-HH.mm.ss")

    Move-Item $ProfilePath\prefs.js "$ProfilePath\prefs.js-$TimeStamp-backup.txt"
    $NewPrefs| Out-File $ProfilePath\prefs.js -Encoding Default -Force
    $RemovedPrefs| Out-File "$ProfilePath\prefs.js-$TimeStamp-removed.txt" -Encoding Default -Force

    Write-Host 'Done!'
    Write-Host ''
    Write-Host "Backup of original: $ProfilePath\prefs.js-$TimeStamp-backup.txt"
    Write-Host "Removed prefs log : $ProfilePath\prefs.js-$TimeStamp-removed.txt"

    Exit
}

Write-Host 'No changes needed. Exiting...'
```

**Comment by Thorin-Oakenpants** [comment]
Um .. so what does this do exactly?

Take commented out preferences from user.j section 9999 and remove them from pref.js if they exist in there? Is that what it is meant to do? And does it account for the fact that the ESR sections in deprecated do not use `//` but instead have a whole section switch?

^^ If that is what this does (section 9999) then why not just do the entire user.js?

I need an English description of what this is meant to do

**Comment by crssi** [comment]
It takes all prefs (commented and not commented) from Section 9999 up to and included your version of FF. But you can also choose to override  by entering desired version of FF.

What do you think with entire user.js?
Your ghacks user.js as a source or users user.js file?

**Comment by Thorin-Oakenpants** [comment]
> What do you think with entire user.js?
> Your ghacks user.js as a source or users user.js file?

Always use the local file

**Comment by crssi** [comment]
Give me please couple of hours... I have found one non-lethal bug (annoyance).
I will also add comments, to see clearly what does what.

Why local? Who says that user didn't strip out Section 9999?
I am using your web file, since is most up-to-date and it really has Section 9999.

**Comment by crssi** [comment]
Updated.
Cheers

**Comment by Thorin-Oakenpants** [comment]
> Why local? Who says that user didn't strip out Section 9999?

Who said u were referring to just the section 9999? IDK, maybe build in a switch to use local or latest-on-web. Take your time. This is @earthlng and @claustromaniac territory

**Comment by crssi** [comment]
Implementing local would be simple.
Implementing only local would be too simple.

Upper script looks complicated, since it takes ghachs-user.js from the web and parses all deprecated up to, including, you version of FF.
So there is your FF version detection and there is your profile detection.

Script would be a few lines long if I do it to process only the folder in which the script is started (so there is no profile detection needed) and with the use of file with a list of deprecated prefs of interest (so there is no FF version detection needed).

I actually don't need time... if you find that I could be in any help here, then here I am to use me. :)
Just let me know what and how would you like and will do.

It would also be no hard feeling in case you just close this "issue".

Cheers

**Comment by claustromaniac** [comment]
For convenience, I could add similar functionality to the batch updater if there was a demand for it (or if I'm bored and can spare the time to do so).

**Comment by Thorin-Oakenpants** [comment]
I'm only just recovering from all those scratchpad scripts, which served a purpose. It's a scary thing for someone to run those - effectively clearing 600+ prefs

The purpose was to make sure that end users were effectively in sync, and hadn't forgotten to rest anything. It also worked in reverse by showing me what I had forgotten to add to my overrides section.

However
- it's a bit scary, maybe
- it's (probably) immediately out of date as soon as the end user does changes or updates

So... a script (and Firefox must be closed), that
- checks for `webappsstore.sqlite-shm` to determine if FF is open
- checks for user.js
- backups prefs.js
- removes entries in prefs.js that are `//` in user.js
- creates a log of changes (only items that were actually removed)
- closes, user restarts FF

THIS would be an always-up-to-date solution, rather than the scratchpad sripts

I would like to see this as a separate file and not built into the updater bat. A single purpose clear bat

**Comment by Thorin-Oakenpants** [comment]
^^ not quite right. It's inactive prefs, not just those with `//` .. some inactive prefs are behind one-char switches, so we need to determine those as well

**Comment by claustromaniac** [comment]
I haven't yet tested the script @crssi provided here, but if I understand correctly it already more or less covers that. For a standalone solution, the only advantage a batch script would have over this powershell script, as far as I know, is that it wouldn't require the user to change powershell's execution policy first (which defaults to _restricted_). However, if you hosted the script in this repository you could simply add instructions for that in the wiki or somewhere else. It is as simple as:

1. Save the above script with a .ps1 extension.
2. Open the command line prompt, and enter the following:
```
powershell
Set-ExecutionPolicy RemoteSigned
```
3. Run the script.

It seems it would still need a few changes to make it work exactly the way you describe, though. Also the RemoteSigned policy requires that users create the .ps1 files themselves, otherwise they would need to set the execution policy to Unrestricted.

**Comment by earthlng** [comment]
> THIS would be an always-up-to-date solution, rather than the scratchpad sripts

this would not detect any prefs that we removed from the user.js

**Comment by Thorin-Oakenpants** [comment]
True, that's the only drawback - but it's the same for any method, because the item is gone. Heck, even our list has been manually created

**Comment by claustromaniac** [comment]
Pants, is there any good reason not to remove every preference (active and inactive) in user.js from prefs.js? Active preferences would end up in prefs.js anyway, and it would simplify such a script a lot.

amirite?

The only downside I see: a log would include removed active preferences.

**Comment by Thorin-Oakenpants** [comment]
I'm not sure I follow

### scratchpad
The scratchpad scripts remove every pref (because we do not know what end users have done to their copy, i.e in the main body, not an override section), so by clearing the lot and then a restart to re-apply the active ones, it means it should now be all squeaky clean and in sync. Note: the "removed" prefs are a different story.

### bat file for local user.js
For THIS local bat file idea where it ONLY reads the local user.js, then all it needs to do is remove the inactive prefs, which is what I said. This bat file can also be used with ANY user.js, not just ours

### bat file as outlined by crssi
The idea that this local bat file idea clears shit based on the online version is not suitable IMO, and should be dropped. It complicates things

### summary
- updater scripts to update user.js and append overrides
- cleaner script for local user.js->prefs (remove inactive prefs only) <- universally good with any user.js (assuming syntax convention that we can pick up on any `user_pref("` string and determine it is inactive)
- scratchpad script for removed items

That's all that would really be needed, although the other scratchpad scripts can come in handy if people trim their user.js, i.e they remove items/sections, it could help them clean up missed resets

**Comment by claustromaniac** [comment]
I just meant that if we remove from prefs.js all the preferences in user.js, commented-out (inactive) or not, then the active ones will end up in prefs.js anyway. This would simplify the script since it wouldn't need to determine what is active or inactive in user.js first. Is there any good reason to **only** remove commented-out preferences instead?

**Comment by Thorin-Oakenpants** [comment]
Well, yup, that's the simplest way - that's what the scratchpad scripts do, because as you said, active ones get reapplied.

**Comment by Thorin-Oakenpants** [comment]
why close this? we haven't produced a final script(s) or documented it anywhere

**Comment by crssi** [comment]
I don't see a reason to keep this one open simply because @claustromaniac script makes more sense and even doe PS is more capable, the BAT is easier for end user.

**Comment by Thorin-Oakenpants** [comment]
issues are like a checklist of todo items - so I want it open until the job is finished, that's all :)

**Comment by Thorin-Oakenpants** [comment]
have added a note to #283 for adding this to the wiki

**Comment by claustromaniac** [comment]
I came up with a neat way to make the script reset preferences that have long since been removed from the `user.js` in addition to those that still are in that file. The method uses an internal list that works like arrays in other scripting/programming languages. It's far less complex than it sounds and the script would then replicate the functionality of the scratchpad scripts, but it would be a bit more comfortable to use.

I've been wondering if that would be a worthwhile addition to the script. Maybe as an optional feature or something. What do you guys think?

I wouldn't mind writing the code first so you can judge by yourselves if it is good enough or not. Just let me know if you're interested.

**Comment by Thorin-Oakenpants** [comment]
IDK, the deprecated scratchpad script is universal and takes all of 3 seconds to run (and another 3 to restart FF). It's a one off job as well. I don't think we need another list to maintain ("method uses an internal list"),

**Comment by claustromaniac** [comment]
> takes all of 3 seconds to run

In the wiki there are 9 steps for the scratchpad scripts vs 2 clicks for the prefsCleaner.bat. But yeah, I never said they were hard to use or anything like that.

>  I don't think we need another list to maintain ("method uses an internal list"),

Yeah, we don't need it, and it's understandable if you don't want one. I get that you're busy enough as it is. That's why I asked before doing anything.

Here's another idea that doesn't seem to have any drawbacks. The version 4.3 of the `updater.bat` (if accepted) will not overwrite previous backups of the `user.js`. Since the `prefsCleaner.bat` already uses `user.js` as an _external_ list, it would be useful if it was able to reset preferences using all of the backups as sources instead of just the current `user.js`. It could be an optional feature (or default behaviour, I don't care), and it would help because the script would never miss any of the removed preferences, as long as one does not remove any backups from the profile folder before running the script. Then you guys wouldn't even need to temporarily make the preferences that you want to remove inactive, you could just remove them instead.

Does that sound better?

**Comment by Thorin-Oakenpants** [comment]
I'll leave the updater bat to you and earthlng :)

I follow the argument for prefsCleaner to optionally use previous backups for resetting (i.e it will pick up on items we remove), but is it really necessary? I think it complicates things.I think we're almost done removing items (except the e10s section at some stage - and the e10s section should not be reset IMO as some are set internally depending on HW, and there are possible issues if the system xpi is missing - we left them out of the scratchpad scripts)

**Comment by claustromaniac** [comment]
> is it really necessary?

The `prefsCleaner.bat` is not necessary at all. This was never about fulfilling _needs_.

> and the e10s section should not be reset IMO as some are set internally depending on HW...

Internal settings, of course! I didn't consider that. Taking that into account, this is definitely not a good idea. Good thinking, Pants.

**Comment by Thorin-Oakenpants** [comment]
>  This was never about fulfilling needs.

I know. You just want to rack up your commit numbers and develop the ultimate bat AI

**Comment by claustromaniac** [comment]
Sounds pretty shallow when you put it that way, but yeah. I like challenges. Life would be boring without them, and they are somewhat more rewarding when they produce something that can be useful to someone else, even if they don't get to thank me for it.

**Comment by Thorin-Oakenpants** [comment]
None of us here are doing it for the reward .. its always the challenge (and learning curve) buddy! That and the makeup sex after we ~~have passionate discussions~~ argue. But if it makes you feel better, I can gift you two rocks that keep tigers away :) Send me your address...

**Comment by claustromaniac** [comment]
> None of us here are doing it for the reward

You sure? Did you ask everyone?

I don't know or care about anyone else's motives.

> But if it makes you feel better, I can gift you two rocks that keep tigers away :) Send me your address...

If that was a reference to The Simpsons, I don't see how it applies to this discussion. Sorry, I know I can be dense sometimes.

**Comment by Thorin-Oakenpants** [comment]
> You sure? Did you ask everyone?

There is no reward.. cogito ergo....

Not really a Simpsons reference.. I just have two rocks, but needed to make them seem special so you would feel special :) .. nvm

**Comment by claustromaniac** [comment]
> There is no reward.. cogito ergo....

Right, because humans never make futile attempts.
