### ISSUE TITLE
FYI: e10s section can cause missing tab close icons

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#306]
FYI: I have known this for a while, but did not bother tracking it down until now, while I was testing the clear scratchpad scripts

When I apply the user.js to a new profile (FF57) and restart, I get this
![closebutton](https://user-images.githubusercontent.com/16656956/33756660-5d37142c-dc5b-11e7-8047-ce761b463a3e.png)

The close icon is not drawing properly or something. I came across the same thing when I tested resetting all the inactive prefs (I used my main everyday FF) - see https://github.com/ghacksuserjs/ghacks-user.js/tree/master/scratchpad-scripts. I have since fixed that script by removing the e10s section, which I think it best left alone - it will most likely have modified/user-set values set internally by FF.

I narrowed the issue down to these two prefs
```js
   // user_pref("browser.tabs.remote.autostart", true);
   // user_pref("browser.tabs.remote.autostart.2", true); // (FF49+) (hidden pref)
```
and the solution was to set `browser.tabs.remote.autostart` to true and restart. However, these are inactive prefs, so I am yet to find the cause on a new profile.

I suspect it may have something to do with the fact that my nilla portable for testing has no system addons including the e10s rollout one.

So, scratchpad script is all good (just one script to go), but will investigate the new profile+user.js one later

**Comment by earthlng** [comment]
> I suspect it may have something to do with the fact that my nilla portable for testing has no system addons including the e10s rollout one.

That's exactly it. FF59 doesn't have that system addon anymore and e10s will be enabled by default.

**Comment by Thorin-Oakenpants** [comment]
Well, come 59 we could probably pull the e10s section (or leave it in until 61 for the ESR diehards). Still probably a good idea to leave e10s out of the clear scripts

**Comment by earthlng** [comment]
Yeah, we could keep the prefs to change the *number* of processes but removing all of it is fine as well.

> Still probably a good idea to leave e10s out of the clear scripts

Yes, I agree with your reasoning. ("likely set internally by FF")

**Comment by Thorin-Oakenpants** [comment]
Holy sh*t you're in an agreeable mood today ... should we discuss something contentious? xD

**Comment by earthlng** [comment]
credit where credit is due :)

**Comment by earthlng** [comment]
sorry about my not-so-nice comments about the wiki btw. I didn't mean to upset you and I didn't know that it means so much to you.

Regarding the Search engines stuff I now think we should only recommend DuckDuckGo. Based on my own experience I can no longer recommend Startpage and ixquick. I used SP for the longest time but I changed it to ixquick a couple days ago because Google is now actively censoring stuff that doesn't fit the narrative (Russia Today for example). Then yesterday I heard something about Glenn Greenwald and his alleged former involvement in the porn industry and since I'm not the kinda guy that trusts what people say without checking the sources myself, I started a search on ixquick and didn't find anything. I was almost ready to disregard what was said as pure rumours and bad-mouthing but then I decided to search with a couple other SEs and they actually found something about it. I don't know why ixquick didn't show these results but something doesn't seem quite right. Maybe they're just using shitty SEs in their searches or there's something more sinister going on with ixquick too. DDG on the other hand doesn't have any of these issues.

We could create a new Category "Further Hardening" or "Other Recommendations" and move the 2 SE pages into a single one with the links to 12bytes articles and a single recommendation to use DDG. And then move Extensions up under that new Category and maybe rename User Scripts to "User Scripts + Extension rules/filters". Then we could get rid of the empty placeholders for uMatrix, Redirector, etc. Something like this:

* Other Recommendations
  * 3.1 Extensions
  * 3.2 Search Engines
  * 3.3 User Scripts + Extension rules

**Comment by Thorin-Oakenpants** [comment]
Awww man .. I was gonna close this.

I just set up a new FF portable 57.0.1 (57.0.2 ain't out yet) with system addons and can confirm the missing close icon does not happen. I can also confirm the three suggest prefs do not get applied - will check the reverse if I only apply 0850a with the 3x850b at default which = true.

**Comment by Thorin-Oakenpants** [comment]
see #307
