### ISSUE TITLE
After login blank page [solved: FPI]

### ISSUE THREAD

**Issue by Virusrud** [ghacksuserjs/ghacks-user.js#315]
I have an issue... When I want to pay by AmazonPay there comes a blank page instead of being logged in. I tried it with my Opera browser and there it works fine.

The normal steps to login in are:
1. Click on "pay with AmazonPay"- Button
2. A popup-window opens and I have to enter my login data
3. He asks if I accept that Amazon gives the data to the website I want to pay by AmazonPay
4. After hitting Yes the popup closes and the page reloads and shows the data which were given by Amazon

The problem now is that FF does open a new Tab at step 1 and after step 2 it shows a blank page.

I tried many things and changed some settings but nothing works... I changed:

- cookie setting to allow
- TSL and SSL settings to the lowest 
- refresh page and hold shift when I push refrsh
- allow some cache functions
- set all 2203: disable [popup window] scripts hiding or disabling the following ***/ to false
- network.cookie.cookieBehavior", 0
- privacy.resistFingerprinting", false

**Comment by Thorin-Oakenpants** [comment]
Yes, you'll need a cookie because you're dealing with logins etc. I have never used AmazonPay and the last time I actually bought anything from Amazon itself, was 15 yrs ago. I have no way to diagnose this for you.

I'm not following this 100%, so please bear with me.
- when you click on "pay with AmazonPay", you are on a site that is NOT amazon, right?
- the pop-up window that opens, is this an actual new window, or just an overlay - by this I mean normally when it works. I see the behavior right now is it opens a new tab - sounds like it's not redirecting back? 
- cookie setting to allow - how did you do this, what did you use, eg did you go Right Click>View Page Info>Permissions>etc
- What is the AmazonPay domain being used etc

You might need to allow a third party cookie. Do you use uBlock or uMatrix - they can be handy to see all the domains being used. I was going to say workers/web workers might be needed, but they can only work across the same domain AFAIK. Maybe referrers (which we do not spoof)  - are you using any extensions?

At this stage I'm  just guessing. Cache shouldn't make any difference. Amazon should be fine with TLS, they wouldn't be running old stuff like 1.0/1.1 I wouldn't think. RFP you seem to have ruled out (that *can* have issues with logins from one domain used on another).

At the end of the day the only way to really find the culprit is trial and error, or create a new profile, test half the user.js .. reset the profile, retest again, etc .. halving each time to narrow it down. Shouldn't take more than 4 or 5 tests. See the wiki section on troubleshooting - maybe someone else has some ideas

**Comment by Atavic** [comment]
Surely they use referrers, the user.js has only one entry different from defaults:
`user_pref("network.http.referer.XOriginPolicy", 1);` 

It's default value is 0

**Comment by Virusrud** [comment]
Thank you very much for all your help!

I am a littlebit desperate now... I tried all the things you all told me but nothing works.

@Atavic I set it to 0 but no change
@mazesy I set it to false but no chnage
@Thorin-Oakenpants 

> when you click on "pay with AmazonPay", you are on a site that is NOT amazon, right?
Right!

> the pop-up window that opens, is this an actual new window, or just an overlay - by this I mean normally when it works. I see the behavior right now is it opens a new tab - sounds like it's not redirecting back?
It is actual a new window. It closes when the login-data is right and the paymentdata of my Amazon account are shown at the checkoutpage of the shop where I want to order something.

> cookie setting to allow - how did you do this, what did you use, eg did you go Right Click>View Page Info>Permissions>etc
I set all to allow and it even don`t work. 
I also set user_pref("network.cookie.cookieBehavior", 0); 
At the settings page of FF under security there is shown that coolies are always enabled

> What is the AmazonPay domain being used etc
**Thats the domain of the login (works normal and I could type in my account-data):**
https://eu.account.amazon.com/ap/signin?_encoding=UTF8&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.pape.max_auth_age=0&ie=UTF8&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_lwa_eu&marketPlaceId=A3M3RRFO9XDT2G&arb=840864cf-ebe3-4b8a-a011-02bec4d98215&language=de_DE&openid.return_to=https%3A%2F%2Feu.account.amazon.com%2Fap%2Foa%3FmarketPlaceId%3DA3M3RRFO9XDT2G%26arb%3D840864cf-ebe3-4b8a-a011-02bec4d98215%26language%3Dde_DE&metricIdentifier=amzn1.application.97a6630dd9a543c68880279349a8cc71&signedMetricIdentifier=ebn7ejGD9S%2BXxKnL2zjE75GipnazL4ofvleWtqKOZ%2FA%3D

**Thats the link which opens after I click login and the blank page comes:**
https://eu.account.amazon.com/ap/oa?clientContext=259-0246288-2288010&aToken=Atza|IwEBINlopPNy7lTjwuvCnMtyze-H68pJXEBORHNQsKTyIAYONywkktuzCcnRXWBn58m9V_4d3d-NJn583Kl0EIesCMlEW3kvy5eZfPD1K6xb3htM5H1VjxaxVavBmE7yWHwtHqYnDYlHM7pBKzsSwHZdtwP1cI48vaN2ko1kKi6b8_pDdMH2Fi1wxLQGku1FFf_lc1LV73RjmICF8QNvCdTz50h5YVW08_WrXpPrV1OjKAh_VC_X5t-sj0dxCePfcfFxvHgwL0hTNhKsyUNPtxq8MKASVBNlC3qGhKBF8vk9L2X83eqJfZMbVdWVIDLebvuUOiUYkNX8JjXVwPDZVtGyYJ1cXeuO57-hpcu1wU752ahtco0ZVizADbz25AmZTpWC6ljLR2ADu8VU4fIKXeYpCBuo&openid.pape.max_auth_age=0&openid.identity=https%3A%2F%2Feu.account.amazon.com%2Fap%2Fid%2Famzn1.account.AGM6BUKYS6B7COTEELLFBPPRAB5Q&openid.op_endpoint=https%3A%2F%2Feu.account.amazon.com%2Fap%2Fsignin&openid.pape.auth_time=2017-12-22T11%3A25%3A34Z&marketPlaceId=A3M3RRFO9XDT2G&openid.signed=assoc_handle%2CaToken%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2Cns.pape%2Cpape.auth_policies%2Cpape.auth_time%2Csigned&language=de_DE&stashKey=ee71f0d0-aa37-4149-bd06-9c5a8262b8f2&arb=840864cf-ebe3-4b8a-a011-02bec4d98215&openid.return_to=https%3A%2F%2Feu.account.amazon.com%2Fap%2Foa%3FmarketPlaceId%3DA3M3RRFO9XDT2G%26arb%3D840864cf-ebe3-4b8a-a011-02bec4d98215%26language%3Dde_DE&openid.assoc_handle=amzn_lwa_eu&serial=1&openid.mode=id_res&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&openid.sig=eIyaZkSLpgdob3bz2EfsDkKpIiD4o0dgF%2FBkEdDzKQqeGWCqIDv70643xEgxjzM8tP%2BOgtn%2FQIPHXuJpMjRm%2BOIZrU9gAGxl2U3uoe7dXfFOGbm6mw7pT0qHUDVp9i%2Bt%2FayWoF4H7NchFm6hgy4HikJw9zKEh0jZC%2FnY9MvWmxpMMgnT1SGwLqFcSm2xdZmArmPRb5mDPDw9FfpaM6Tmdg786%2FxxpnAr1ZBe234jzavG9ohhXoixupbwTrAbtb%2ByinIH1XqqxcIGzpjDP%2BVN2RDl3SQpAlsV0QkUmp3ukTOTT%2Fi1t%2BByrwg9KOWQVdEnBKPNHKgFPaJD4Kjk7MK9DQ%3D%3D&openid.claimed_id=https%3A%2F%2Feu.account.amazon.com%2Fap%2Fid%2Famzn1.account.AGM6BUKYS6B7COTEELLFBPPRAB5Q&openid.response_nonce=2017-12-22T11%3A25%3A34Z-808595910497340577&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0

> At the end of the day the only way to really find the culprit is trial and error, or create a new profile, test half the user.js .. reset the profile, retest again, etc .. halving each time to narrow it down. 
I also tried this too. I cut out eg the whole part /*** 2700: COOKIES & DOM STORAGE ***/ and saved the user.js afterwards. Tried once more and when it didn`t work I put the part back in the user.js and cut out the next part...


So maybe I explained the failure a littlebit wrong. I am sorry but english is not my foreign language.
Short: Instead of closing the login-window after I pressed "login" and showing me the account details of my Amazon account, the window stays open and is blank.

**Comment by mazesy** [comment]
> I also tried this too. I cut out eg the whole part /*** 2700: COOKIES & DOM STORAGE ***/ and saved the user.js afterwards. Tried once more and when it didn`t work I put the part back in the user.js and cut out the next part...

Before carrying on be aware that the user.js script writes but doesn't erase : if you disable, remove ant setting in user.js it will not restore those settings to what they were previously/as default. You'd have to enter about:config and reset manually all that has been modified by user.js ... which is why one must always think carefully before using user.js.

Back to your issue.

**Comment by Virusrud** [comment]
> Before carrying on be aware that the user.js script writes but doesn't erase : if you disable, remove any setting in user.js it will not restore those settings to what they were previously/as default. 

Ahhhh! I didn`t know that. Thats why @Thorin-Oakenpants said I have to "... create a new profile, test half the user.js .. reset the profile, retest again, etc .. halving each time to narrow it down."

So before I work on the user.js for plenty more hours I ask in advance if the right way is:
--> Setting up a clean user.js (clean install of FF portable) and paste part by part of the ghacks-user.js in the clean user.js until the error happens???

**Comment by earthlng** [comment]
> Setting up a clean user.js (and clean install of FF portable) and paste part by part of the ghacks-user.js in the clean user.js until the error happens???

yes that's right. 

> when I change parameters in the user.js from 0 to 1 or false to true, it also changes in the about:config

when you **change** a value in the user.js then yes it also changes in about:config, but if **remove** something from the user.js it does NOT automatically reset that value.

Since this seems to be a openid login attempt I suggest you try to disable `privacy.firstparty.isolate`, and because the link you posted says "bad request" you should also try to reset all the Referrer settings. If that doesn't work then I'd try workers next which is `dom.workers.enabled`.

**Comment by mazesy** [comment]
user.js writes its settings and about:config displays those settings.

- If you modify user.js modification will be displayed in about:config.
- If you remove a user.js setting it will not reset (as mentioned above).
- If you modify manually an about:config setting it will be overwritten by user.js on next Firefox start if that setting is activated in user.js: that's how to revert (reset) a user.js setting which we've disabled/removed.

**Comment by Thorin-Oakenpants** [comment]
I edited your post to remove those links - they may have had identifying info in them, not sure. I can see that AmazonPay is still TLD amazon.com - I'm just not sure how *amazon.com gets to send its info to someshop.com.

Testing. Download a portable FF. Start it, and it creates a new empty profile. Add a bookmark for the site etc. Close Firefox. Under FirefoxPortable/data/ is a profile folder. Copy it and call it profile-clean.

```
FirefoxPortable
-- data
---- profile
---- profile-clean (we will use this to reset if need be)
```

So in your profile you add a blank user.js and paste in half the contents (eg up to section 1600), and start FF, and test everything works.
- If the problem does not exist then you paste in some more items (eg 1600-2200) and test again etc etc
- If the problem occurs we now KNOW its somewhere in 0-1600, so you can close reset your test profile and start again with eg say sections 0-800.

Note: resetting you profile is as simple as closing portable FF, deleting the `profile`, and copying the `profile-clean` back as a new `profile`

^^ keep halving the problem error and you will quickly narrow it down.

**Comment by Thorin-Oakenpants** [comment]
@mazesy et al .. OT: that `network.http.tailing.enabled` - I was was wondering if that affects extensions at all, eg some scripts are delayed for up to 6 seconds etc. I'm an idiot, so I do not know about asynchronous things etc, but I would assume uM, uBo etc still detect and work etc

**Comment by mazesy** [comment]
@Thorin-Oakenpants I have exactly that same questioning in mind ever since I read the article but didn't bounce on gHack's blog to further develop that idea.

You know far more than me but obviously any rational mind may wonder if postponing tracking scripts (with the tailing feature),
1- remains pertinent when dedicated tools (uBO in particular) block their very download,
2- might even be counter-productive in the dedicated tools' very action, i.e. uBO acting on page load then 6 seconds on remaining tracking scripts ...

I guess it's a valuable topic. I lack info as always. Gorhill's opinion regarding uBO & tailing is the right opinion to get, indeed.

**Comment by Thorin-Oakenpants** [comment]
I've read a few things in the past - eg how a uBo counter can end up as 95% blocked items - it ends up in a bit of a race condition as the web page JS and uBo go hard at each other - i.e the JS is detecting blocking and replacing it, and uBo just keeps doing it's job

At the end of the day, I'm pretty sure everything is caught because at a lower level it all goes thru Firefox's API, and extensions just have to do is listen (clearly I am not a developer!), so a six second delay means nothing - it;s just like you were on dial up, or have a really shitty connection

**Comment by Thorin-Oakenpants** [comment]
@Virusrud Sorry buddy, with all that advice etc, no-one pointed you to the Wiki page
- https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting

**Comment by Virusrud** [comment]
WOOHOO!!! I got it!!! Thank @all for your device and patience!!!

The failure was/is the "/*** 4000: FIRST PARTY ISOLATION (FPI)" part. I deleted the whole part and now everything works propper!!! 💃 

Are there many "leaks" when I open up/erase this part?

And just one quick question: I asked some time ago in an another thread I opened up (https://github.com/ghacksuserjs/ghacks-user.js/issues/280) if it is possible to change the system time or if it is possible to block that FF shows this time? @earthlng said that`s not possible at this time but maybe someone found a solution ;)

Again thanks to all of you!!!

**Comment by mazesy** [comment]
Great, @Virusrud ! 
You did notice the warning concerning first-party isolation:
```
/* 4001: enable First Party Isolation (FF51+)
 * [WARNING] May break cross-domain logins and site functionality until perfected
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1260931 ***/
```
This could have saved you time and efforts... but the main thing is that you got it spotted.

For system time spoofing without First Party Isolation you'd need a dedicated extension I guess.

**Comment by Thorin-Oakenpants** [comment]
FPI isolates by the domain .. so...
- you go to `siteA.com` and it loads `googleapis` (in order to function)
- you go to `siteB.com` and it ALSO loads `googleapis`

With FPI you get two sets of `googleapis` - and they cannot talk to each other. With FPI turned off, you would get a single `googleapi` and it would "know everything" - i.e it would know you were at both sites.

^^ this is a really simplistic example. There is way more to FPI than just cookies - it covers localstorage, IDB, workers. cache, HSTS, DNS and so on. In the case of cookies, we block third party cookies anyway. But as I said, there are many other tracking/storage mechanisms.

Effectively FPI protects you from third party tracking (by isolating everything used in "contexts" based on the Origin, i.e the site that called everything, i.e the "First Party").

What it does NOT protect you from is FIRST party tracking, i.e repeat visits back to the same site. For that you can use mechanisms such as clearing persistent data, using one off PB windows. FPI does have issues with logins used from different domains (eg using google.com to log into youtube), because the ""first party" is not the same domain, and the login flow is essentially an evercookie.

FPI is great, but not strictly necessary if you have good habits and can properly clean house - which at the moment is a bit hard due to issues with Mozilla's sanitize and other cleaning (eg forget site) etc. In a few more releases it should be much better.

So you have two choices. Use FPI in your main FF, and use a secondary browser for your amazonpay stuff. Or disable FPI and get into some good cleaning habits (which should be fairly good since FPI will no longer block extensions clearing cookies and local storage - note local storage cleaning won't land until 58+, and IDB cleaning by site does not yet exist). You can also severely limit persistent data by tightly controlling at a  granular level any XSS and JS etc - see uMatrix, uBlock Origin

**Comment by Thorin-Oakenpants** [comment]
> For system time spoofing without First Party Isolation you'd need a dedicated extension I guess.

Tom, system time spoofing is under RFP, not FPI

**Comment by Thorin-Oakenpants** [comment]
@Virusrud 
Re `privacy.resistFingerprinting` which spoofs your timezone as UTC 0. Why do you feel the need to set it as CET (central european time)? The whole point of this spoof is to enforce everyone to use the same value in order to lower entropy. Yes there are issues - eg this will affect your email time stamps in gmail for example .. or you go to look up when a baseball game is on, and it uses your system time and you end up missing it. At some stage when RFP is more refined and has a front facing interface, there **may** be a whitelisting feature, either for the whole RFP or for an aspect of it (eg you can now add/remove exceptions for canvas blocking)

**Comment by Thorin-Oakenpants** [comment]
^^ to directly answer your question. If you use `privacy.resistFingerprinting` (which covers an awful lot of things), then you cannot override the system time that Firefox reports to websites. There are two things that *may* work, but I doubt it

- In linux, you can load Firefox with a TMZ variable, however, I am 99.99% positive that the application level internal code for RPF will override this anyway
- An extension may be able to spoof your timezone. One example was Random Agent Spoofer, but that is not a web extension, and I do not even know if the APIs exist. And it would also come down to testing which of the two prevails: RFP patch or Extension. But since no extension I know of exists, it's a moot point

**Comment by mazesy** [comment]
First Party Isolation (FPI) and Resist Fingerprinting (RPF), OK. I get things mixed up sometimes (which means I don't conceptualize correctly!).

FPI is a work in progress but certainly very powerful and an essential tool in the privacy area. Your explanation, @Thorin-Oakenpants makes it more "_conceptualzable_" (that ain't proper English!). 

The beat goes on :=)

**Comment by Virusrud** [comment]
@Thorin-Oakenpants 
I salut you for your knowledge! I just asked a quick question and got so many information from you! Thanks a lot! I think I will just let it be and wait for an update that solves the problem. As you said its is not that important. I just like things to know and make them work as you can see at the Amazon problem... I try as long as it takes to solve problems ;)

Thank again for the great detailed answere!

**Comment by mazesy** [comment]
> An extension may be able to spoof your timezone. One example was Random Agent Spoofer, but that is not a web extension, and I do not even know if the APIs exist. And it would also come down to testing which of the two prevails: RFP patch or Extension. But since no extension I know of exists, it's a moot point

I had tried the _ScriptSafe_ Firefox extension which handles timezone spoofing if I remember correctly (I was then focusing on other features), not sure though. I didn't keep the extension as it overlapped several of uBO's functions, even if it had its specifics.

**Comment by Thorin-Oakenpants** [comment]
> I think I will just let it be and wait for an update that solves the problem

There won't be a solution. When a login flow is essentially an supercookie, it will never be fixed because it totally breaks all the rules (unless they develop some kind of whitelisting of pairs of domain+3rdparty) because of what I said above. There are dozens of bugzilla tickets about login issues. IN the end they created the pref listed as `4002` `privacy.firstparty.isolate.restrict_opener_access` as a means to relax it a little, but that's it.

directly told to me by Arthur Edelstein via IRC
> FPI will always have cross-domain login issues because some websites effectively use supercookies for their login flow.

**Comment by Thorin-Oakenpants** [comment]
Tom .. totally forgot about that SafeScript. Haven't tried it at all - have'nt had time and 99% of it is nothing new AFAIK

**Comment by Thorin-Oakenpants** [comment]
just to ram the point home - from #8 

* cross-domain / login issues
   [lots: here are *some*] [1319728](https://bugzilla.mozilla.org/show_bug.cgi?id=1319728), [1336458](https://bugzilla.mozilla.org/show_bug.cgi?id=1336458), [1319839](https://bugzilla.mozilla.org/show_bug.cgi?id=1319839), [1319761](https://bugzilla.mozilla.org/show_bug.cgi?id=1319761), [1319756](https://bugzilla.mozilla.org/show_bug.cgi?id=1319756), [1316019](https://bugzilla.mozilla.org/show_bug.cgi?id=1316019), [1340949 - breaks FF Sync's Manage Accounts](https://bugzilla.mozilla.org/show_bug.cgi?id=1340949)
