### ISSUE TITLE
updater.sh error

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#325]
https://www.ghacks.net/2017/12/29/automation-comes-to-the-ghacks-user-js-configuration-for-firefox/#comment-4325323

> when runing the updater on Linux, I have this :
> 
> ```
> bash updater.sh
> updater.sh: line 7: syntax error near unexpected token `newline'
> updater.sh: line 7: `'
> ```

**Comment by claustromaniac** [comment]
I don't know much about bash, but I would try something like this:

ghacksjs='https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/user.js';

Even though it shouldn't be necessary in that context. The raw already has LF line breaks, by the way. Could it be that it has something to do with [.gitattributes](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/.gitattributes)? Maybe it needs to explicitly convert bash file line breaks to LF, similar to what happened with the batch scripts?

**Comment by overdodactyl** [comment]
Can't reproduce here on a mac...I'll do some digging on the error message and see if I can come up with anything

**Comment by earthlng** [comment]
I've added .sh to gitattributes: https://github.com/ghacksuserjs/ghacks-user.js/commit/dd29583735642ee5d4fbc51e0e8dd4be2fe5363c - maybe that will fix it

**Comment by arnauldb** [comment]
Thank you @earthing

I still have the same error:

> bash updater.sh
> updater.sh: line 7: syntax error near unexpected token `newline'
> updater.sh: line 7: `<!DOCTYPE html>'

**Comment by Thorin-Oakenpants** [comment]
I downloaded the file .. well TBH, I opened the file ont he web and chose the RAW view and copypasta'd it into a new file .. its all mixed up for me

![mixed](https://user-images.githubusercontent.com/16656956/34462147-be217298-eea1-11e7-88fc-ed60e0de95d5.png)

@arnauldb - do you have Notepad++ at all? You can go `View>Show Symbol>Show End of Line` to see what EOLs you have

You can also go `Edit>EOL Conversion>Unix (LF)` to fix all the endings to LF, and save the file

Can you try that please? :)

**Comment by claustromaniac** [comment]
Yeah, it seems it could be what happened with the batch scripts. I'm getting LF line breaks in both the raw and the zipped file, but still, for the batch files merely modifying gitattributes wasn't enough to get GitHub to use the proper line endings in the raws. For it to work, earthing had to re-upload the file with the right line endings in addition. Maybe the same is necessary now.

**Comment by arnauldb** [comment]
@Thorin-Oakenpants 

It just worked, don't know what happened...
![selection_001_31_17 21 05](https://user-images.githubusercontent.com/13196747/34462975-4f23ca6e-ee4f-11e7-9b11-ab8ee2594a01.jpg)


Thank you.

**Comment by Thorin-Oakenpants** [comment]
@arnauldb awesome. I'l leave this open for earthlng to look at the RAW version

**Comment by kerframil** [comment]
The error that arnauldb originally reported at ghacks.net was **not** symptomatic of carriage returns being present in the content. Indeed, I had guessed that it might be an issue with mangled content and the shell processing a redirection operator. Having read his post here, it's clear that he downloaded and attempted to execute an HTML document instead of the raw script content (whose line endings were - and still are - correct).

@Thorin-Oakenpants Pasting content into Notepad++ isn't a valid test because Notepad++ will coerce the line endings into whichever format is in effect for the document window (CRLF by default). Downloading https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/updater.sh, then opening it with Notepad++ as a separate step would be OK.

**Comment by Thorin-Oakenpants** [comment]
@kerframil Thanks for your expertise. I saw that (HTML reference) in his linked screenshot and wondered about it for second or two, but ~~my lack of knowledge~~ fear prevented me from making a fool of myself :)

>  Notepad++ will coerce the line endings into whichever format is in effect for the document window (CRLF by default).

I knew it wasn't a totally valid test, but the fact that it had mixed line endings puzzled me - if I can get that, so could others. For ref, I am on Windows, I created a new txt file (right click, new text document), renamed it including ext name, dragged it into Notepad++, and pasted FF browser window contents (raw) into it.

@arnauldb - how did you create/get the updater.sh file the **first** time round?

**Comment by kerframil** [comment]
No worries, Thorin. For the record, if you use File > Save Page As from FF - selecting All Files (*.*) as the type - then open the file in Notepad++, the reported line ending format can be trusted. However, you may find it more convenient to paste the URL into the file open dialog of Notepad++.

**Comment by Thorin-Oakenpants** [comment]
^^ true that. Except 99% of my portable apps have no internet access via my firewall :)  gonna need MOAR tinfoil xD .. nah, I trust Notepad++, I can let him thru

**Comment by claustromaniac** [comment]
>  but my lack of knowledge fear prevented me from making a fool of myself :)

If it makes you feel any better, I missed it completely. I now started wondering how could that have happened, I mean, how could he get an HTML document in the first place, and checked the link on the article, which merely points to the wiki, and then I discovered that the link on [section 3.3](https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.3-Updater-Scripts) is wrong:

> https://github.com/ghacksuserjs/ghacks-user.js/blob/master/updater.sh

Fixing that will - hopefully - prevent this from happening again.

**Comment by Thorin-Oakenpants** [comment]
what is the link meant to be?

**Comment by arnauldb** [comment]
@kerframil & @claustromaniac 

> I now started wondering how could that have happened, I mean, how could he get an HTML document in the first place? 

yes, sorry for that, I should have checked the content of the "updater.sh" file I ran the first time...

**Comment by claustromaniac** [comment]
> what is the link meant to be?

I mean where it says ...

> [Download ](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/updater.sh)the updater.sh script and save it in your profile folder.

the link should be one for the raw version, either...
https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/updater.sh
or...
https://github.com/ghacksuserjs/ghacks-user.js/raw/master/updater.sh

Otherwise people can end up downloading an HTML document or, if they just follow the link, they have to figure out by themselves that they need to get the raw version.

@arnauldb Don't sweat it, man :) and thanks for letting us know that you couldn't get the script to work.

**Comment by Atavic** [comment]
The best way is to provide it from a specific repository or as a gist, where there's a download button to avoid any of the errors mentioned above. Then the repo could be listed [here](https://github.com/ghacksuserjs).

**Comment by claustromaniac** [comment]
@Atavic I see a downside to using gists, and it is that they would need to be manually updated every time that we want to make changes to the scripts in the repository. Also, they can only be edited by the one person who makes them, right? 

Secondary repositories sound like a better alternative, I guess. But still, if it were up to me I think I would simply change that part of the wiki to something like this:

> Download the [updater.sh](https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/updater.sh) (right click > save link as...)

**Comment by Atavic** [comment]
:+1: Yes.

**Comment by kerframil** [comment]
I recommend that the would-be user is instructed to either:

a) mark the script as executable with chmod +x before executing directly
b) specifically run the script by providing it as an argument to bash (as arnaudb did)

Otherwise, don't be surprised if someone eventually does something along these lines ...

```
$ curl -O https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/updater.sh
$ sh updater.sh
```
Cue a slew of errors because /bin/sh is not necessarily provided by bash and is thus limited to the features defined in the POSIX specification for the Shell Command Language. In short, sh is not bash.

I recommend (a). In that case, the user would need to either place the script in a directory referenced by PATH, such as /usr/local/bin, or qualify the path when executing it. For example: `./updater.sh`

**Comment by Thorin-Oakenpants** [comment]
I changed the link to point to the raw version and @kerframil et al, thanks.

@arnauldb Special thanks for bring up the problem(s) buddy :kiss:

**Comment by earthlng** [comment]
The only problem here was that the link didn't point to the raw file and someone downloaded the html document and tried to run that. I believe Linux users know how to make a script executable.
Placing the script in one of the default PATHs won't work because it needs to be in the FF profile folder.
