### ISSUE TITLE
Explicitly document that security.OCSP.enabled only affects OCSP fetching, not stapling

### ISSUE THREAD

**Issue by smithfred** [ghacksuserjs/ghacks-user.js#334]
Per https://hg.mozilla.org/mozilla-central/file/bd02f1cb9f4f/security/manager/ssl/nsNSSComponent.cpp#l828, setting the above pref to false doesn't (or shouldn't) affect stapling.

Though the user.js comments are correct in describing the actual effect, the pref. name itself is inaccurate/misleading - would be useful to specifically mention this, and that setting it to false (e.g. for privacy reasons) doesn't affect the non-trash-fire version of cert verification (stapling+must-staple) ;)

**Comment by Thorin-Oakenpants** [comment]
For reference
```js
/* 1211: control use of OCSP responder servers to confirm current validity of certificates
 * 0=disable, 1=validate only certificates that specify an OCSP service URL (default)
 * 2=enable and use values in security.OCSP.URL and security.OCSP.signing.
 * OCSP (non-stapled) leaks information about the sites you visit to the CA (cert authority)
 * It's a trade-off between security (checking) and privacy (leaking info to the CA)
 * [1] https://en.wikipedia.org/wiki/Ocsp ***/
user_pref("security.OCSP.enabled", 1);
```

> and that setting it to false

I assume you mean setting it to `0`?

**Comment by Thorin-Oakenpants** [comment]
I'll butt out of this one and leave it up to @earthlng

**Comment by earthlng** [comment]
@smithfred good find, thanks for reporting.
While researching this I also found that this line `2=enable and use values in security.OCSP.URL and security.OCSP.signing.` is (a) no longer the case and (b) was incorrect anyway. From what I can gather there never was a pref `security.OCSP.signing`. Back in ESR17 (!) there used to be a security.OCSP.**signingCA** but it does not exist anymore in ESR24 and newer.
So that's another thing we need to fix. How is this? ...
```js
/* 1211: control use of OCSP responder servers to confirm current validity of certificates
 * 0=disabled, 1=enabled (default), 2=enabled for EV certificates only.
 * OCSP (non-stapled) leaks information about the sites you visit to the CA (cert authority)
 * It's a trade-off between security (checking) and privacy (leaking info to the CA).
 * [NOTE] This pref only controls OCSP fetching and does not affect OCSP stapling.
 * [1] https://en.wikipedia.org/wiki/Ocsp ***/
user_pref("security.OCSP.enabled", 1);
/* 1212: set non-stapled OCSP to hard-fail
 * When a CA cannot be reached to validate a cert, Firefox just continues the connection (=soft-fail).
 * Setting this pref to true tells Firefox to instead terminate the connection (=hard-fail).
 * For more info about the problems with soft/hard-fail (and OCSP in general) see [2].
 * [NOTE] this pref is ignored if 'security.OCSP.enabled' is set to 0.
 * [1] https://blog.mozilla.org/security/2013/07/29/ocsp-stapling-in-firefox/
 * [2] https://www.imperialviolet.org/2014/04/19/revchecking.html ***/
user_pref("security.OCSP.require", true);
```
FYI mozilla set 1211 to [2 in nightly](https://bugzilla.mozilla.org/show_bug.cgi?id=1366100) for a while but apparently it didn't produce the outcome they'd hoped because in the latest nightly the default value is 1 again.

**Comment by smithfred** [comment]
Looks good to me re. the note. Could optionally refer to the source code comments, but that's the Wikipedia mentality in me ("citation needed") :D

**Comment by Thorin-Oakenpants** [comment]
Looks good to me as well

PS: Who broke github for the last 25 minutes? Was that u smithfred?

**Comment by smithfred** [comment]
Yep, that was me. I ticked the "break GitHub" box when I was submitting my comment, should I not have done that?

**Comment by earthlng** [comment]
so what about Mr. Fred's EDIT, Pantsky? Very eloquently written indeed, and I couldn't agree more :)

`[NOTE] OCSP fetching without hard-fail is completely fucking pointless` or something like that

**Comment by Thorin-Oakenpants** [comment]
^^ do an commit then

**Comment by smithfred** [comment]
I only license my characterisation colourfully verbatim 😁

**Comment by grauenwolfe** [comment]
> I only license my characterisation colourfully verbatim (last 3 words at least) 😁

LOL, this guy!

**Comment by earthlng** [comment]
> ^^ do an commit then

https://github.com/ghacksuserjs/ghacks-user.js/commit/8c35bf5d1116a5ae8b8dca3470e21d99c5baf856

**Comment by Thorin-Oakenpants** [comment]
Now that I see it, this seems a very pointless addition. It's already explained in the two lines above - verbal reasoning 101. If a cert cannot be validated, then you cannot tell if it is valid or not, so therefore a soft-fail puts you at risk

fetching, stapling ... 1211 controls when to fetch, 1212 controls how to handle fetch "failures to connect to a CA"

I also kind of disagree with the statement. Fetching on it's own has merit, right? - eg when a CA is reached and it revokes a cert? In other words, 1212 only handles FAILURES not successes

changes
```js
/* 1211: control OCSP fetching (to confirm current validity of certificates)
```
```js
/* 1212...
 * [NOTE] this pref is ignored if OCSP fetching (1211) is set to 0
```

PS: The seat belt bit needs to go - no humor allowed, remember - this is a professional document - yup, I remember all the bashing of my writing style.. I have an elephant's memory (somewhere out there is an elephant asking `who am i? how did i get here?`)

Class discuss!

**Comment by smithfred** [comment]
> If a cert cannot be validated, then you cannot tell if it is valid or not, so therefore a soft-fail puts you at risk

The user might think the "unable to validate" condition would only be coincidental (e.g. OCSP server down) rather than maliciously blocked, and consider it a reasonable trade-off on that basis.

> Fetching on it's own has merit, right? - eg when a CA is reached and it revokes a cert? In other words, 1212 only handles FAILURES not successes

And this kind of makes my point (i.e. believing it has any use against a competent attack). With a competent attacker, and given the likely prerequisites of a revoked cert attack, they will be a position to block, and will block, access to the OCSP server.

**Comment by Thorin-Oakenpants** [comment]
Not arguing that a failure should be hard-fail... not arguing that unable to connect might be an attack... I am stating that the statement `OCSP fetching without hard-fail is completely pointless` is clearly false, because it can successfully connect and receive a revocation

As long as the info is there (and it's already stated/implied without this line), and linked to, then this extra line is a waste of time

If we changed it (instead of removing it), then something like
 - OCSP fetching **FAILURES** without hard-fail is completely pointless (because you did not manage to check the validity so it could have been revoked, or indeed you could be under attack, eg the OCSP is maliciously blocked)
- ^^ except make it one line
- ^^ now it is a true statement

**Comment by Thorin-Oakenpants** [comment]
PS: @smithfred - I have invited you to be a collaborator - go here to accept if you want: https://github.com/ghacksuserjs/ghacks-user.js/invitations

We value people who know what they're talking about :) And you've brought valid points, additions and arguments to the table. It also means I can @ symbol to bring you up .. and you get to be one of the cool kids. I think it auto adds you to watch, but you can change that if all the notifications get on yur nerves :)

Personally .. its the cool kids part that sells this :)

**Comment by earthlng** [comment]
> The seat belt bit needs to go - no humor allowed

no humor - it's a quote from a google engineer hence the quotation marks ;)

You're right though, maybe we should change it to "OCSP fetching without hard-fail is almost completely pointless" or "OCSP fetching without hard-fail is mostly pointless" or something like.
But the point and the question is, have you ever encountered a site that failed to load due to the cert being revoked? I have not, at least not that I remember.
In most cases companies will probably issue a new cert before revoking the old one. The potential damage has already been done at that point anyway and it would just be more bad publicity to revoke the cert first.

**Comment by Thorin-Oakenpants** [comment]
> But the point and the question is, have you ever encountered a site that failed to load due to the cert being revoked? I have not, at least not that I remember.

Not really - not here to work out percentages or odds, just following the rules/logic. I'm not an expert on this stuff, but are companies the only ones who can revoke **their own** certs? I'm sure revocations must have happened

Anyway, some rewording is definitely required, and some consistency that across the two prefs - I'll post it shortly for a thumbs up

**Comment by Thorin-Oakenpants** [comment]
draft

```js
/* 1211: control when to use OCSP fetching (to confirm current validity of certificates)
 * 0=disabled, 1=enabled (default), 2=enabled for EV certificates only
 * OCSP (non-stapled) leaks information about the sites you visit to the CA (cert authority)
 * It's a trade-off between security (checking) and privacy (leaking info to the CA)
 * [NOTE] This pref only controls OCSP fetching and does not affect OCSP stapling
 * [1] https://en.wikipedia.org/wiki/Ocsp ***/
user_pref("security.OCSP.enabled", 1);
/* 1212: control how to handle OCSP fetching failures (non-stapled, see 1211)
 * When a CA cannot be reached to validate a cert, Firefox continues the connection (=soft-fail).
 * Setting this pref to true tells Firefox to instead terminate the connection (=hard-fail)
 * It is pointless to soft-fail when an OCSP fetch fails: you cannot confirm a cert is still valid (it could
 * have been revoked) and/or you could be under attack (e.g. malicious blocking of OCSP servers)
 * [1] https://blog.mozilla.org/security/2013/07/29/ocsp-stapling-in-firefox/
 * [2] https://www.imperialviolet.org/2014/04/19/revchecking.html ***/
user_pref("security.OCSP.require", true);
```

**Comment by earthlng** [comment]
:+1: to the 1211 title change. Big fat :-1: to the changes in 1212.
"pointless" vs. "completely pointless" is still an absolute statement.
Like dead vs completely dead - not much difference, is it?
If you don't like that 1 line I added in 1212, just remove it again. We now also have [2] which explains it much better than we ever could with a few short sentences, anyway.
And what you wrote is also wrong btw. If a cert has been revoked the fetch wouldn't fail and soft-fail would still block the connection.

**Comment by Thorin-Oakenpants** [comment]
Its not about the diff between `pointless` vs `completely pointless`: you're the one who used the tautology, not me. I was shortening it. The point is that I changed the subject to the FAILURE of the fetch, not the FETCH itself

1211 title change and 1212 title change so they compliment each other. I think 1212 should be reworded a little and actually describe the boolen value we used
-  `1212: set OCSP fetch failures (non-stapled, see 1211) to hard-fail`

> And what you wrote is also wrong btw. If a cert has been revoked the fetch wouldn't fail and soft-fail would still block the connection.

If a fetch comes back as invalid cert, then the site is blocked anyway, if it comes back as valid, then it continues, correct - these are not considered fails because the fetch worked, and 1212 **does not even apply**

A fail is when the server gives no reply/ is down/ is blocked etc which is exactly what I wrote ***"when an OCSP fetch fails"*** .. let me emphasize that again .. when an OCSP **FETCH** fails. What I wrote is 100% true

**Comment by earthlng** [comment]
> when an OCSP fetch **FAILS**. What I wrote is 100% true

you're right, I'm sorry mate.

> I'll butt out of this one and leave it up to @earthlng

why are you even in here + annoying me? ;)
I like 1212 the way I committed it. But if you hate it go ahead and change it to whatever you want.

**Comment by Thorin-Oakenpants** [comment]
I only disliked that one line, because it didn't make things clear IMO, and we already had the [2] link. The butting out was so you did the work checking @smithfred 's question! :)

I think my changes make it clearer (it gives cases), but of course I'm me. I like it to be as plain as possible for laymen (like me). You liked your version (and there was nothing incorrect about it), because you're you - go figure!

:kissy: :kissy: :make-up sex: xD

**Comment by smithfred** [comment]
My take is soft-fail is of theoretical value only. If the cert is revoked but OCSP fetch succeeds, it's either a shit attacker (can interfere with DNS/routing to MITM to another endpoint serving the stolen cert), but doesn't know they need to prevent OCSP fetch using the same mechanism) or a useless sysadmin (still "legitimately" serving a revoked cert). And on that basis soft-fail would only be of any *real-world* use if there were some sort of notification of the soft-fail. Which there ain't.
<br/><br/>
> "OCSP fetching without hard-fail is mostly pointless"

I like this one. Mostly because [Mostly Harmless](https://en.wikipedia.org/wiki/Mostly_harmless).
<br/><br/>
> PS: @smithfred - I have invited you to be a collaborator - go here to accept if you want: 

https://www.youtube.com/watch?v=t7Dc1ZD-hMQ

**Comment by Thorin-Oakenpants** [comment]
> `https://www.youtube.com/watch?v=t7Dc1ZD-hMQ`

I have no idea what that means? Are you declining the invite (which is perfectly fine, just asking)?

**Comment by smithfred** [comment]
It means you're inviting me to look after the news stand. I'll just nick it.

**Comment by Thorin-Oakenpants** [comment]
you can nick it mate .. its free and digital .. also, your access is "read only" (same as all the other collabs)... up to you.. if the invite is still there in a month, I'll just remove it, if I remember

**Comment by smithfred** [comment]
No no no, digital duplication is theft, please re-insert MPAA/RIAA consumer compliance needle into brain.

Also, where's the fun if I can't trash your whole repo? Boo.
