### ISSUE TITLE
Comment out ui.submenuDelay by default

### ISSUE THREAD

**Issue by smithfred** [ghacksuserjs/ghacks-user.js#337]
Since this is a custom value for a personal-taste hidden item that apparently by default uses the OS setting, it can't be "reset" easily in an override.js AFAICS.

Having it commented in user.js OTOH, and then added to overrides.js to taste, is trivial.

I don't think most users are going to want to slow down Firefox's submenus 2x (vs. 75? per https://github.com/ghacksuserjs/ghacks-user.js/issues/96) vs. the rest of the applications on their system. AFAICS it would make more sense to change the desktop-wide setting anyway (e.g. https://www.raymond.cc/blog/only-open-submenus-on-mouse-click-in-firefox-and-windows-7/ for Win)

**Comment by Thorin-Oakenpants** [comment]
75 is not the default value - its more like 500 or 1000. 75 was the old value. With Quantum etc (and fast 60fps animations) I think this is fine. DXR is unavailable right now, so I cannot look up the default value - will do later

**Comment by Thorin-Oakenpants** [comment]
on my Windows 7 the delay HKEY_CURRENT_USER\Control Panel\Desktop\MenuShowDelay is 200

**Comment by smithfred** [comment]
OK, but point is, it's better included commented out by default for the reasons mentioned ;)

**Comment by Thorin-Oakenpants** [comment]
and what about the other 13 hidden prefs we have active... I suppose for *that* reason we better also make them inactive (and no, not all of them are simple boolean values). It's impossible to "reset" ANY pref, so hidden or not is irrelevant - the caveats/pitfalls to a user-override.js list is outlined in the wiki

Long term I wish to remove all the personal stuff (section 5000)  - so until then, nah, sorry

**Comment by smithfred** [comment]
That one stands out as egregiously unnecessary. It doesn't give any security or privacy benefit to set it, and it's entirely a personal preference thing.

And yes, it's impossible to "reset" prefs, but most of them have a known, fixed, default value for a given version of Firefox.

This one's just the worst combination of unnecessary and a PITA to undo.

**Comment by smithfred** [comment]
BTW GTK's is 225 as of GTK 3.22:

```
>>> from gi.repository import Gtk
>>> Gtk.Settings.get_default().get_property("gtk-menu-popup-delay")
225
```

**Comment by Thorin-Oakenpants** [comment]
> That one stands out as egregiously unnecessary

The whole personal section is egregiously unnecessary - just deal with it until I one day get around to this section.

Whatever the default is 200, 225 .. its only a few ms. My original entry was 75 - it speeds things up. I hate delays. Almost a bit pointless changing it to 150, but I relented when others wanted it changed (it was mainly in order to fall in line with atomGit's 12bytes and provide one less change for him - 12bytes is a great article/resource and uses our user.js). Users who do not modify it would probably never even know/notice.

**Comment by smithfred** [comment]
> The whole personal section is egregiously unnecessary

You're ignoring that it's the *combination* of factors I mentioned about this specific pref.

> I hate delays.

Yes, but that kind of just supports my point that it's not a well-justified inclusion for the entire user base ;)

https://www.youtube.com/embed/PWmNi_VVVko?start=45&end=52 😁

**Comment by Thorin-Oakenpants** [comment]
I am not ignoring anything. I do not care about the combination of factors - there are other active hidden prefs with this exact same issue. If anything I should leave it in as an EXAMPLE

Yes, you keep repeating what I said re the personal section not belonging. Once again .. nah! I will address the whole personal section in due time

**Comment by smithfred** [comment]
Personal taste + no browser-level default + no security/privacy benefit? Which one(s)?

**Comment by Thorin-Oakenpants** [comment]
This is starting to get on my nerves dude - I already know all this. How many times do I have to tell you that the personal section (named the PERSONAL section with a header info that says *Users can put their own non-security/privacy/fingerprinting/tracking stuff here* ) will be dealt with in time. The section is a throwback from pre-github and stems from my own user.js way back and since been added to and built on - at some stage it will get removed (but I do not want to lose the info becuz quote: **Settings that are handy to migrate and/or are not in the Options interface** ). I will probably split it out to a `user-personal.js`

Until then I do not care. I do not care about the tiny diff in delay for users. I do not care about the hidden pref factor and the value not being a simple boolean - people have to learn how to deal with this pitfall, which ALREADY exists with other prefs in the user.js.

**Comment by smithfred** [comment]
A few more times, until you really hate me :)
