### ISSUE TITLE
mis_match

### ISSUE THREAD

**Issue by lumbdeal** [ghacksuserjs/ghacks-user.js#355]
firefox 52.6.0. x64_linux

1° user.js
	user_pref("browser.search.defaultenginename;data:text/plain,browser.search.defaultenginename", "DuckDuckGo");
(recommended duckduckgo)
	user_pref("browser.search.defaultenginename.US;data:text/plain,browser.search.defaultenginename.US", "DuckDuckGo");
(recommended yahoo)

3° about:config > google

* browser.search.defaultenginename;Google
* browser.search.defaultenginename.US;data:text/plain,browser.search.defaultenginename.US=Google
* browser.search.order.1;Google
* browser.search.order.US.1;data:text/plain,browser.search.order.US.1=Google
* gecko.handlerService.schemes.mailto.1.name;Googlemail
* gecko.handlerService.schemes.mailto.1.uriTemplate;https://mail.google.com/mail/?extsrc=mailto&url=%s

Q : what is the reason why the values in user.js are not the same than about:config (6 values about google are still here) ? 
Q : can i replace these 4 values with 'duckduckgo' (2 are about mail ... could i replace it with an empty field like this "" ? ) ?
Q : for a better anonymous research & protected privacy do you recommend startpage or duckduckgo ?
Q : what are the relevant/good values of the 2 user_pref above ?
Q : and why it is not https://encrypted.google.com/ ?

**Comment by Thorin-Oakenpants** [comment]
> what is the reason why the values in user.js are not the same

None of the 6 preferences listed are in the user.js

> can i replace

You can do whatever you like :)

>  for a better anonymous research & protected privacy do you recommend startpage or duckduckgo

I think @earthlng said Ixquick (he needs to finish our wiki page), but your choice it depends on your needs - the wiki page links to Atomgit's super-duper search engine comparisons list and in depth info - suggest you read it. (click the wiki link, click the search engines page which links to the article(s)

---
You can control all your search engines (and order, and default) via the UI. The *order may be used by FF internally for localized search engine deals - not 100% sure since I have never bothered to deal with it. Or it denotes the default engine (eg if you change it via the searchbar context menu or in options) and order1 = always the default.

Users can choose ANY search engine (quite a few choices), and we're not messing with their choices - also think of the localized versions (yeah, I get that google.* redirects to *yourIPcountry) but the world is bigger than my/our choice if we included it (so definitely not adding as active pref(s) for users to set their own). Also the search engine must be present in their profile - not everyone will have SuperSecureUberPrivateEngine for example. Everyone by now should be aware that google search is not "private" and make their own choices.

---
Handlers? dunno. Mine are at default (yahoo, gmail) but AFAIK don't do anything - for me an email link uses my portable thunderbird. Maybe they kick in if an external app hasn't been associated ( `Options>General>Applications>mailto` )

**Comment by lumbdeal** [comment]
ok : user.js change the value that i can find in about:config and only these ones but do not 'reformat automatically' the value of about:config in a coherent way ; google is still here in 6 lines and i did not choose it (2 = user_pref : duckduckgo and the order/UI does not include google) .
i mean that it does not respect my choice (hardening FF & keeping google : lol ).
FF read these 6 lines despite the fact i set 'without' so i must included/replaced these 6 lines in the user.js with my values : it is not normal.
It is bizarre that a tweaked user.js does not include the first 6 values "google" or at least explain what/how an user could do *deal with ... it is more complicated than i though.
>You can do whatever you like :)
yes, but i do not know if it should work ;)  ... so i asked here few explanations.
Another point is this obscure agreement with google/yahoo and others when you use a *private engine. 
Everyone knows since a long time that google search is not "private" (it should not be important if the elementary rights were stronger) but even yourself had not included in your user.js some examples, options, explanations, the right way to remove google : ). 
Should it not be the job of mozilla team/dev to propose an 'empty' field letting the user choose ANY search engine (and others options) ? it is a matter of corruption/incompetence , it sounds that FF & Tor look more like a marketing product than a tool designed security/privacy in mind (cypher).
The users deal with few choices not always the best not always that it suits the better.
thank you. 

 - gecko.handlerService.schemes.mailto.1.name;Googlemail
 - gecko.handlerService.schemes.mailto.1.uriTemplate;https://mail.google.com/mail/?extsrc=mailto&url=%s
should it work with an empty value ? (anyway , i should do it but i ask the question).

**Comment by Thorin-Oakenpants** [comment]
I cannot change the two `browser.search.defaultengine*` prefs because NOT every FF user will HAVE that search engine "name" in their profile

The six `browser.search.order*` prefs **LOOK** like they are only used for default resetting - that is when you go to Options>Search>Restore Default Search Engines. Mine are set as Google, Yahoo, Bing and I do not even have the last two in my search engines, and even the first one was removed and replaced by a sanitized one (but same name). These prefs are irrelevant (not that I have looked up exactly what they do). And, moot point, I cannot set these due to localized versions of FF - i.e the search engines names may not exist in their profile.

I also cannot deal with handlers and mailto for pretty much all the same reasons - except to block them, which is pretty extreme given users can change this themselves.

All these - search engines and file associations etc are easily (and best) done via the UI. I shouldn't have to spell out in the user.js that using google is not the most private-friendly search engine in the world
