### ISSUE TITLE
[FIXED] User agent ends up stuck on Windows 52. Is (disabled) section 4701 the reason?

### ISSUE THREAD

**Issue by older-pack** [ghacksuserjs/ghacks-user.js#357]
My default user agent is stuck on 
`Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0`
After a lot of checking and disabling of all extensions I think its due to section 4701 of ghacks user.js.

BUT the weird thing is section 4701 is disabled!

And this happend to me before around the update from FF56 to FF57.
So I did a clean re-install. But the issue is back.

Any ideas how the disabled section 4701 could be enabled behind the scenes?

FF 58.0.1 Ubuntu.
ghacks user.js ver 2017-11-30

**Comment by ArchangeGabriel** [comment]
No, this is privacy.resistFingerprinting https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js#L1580.

Your user-agent is spoofed to the closest ESR version with strictly inferior number (I’m running Firefox 60 and my UA is currently spoofed to 59, but this will change soon to 60 since the ESR has been shifted), and until Firefox 59 if I remember correctly is also spoofed to Windows whatever your OS is (but now it keeps the correct OS, since spoofing it is too hard for several reasons, some of them being browser independent).

**Comment by older-pack** [comment]
Great! That's it. I'd never have found that. That was really annoying me. I've wasted far too much time on it. Thank you very much :)
