### ISSUE TITLE
security.mixed_content.upgrade_display_content

### ISSUE THREAD

**Issue by ArchangeGabriel** [ghacksuserjs/ghacks-user.js#367]
(From https://www.ghacks.net/2018/02/24/firefox-60-https-upgrade-for-mixed-content/)

I think this is something we might want to set as on by default. This is better than purely blocking mixed-content, and I see no disadvantages over what we do currently.

**Comment by Thorin-Oakenpants** [comment]
I was just going to wait until the 59->60 diffs. I'd have to re-read it to refresh my mind, but...

mixed content prefs `1240` + `1241` only apply to HTTPS sites (i.e first party) and why would anyone want insecure content on those these days (see that Mozilla privacy study on what they could flip - I think breakage was 1 or 2%)

So I'm not entirely sure what this new pref offers - like I said, ***I would have to re-read it***. If it offers something for HTTP sites to upgrade some 3rd party content to secure, then sure, but wasn't that part of HSTS priming (the prefs are deprecated in 59 I think). Maybe this is the replacement

But sure, if we someone drafts up the item here ahead of time, I'll add it. One less thing to do in 59->60 diffs

**Comment by Thorin-Oakenpants** [comment]
@ArchangeGabriel  PS: I see you found [1433592](https://bugzilla.mozilla.org/show_bug.cgi?id=1433592) .. was that because I mentioned it @overdodactyl re [this](https://www.reddit.com/r/firefox/comments/80yqnx/google_apps_privacyresistfingerprinting_problems/) reddit post?

**Comment by ArchangeGabriel** [comment]
If I understand it well, it tries to load eventual http ressources of https website (i.e. mixed content) over https (i.e. does the job of the lazy web dev), meaning that it might reduces –already rare as you pointed– breakage.

P.S.: Re: 1433592; yes, that’s because you’ve mentioned it in https://github.com/ghacksuserjs/ghacks-user.js/issues/7#issuecomment-369475271

**Comment by Thorin-Oakenpants** [comment]
so do the two mixed content blocks (active and passive) override this new pref. eg it cannot fall back to requesting the insecure content. If so, then I see no harm. What's the pref name and default value (and ticket)?

**Comment by earthlng** [comment]
There's probably a reason why they don't enable it by default just yet. I would wait.

**Comment by ArchangeGabriel** [comment]
Pref name is this issue title (I don’t know if there is a ticket about it, would have to look more deeply at Martin’s post and follow links —don’t have time for that right now). The two mixed content blocks are made useless, because this new one can already not fallback to requesting insecure content on its own. I think it’s not enabled by default because it breaks sites the same way blocking passive mixed content does, and AFAIK this is not activated by default either (but we do).

**Comment by earthlng** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435733

**Comment by earthlng** [comment]
> The two mixed content blocks are made useless

it only upgrades passive display content, ie. [images + media](https://dxr.mozilla.org/mozilla-central/source/dom/base/nsContentUtils.cpp#8827).

**Comment by ArchangeGabriel** [comment]
OK, so it only makes blocking passive mixed content obsolete. Which make sense, since active mixed content has been blocked by default for a while.

**Comment by Thorin-Oakenpants** [comment]
1. Its an experiment, and they're grabbing telemetry, as earthlng says the default is false for a reason
2. we block all mixed content, and the reason we flipped mixed display was the telemetry showed it was down to around 1.4% <sup>1</sup>. This was two months ago (https://github.com/ghacksuserjs/ghacks-user.js/commit/d82791a93347799898487adcabe827807abda753 Jan 4th) and personally I haven't seen any issues. The adoption of HTTPS is escalating (from 33% a year ago to 66% to now some telemetry I think shows its over 80%)
3. I do not think this is worth it for a possible ~2% of the web that is affected, especially given some questions below
4. who needs pictures away!
5. we can always reassess with 59->60 diffs

So going to close this

<sup>1</sup> https://github.com/ghacksuserjs/ghacks-user.js/issues/326#issuecomment-355383575 - the telemetry link is fubared, but feel free to generate a new report. I came up with 1.4% of traffic = mixed passive

=========

Rambling thoughts follow: ignore or read on :)

- security.mixed_content.upgrade_display_content = let's call it `upgrade`
- the two existing mixed content prefs = let's call them `mixedDisplay` and `mixedActive` (which we have both set as true)

`Upgrade` only applies to `mixedDisplay` on secure pages. So what happens when both `upgrade` and `mixedDisplay` = true? See [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1435733#c35) which answers the question posed in the previous comment, and then go look at all the results in comment 10 :headspin:

> Upgrade take precedence over mixedDisplay

So what does that actually mean? If the upgrade fails, then what?

> For some reason when mixedDisplay=false and mixedActive=true it takes precedence over upgradeDisplay

I can't follow this case, it makes no sense to me. Why is mixedActive causing issues? So when you want to allow insecure images, for example, then the upgrade doesn't happen, which would be exactly WHEN you would want this the most, or get the most benefit out of it? This is whack!

Here's what should happen, IMO. On secure pages, if `upgrade=true` insecure display content is upgraded if possible, if it is not, then the `mixedDisplay` preference is followed.

But that doesn't seem to be what they're doing. I'm not even sure WTF they're even trying to achieve.

**Comment by Thorin-Oakenpants** [comment]
PS: also I have no idea what uMatrix's `https-strict: * true` would do in all of this

**Comment by Thorin-Oakenpants** [comment]
@ArchangeGabriel 

> This is better than purely blocking mixed-content

Agreed. If it worked.

**Comment by Thorin-Oakenpants** [comment]
ok, soz, i can to fiddle somewhat with uM & decentraleyez - [link[(https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2018-03-02&keys=__none__!__none__!__none__&max_channel_version=nightly%252F60&measure=MIXED_CONTENT_PAGE_LOAD&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2018-01-22&table=1&trim=1&use_submission_date=0)

![mixed](https://user-images.githubusercontent.com/16656956/36935008-a243a802-1ee9-11e8-9a56-5902c227d2a6.png)

On nightly, for the last 5 and 1/2 weeks, out of some 372 million samples (pages?), types `1` and `3` (which both have mixed passive content) totaled 1% (0.99% to be exact) of the sample size
