### ISSUE TITLE
discussion: revamp 2600 (misc)

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#368]
2600 became kind of a bloody mess over time with 42 numbered items atm.

* 10 are `network.*` prefs which we could re-order alphabetically and move to a new section 0700 because most of the prefs in 0600 are `network.*` prefs too.
* 7 `security.*` prefs that we could move to a new section 1300, next to 1200 where most prefs are `security.*`
* 2602: discourage downloading to desktop -> move to 5000?
* 2664: disable DeviceStorage API -> move somewhere storage-related?

that would bring it down to 23 prefs in 2600, all of which we could re-order alphabetically and renumber.

:+1: or :-1: ?

**Comment by Thorin-Oakenpants** [comment]
totally agree .. 2600 is a mess.. it's been on my mind for ages .. adding new ones, the gaps got too big and we're almost into the 80's - could totally do with a cleanup

- :white_check_mark:  `network` section :+1: - although 2608 is not about networks like the others, so exclude that one, so yeah .. move those 9 - do a patch
   * note: - 2625 dns + .onion -> into the network section?
- devicestorage API -> persistent storage 2700? i need to look at it more
- download to desktop is a privacy issue, so at first glance, no to 5000s
- security.* .. could be a go - there are other data uri prefs not in the js. I'm not convinced they could be a new section, because it's just such a diverse group. a mock re-order of the whole section might shed some insight on how/if we break off another section

other
- uitour -> keep FF quiet? does UI tour use any external sources?

**Comment by Atavic** [comment]
>For security reasons Mozilla.UITour will only work on white-listed domains and over a secure connection.

[Source](http://bedrock.readthedocs.io/en/latest/uitour.html)

**Comment by earthlng** [comment]
* `/*** 0700: MISC - NETWORK ***/` ?
* why not include 2608? IMO everything that starts with network. and doesn't fit better in another section should go in 0700.
* download to desktop is a privacy issue - how so? the important one IMO is 2603
* security.* - there are 7 MISC SECURITY items and already we have sections with less than that

**Comment by Thorin-Oakenpants** [comment]
download to desktop is a privacy issue because desktops are displayed on your screen and people can see all that shit - it's not like it's your special folder for llama porn u stashed away and labeled "Work Permits". The pref doesn't stop you using the desktop though. 2603 is a security measure, much less a privacy one, although yes, it would allow you to save the 1 in 10 downloads of llama porn to your actual llama porn folder.

7 misc security - lets look at it after the network stuff

network
- `/*** 0700: NETWORKING / DNS / PROXIES ***/`
   * I don't think we need a `MISC` in there, do we?
- `2608` has nothing to do with the section (unless I'm missing something). So what if Mozilla misnamed it, it wouldn't be the first time.
- This section could be beneficial for when [Fusion](https://wiki.mozilla.org/Security/Fusion) gets going

**Comment by earthlng** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/pull/369

**Comment by earthlng** [comment]
I like the MISC in there. Header description could be `basically everything that starts with 'network.' and doesn't fit better in another section`

**Comment by Thorin-Oakenpants** [comment]
`2607` (page thumbnails) could go in the cache section?

**Comment by Thorin-Oakenpants** [comment]
re #369 

We don't need a header description. A title such as `network / dns / proxy` covers it all and is self explanatory, and it can be built on as other networking protocols come into play.

the two jar prefs clearly belong with the other prefs about files & file blocking - look at the data uri blocks, svg block, mathml block, mime types bypassing stuff, opening files (`2662`), downloading files - they belong in 2600s (for now), not the new 700s. Since when have we organized prefs into groups based on names - never, the sections have always been about function, let's keep it that way

- disable JAR from ***opening*** Unsafe File Types
- disable remote JAR files being ***opened***, regardless of content type

I don't want to upset you, but after my explanation above, what do you say to me backing the the two jar prefs back to 2600 (for now) and naming the section as per what I said earlier?

**Comment by earthlng** [comment]
The idea was to make it easier for us by just lumping all the misc. network and security stuff together.
I mean, I'm sure the guys @ mozilla named them that way for a reason.
And it's not like the prefs were grouped together in any meaningful way in 2600 so far and I don't understand why you now all of a sudden see a connection between these randomly thrown-together prefs that didn't fit anywhere else.
Are those JAR prefs mis-named by mozilla? Maybe, IDK. Is that our problem? Nope.

Re: the title - not a fan. fe. there are 2 DNS prefs in 0600 - are we gonna move them to 0700, too?

**Comment by Thorin-Oakenpants** [comment]
I've wanted to clean up 2600 for ages. I LOVE your idea of the network prefs, and am discussing refining it. It still helps reduce 2600 (by a lot of lines too with that ipv6 stuff) and make the user.js better. I'm not rubbishing what you've done/suggested, I'm discussing it. I'm not sure if I get my points across sometimes, so sorry for that.

> And it's not like the prefs were grouped together in any meaningful way in 2600 so far

That doesn't preclude us from making it better, does it? Which is what the point of this was.

> Are those JAR prefs mis-named by mozilla? Maybe, IDK. Is that our problem? Nope

Exactly. Why should we fall into their problem. And no, they're probably not misnamed, or weren't when they created them. The key part of the pref names is the intended consequences of the pref, not the method/delivery. Its the JAR files that are important, not the network

>  I don't understand why you now all of a sudden see a connection between these randomly thrown-together prefs that didn't fit anywhere else

You grouped them together, and yes, I do see a connection (in which a couple do not fit). Like I said, I love the `idea`

these are ***directly*** related to NETWORKING protocols (DNS, HTTP, HTTP2, PROXY)
- network.dns.blockDotOnion
- network.dns.disableIPv6
- network.http.fast-fallback-to-IPv4
- network.http.altsvc.enabled
- network.http.altsvc.oe
- network.http.spdy.enabled
- network.http.spdy.enabled.deps
- network.http.spdy.enabled.http2
- network.proxy.socks_remote_dns
- network.proxy.autoconfig_url.include_path (kinda not uber directly related)

this one is NOT about networking, it is about legibility for western users
- network.IDN_show_punycode

this one is NOT about networking, url redirection is a WEB technology
- network.http.redirection-limit

But I can see the relationship with those two (but now I think I would remove them as well). Hell I can see "relationships" all over the place (as you said there are two `dns` prefs in 0600), and that is because this is not black and white. You know the answer to the two dns prefs. Sure, they're about DNS, but their **function*** is to prefetch the DNS which fits under "quiet fox". Do we stick all the headers/referers section under this network section as well - they all start with network - oh wait, one starts with privacy. 

Most prefs have overlap. We only have one way to "slice" this (and so do Mozilla with their pref naming convention), we can't cube it and "dice" from multiple angles. Its a txt based file. If we create sections, we make them meaningful. Everything else goes under MISC. There is only one MISC. We've never made sections before based on name (especially the first part), it's always been on function (usually the later parts describe this) sliced the way we think is best

examples
- app.update and extensions.update - why didn't Mozilla use update.app* and update.extensions*
- javascript.use_us_english_locale & intl.accept_languages - why didn't Mozilla use languages.* or locale.*

Did I get that across? The pref naming convention is nice at times, but means nothing when our sections are based on the consequences of the prefs. As for the section name, it would be what I said if we did what I said. If you're really unhappy, then provide credible arguments

:kiss: You know I love you, so don't get all stroppy

**Comment by Thorin-Oakenpants** [comment]
I've re-looked at your first post, because I'm guilty of not standing in the other person's shoes at times. <sup>1</sup>. I was guilty of my own narrower view/vision.

I see that you simply wanted to break away two new sections from MISC (and call them MISC as well) so that 2600 would not be so large. Whereas I always looked at it as why would we have extra misc sections, to me all sections have a purpose, and only one misc exists.

If the sections were called
- `0700: MISC network RELATED`
- `1300: MISC security RELATED`
- `2600: MISC ...` < and we remove the word security cuz that's in 1300

*then* it makes sense to me (sorry about that). Although I think we would be missing a chance with the network one (think of the tor and proxy and socks etc options coming up). Haven't looked at the security prefs yet. But I NOW get what you're saying, it just doesn't fit my model/view

---
<sup>1</sup> I was always told that if you're going to criticize someone, walk a mile in their shoes... ***then*** criticize them, because one, you'll be a mile away, and two, you'll have their shoes :grin:

**Comment by earthlng** [comment]
All the new Fusion stuff (thanks for the link btw, I hadn't seen that yet) is months if not years away.
In the meantime we have 2 new sections that make our decision making easier because we can just add new prefs that don't fit anywhere else in there. If they grow too much we can always create new sections or group some of them together in a better way.
As for the 2 JAR prefs, 1. they're already working on removing `block-remote-files` and 2. the default for `open-unsafe-types` is false in all current versions and OSes and we could just remove that one. It's certainly not worth arguing about them.

**Comment by Thorin-Oakenpants** [comment]
and as i type your post pops up - JAR we could merge, or as you say remove one of them. if you read below there are a LOT of other ways to reduce 2600

---
Right, so we're over that misunderstanding... so the question is do we want THREE misc sections, or ONE (assuming security.* gets a section)?

My personal answer to that is no. For the sake of 4 network.* prefs as it currently stands, we can have a dedicated `network` section - this reduces the section by 6 numbered items). Secondly, just breaking one MISC section into multiple sections and scattering them about has real purpose to it - its just scattering unrelated stuff into three piles. Why? So what if a section is long: we'd already be removing some, and re-ordering can make it easier to comprehend, as well as the renumbering to allow for growth, and there are others we can move (see thumbnail cache idea, storage api idea, security.* to look at). We could even merge some items.

So I propose that we do the network section the way we have always done a new section (i.e not as a misc), look at a few other prefs for moving/merging (edit: see your comment about the open-unsafe-types) and THEN take stock of the security.* ones and what's left

**Comment by Thorin-Oakenpants** [comment]
> All the new Fusion stuff (thanks for the link btw, I hadn't seen that yet) is months if not years away

I know. At the rate they're going with RFP, we'll be old wimmins ... although it gets me all excited. There's actually tickets already in for adding the tor protocol, I'll have to find them gain if I get time

**Comment by earthlng** [comment]
> you really need to work on your communications skillz bro

I know right?! I should have made it clear in my 1st post that I intended to name the 2 new sections MISC network + MISC security -> split off from MISC all-kinds-of-things.

> do we want THREE misc sections

YES :smile: ! You were in favor of naming the revamped 5000 "MISC", right?. 2? 3? 4? who cares.
It makes sense to have short sections instead of subgroups and the title is less important. Since you now walked a mile in my shoes (btw I want my shoes back!), walk a mile in other users shoes. The user.js is so massive that new users start adopting it section by section, maybe over several days. I've seen comments of people who said that and I myself did it that way as well when I first found your user.js on ghacks.

**Comment by Thorin-Oakenpants** [comment]
I said I liked it (at first glance, immediate response to the post), but hadn't made a decision (big difference). I actually have the whole thing almost ready to go

FYI
```js
/*** 5000: PERSONAL [SETUP]
     Non-project related but useful. If ANY of these interest you, add them to your overrides ***/
```

I take things very literally .. the suggestion of "MISC - network" is very different to "MISC - network **related**", but yeah, I failed to understand what you meant "exactly"

Totally on board with breaking up large sections if it warrants it. Never said I wasn't. I **NEVER** envisaged the new sections to also be misc bundled unrelated-by-function prefs.

I've read those comments as well, re how to apply it. It says it in our wiki as a means to start getting to use it. I mean, its logical, right.

Taking on board how big sections can be daunting, we should look at the number of `active` items users would need to look at. 2600 has 41 numbered items, total section is 186 lines - a whopper. Remove the 6 network ones - down to 148 lines, 38 lines moved, 20% reduction right there. And we haven't even gotten to some of the one offs we can move, shrink, merge, remove, or the security.* ones

Lets do the network section and clean up some other stuff first (haven't even looked at the security.* ones). At the end of the day, I would not be against a second MISC section, as long as it was consecutive - i.e simply broken by a line space, but I actually believe we can get this down without resorting to that

If it doesn't work, then it's trivial to do it the way you want

**Comment by Thorin-Oakenpants** [comment]
for consideration as the solution or as part of a solution

```js
/*** 2600: MISC - PART ONE: networking related ***/
user_pref("_user.js.parrot", "2600 part 1 syntax error: eek!");
/* 2601: blah blah ***/
user_pref("name", 1)

/*** 2600: MISC - PART TWO: security related ***/
user_pref("_user.js.parrot", "2600 part 2 syntax error: eek!");
/* 2610: blah blah ***/
user_pref("name", true)

/*** 2600: MISC - PART THREE: download & file related ***/
user_pref("_user.js.parrot", "2600 part 3 syntax error: eek!");
/* 2630: blah blah ***/
user_pref("name", 5)

/*** 2600: MISC - PART FOUR: everything else ***/
user_pref("_user.js.parrot", "2600 part 3 syntax error: eek!");
/* 2650: blah blah ***/
user_pref("name", "llama porn")

```

**Comment by earthlng** [comment]
6 network ones? I counted 10. whatever dude. do whatever the fuck you want

**Comment by Thorin-Oakenpants** [comment]
^^ 6 because 2 are the JAR ones and the other two I outlined already

> this one is NOT about networking, it is about legibility for western users
> -    network.IDN_show_punycode

> this one is NOT about networking, url redirection is a WEB technology
> -  network.http.redirection-limit

10 - 4 = 6

**Comment by Thorin-Oakenpants** [comment]
> do whatever the fuck you want

Now you're all pissed off. Whatever I do not everyone will be happy. The same goes with us. We don't always see eye to eye - and this is on a fucking **trivial** matter about formatting and layout.

Do I not listen to you, do I not take time to discuss options, do I not accept a lot of your suggestions? You know I value your input. Am I always wrong when we don't agree on something?

As I said, "If it doesn't work, then it's trivial to do it the way you want" - sheesh, it's one commit - so how about just letting the owner of this repo do it the way she wants and **then** point out how stupid it was

Or would you rather we put it to a useless vote or something? Speak up. Cuz I'm kinda tired of all this now, and I might do nothing instead

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/issues/360#issuecomment-365836755

Actually, I didn't say I liked misc, I said I liked optional

**Comment by earthlng** [comment]
^^ my bad.

> 10 - 4 = 6

let's turn the tables for once and let me make a claim and you try to proof me wrong: network.http.redirection-limit and the 2 JAR prefs **are** network related

**Comment by Thorin-Oakenpants** [comment]
But I am advocating that the new section be "network" and NOT "network *related*"

**Comment by earthlng** [comment]
Even the dumbest fucking people will recognize that **MISC** + **NETWORK** + **a bunch of prefs starting with `network.*`** *proooobably* means something like 
> miscellaneous network-related prefs that *for some reason* are not in any of the other sections, so ... um... I guess they are ... um.... miscellaneous and .. um .. don't fit anywhere else, duh!

We can spell it out in the header for all The Donalds out there if you think that's necessary, though.

**Comment by Thorin-Oakenpants** [comment]
Idea no.1:
- move `2672` (re punycode) to `0811` with all the other locationbar items - that's 11 lines, maybe we can shrink that a little, remove a couple of references (note: it does blow 0800s out into a 100+line section but it does fit being in that section)

**Comment by earthlng** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/pull/416/files

**Comment by Thorin-Oakenpants** [comment]
why now? we've had this discussion before - just because the first word in the pref is the same does not mean we *have to* group it hat way (see numerous examples throughout the current js) - although I am not saying that this lot shouldn't be lumped together - but I'm just going to re-organize it all again later anyway (not 100% sure how, but I've had three or four goes at it in the last 3 weeks)

I can commit this, but it's going to change again. Also, why the line spaces and a sub heading?

**Comment by Thorin-Oakenpants** [comment]
/* 2622: enforce a security delay when installing extensions (milliseconds)
 * default=1000, This also covers the delay in "Save" on downloading files.

changed in that commit to

/* 2685: enforce a delay for security dialogs
 * fe. when installing extensions or downloading files.

Couple of nits:
There is no such thing as a "security dialog" here. It's a delay in the dialog for *security reasons*, not a dialog *about security*. Also its the save dialog, not "downloading" which can be configured to happen automagically without asking, so I'd rather be more precise.

There was nothing wrong with the old description, but I think we can improve it to a single line (and keep the default info on the pref line as per your changes)
/* 2685: enforce a security delay on install and save dialogs

**Comment by earthlng** [comment]
> why now?

it's been 2 months

> why the line spaces and a sub heading?

because I was also gonna add `// downloads` and `// extensions` and perhaps `// network`

> There is no such thing as a "security dialog"

link [2] is literally titled "Race conditions in **security dialogs**"

**Comment by Thorin-Oakenpants** [comment]
I meant why now when we have a few days left and are busy finishing off diffs (and I have to redo all the scratchpads). Just a timing question. Hadn't forgotten about this at all. I've actually been drafting lots to see what I can reduce and move and split off. It's so messy I keep getting stuck, and I'm afraid to suggest anything because of the last time we had a discussion about it in here

I want the info to be understandable to the layman "security dialog" is not meaningful IMO (Jesse Ruderman has used that term, but google it - in fact google "security dialog" images and all you see are security related dialogs) - its an "installation prompt" and a "save dialog". I understand there may be other instances (e.g. you mentioned  a network related prompt?), we can add that if you provide more info

**Comment by earthlng** [comment]
> you mentioned a network related prompt?

no, I answered your question about the line spaces and sub heading:

https://github.com/ghacksuserjs/ghacks-user.js/pull/417/files

**Comment by Thorin-Oakenpants** [comment]
I suggested two ways to break up the 2600s 2 months ago and one of them was with subheaders and I got downvoted

I appreciate the flood of rearranging everything (although the timing sucks - I planned to do it after 60 release). You're "duplicating" a lot of what I already have in my draft(s) and I might as well commit it (it will make it easier later on).

Back to these subheaders : then they should match how we do it elsewhere (no line spaces), which means we probably want those not grouped at the end under `// other` or something (debatable?). 

Lets just leave the subheaders OUT for now

**Comment by Thorin-Oakenpants** [comment]
Well, lets finish it then, the numbers are out of sequence .. wot's next?

**Comment by earthlng** [comment]
you got downvoted because the main idea was to reduce the # of items in 2600.

> I'll stick them in in caps with no line spaces same as 1200's for now

can we use double empty lines between sections and single empty line for subheaders?

> Well, lets finish it then, the numbers are out of sequence .. wot's next?

re-order alphabetically and renumber

**Comment by Thorin-Oakenpants** [comment]
And we did reduce the number of items, and we hadn't made a decision or worked out 100% that no other sections would be split off. And we hadn't worked out one offs we could move to other sections. So more reduction in numbers of items was STILL on the cards. AND it was to also reduce the length, which we could still do by trimming descriptions/refs etc.

So much bitching over trivial shit. Leave the subheaders the same as they are now, the same as they are in other sections (call me pedantic or OCD or "special", but I like things symmetrical, the same, uniform) - we can address it at the end, because: yes, its needs some visual breakage because it is so long

> re-order alphabetically

You always seems to want to do this. I'd rather re-order it using some logic (eg mathml, svg, etc next to each other)

**Comment by Atavic** [comment]
I always end up looking for entries in an alphabetical order, despite starting from logically ordered lists.

**Comment by Thorin-Oakenpants** [comment]
yes or no (I'm 50/50 on it)

Move 2762 punycode (11 lines) to 0811 (and shrink it, we do not need 11 lines to explain punycode). It fits with the location bar items, such as showing the full url (0803), but then other "security" items (eg 1273) aren't there. 0800 is more about FF internals.

Otherwise lets just clean it up and shrink it

```js
/* 2672: enforce Punycode for Internationalized Domain Names to eliminate possible spoofing security risk
 * Firefox has *some* protections to mitigate the risk, but it is better to be safe
 * than sorry. The downside: it will also display legitimate IDN's punycoded, which
 * might be undesirable for users from countries with non-latin alphabets
 * [TEST] https://www.xn--80ak6aa92e.com/ (www.apple.com)
 * [1] http://kb.mozillazine.org/Network.IDN_show_punycode
 * [2] https://wiki.mozilla.org/IDN_Display_Algorithm
 * [3] https://en.wikipedia.org/wiki/IDN_homograph_attack
 * [4] CVE-2017-5383: https://www.mozilla.org/security/advisories/mfsa2017-02/
 * [5] https://www.xudongz.com/blog/2017/idn-phishing/ ***/
user_pref("network.IDN_show_punycode", true);
```

to 

```js
/* 2672: enforce Punycode for Internationalized Domain Names to eliminate possible spoofing
 * Firefox has *some* protections, but it is better to be safe than sorry. The downside: it will also
 * display legitimate IDN's punycoded, which might be undesirable for users of non-latin alphabets
 * [TEST] https://www.xn--80ak6aa92e.com/ (www.apple.com)
 * [1] https://en.wikipedia.org/wiki/IDN_homograph_attack
 * [2] https://www.xudongz.com/blog/2017/idn-phishing/ ***/
user_pref("network.IDN_show_punycode", true);
```

The mozillazine and mozwiki pages are old as F, and the CVE is not needed IMO. The rest of the words removed are implied or redundant, and countries -> users of the actual language (I could be a russian living in new york and I could use english or cryllic - its the language we care about, not the country they're from) which helps reduce that by a line

:question: We could also take the test out - it is linked in our wiki, and is totally mentioned and highlighted in the first sentence of [2]

**Comment by Thorin-Oakenpants** [comment]
yes or no?

remove 2664 DeviceStorageAPI - this looks pretty much obsolete to me. What is the default value in 52? in 60 branch it is false

**Comment by earthlng** [comment]
IMO no to the move, the text changes are fine but I would keep all the links. The length of item descriptions isn't much of an issue IMO because people can view the user.js in collapsed form and only open the ones they want to read. What is a slight issue though is too many items in a section, IMO.

**Comment by Thorin-Oakenpants** [comment]
yes or no?

2617 pdfjs - stick that description into a wiki page or issue (locked, I do not want hundreds of people telling me what pdf reader they use) and link that - its eating 15 lines. I'm kind of against this. I personally do not care that 2600 is so long - it is what it is, and I don't really want to remove information, maybe we could trim it. It also is only removing number of lines, not number of items

ahh you posted as I was writing this - yes number of lines reduced is good, its more about the number of items - but I have no issue with that myself, so struggling here

**Comment by earthlng** [comment]
DeviceStorageAPI default is false everywhere except in Android. see my comment here: https://github.com/ghacksuserjs/ghacks-user.js/commit/459396ed5b23889fe4053d2f7dca0a10b4cde291

**Comment by Thorin-Oakenpants** [comment]
^^ I'll stick that in a new topic so we can process it :+1:

**Comment by Thorin-Oakenpants** [comment]
FYI: numbered items in each section, as of right now
```
0100:  3
0200:  9
0300: 21
0400: 17
0500: 12
0600:  8
0700:  6
0800: 19
0900: 11
1000: 14
1200: 22
1400:  9
1600:  8
1700:  4
1800:  8
2000: 11
2200:  7
2300:  4
2400: 10
2500:  5
2600: 34 <= yup its big
2700: 15
2800:  5
```

**Comment by Thorin-Oakenpants** [comment]
the twenty items to renumber / reorder : only 2612 is already taken in deprecated, everything else is available up to the 2630s

Of the twenty items, I will put pdfjs and punycode at the end. I'll keep as many of the others at their original numbers if I can. I'll do a PR tomorrow - so any ideas, spit them out now :)

**Comment by Thorin-Oakenpants** [comment]
or we could take the one-off items (beacon, mathml, svg, accessibility, ui-colors, etc) and stuff em all consequently in the first 10 or 11 numbers and then group the rest a bit with some spaces

we can also nudge downloads etc out by 10

**Comment by earthlng** [comment]
IDK if it matters for your decision making but the 2 jar prefs will be removed in FF61

**Comment by Thorin-Oakenpants** [comment]
Maybe we can remove them? What is default for ESR52.latest for these
- network.jar.block-remote-files (in 59 = true = same as user.js)
- network.jar.open-unsafe-types (in 59 = false = same as user.js)

side note: we could even move `browser.helperApps.deleteTempFileOnExit` to downloads because "open with" = the same mechanism per se - its just viewed in a diff app (i.e there is still a local copy). Maybe rename to /** DOWNLOADS / OPEN WITH ***/

^^ clean that up if required after your thoughts, and then I'll do it

---

Any attempt to install some sense of order is superficial anyway - that's what MISC means. Haphazard is kinda good in a way

Good points on jar, also those pagethumbs and UI tour are likely to get removed, maybe I'll stick em at the end high numbers, although it doesn't really matter. If I nudge like below we have 50 numbers to play with.

downloads = 2450s
extensions = 2460s
security - stay at 2480s

**Comment by earthlng** [comment]
- jar: let's wait for 61 and move them to 9999
- no to the side note
- I would go fully alphabetical with consecutive numbering for everything that's not in already in the subgroups. You tried to keep the original numbers as much as possible but only 3 still have it, so why bother if everything around them is renumbered too. Add some gaps if you like but it's unnecessary IMO. We're revamping 2600 based on what we currently have and everything new will go at the end again.
That is, until we have enough similar prefs to form a new subgroup or split them out into a new section.
- renumber 268x+ to start at 2680

**Comment by Thorin-Oakenpants** [comment]
- jar: no worries, they can move to deprecated in next diffs
- sidenote: no worries, was just a thought
- renumber 268x etc- okay, will do

- wasn't really trying to keep original numbers (although it helps with looking for references to them in the js), I was just trying to appease this "alphabetical" order some people are keen on - it means nothing really. As well as my own sense of trying to group things. And I left in some gaps to maybe facilitate that in the future (both mine and yours). At the end of the day, its all MISC and its all meant to be random.

I'll just leave the order as is (in above draft), and squash it up, no gaps (we can always do more commits later if someone really throws their toys out of the cot over something)

**Comment by Thorin-Oakenpants** [comment]
^^ double check I didn't screw anything up. I think I've covered all the numbers referenced elsewhere and made the numbers unique or linked with deprecated section
