### ISSUE TITLE
network.http.referer.XOriginPolicy = 1 breaks embedded Vimeo videos

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#373]
... might want to mention that as a comment in user.js or somewhere?

i set it back to 0 and started using [Smart Referer](https://addons.mozilla.org/en-US/firefox/addon/smart-referer/) with an exception rule for Vimeo (source: *, dest: player.vimeo.com)

**Comment by atomGit** [comment]
oops - forgot to mention - the videos don't appear to be broken - what happens is that the video frame loads, but with the "error" msg: "sorry, this video can't be played here because of privacy settings"

example page:
`http://www.ancreport.com/podcast/ian-williams-israel-lobby-u-n/`

**Comment by mazesy** [comment]
Indeed. I wouldn't use any Referer manager until now, discovered the one mentioned by @atomGit , _Smart Referer_ and adopted it.

Be mentioned that [Referer Control](https://addons.mozilla.org/firefox/addon/referercontrol/ at ), stated here at #294 would suffer (haven't tested the extension myself) of what is described by a reviewer on [AMO](https://addons.mozilla.org/en-US/firefox/addon/referercontrol/reviews/) as

> Settings by are lost by clear 'offline website data'. localStorage API use in extension is not advised

Because I do clear offline website data on Firefox exit, _Referer Control_ wouldn't be of any use for me (if indeed it is confirmed that its settings are stored in localStorage).

_Smart Referer_ does the job, clearly.

**Comment by Thorin-Oakenpants** [comment]
I don't want to start adding information on breakage thru-out the js, or we'll end up with TMI. The real answer is down the track to have a sticky/relaxed branch of breakage items

That said, according to Alexa, Vimeo is pretty popular - 133rd globally, 94th in the USA. We already have `To fix broken sites, temporarily set XOriginPolicy=0` in the js - but the problem is people don't **know** its referers that are breaking the site
