### ISSUE TITLE
Does ghacks-user.js certifiably not compromise any built in TBB security?

### ISSUE THREAD

**Issue by monerodude111** [ghacksuserjs/ghacks-user.js#392]
Just curious. I'd be surprised if Tor did not implement much of the security features offered by ghacks. I'd love to test this with tor but would hate to break any of its inbuilt security measures.  Do you believe this would positively complement the Tor browser?

**Comment by Thorin-Oakenpants** [comment]
I will just treat "security" to mean privacy / anti-fingerprinting / security / leaks etc because they're generally all intertwined

A lot of these changes came from looking at TBB - I started doing that 3 years ago, and have kept up with every release's changelogs and numerous tor trac tickets ever since. And I based the model the same - that is state separation of data, lowering entropy (not making random noise), etc as per the TBB design notes. So we're very similar. Ignoring extensions and what TBB has hard-coded that we can't do via prefs - it's almost the same (depending on the slider). Earthlng did a diff a while ago, there was almost nothing from memory.

We'd have to wait until TBB based on ESR60 comes out to do a decent comparison - because there are way too many changes, not just with Quantum/ XUL deprecation, etc but also the large number of different Tor Uplift approaches (eg spoofing / rounding instead of blocking). They're too divergent at the moment. But I do not think there are many active prefs that lower TBB's security model (one would be we don't clear everything on close, eg cookies, but then again, we block all cookies - some combinations are just a little more end-user friendly). On the flip side, there are also some settings we have that would that tighten TBB.

Side note: If you wanted to take advantage of TBB's hard-coded patches, I believe you could take TBB, uninstall the tor button and change the network settings, and you'd have a TBB that works like a hardened FF. I haven't tried it. You could then flip the startup mode to normal windows, add uMatrix, uBO, etc, dump NoScript, slap on the user.js (but do some diff analysis first) ...

**Comment by Thorin-Oakenpants** [comment]
Fixed the title for you. spelling of `certifiably` and also it is not `Tor` (that's `the onion ring` or network/protocols if you like), but TBB (tor browser bundle).

Short answer: No, there is no `certificate` because no one has really looked at it at that depth, and ~~we~~ I do not recommend fiddling with TBB's settings.

That said, can't wait for ESR60 now

**Comment by earthlng** [comment]
> Earthlng did a diff a while ago, there was almost nothing from memory.

that was only for the security slider prefs. Outside of that there are quite a lot of differences

**Comment by Thorin-Oakenpants** [comment]
Oh, that's right. I thought we did one before that as well? Anyway, a TBB based on ESR60 vs ghacks user.js 60 would be good. We can leave this open to remind us

**Comment by monerodude111** [comment]
Awesome Pantsdidz I appreciate that so much thank you so much.   I dug into tors browsers config settings and I noticed everything I looked up from your user.js was already implemented in Tor.  So I thought you may have used that as a model or visa-versa.  I'lll stick to using vanilla Firefox with your amazing addition. I've only been testing it lately. The only issue I've been having was finding the toggles to allow full screen playback on flash videos; am able to see RT, Youtube videos etc by enabling plugins & SVG, and full screen to the window dimensions, but not able to find the keys to allow legacy fullscreen. Do you know how to accomplish this? Once this is implemented I'm pretty sure I'll be able to use your mods for daily surfing without losing very much usibility; and next to Tor browser,  this this is the best FF mod in the world I'd feel should be mandatory for security oriented features.

**Comment by Thorin-Oakenpants** [comment]
> The only issue I've been having was finding the toggles to allow full screen playback on flash videos

```js
/* 2204: disable Fullscreen API to prevent screen-resolution leaks [SETUP]
 * [NOTE] You can still manually toggle the browser's fullscreen state (F11),
 * but this pref will disable embedded video/game fullscreen controls, e.g. youtube
 * [TEST] https://developer.mozilla.org/samples/domref/fullscreen.html ***/
user_pref("full-screen-api.enabled", false);
```

Is this what you were after? So you can hit the full screen button in the flash nav bar?

**Comment by monerodude111** [comment]
Could very well be however I do not see this listed in the : ghacks user.js * date: 16 March 2018, I am using. How can fullscreen be disabled then?

**Comment by monerodude111** [comment]
Oh I see it now, n/m!

**Comment by Thorin-Oakenpants** [comment]
Yeah, we did some changes very recently with the whole window sizing stuff

**Comment by Atavic** [comment]
Related to https://github.com/ghacksuserjs/ghacks-user.js/issues/336

**Comment by Thorin-Oakenpants** [comment]
Closing this. When TBB based on ESR60 comes out, we will do a diff as a long overdue exercise. What we are doing here, is seeing what TBB does that we can use in FF that fits our purpose.

To be clear, we do not recommend mucking around with TBB settings/prefs. And we don't recommend accessing hidden services via FF. If you **need** anonymity (whistleblowing, fear of reprisal from govt, etc), then a hardened FF is not the answer.
