### ISSUE TITLE
Preventing activity-stream.topstories.json from getting downloaded

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#396]
Even with:

user_pref("browser.newtabpage.activity-stream.enabled", false);
user_pref("browser.library.activity-stream.enabled", false); // (FF57+)

Firefox 60.0b8 is downloading data to create ***activity-stream.topstories.json*** within the current profile.

UPDATE: Also ***activity-stream.tippytop.json***

How do we make it stop?

**Comment by Atavic** [comment]
The "refreshed new tab page" has a [repo](https://github.com/mozilla/activity-stream)

>https://github.com/mozilla/activity-stream/commit/c260e0a
>https://github.com/mozilla/activity-stream/commit/0376728

Maybe blocking `getpocket.com` and `getpocket.cdn.mozilla.net` may help.

https://bugzilla.mozilla.org/show_bug.cgi?id=1410075 *RESOLVED WONTFIX*

**Comment by grauenwolfe** [comment]
From DXR, "testing" setup: ["Use an empty list of sites to avoid fetching"](https://dxr.mozilla.org/mozilla-central/source/testing/profiles/prefs_general.js#290-295)

    // Use an empty list of sites to avoid fetching
    user_pref("browser.newtabpage.activity-stream.default.sites", "");
    user_pref("browser.newtabpage.activity-stream.telemetry", false);
    user_pref("browser.newtabpage.activity-stream.tippyTop.service.endpoint", "");
    user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
    user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);

**Comment by Thorin-Oakenpants** [comment]
In 59->60 diffs, there are 4 `browser.newtabpage`* prefs in the user.js that are being deprecated/removed. The bugzillas are listed next to them thanks to earthlng, there are three of them. I haven't looked at this yet.

As for the activity stream page, the cog in the top right has options under it to control snippets, top stories, search element, etc. I disabled all that in my 60beta. I will check what prefs they map to in 60. And I'll check if any connection are made when disabled

**Comment by Gitoffthelawn** [comment]
@Thorin-Oakenpants You got me thinking... I never even see FF's newpage tab.  So I forced FF to use it, and then clicked on the cog, and turned everything off.  So far, no spurious files being added to the profile.

I had done that in the past, but FF must have turned everything back on when they came out with a new version of newtab.

**Comment by Thorin-Oakenpants** [comment]
[Ch-ch-ch-ch-changes](https://en.wikipedia.org/wiki/Changes_(David_Bowie_song)) ... can't open 60 right now, and I think this new UI is 61 (https://pbs.twimg.com/media/DYzdC_XW4AAMzxV.png)

See the `Homepage & New Windows` > `dropdown` - `Firefox Home (default)`=activity stream. They've just simplified things with AS & homepage & new windows etc, hence why the `master switch` of `browser.newtabpage.activity-stream.enabled` is gone, as it probably now maps to `0103` (set home page) or something like that. Also, never understood why they had a separate `new tab` and `home page` setting - seems like its combined now

I would expect the right setting will stop background grabbing stuff, but it wouldn't surprise me if its happening (regression or by design) and it may be we have to add the snippets, top sites, highlights prefs to the user.js

**Comment by Thorin-Oakenpants** [comment]
In FF60.08b, there is no new preferences `Home` tab, that must be in coming in 61. Anyway, the cog wheel items in 60 are respective prefs are

Activity Stream cog wheel: New Tab Preferences
- Search = browser.newtabpage.activity-stream.showSearch
- Top Sites = browser.newtabpage.activity-stream.showTopSites
- Highlights = browser.newtabpage.activity-stream.feeds.section.highlights
- Snippets = browser.newtabpage.activity-stream.feeds.snippets

Now I was in a new profile with a couple of preset changes (I keep a copy for starting new types of tests), so all these were already disabled, and my start page etc was the activity page with nothing on it. I must have had some local data already present, because as soon as I toggled Top Sites on, I instantly had tiles. This may just be the Alexa top100 or so sites pre-listed with FF, I'm not sure. I think all these prefs do is to hide the relevant sections

**Comment by Thorin-Oakenpants** [comment]
[1433133](https://bugzilla.mozilla.org/show_bug.cgi?id=1433133) FF60
- comment 0 has some info
- > about:home can revert to the classic version by turning off `browser.newtabpage.activity-stream.aboutHome.enabled` and about:newtab can revert to Tiles by turning off `browser.newtabpage.activity-stream.enabled`.

So they want to remove the `classic` about:home and I guess about:newtab as well (I'll have to set up a 61Nightly and see what that new Home options tab offers). This kinda leaves 60 in the middle of changes.

Note: both these prefs were removed (in 1433324 below), but we never had `browser.newtabpage.activity-stream.aboutHome.enabled` in the user.js.

------
[1433324](https://bugzilla.mozilla.org/show_bug.cgi?id=1433324) - removes the two prefs and assumes everyone wants AS

.. man, I've just about had it with all this crap, reading thru all this rubbish trying to keep up. NO means no. FFS :grumpyface:  How TF am I am suppose to work out how to make sure AS never loads and no external connections are ever made. FFFFFFFFFFk

How about we just edit the user.js to say, DELETE the AS xpi, and set your home page to about:blank (unless they set about:blank to use activity stream as well)

**Comment by Thorin-Oakenpants** [comment]
deprecated/removed in 60

pref("browser.newtabpage.activity-stream.enabled", true);
- https://bugzilla.mozilla.org/show_bug.cgi?id=1433324

pref("browser.newtabpage.directory.source", "https://tiles.services.mozilla.com/...");
- https://bugzilla.mozilla.org/show_bug.cgi?id=1370930

pref("browser.newtabpage.enhanced", true);
pref("browser.newtabpage.introShown", false);
- https://bugzilla.mozilla.org/show_bug.cgi?id=1433133

All these tickets and others I dig into linked in the comments etc, reviewing them, all I see is removal of code, and I cannot work out what replaces them. Nothing I guess since they want to force AS on everyone. Other changes don't land until 61. Wot a mess.

**Comment by 2glops** [comment]
Nightly 61.0a1
about:preferences#home UI shows :

Homepage and new windows : blank page, Firefox Home (default), custom URLs
New tabs : blank page, Firefox Home (default)

I set blank page for both.

Firefox Home Content : Choose what content you want on your Firefox Home screen (web search, top sites, recommended by Pocket, highlights, snippets could be un-ticked)

**Comment by Thorin-Oakenpants** [comment]
Nah, its deeper than that. Not looked at 61 like you have, but I need to deal with 60. Some of the AS page cog icon options are misleading - they only *hide* the section, not disable it. Also, I can't seem to trigger getting any highlights or topstories or snippets in my nilla 60 - I guess it's on a timer or triggered by x views and loads of traffic. I ain't got time for that

In FF60:
- `browser.newtabpage.activity-stream.default.sites` is why I had some instant top sites = harmless
- `browser.newtabpage.activity-stream.feeds.section.topstories.options`
  - set to blank, maybe this stops pocket (it should, the whole thing is pocket)
- `browser.newtabpage.activity-stream.telemetry.ping.endpoint` -> points to "https://tiles.services.mozilla.com/v4/links/activity-stream"
  - blank it to stop ??
- `browser.newtabpage.activity-stream.feeds.topsites`
  - note cog wheel option prefs is `*showTopSites` .. SHOW, not enable
  - set to false, maybe this stop outgoing traffic to get top sites
- `browser.newtabpage.activity-stream.feeds.telemetry` + `browser.newtabpage.activity-stream.telemetry`
  - set to false

so IDK if this covers it
```js
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.options", "") // blocks pocket
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false); // hide?block? highlights
user_pref("browser.newtabpage.activity-stream.telemetry.ping.endpoint", ""); // blocks tiles service
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false); // blocks topsites
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false); // hide?block? snippets
user_pref("browser.newtabpage.activity-stream.feeds.telemetry", false); // fuck telemetry
user_pref("browser.newtabpage.activity-stream.telemetry", false); // fuck it again
```

I'm in my main pimped FF60 and these do not exist, probably because I don't AS xpi and never used it. They not listed as new in 59->60 diffs. I think the above should kill it all, probably one or two are redundant, but f**d if I know because its a labyrinth. I feel like Andy in The Shawshank Redemption crawling thru 500 yard of sewer pipe (in reality, anyone doing that would die from the fumes).

**Comment by Thorin-Oakenpants** [comment]
> Homepage and new windows : blank page, Firefox Home (default), custom URLs
> New tabs : blank page, Firefox Home (default)

Wait a second... are you telling me that a new tab can't use a custom URL (you know, like a speed dial extension) .. I F hope not - surely an extension can still hook in (you know, "an Extension has set your homepage" bit).

**Comment by 2glops** [comment]
> are you telling me that a new tab can't use a custom URL

Yes.
At least on the UI, I don't search about:config to find an option to do that.

**Comment by Thorin-Oakenpants** [comment]
If I get time I'll grab a nightly portable and install Group Speed Dial. I'm betting extensions can still hook into new tab

**Comment by Thorin-Oakenpants** [comment]
^^ when you set a custom url (in my case I pasted in the `moz-extension...` address, then the New Tab section changes - see pic

![homepage](https://user-images.githubusercontent.com/16656956/38206701-eb6213d4-369a-11e8-9dd5-2ba22c58052e.png)

**Comment by Gitoffthelawn** [comment]
I'm now getting ***activity-stream.tippytop.json*** in the profile on 60.0b8.  WTF.

**Comment by Thorin-Oakenpants** [comment]
```js
user_pref("browser.newtabpage.activity-stream.tippyTop.service.endpoint", ""); // favicons in AS
```

**Comment by Atavic** [comment]
@Thorin-Oakenpants asks... `browser.newtabpage.activity-stream.telemetry.ping.endpoint` points to "https://tiles.services.mozilla.com/v4/links/activity-stream"

>blank it to stop?

Not enough, according to: https://github.com/mozilla/onyx/blob/master/onyx/default_settings.py#L18

Look, there are 4 **CDN** links -> https://tiles.cdn.mozilla.net/

---

>// These fields are sent from the client
>"client_id": "374dc4d8-0cb2-4ac5-a3cf-c5a9bc3c602e",
>"session_id": "{12dasd-213asda-213dkakj}",
>"profile_creation_date": 14786,

>// These fields are generated on the server
>"ip": "10.192.171.13",
>"receive_at": 1457396660000

Source: https://github.com/mozilla/activity-stream/blob/b69291f6f37d1625134247c537d8796aae2c0695/docs/v2-system-addon/data_dictionary.md

The server is [onyx](https://github.com/mozilla/onyx#v4linksactivity-stream)

**Comment by Atavic** [comment]
@Thorin-Oakenpants asks: `browser.newtabpage.activity-stream.telemetry.ping.endpoint` points to "https://tiles.services.mozilla.com/v4/links/activity-stream"

>blank it to stop?

Not enough, according to: https://github.com/mozilla/onyx/blob/master/onyx/default_settings.py#L18

Look, there are 4 **CDN** links -> https://tiles.cdn.mozilla.net/

*activity-stream* is full-off telemetry:

>// These fields are sent from the client
>"client_id": "374dc4d8-0cb2-4ac5-a3cf-c5a9bc3c602e",
>"session_id": "{12dasd-213asda-213dkakj}",
>"profile_creation_date": 14786,

>// These fields are generated on the server
>"ip": "10.192.171.13",
>"receive_at": 1457396660000

Source: https://github.com/mozilla/activity-stream/blob/b69291f6f37d1625134247c537d8796aae2c0695/docs/v2-system-addon/data_dictionary.md

The server is [onyx](https://github.com/mozilla/onyx#v4linksactivity-stream)

**Comment by grauenwolfe** [comment]
@Gitoffthelawn You may know this already and sorry if you mentioned this and I missed it but you can just delete the activity-stream system extension from your application folder. I do this after every update or fresh install along with the other system extnesions. My about:support shows nothing under Firefox Features.

**Comment by Gitoffthelawn** [comment]
@grauenwolfe No harm in mentioning it! :)

I think it's worthy of a new issue... #397

**Comment by Thorin-Oakenpants** [comment]
I'm using this issue as a ticket to revamp item 5014. I'm not sure if I want to include let alone maintain all those prefs, and I certainly can't be bothered with checking that telemetry in AS respects FF's send data preference. Not can I be certain that "pings" respect telemetry because see pingsender.exe which doesn't. And I can't be certain that stuff isn't sent if we block pref urls, because stuff may be hardcoded (I'm done wasting my time in this maze).

It will probably end up like follow on search `5013` - instructions to set Homepage/newwindows and newtab to about:blank or use an extension, and delete the xpi.

**Comment by Thorin-Oakenpants** [comment]
@earthlng So what's the verdict? Add all these prefs in (maybe dig into the code a little to check what isn't strictly needed) or just tell people to delete the xpi and change their homepage etc?

Because the xpi is always added when the app updates, users could inadvertently run FF with this present (I'm not even sure if anything happens (data collection) when AS isn't used to load newtab or homepage). So I'm leaning towards adding all the prefs, but would need some help deciphering which ones are necessary.

**Comment by earthlng** [comment]
> just tell people to delete the xpi and change their homepage etc

:+1: 

The telemetry uses ping-centre and should be covered by 0506 and 0333.

If you wanna add the prefs I'd just disable everything:
```js
user_pref("browser.newtabpage.activity-stream.disableSnippets", true);
user_pref("browser.newtabpage.activity-stream.feeds.aboutpreferences", false);
user_pref("browser.newtabpage.activity-stream.feeds.favicon", false);
user_pref("browser.newtabpage.activity-stream.feeds.migration", false);
user_pref("browser.newtabpage.activity-stream.feeds.newtabinit", false);
user_pref("browser.newtabpage.activity-stream.feeds.places", false);
user_pref("browser.newtabpage.activity-stream.feeds.prefs", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.options", "");
user_pref("browser.newtabpage.activity-stream.feeds.sections", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.systemtick", false);
user_pref("browser.newtabpage.activity-stream.feeds.telemetry", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.showTopSites", false);
user_pref("browser.newtabpage.activity-stream.telemetry", false);
user_pref("browser.newtabpage.activity-stream.telemetry.ping.endpoint", "");
user_pref("browser.newtabpage.activity-stream.telemetry.ut.events", false);
user_pref("browser.newtabpage.activity-stream.tippyTop.service.endpoint", "");
```

**Comment by earthlng** [comment]
browser.newtabpage.activity-stream.feeds.aboutpreferences is new in FF61. FF61 also adds:
```js
pref("browser.newtabpage.activity-stream.feeds.messagecenterfeed", true);
pref("browser.newtabpage.activity-stream.feeds.theme", true);
pref("browser.newtabpage.activity-stream.messageCenterExperimentEnabled", false);
```

**Comment by Thorin-Oakenpants** [comment]
Sheeshus H Christ .. that's a lot of prefs. OK, I think we'll stick with the KISS principle :kiss:

**Comment by Gitoffthelawn** [comment]
Which is what in this case?  Deleting the XPI is nice and clean, except for the fact that it gets reinstalled at (almost) every release (which is weekly is you are on beta and daily if you are on nightly).

**Comment by Thorin-Oakenpants** [comment]
KISS = least lines possible, plus it removes the overhead of dealing with all the gazillion changes they keep making. Sucks to be on nightly then - but I can add a line about `browser.newtabpage.activity-stream.*`

**Comment by Thorin-Oakenpants** [comment]
> The telemetry uses ping-centre and should be covered by 0506 and 0333

IDK about that. I don't have the full STR, but OP had issues with data still being collected. IDK if it was sent, but it was being collected!

**Comment by Thorin-Oakenpants** [comment]
^^ comments on my patch? I feel that for me, I'll be fine .. but others may not be, because local data is still compiled (not 100% sure on that) if the xpi is present

**Comment by overdodactyl** [comment]
How hard would it be to get essentially a "blank" add-on submitted to AMO with the same ID as activity stream?

```
Available locations, starting from the highest priority include:

    1. temporary install (about:debugging)
    2. normal user install into profile (about:addons or AMO/TestPilot/etc.)
    3. system add-on updates
    4. built-in system add-ons

This makes it possible for a developer or user to override a system add-on by installing an add-on with the same ID from AMO or TestPilot or as a temporary add-on.
```

https://firefox-source-docs.mozilla.org/toolkit/mozapps/extensions/addon-manager/SystemAddons.html

Was just trying to think of a way to override the `.xpi` file on a per-profile basis and not have to worry about the file being re-installed upon updates.

**Comment by Thorin-Oakenpants** [comment]
>  with the same ID

I would have assumed it would be impossible (in stable, signed extensions) because surely whatever is used as the ID is unique? Over my head. Not an extension dev. Otherwise, surely we would have seen malicious extensions using this by now - or did I misunderstand something?

**Comment by overdodactyl** [comment]
I would have assumed the same (I'm also not very familiar with webextension development), but the documentation seems to imply it's possible, specifically:

>This makes it possible for a ... user to override a system add-on by installing an add-on with the same ID from AMO

Maybe @earthlng would have a little more insight here?

**Comment by Thorin-Oakenpants** [comment]
Even if it were possible, and it would have to be signed, I think Mozilla would shut it down - the extension and maybe/probably the method, IDK. They refused to show system addons in about:addons and allow any way to disable them - wontfix, wontfix, wontfix

**Comment by claustromaniac** [comment]
A blank xpi would be an easy and elegant set-and-forget solution for everyone but, personally, this is the kind of task I use scripts for. I don't give a shit if the xpi's keep coming back.

A likely working alternative would be to make a blank xpi and tamper with access rights to prevent it from being overwritten by Firefox, but I don't know if the latter would be OK with that.

**Comment by overdodactyl** [comment]
I was just about to look into the blank addon a bit more. Simply using the following for `manifest.json` works to override the `activity-stream@mozilla.org.xpi` when loaded as a temporary add-on:

```
{

  "description": "A blank extension used to override the Activity Stream system add-on. See https://firefox-source-docs.mozilla.org/toolkit/mozapps/extensions/addon-manager/SystemAddons.html",
  "manifest_version": 2,
  "name": "Activity Stream Override",
  "version": "1.0",
  
  "applications": {
  "gecko": {
    "id": "activity-stream@mozilla.org"
  }
}

}
```
I can try submitting it to AMO and see if it's rejected or not. 

A script would certainly be an effective method, but personally I would like a per-profile solution (I need access to the activity stream for another repo I maintain).

**Comment by overdodactyl** [comment]
No luck submitting to AMO. I get the following from the validation report:

`You cannot submit an add-on with a guid ending "@mozilla.org" or "@shield.mozilla.org" or "@pioneer.mozilla.org"`

I can try using the signing API, but would be surprised if it's the same issue..

**Comment by Thorin-Oakenpants** [comment]
^^ yeah, but can you "hijack" a non mozilla extension this way?

**Comment by overdodactyl** [comment]
I just tried to upload a blank one using the id for uBO and it failed with the following error:

```
Your add-on failed validation with 1 error.

    * Duplicate add-on ID found.
```

So it doesn't look like that would be possible.

**Comment by Gitoffthelawn** [comment]
For Windows, I have written a script that runs Firefox using `Shell.Run`.

I'm thinking that before the `Shell.Run` command, to delete any unwanted Firefox Feature .xpi files.

The challenge to doing this is that the script must have admin privileges in order to delete those .xpi files.

But it seems like a real bad idea to run Firefox from an admin elevated script. 

Is it?  And if so, is there a way to accomplish this goal programmatically (that is, to delete the unwanted .xpi's using admin privileges, then run Firefox without any privilege escalation)?

**Comment by claustromaniac** [comment]
> Is it? And if so, is there a way to accomplish this goal programmatically (that is, to delete the unwanted .xpi's using admin privileges, then run Firefox without any privilege escalation)?

Nowadays Firefox runs sandboxed and there are now plenty of limitations on add-ons (since webextensions came to be), so I think it _should_ be safe enough to run elevated. Still, you know how this has always been. You can't do much against zero-day attacks before they are discovered, and running Firefox with low privileges is one of the few things you **can** do.

As for your second question, I searched a bit and, apparently, it can be done using [runas.exe](https://ss64.com/nt/runas.html), by passing `trustlevel:0x20000` to it. Still haven't tried it out.

**Comment by Thorin-Oakenpants** [comment]
^^ https://github.com/ghacksuserjs/ghacks-user.js/blob/master/prefsCleaner.bat ... lines 53+

**Comment by claustromaniac** [comment]
@Gitoffthelawn You mean to see if the script is working? 

You can see it in the processes tab in task manager. Under _Virtualization_, it should say _Not Allowed_ if the process running with admin privileges, otherwise it means it's not. You may need to make that column visible first from the menu (View > Select Columns).

@Thorin-Oakenpants the prefsCleaner doesn't care about admin privs, though. I'm sure there must be ways to check for that in VBS and PowerShell scripts, but I don't know if that's what @Gitoffthelawn wants anyway.

**Comment by Gitoffthelawn** [comment]
@claustromaniac I just wanted to be able to know a way to determine whether or not FF is running with admin privs.  Your tip regarding task manager will likely do the trick.  Thanks. :+1:

**Comment by claustromaniac** [comment]
> BTW, the column is entitled UAC Virtualization in Win7.

True. Sorry about that.

You know, I'm a bit curious about what you said before that the script does more than just delete those xpi files. Is it related or just personal-preference stuff? If there are other good reasons for using this sort of launcher script, maybe others can benefit from something like it too.

BTW, I was now thinking that for people that want to remove those files on a per-profile basis, like @overdodactyl, a script like this could simply rename/move the files instead of deleting them. I know it's far from ideal but it might be worth it in the long run. I know it wouldn't take too long to write a script like that.

**Comment by overdodactyl** [comment]
> for people that want to remove those files on a per-profile basis, like @overdodactyl, a script like this could simply rename/move the files instead of deleting them

**Comment by overdodactyl** [comment]
I just gave that a try and interestingly get the error, "This addon could not be installed because it has not been verified"

**Comment by overdodactyl** [comment]
It is kind of ironic their own extension isn't signed haha.

No luck there either unfortunately...no error message but it just doesn't go into effect.

**Comment by earthlng** [comment]
^^ just tried that in my nightly and apparently activity-stream is not only unsigned but also a "legacy extension" - LO-fucking-L, mozilla and their fucking double-standards!

**Comment by earthlng** [comment]
but it has to work *somehow* - how else would updates to system addons be able to work? maybe it needs to go into a special profile subfolder? has anyone ever received an update for one of the system addons and would know where these files are placed?

**Comment by earthlng** [comment]
one workaround is to set `extensions.legacy.enabled` to true and `xpinstall.signatures.required` to false but that's only allowed in ESR and Nightly.

**Comment by overdodactyl** [comment]
Ya I wish you were allowed to change that setting in stable as well.

**Comment by overdodactyl** [comment]
Looking at the system addons, I'm curious how many of those are truly necessary:

* `aushelper@mozilla.org.xpi`
* `firefox@getpocket.com.xpi`
* `followonsearch@mozilla.com.xpi`
* `formautofill@mozilla.org.xpi`
* `onboarding@mozilla.org.xpi`
* `screenshots@mozilla.org.xpi`
* `shield-recipe-client@mozilla.org.xpi`
* `webcompat@mozilla.org.xpi`

**Comment by overdodactyl** [comment]
I'm not seeing any references to `activity-stream` within a specific profile

**Comment by overdodactyl** [comment]
I guess yet another workaround would be to simply use a different install of FF - one were the xpi file is deleted, one where it's not.

**Comment by Thorin-Oakenpants** [comment]
^^ that wouldn't work for people who update from within the app. And even if an install like that was around, its more work than it is to just delete the xpi files manually

The solution appears to be, in order to be 100% proof, to add all the prefs to the user.js, all 95 of them

**Comment by earthlng** [comment]
https://firefox-source-docs.mozilla.org/toolkit/mozapps/extensions/addon-manager/SystemAddons.html

> **System add-on updates**
> These are installed into the users profile under the *features* directory.

**Comment by overdodactyl** [comment]
>And even if an install like that was around, its more work than it is to just delete the xpi files manually

True, but I was trying to address the issue of wanting to be able to access activity stream in one profile, while simultaneously having it removed from another without user.js.  

I agree though, the best solution unfortunately seems to be to add those prefs.

>These are installed into the users profile under the features directory.

The system addons (for me at least) are located in the *features* directory of my Firefox app (`/Applications/Firefox.app/Contents/Resources/browser/features`), but the *features* directory of an individual profile is empty

**Comment by Thorin-Oakenpants** [comment]
This local data collection - I wonder if AS runs in PB mode - if it does and collects things like most visited sites, that could be problematic. Wonder if @fmarier knows

**Comment by earthlng** [comment]
ok I figured it out, the trick is to customize the pref `extensions.systemAddonSet` and the xpi needs to go in profile/features/{UUID}/ where UUID is a valid, well, UUID ;)

for example this works:

set `extensions.systemAddonSet` to `{"schema":1,"directory":"{9c223810-fd9c-4c4d-809b-838623587fe7}","addons":{"activity-stream@mozilla.org":{"version":"2018.04.13.1371-d6edded2"}}}`

To get the version of your activity stream xpi place it in your extensions folder and check about:support. 
if necessary update the version in the `extensions.systemAddonSet` pref. Then move the xpi to `profile/features/{9c223810-fd9c-4c4d-809b-838623587fe7}`

**Comment by overdodactyl** [comment]
Thanks @earthlng!! That seemed to do the trick :)

**Comment by Atavic** [comment]
@Thorin-Oakenpants
https://sql.telemetry.mozilla.org/dashboard/activity-stream-metrics-summary - requires login

**Comment by Thorin-Oakenpants** [comment]
@Atavic - no, telemetry for Firefox users (nightly) web traffic of HTTP vs HTTPS - https://telemetry.mozilla.org/

**Comment by Thorin-Oakenpants** [comment]
So where are we with this?

Current
```js
/* 0514: disable Activity Stream (FF54+)
 * Activity Stream replaces "New Tab" with one based on metadata and browsing behavior,
 * and includes telemetry as well as web content such as snippets and "spotlight"
 * [1] link etc
```

I created a patch (branch only, now deleted) with changes a week ago and no one said anything - its linked right there from 7 days ago
```js
/* 0514: disable Activity Stream (FF54+)
 * Activity Stream is the default homepage/newtab, based on metadata and browsing behavior,
 * and includes telemetry and web content such as snippets, top stories (pocket), top sites, etc.
 *  - ONE: make sure to set your "home" and "newtab" to about:blank (or use an extension to control them)
 *  - TWO: DELETE the XPI file in your System Add-ons directory (note this get reinstalled on app updates)
 * And/or you can try to control the ever-growing, ever-changing "browser.newtabpage.activity-stream.*" prefs
 * [1] link etc
```

Or we could change the info bit to something like I have above AND add all 28 AS prefs, inactive maybe?. The only reason I would do this is because not all users will remember to remove the xpi each update

Where's the feedback on this, guys, gals?

**Comment by earthlng** [comment]
> I created a patch (branch only, now deleted) with changes a week ago

I didn't realize it was in a different branch, I thought you already committed it to the master.

As long as AS remains a system addon, the short one without the new prefs is fine IMO.
