### ISSUE TITLE
add: browser.privatebrowsing.autostart

### ISSUE THREAD

**Issue by Roman-Nopantski** [ghacksuserjs/ghacks-user.js#4]
Based on pyllyukko's user.js, something like

// Start in private browsing mode
// https://wiki.mozilla.org/Private_Browsing
// user_pref("`browser.privatebrowsing.autostart`", true);
// user_pref("`extensions.ghostery.privateBrowsing`", true);

- Should I add an explanation that PB means no retained session data such as history, cookies etc? Part of this js' appeal is the descriptions and notes.
- And where to put it. I would like to put it in startup 0100, as it doesn't singularly fit in another section, eg 0800 (forms, history) and 2700 (cookies/dom)

**Comment by earthlng** [comment]
re: explanation: No, the link to the mozilla wiki is good enough IMO, and most users should already know what PB is/does anyway.
I kinda don't like the ghostery part though. That's a very shitty choice of an addon and we shouldn't encourage anyone to use it. Also I'm not sure how I feel about adding 'extensions.' prefs in general. NoScript f.e. would have quite a few that would be worth including then, but imo that's best left to the users of those addons.
As for the number, it doesn't really fit with the other ones under 0100, and since it makes a lot of other prefs obsolete, maybe it deserves something like 0001. (?)

**Comment by Roman-Nopantski** [comment]
I agree we do not WANT to be adding extension's prefs: And ghostery IMO is worthless if you have uBlock Origin, and it's ties to advertising, while they *may* be above board, is a bit dodgy. Plus it has a crappy interface :)

I do mention in 1602 (DNT) a NoScript pref that needs to match if you are going to turn DNT on or off. It is these sorts of things that we need to add to help end users. Since I recommended NS in appendix b, that one is ok IMO, it is simply listed without a user_pref("",). But we don't recommend ghostery, so do we leave that out? The last thing we would want is for end users who have ghostery to have issues, or think they are in PB mode when they are not. I'm not installing ghostery and testing it.

I'm struggling a little here. I don;t want a new section, and it needs to come after the first parrot demise.

/*** 0100: STARTUP & PB MODE ***/
user_pref("ghacks_user.js.parrot", "0100 syntax error: the parrot's dead!");
// 0001:  Start in private browsing (PB) mode
// https://wiki.mozilla.org/Private_Browsing
// user_pref("browser.privatebrowsing.autostart", true);
// 0101: disable "slow startup" options

^^ how does that sound? I'm leaving it inactive, because I like my few (5) auto-logins and cookies (10? - site prefs and logins). That said, we need to formulate a proper PURPOSE in the readme. Because this is no longer about being MY js xD

**Comment by crssi** [comment]
I am avoiding private browsing for several reasons:
1. I cant control cookies at all, and cookies are not destroyed properly when tab is closed. I am using Self-Destructing Cookes (SDC). Havent find better sollution till now. SDC doesnt destroy LSO na HSTS.
I believe LSO is not a problem is you dont your Flash (and I dont)... am I true here???
Havent found a good sollution for HSTS, but havent got time yet.
2. Same as you, I like some cookies to keep and I do also use auto-login/pass-manager.

I am in a investigation of the diff from your and mine user.js. Have quite a few and need some time. :)
I also dont try to make my browser full "goverment grade" tracking prof, since its futile.

Cheers

**Comment by Atavic** [comment]
Regarding _1602 (DNT)_ I quote a paper called _Dusting the Web for Fingerprinters_:

> We set the DNT header to 1 in the PhantomJS browser and visited the websites identiﬁed as performing ﬁngerprinting in our previous experiments. For all of these pages, we obtained the same results with respect to the number of fonts probed and other browser properties accessed, suggesting that DNT preferences are ignored by ﬁngerprinters.

Available on the [fpdetective page](https://github.com/fpdetective/fpdetective).

**Comment by crssi** [comment]
Statistically, which one we have more, users with DNT=1 or users with DNT=0 or users with no DNT?
Tried to find some statistics about DNT usage, but have failed. :(

**Comment by Atavic** [comment]
I suppose it's one of the most popular changes, as it appears in the options. Users with no DNT are using very old browsers.

**Comment by crssi** [comment]
I guess so too... I am using DNT=1 with the latest stable, which is also having more marketshare than other versions.

**Comment by Roman-Nopantski** [comment]
DNT is useless IMO. It's off by default last time I checked, so I reckon its better off from a FP perspective. The test sites entropy results ate skewed - disproportionate amount of FF users, and eg Panopticon says its roughly 50/50 (as does Am I Unique) which I call BS on. That's the metric from a small subset consisting of paranoid tinhatters, who being good boys and girls turned it on because the EFF said to :) Silly naive people.

Just on DNT - if you use NoScript MAKE SURE to set your noscript.doNotTrack.enabled to match.

@crssi : Yup, we want the browser to be useable (eg 1217 is inactive, we allow mixed passive content such as images and css), whereas pyllyukko's is more hardened. PB mode will definitely stay inactive. The whole idea is people can make their own decisions, because we've added a ton of explanations in easy to understand laymen terms (as best as we can). That said, we need to clarify the purpose. And we need some big ass warnings - eg out of the box there is no tracking protection and some protections are off - we'll get to all that when I make the readme.

**Comment by crssi** [comment]
When you mention 50/50 on Am I Unique or panoptics, which suggest that more than 50% users have DNT=1.
Why is that? The most latest version browsers defaults to DNT=1 and you need to opt-out.
Only paranoid tinhatters turns it off then, and those are making 50/50 on sites like AmIunique or panoptics. But in a real world it makes DNT=1 much more than 50% of marketshare,.

I am not saying that I am true, but I am guessing so. Thats why I have switched to DNT=1 a while ago.
By a wild guess, I would recommend to use DNT=1 to lower FP usability.

Cheers

**Comment by Roman-Nopantski** [comment]
I have DNT disabled, as does everyone in the world by default (well at least FF users)

- Panopticlick: 1.18 (entropy)  1 in 2.26 browsers - that's 44.5% have DNT disabled.
- Am I Unique: 48.51% of users are the same as me with DNT disabled
- Browserprint: 1 in 1.95 browsers - that's 51.28%

These figures are based on datasets that have been created by those DRAWN to them - users who have been told from numerous articles etc, tech readers who like tweaking, that this would increase their privacy. You can't seriously tell me that 50% of the world has bothered to go into their settings and turn this on. By its very nature, and multiple repeat visitors to each test site, the actual data set is much smaller in reality, and the figures are skewed. It's opt-in and 90% of the world wouldn't have a clue.

Your best bet is leave DNT disabled, IMO. The only exception I would make is if a small subset used it, such as TBB (and I was using TBB), or it was tied to privacy.resistFingerprinting - because the purpose of those is to make a significant subset identical - and that is all you need to beat entropy.

**Comment by crssi** [comment]
I guess I was wrong. ;)
Thanks you for response.

**Comment by rekixex** [comment]
@Thorin-Oakenpants 

> Just on DNT - if you use NoScript MAKE SURE to set your noscript.doNotTrack.enabled to match.

Are you sure about this? Majority of NoScript users probably leave it on true, wouldn't setting it to false raise entropy?

**Comment by Thorin-Oakenpants** [comment]
Back in the day when I was testing DNT, for some reason I was not getting the correct results, and I narrowed it down to that NS setting - i.e I would fully disable DNT but tests would show I had it on (because it was on in NS) - so that line was added (since NS is an add-on we have on our recommended list) so end users are aware.

Come EOL for ESR52, we can remove that line, because Extensions do not store settings in about:config. And indeed, it should go without saying that add-ons/extensions can change pref setting behavior.

As for DNT re entropy. Initially (2+yrs ago) I had it on (this was my version shared at ghacks, not the collaborative effort here) - it was new, shiny and exciting <sup>[citation needed]</sup>. At some stage I decided it was a load of bollocks from an entropy point (I do not care about it's effectiveness - we recommend blocking as much tracking via other means). No need to rehash it here suffice to say that IMO most people would not bother to change this setting (i.e within FF users) and that online tests are skewed (massively towards DNT users) because of the nature of the visitors - even then it was 50/50.

Then we enabled Tracking Protection - but this means that TP enforces DNT in PB mode, regardless of the setting in prefs - which I was unaware of at the time. We flip flopped for a while. DNT on in all windows. **now** we have DNT at default, and TP at default = extremely likely the most common setting - a lot of users use PB mode (I think Francois said 25%), and PB mode can be detected as well. So in conjunction with other relevant FP points, we're consistent - normal windows=off, pbmode=on. What the end user decides to do is up to them.

DNT is one bit of entropy (I think it's a quarter of that - two bytes? - but that's not how it's computed but is, I think, the figure used in algorithms) - at the end of the day it's not that big a deal in the scheme of FP'ing items.

**Comment by Thorin-Oakenpants** [comment]
> Are you sure about this? Majority of NoScript users probably leave noscript.doNotTrack.enabled on true, wouldn't setting it to false raise entropy?

Also .. what % of NS users make up the FF base: NS users on AMO currently shows 1.7+ million. That's like 1 or 2% of FF users

**Comment by rekixex** [comment]
@Thorin-Oakenpants I agree with your points on DNT. Unfortunately, not many sites respect the DNT header.

> Also .. what % of NS users make up the FF base: NS users on AMO currently shows 1.7+ million. That's like 1 or 2% of FF users

That's why I ask, I guess sites can detect you are a NoScript user? I may be very wrong but since the browser with NoScript sends the Do Not Track header by default, are you more unique with noscript.doNotTrack.enabled on false?

Is this preference set to false in Tor Browser?

**Comment by Thorin-Oakenpants** [comment]
> not many sites respect the DNT header

AFAIK **no-one** respects the header - but again, this is not about its effectiveness

>  I guess sites can detect you are a NoScript user

Not that I know of - they can detect the DNT header

> Is this preference set to false in Tor Browser

I do not think it is used in TBB, but this is irrelevant - the entropy only matters within the FF set of users
