### ISSUE TITLE
geo.wifi.logging.enabled

### ISSUE THREAD

**Issue by kgbm3** [ghacksuserjs/ghacks-user.js#427]
It had been mentioned [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/222) and, also, in a [gist](https://gist.github.com/0XDE57/fbd302cef7693e62c769#gistcomment-2553208) (Apr 12). 

Are we sure that the (_hidden!_) preference still exists?! Firefox 60.x (FF 6.x)

On **R**eset it goes blank, but - not sure whether that's the expected result?!

![geo wifi logging enabled](https://user-images.githubusercontent.com/30203280/40270290-aade4e0a-5b79-11e8-97cc-97f054e541a8.png)

^^ **geo.wifi.logging.enabled**

**Comment by Thorin-Oakenpants** [comment]
> Are we sure that the (hidden!) preference still exists?! 

Yes. You can see them in the source code: I use DXR and search the central branch
- [Bookmark this page](https://dxr.mozilla.org/mozilla-central/source/) - **h**ttps://dxr.mozilla.org/mozilla-central/source/

Example: https://dxr.mozilla.org/mozilla-central/search?q=geo.wifi.logging.enabled&redirect=false

Whether it actually does anything is a different story. For that you need to dig into the code itself

> On Reset it goes blank, but - not sure whether that's the expected result?!

That's expected behavior. If you then refresh about:config the pref itself is also gone. *Hidden* prefs are ones they don't want to expose via about:config: usually to limit exposure and stop possible breakage - i.e they know that people play with about:config. They will only show in about:config if you manually enter it (and thus it ends up in prefs.js).
