### ISSUE TITLE
Sanitize app.update.url and extensions.update.url

### ISSUE THREAD

**Issue by Dupond** [ghacksuserjs/ghacks-user.js#432]
Hello,
First of all, I'd like to apologize for my bad english, and to thank all the contributors of this very useful project.
It seems that those two preferences give many informations :
```
app.update.url;https://aus5.mozilla.org/update/6/%PRODUCT%/%VERSION%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%SYSTEM_CAPABILITIES%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/update.xml

extensions.update.url;https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=%APP_LOCALE%&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%
```
Since ghacks-user.js already sanitizes blocklist url (see the 0401 section), wouldn't it be more consistent to sanitize `app.update.url` and `extensions.update.url` too ? Or do they have different involvments concerning users'privacy ?... or are all these informations really needed in order for the updates to work ?

**Comment by Thorin-Oakenpants** [comment]
I'm not 100% entirely sure, but I would guess that's how the current version of your browser is passed on to those Mozilla servers in order to let you know if you have updates

I was actually thinking of removing the 0401 sanitized blocklist pref. If Mozilla gets that tiny bit of info from you anyway (if my statement above is correct), then why bother with sanitizing the blocklist one. Although my original reasoning was more along the lines of "if you can't trust Mozilla with that tiny bit of info, which is insignificant anyway, not unique, and anonymized, then why bother using Firefox). Am trying to cut down the user.js if I can, and I see zero harm in removing this one.

But we'll wait and see what earthlng says

**Comment by Thorin-Oakenpants** [comment]
@earthlng (or anyone)

what is `privacy.trackingprotection.ui.enabled` 's default value in ESR52.x

In FF60 it is true, which is what we set in the user.js. Its the pref (0421) to enable more choices in the preferences UI. If its true in ESR52.x, then I think we could get rid of it

**Comment by earthlng** [comment]
> what is `privacy.trackingprotection.ui.enabled` 's default value in ESR52.x

default is false in ESR52.x. But that's one of the prefs I wanted to bring up for removal once ESR is EOL.

Another thing I'd like to see removed is the double entry for 0422. Basic is the default anyway but another problem is that selecting strict via the UI just adds `,content-track-digest256` to the default value. If that default value changes or they change/rename the part that gets appended, we would fuck up people's configs. We will see changes to the default value in the diffs but not changes to the to-be-appended part.
Just something to think about I guess.

> or are all these informations really needed in order for the updates to work ?

IDK either. Certain things in the extension url could definitely be removed, like status for example and probably locale, but others I'm not so sure. It would need some testing to see what can or can't be removed to still keep it functional and getting the correct updates.

1 difference for the blocklist is that [Mozilla's list of blocked add-ons and certificates is not OS specific](https://trac.torproject.org/projects/tor/ticket/16931) but app.updates are very much OS, channel, etc specific. For `app.update.url` there's even a system addon that mods this pref based on certain OS, etc conditions. So I'd not mess with this.

I don't agree with Pants in that just because we don't sanitize everything means we should remove the parts that we can and do sanitize. I like the approach of "when in doubt, check what others are doing" and in this case https://github.com/pyllyukko/user.js/blob/master/user.js#L436 also has the blocklist sanitize. Ergo I would keep it.

**Comment by Thorin-Oakenpants** [comment]
Just because PK does, doesn"t mean we should. I'm actually going thru doing a comparison right now, and I do not agree with some of his settings AT ALL (and neither do you, because you like our ones). Although, no disrespect meant to PK, these are guidelines/templates.

```
* PK: https://blocklist.addons.mozilla.org/blocklist/3/%APP_ID%/%APP_VERSION%/
* GH: https://blocklists.settings.services.mozilla.com/v1/blocklist/3/%APP_ID%/%APP_VERSION%/
* DF: https://blocklists.settings.services.mozilla.com/v1/blocklist/3/%APP_ID%/%APP_VERSION%/%PRODUCT%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/%PING_COUNT%/%TOTAL_PING_COUNT%/%DAYS_SINCE_LAST_PING%/ 
```

Can you spot the difference? DF = default (it hasn't changed since we came to github, so this covers 52+)

**Comment by earthlng** [comment]
Actually, in ESR52 the default value is
```
https://blocklist.addons.mozilla.org/blocklist/3/%APP_ID%/%APP_VERSION%/%PRODUCT%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/%PING_COUNT%/%TOTAL_PING_COUNT%/%DAYS_SINCE_LAST_PING%/
```

**Comment by Thorin-Oakenpants** [comment]
Closing this. It's not feasible to sanitize these IMO.

So I can see what we're dealing with
- app.update.url;**h**ttps://aus5.mozilla.org/update/6/%PRODUCT%/%VERSION%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%SYSTEM_CAPABILITIES%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/update.xml
- extensions.update.url;**h**ttps://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=%REQ_VERSION%&id=%ITEM_ID%&version=%ITEM_VERSION%&maxAppVersion=%ITEM_MAXAPPVERSION%&status=%ITEM_STATUS%&appID=%APP_ID%&appVersion=%APP_VERSION%&appOS=%APP_OS%&appABI=%APP_ABI%&locale=%APP_LOCALE%&currentAppVersion=%CURRENT_APP_VERSION%&updateType=%UPDATE_TYPE%&compatMode=%COMPATIBILITY_MODE%

I don't see anything in app.update, they all look important. extensions.update IDK, WTF is an `appABI`. I think locale could be important in some cases. What works for us in testing might break something for someone else, or down the track. Maybe status, as earthlng said, but I do not think it's worth it

Feel free to reopen if new info comes to light
