### ISSUE TITLE
vote: change cookies from block all to allow 1st party

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#439]
proposal
- `2701`: `network.cookie.cookieBehavior` : currently 2, block all: suggested 1, allow only first party
- `2800s`: change the two cookie clearing prefs to true

reason
- website breakage (see story below)
- makes the user.js more user friendly (1 less thing to unbreak a site, or get logins to work etc)
- its simple enough for "hardened" users to add to their overrides
- we expect users to be using an extension or some other mechanism that suits them - there are so many options eg uMatrix (allows in = no web breakage, but blocks it going out), or C-AD, or containers, or TC, cleaning mechanisms and so on. And users can still set site exceptions for block and session only if they want.

issues:
- none. It's just the default we present in the template. It's a choice between my more hardened setup (default deny and allow exceptions, and I don't clear on close because I like my 4 or 5 sites auto-logins etc, and I don't even need an extension, well not quite true: session cookies used only to make a site work are still usefully blocked in uM) vs a more relaxed approach which requires cleaning (not just cookies but localStorage and IDB - on close is fine, its more about in-session).

I don't think my strategy would be the most popular. This is a fairly simple step to take in making the user.js more "mainstream" which can be supplemented with `relaxed` and `hardened` overrides (in the making).

story:
- I just wasted 15 minutes trying to get imgur to display a godamn image - pissed around with uM and uBO and decentraleyes and even ClearURLs. Then did the troubleshooting trick in a new profile and it came down to allowing a cookie to be *sent* to me. So I can see people getting frustrated. Not that I will change my strategy just yet. 

edit: FYI here was the imgur link - https://imgur.com/a/PPsbbKV . Its an album. Never had a problem with imgur before. Now it seems I need to let them send me a cookie (at least for albums).

:+1: or :-1:

**Comment by Thorin-Oakenpants** [comment]
OT probably: maybe its because cookies are worth so much - [medium article](https://medium.com/@thezedwards/the-cookie-exchange-how-gdpr-created-a-new-market-for-pseudonymized-cookies-592cbde9b44b?source=linkShare-e55d568b3a27-1527345283) - go on, read it. Maybe its because of GDPR and they want to make sure everyone gets a cookie. IDK. Interesting read, will put you to sleep

**Comment by earthlng** [comment]
IDK, changing the template to clear all cookies on shutdown could piss off existing users who like to keep some cookies. Might be better to list this for a `relaxed` mode. Or we wait with this and mention in the next changelog that we will soon change the cookie settings and that those who want to keep the old blocking behavior (+ all their stored cookies) need to add these prefs to their overrides.

**Comment by Atavic** [comment]
For a relaxed override, it seems reasonable.

**Comment by Thorin-Oakenpants** [comment]
> IDK, changing the template to clear all cookies on shutdown could piss off existing users

Agreed. Needs timing *if* we do it. The default shouldn't leave users being tracked via cookies (across sessions), hence why the three prefs were lumped together.

**Comment by claustromaniac** [comment]
I'd take my time to decide this. It's better to see how the relaxed overrides turn out first, IMO. If that was your intention all along, I think it was still a good idea to open this issue ahead of time.

**Comment by Thorin-Oakenpants** [comment]
> If that was your intention all along

A relaxed (and/or hardened) version has been on the cards since we got here (to github). Now that the js is pretty much matured: I did not want to deal with two branches while we decided to revamp sections etc, although this is a moot point with doing a sticky (and I've been a lazy SoB in getting around to it) .. then all that is undecided is... the initial state of the user.js.

From others' comment(s) I got a vibe/idea that the default state could be `relaxed` (or at least some aspects of it), as this would be more readily usable for end-users / uptake. **Then** more tech savvy users could flip (or paste in) *hardening* overrides. As compared to what we are doing now, which is pretty much a hardened default js (yes there are more items we could harden by making prefs active etc) and then we possibly confuse users with relaxed *and* hardened overrides.

For most widespread uptake and simplicity, a user.js that is relaxed, with a couple of inbuilt hardened overrides on 1-char switches seems like the simplest, end-user friendliest, widest appeal, single file option. If the updater could replace the one char switches to their original state (i.e the state in the user's profile dir), that would solve about the only technical barrier I can think of. eg we add `/* [SWITCH] ***/` above each one or something. IDK, don't want to get off topic too much

I'm testing the waters a little, since the proposed change is just one pref that doesn't really affect end users privacy, its just a different way of looking at it, kinda. Most users already deal with cookies in numerous ways, the vast bulk of which would entail allowing 1st party.

**Comment by overdodactyl** [comment]
>it might even be a good opportunity to take an approach like the one @overdodactyl suggested some time ago

I don't have much experience with GoLang, but I've been really pleased and impressed with the updater script someone created for my ShadowFox project with it.  It has a nice simple GUI (drop down to select what profile it should be installed in, buttons to install/update or uninstall, few checkboxes with options etc).  Assuming it's ok with the dev/license he put on, we would be able to re-purpose most of the code...at their core, there are a lot of similarities between what they do (i.e. install into a FF profile a file downloaded from GitHub and append some extra customization files to the end of it).  

For users who maintain multiple profiles, it has the added bonus of only needing one installer instead of multiple.  We could add a checkbox for whether or not a user wants to use a relaxed version or the hardened one, and we could try and incorporate the cleaning scripts into it as well.  

Just some food for thought :)

**Comment by claustromaniac** [comment]
@overdodactyl It's an interesting possibility. I haven't looked at the code yet, but I think I'd probably still want to rewrite it from scratch, since we would have to make significant changes to it anyway. For starters, we would want to support FF portable profiles (AFAICT that one doesn't), and I would also want it to have most of the advanced functionality of the current updater for Windows (but improved). 

Just thinking out loud. 

If we took this path we should use a separate repo exclusively for the updater, but something tells me @earthlng may not be too enthusiastic about the whole idea, since he would have to do the audits as always :sweat_smile: 

I think I heard him sighing already.

**Comment by overdodactyl** [comment]
@claustromaniac -

> For starters, we would want to support FF portable profiles (AFAICT that one doesn't)

I can double check to make sure nothing has changed, but last I saw, it required a `profiles.ini` file to work, which isn't created by default for portable installations.  The current workaround is to just manually create one.  See here:

`https://github.com/overdodactyl/ShadowFox/issues/127#issuecomment-384812766`

It might be good to start from scratch, I just thought it was worth pointing out that there is a nice foundation we can work from, or at least reference, that already has several of the functionalities we would need.  I'm not sure about you, but I don't have much experience with GoLang, so I thought that would be really helpful haha. 

If we were to use this approach, I think a separate repo is a must.  Here's the one for the ShadowFox updater.  Sorry, should have linked that earlier so anyone interested wouldn't have to search it out:

https://github.com/SrKomodo/shadowfox-updater

**Comment by Thorin-Oakenpants** [comment]
> I think a separate repo is a must

If you want one, I can set it up under the [ghacksuserjs organization](https://github.com/ghacksuserjs) and give the required perps full control

**Comment by overdodactyl** [comment]
I don't mean to push this approach down anyone's throats, so no hard feelings if you guys just want to stay on the current path!

If there's interest in it though, that would be great @Thorin-Oakenpants

**Comment by earthlng** [comment]
The updater scripts automate a few simple tasks and they work perfectly fine in their current form. Single plaintext files, easy to understand, no need to compile anything, no dependencies besides what's pre-installed on most systems anyway, no need to install go or python or whatnot - just simply download 1 file and run it.
Making it more complex and elaborate than it needs to be just because Pants wants to have 1-char-switch overrides in the user.js instead of a sticky? Yeah, no. You guys can do whatever you want but I will have no part in it.

**Comment by overdodactyl** [comment]
>no need to install go or python or whatnot - just simply download 1 file and run it.

This wouldn't change for anyone except those developing it.

>Making it more complex and elaborate than it needs

One of the biggest advantages is it's cross platform, meaning it removes the complexity of testing on mac, linux, and windows, maintaining different versions, worrying about what tools users have on their system already etc.

**Comment by Thorin-Oakenpants** [comment]
>  just because Pants wants to have 1-char-switch overrides in the user.js instead of a sticky

Its just an idea. If I was redesigning this from the ground up, I would do that (default relaxed with several harden override sections) - but we're not doing it scratch, so it's a discussion :)  The 1-char switches being retained when using the updater(s) was just an observation, not a given.

**Comment by earthlng** [comment]
How does golang compile work? does it produce native binary code like C?
That would probably mean we'd have to provide 2 binaries for linux (1 x86 + 1 x64), 1 for mac (are all macs x64?) and 2 for windows.
And then there's the trust issue. Who would trust an anonymous person's pre-compiled binary if they could have a single and simple plaintext batch or shell script instead?
The shadowfox updater imports 4 packages from 4 different github repos, and each package probably consists of several files. That's a lot of code for not a lot of added benefits IMHO. And you'd either have to trust them or copy their code and maintain it yourself.
I just don't think that's worth it for the simple tasks the user.js updater needs to perform.

**Comment by overdodactyl** [comment]
>does it produce native binary code like C?

It does.  In the ShadowFox case, the travis build calls the following:

`gox -os="windows darwin linux" -arch="amd64 386" -output="dist/shadowfox_{{.OS}}_{{.Arch}}"`

which can create a release with the 6 resulting binaries ([releases page](https://github.com/SrKomodo/shadowfox-updater/releases)).

As for the trust issue, I don't have to much too add there haha.  The downsides might outweigh the positives for this repo

**Comment by claustromaniac** [comment]
@overdodactyl 

> it required a profiles.ini file to work, which isn't created by default for portable installations. The current workaround is to just manually create one.

Yup, that seems to be the case. Thanks for the info :+1: 

> I just thought it was worth pointing out that there is a nice foundation we can work from, or at least reference, that already has several of the functionalities we would need. I'm not sure about you, but I don't have much experience with GoLang, so I thought that would be really helpful haha.

Absolutely. Having examples always helps :) I'm no expert either, but I've always been good at learning stuff on my own, and I'm usually a fast learner when it comes to these things. However, I have to admit that my unorthodox methodology is one of the main reasons my code looks like :hankey: most of the time. I almost never venture much beyond the toying stage in any language :laughing: Regardless, I have written somewhat complex stuff in C++, C# and various scripting languages, and Go was designed to be easier than those.

@earthlng 

> Making it more complex and elaborate than it needs to be just because Pants wants to have 1-char-switch overrides in the user.js instead of a sticky? Yeah, no.

I'll try to make myself clear, since my first attempt failed miserably, for a change (yeah, right). 

I'm not even suggesting that we should do any of the things I said. As far as I know, all we are doing here is discuss possible routes that we can take from this point onward. 

Your logic makes perfect sense when you think from the perspective of getting better results at what we already do and from what we already have. If anyone weighs **right now** the cons and the pros of rewriting the scripts, there's mostly cons. What I tried to say initially is that I wouldn't want you guys to feel constrained in what you can do. Why? Because, if you can think of better ways of doing things that require altering or rewriting the scripts that we already have, I will be happy to help.

By all means, feel free to think outside of the box, and do share your ideas. Don't let them die. Don't be afraid to dream big. Shake everyone's foundations. Open up; let the world meet that wonderful person behind your mask of whatever. [Insert here random self-growth quote/religious teaching/mantra/FFS WTF/:question::question::question:] That's all I'm saying.

I admit that saying that makes me kind of a hypocrite, since I've had several ideas of my own, but I don't want to make you folks hate me by bouncing a barrage of crazy ideas off of you. I have my own censoring filters in place.

**Comment by earthlng** [comment]
> I wouldn't want you guys to feel constrained in what you can do. ... I will be happy to help.

thanks I appreciate it but don't worry we're not constrained at all. The updater scripts are perfectly fine as-is and your merge function is a piece of art.
As I said, just because Pants has another one of his "great" ideas doesn't mean we have to drop everything and start from scratch. We just tell him "NO! bad Pants! NO!" - that usually does the job :)

**Comment by Thorin-Oakenpants** [comment]
> just because Pants has another one of his "great" ideas

It's hard being the *visionary*

**Comment by Thorin-Oakenpants** [comment]
Just my thoughts: I'm still not happy with the ability of extensions to properly clear persistent web data by host in an automated fashion (this includes temporary containers, they have an issue about data not being cleared but I haven't investigated it fully). Here's an example: https://bugzilla.mozilla.org/show_bug.cgi?id=1465063 which only got fixed (FF62) 18 days ago. And we already know there are issues with clearing IDB by host and time-range (except you can clear a time range of all). etc.

The voting seems to have paused at 9 for - 3 against.

In terms of FP'ng (and to me this is secondary, I mean whats the point in lowering your entropy if you leave service worker caches lying around etc), it makes sense to have first party cookies
- eg panopticlick's `DOM localStorage: Yes, DOM sessionStorage: Yes` is about 1 in 1.3, but as Nos it is 1 in 10.5 (this figure is way too high for real world)

https://old.reddit.com/r/TOR/comments/8wf01i/browser_fingerprint_doesnt_look_promising_on_tb/
--> https://i.imgur.com/oxrIS7Q.png

/end of rambled thoughts

**Comment by Thorin-Oakenpants** [comment]
closing this. thanks for the feedback and votes guys and gals - see #479 

PS: For myself, I *might* experiment with setting cookies default to session only (using 2703) and test if a site override for "Allow" (as compared to "Allow for Session") allows those to persist across sessions. If so, then I could do away with clearing cookies and keep my 4 or 5 permanent cookies for auto-logging in
