### ISSUE TITLE
ToDo: standardize [Setting] information

### ISSUE THREAD

**Issue by Roman-Nopantski** [ghacksuserjs/ghacks-user.js#44]
"setting is under" - 9 instances + "settings are under" - 3 instances
eg: [SETTING] Options>Search>Provide search suggestions

**Comment by earthlng** [comment]
yes, but only if the setting is really not 'under' somewhere/something but is the actual setting-name to enable/check/whatever. fe. I would leave `These settings are under Options>Privacy>Location Bar` as is.

**Comment by Roman-Nopantski** [comment]
too late .. i've gone ballistic

**Comment by earthlng** [comment]
also, since they plan to re-do the whole Options layout/design maybe we better wait with changing this until then.

**Comment by earthlng** [comment]
lol, okay, too late ;)

**Comment by Roman-Nopantski** [comment]
> also, since they plan to re-do the whole Options layout/design maybe we better wait with changing this until then.

Yeah, and that may never happen. But in any case, it's easy now to search & replace

**Comment by Roman-Nopantski** [comment]
I also standardized [TEST] lines

**Comment by Thorin-Oakenpants** [comment]
@earthlng I know how valuable an html version is for links and color coding - its why I provided one at ghacks. The standard method of how I typed things up made it fairly easy to create with a handful of search & replace strings.

We currently have [SETTING] and [TEST], [NOTE] so just throwing this out there, should we also use one or more for references (I know its easy to linkify without it). Would it be beneficial to designate `#Required reading` and differentiate bugzilla links? Or just use a [REF], maybe use [BUG] to keep the length the same

eg
```js
/* 0805: disable CSS querying page history - CSS history leak - PRIVACY
 * [NOTE] this has NEVER been fully "resolved": in Mozilla/docs it is stated it's
 * only in 'certain circumstances', also see latest comments in the bug link
 * [TEST] http://lcamtuf.coredump.cx/yahh/ (see github wiki APPENDIX C on how to use)
 * [REF] https://dbaron.org/mozilla/visited-privacy
 * [REF] https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector
 * [BUG] https://bugzilla.mozilla.org/show_bug.cgi?id=147777 ***/
user_pref("layout.css.visited_links_enabled", false);
```

It would only be useful if we generated an HTML version, where it would be easy to span/color-code the tags eg [WARNING] = pale red background, black text. [NOTE] could be pale orange since they're like minor warning, [TEST] could be pale blue. [REF] could be pale green and [BUG] a brighter green. 

Just an idea, may be overkill. I mean links would be linkified anyway and stand out

**Comment by earthlng** [comment]
Idk, I don't really like it. The bugzilla links are easy to spot and doesn't always mean it's a bug. They also use "bugs" or more appropriate "tickets" to implement new stuff. 
We could use [1], [2], etc. Then we could use them to do this `also see latest comments in [3]`
And as you said `links would be linkified anyway and stand out`

**Comment by Thorin-Oakenpants** [comment]
totally get bugzilla is software tracking (new features etc), and yeah, [bug] is stupid, so is [ref]

So every ref has a [1] [2] .. etc, starting a new per pref number - so should we do this? Or drop it. Only really makes sense if we use it later on for a smooth html color scheme

**Comment by earthlng** [comment]
> so should we do this

sure, I like it :thumbsup:

**Comment by Thorin-Oakenpants** [comment]
alrighty .. coffee time and then I'm onto it
