### ISSUE TITLE
Hardening firefox: regular hash checks on preinstalled addons

### ISSUE THREAD

**Issue by rugabunda** [ghacksuserjs/ghacks-user.js#440]
A simple addon could do this automatically very quickly and easily, by downloading the latest addons at semi random intervals, and comparing hashes; if the hashes are not already available on firefoxes own addons page. 

Today I had noticed the user interface in disconnect totally changed in my firefox browser. It had a clean vertical column listing only google, facebook, twitter, and a few other websites; Each was like a rectangular button. Nothing else was visible.  It was completely different than the original. I should have took a screenshot and backed up the extension but failed to do so. I uninstalled the addon and re-installed it from firefox's website;  The UI immediately went back to normal. I confirm signature checks were in fact enabled. I'm curious what kind of security firefox implements. I know its supposed to only allow signed addons, but does it go one step further and do regular hash checks to ensure it has not been modified or replaced with malware? I believe this will be a necessary step in order to mitigate against many zero day threats or vulnerabilities within browser signature verification systems.

**Comment by Thorin-Oakenpants** [comment]
>  I know its supposed to only allow signed addons

Only enforced on stable. ESR, Dev (& Beta?) & Nightly it can be disabled. Anyone can easily and quickly get an extension signed, so this is no barrier.

A signed extension means it can't be fiddled with (eg opening the xpi and changing stuff and re-xpi'ing. Just changing a single byte will cause it to be disabled when you restart. Like a one one hash.

Also, when getting the extension signed, you couldn't just hijack someone else's extension name / account etc - the signing would be rejected. But I am not an expert on these things. The point is, whatever it was, if signed, is *exactly* as Mozilla auto-signed off on it.

So you either had a completely different extension, or a legitimate one (maybe it's settings or localStorage etc got corrupted or something else). If you had a completely different one, then an external factor must have removed the legit one, and installed theirs instead. And there are other things in place, such as a prompt to install (security delay), limiting where extensions can come from, and run from.

I am not an expert - earthlng and overdodactyl had fun replacing a system addon. I can't remember the details, and I think system addons aren't signed. I honestly do not think it's possible to replace an extension with another of the same name

**Comment by fmarier** [comment]
> I think system addons aren't signed.

They are signed too.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/issues/396#issuecomment-381664575
> It is kind of ironic their own extension isn't signed

the next comment
> just tried that in my nightly and apparently activity-stream is not only unsigned but also a "legacy extension"

**Comment by Thorin-Oakenpants** [comment]
slightly OT: https://bugzilla.mozilla.org/show_bug.cgi?id=1415644#c8  .. I like it how some people think when deciding how to thwart attacks

**Comment by Thorin-Oakenpants** [comment]
> noticed the user interface in disconnect

I've played with this in the past in testing - your description rings a small bell. I think from memory, it was when IDB was allowed (eg when cookies were blocked and you had to set an extensions cookie extension). It could also be indicative of a corrupt IDB.

What version of FF are you on?

**Comment by Thorin-Oakenpants** [comment]
I just tested in a nilla 58.0.2 (because FF59 fixed the extensions need cookies thing for IDB)

Cookies allowed
- installed Disconnect
- changed options to only allow 1st party (so 3rd party doesn't confuse the issue)
- loaded a web page
![cookies](https://user-images.githubusercontent.com/16656956/40758524-4bda8bbe-647d-11e8-90d1-6ce0741c1eb1.png)

Cookies blocked
- change site permissions on the loaded web page to block cookies
- closed web page
- cleared all data (but not site permissions) - under Ctrl-Shift-Del
- open test webpage in a NEW TAB
![nocookies](https://user-images.githubusercontent.com/16656956/40758590-95e8973c-647d-11e8-98df-089a81c2c148.png)

Is that what you saw?

**Comment by Thorin-Oakenpants** [comment]
And in a PB window

Cookie allowed
- its blocking (says 45) but can't fill in the panel because IDB is not allowed in PB mode
![pbmode](https://user-images.githubusercontent.com/16656956/40758797-92d384fc-647e-11e8-93c4-f57a8dd41605.png)

No cookie
- site permission block cookie
- clearing everything (except site permissions)
- close all pb mode windows
- retest site in pb mode
- result as expected: no panel info (because IDB isn't allowed in pb mode), and no blocking (because no cookie means it won't work)

**Comment by Thorin-Oakenpants** [comment]
closing as solved your instance of weird sh&t :)  As for extension's and signing and hijacking or whatnot, I am sure Mozilla have that under control. Re-open if need be, and confirm if what happened was the above.
