### ISSUE TITLE
Quick question: pref to force load WEs at start before ready

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#443]
Is there a pref that tells Firefox to load all extensions before making connections at start?
I think I have seen something like that in the past, but can't remember right now. :cry:

**Comment by Thorin-Oakenpants** [comment]
Not that I know if, in fact I'm certain otherwise the bugzillas would have mentioned it, see next sentence. Is this because of the delay sometimes in extensions handling web content on startup?

https://bugzilla.mozilla.org/show_bug.cgi?id=1378459
https://bugzilla.mozilla.org/show_bug.cgi?id=1418030 etc

**Comment by crssi** [comment]
Thank you @Thorin-Oakenpants... confusion in my head (nothing new) and it was uBO advanced setting and not the pref.
`https://github.com/stoically/temporary-containers/issues/153`

**Comment by Atavic** [comment]
We have the option to start FF in offline mode.
