### ISSUE TITLE
Questions about privacy.resistFingerprinting

### ISSUE THREAD

**Issue by Just-me-ghacks** [ghacksuserjs/ghacks-user.js#449]
1. Why is Firefox spoofing the time zone? The IP address reveals your city (or even your neighborhood in some cases). Once they know your city, they know your time zone. So a weird time zone is actually bad for privacy.

2. I'm running a fairly common resolution. Why doesn't Firefox start maximized? How does a weird size window help?

3. Is it better to let Firefox handle the canvas or we should install CanvasBlocker? What are the recommended CanvasBlocker 0.4.5c settings?

**Comment by Thorin-Oakenpants** [comment]
3. see #350 section on canvas in the first post. If you are using RFP (privacy.resistFingerprinting) then it's important that you have the same FP as all the other RFP users - so that means use their canvas blocking (which is a 10x10 white canvas). If you allow an exception (eg google street view currently requires this), then you can fall back to CB to fake it (thus google doesn't get your real unique canvas). If a site absolutely requires your real canvas (I'm not an expert, eg maybe banks or sites you **log into** frequently [ie they know it's you anyway] so as to not get your account flagged, or maybe a web game), then you can whitelist the site in CB as well.

**Comment by Thorin-Oakenpants** [comment]
2. The resolution spoofed is using the **inner** browser window measurements (because anything else would screw up web page layouts etc). All measurements are returned as your actual inner browser windows ones - that's
- browser inner window width+height
- browser width+height (I think, been a while)
- screen resolution
- available screen resolution

If you go maximized, then you cannot control your inner browser window - it is instead controlled by other factors, such as your 1. *available* screen res and 2. browser chrome elements.

Available screen res can differ - such as in windows, the position of the task bar could be left-right, or top-bottom. The height/width of the task bar can differ as well.

Browser chrome elements can differ. All of which affect the inner browser window measurements - such as the extra drag space, displaying the menu bar, sidebar, toolbar. Also the theme can make changes, such as compact vs default. Even flicking the find bar open changes the metric.

So despite having a common screen res, there are too many variables for a consistent result. Also, not everyone in the RFP set would be maximized. The only solution to encompass everyone is to not allow maximized on startup, and to set a standard size.

**Comment by Thorin-Oakenpants** [comment]
1. Because FP'ing as a *science* makes assumptions. It's looking purely at FP'ing and entropy. So all users need to be on one of the most common timezones (i.e there are 24 timezones, but the online population is not evenly distributed).

Clearly if you are *giving away* your IP, then you've possibly already lost the battle (depends on your threat model). TBB doesn't have to worry about this, in the sense that they are using TOR. Firefox users can use VPNs etc. The assumption is that you are already hiding your location.

**Comment by Thorin-Oakenpants** [comment]
Here's an article on how entropy works in the real world : https://www.eff.org/deeplinks/2010/01/primer-information-theory-and-privacy

**Comment by kgbm3** [comment]
"The assumption is [..]" very clear, IMO? A huge, over-elaborate, question about the basics - in the support (issues), doesn't really help anyone? xD

Anyway, Pants, thanks for the entropy URL, it's a great read..:)

**Comment by KOLANICH** [comment]
>The IP address reveals your city

resistFingerprinting mainly enables uplifted Tor Browser patches. Timezone may not reveal additional information if and only if all the users have their geoip-located timezones matching the ones revealed by the browser. The reality is different. Someone uses Tor, someone uses a VPN, someone's geoip points to another city or even country systematically. These all contain some information, which can be used to reduce anonimity of users, including Tor ones.

**Comment by Just-me-ghacks** [comment]
Thanks for the explanation, Pants!

I still think spoofing the time zone is bad unless you have access to IPs in that particular time zone. Which won't be the case for most Firefox users.

**Comment by Just-me-ghacks** [comment]
Running Firefox in a window is only marginally better than a maximized Firefox window according to Panopticlick.

What's the best option to start Firefox maximized? AutoHotkey?

**Comment by Thorin-Oakenpants** [comment]
> Running Firefox in a window is only marginally better than a maximized Firefox window according to Panopticlick.

You can't take most of those metrics seriously, although at least resolutions are relatively stable, eg compared to say user agents. First of all, it is looking at data gained over a long time, rather than real world, right now. Because you cannot really hide you are using Firefox, you could look at the metrics for FF users - https://hardware.metrics.mozilla.com/ - which is gathered every couple of weeks. However, that is just screen resolution. Panopticon is also **only** looking at your screen res. RFP is looking at multiple measurements (see above post).

At the end of the day, you need to be the same as RFP. That said, it sucks width-wise on desktops (I actually resize so my inner window is 1366x768 - this is not ideal, but fuck man, I got work to do).

> What's the best option to start Firefox maximized? AutoHotkey?

No idea, cuz I hate maximized windows

**Comment by Atavic** [comment]
On windows, go to Firefox folder, create shortcut, right click on it then select *properties*
On the *target* line, add:

> -height X -width y

So you get, e.g.:

*"C:\Program Files\Mozilla Firefox\firefox.exe" -height 1400 -width 800*

[Firefox Hacks by Nigel McFarlane](https://www.oreilly.com/library/view/firefox-hacks/0596009283/ch01s12.html)

**Comment by Just-me-ghacks** [comment]
Thanks, Atavic! Unfortunately it didn't work for Firefox Portable 60.0.2

**Comment by Thorin-Oakenpants** [comment]
If you want to start Firefox in as big a window as possible, then use the two hidden prefs

```js
/* 4502: set new window sizes to round to hundreds (FF55+) [SETUP]
 * [NOTE] Width will round down to multiples of 200s and height to 100s, to fit your screen.
 * The override values are a starting point to round from if you want some control
 * [1] https://bugzilla.mozilla.org/1330882
 * [2] https://hardware.metrics.mozilla.com/ ***/
   // user_pref("privacy.window.maxInnerWidth", 1600); // (hidden pref)
   // user_pref("privacy.window.maxInnerHeight", 900); // (hidden pref)
```

I use mine to start at 1400x800, and then I use [Window Resizer](https://addons.mozilla.org/firefox/addon/window-resizer-webextension/) to quickly flick to 1366x768. Note: I only use one window, open opening links in a new one will use a 1400x800 (actually its 1400x799 due to bugs when you show your toolbar). Also the position of FF within my screen is remembered, so if I do use another window, I make sure the first one opened is always the last closed.

![windowresizer](https://user-images.githubusercontent.com/16656956/41820669-02ce7d9e-77c5-11e8-832e-8408d02c49ef.png)

I removed all the presets in Window Resizer and set my own one. That 1380x871 is the browser measurements, which gives me my inner window of 1366x768 (compact theme, extra drag space, toolbar enabled)

Not saying this is ideal for you, but at least you can FF to open as large as possible
