### ISSUE TITLE
q: Access-Control-Allow-Origin headers

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#450]
from uBlock-user
`https://github.com/uBlockOrigin/uMatrix-issues/issues/26#issuecomment-399576889`

> Install ModHeader or any HTTP headers manipulating extension and set [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) to `*` in Response Headers. That will no longer throw CORS errors and it will start working back as it was before.

The linked issue was about Facebook's CDN server recently adding a referrer policy setup ... so now it requires uM's `spoof referrer header` exception

I'm not very knowledgeable on these things, but is this a good or bad idea? I mean, it would be nice to be able to keep spoofing referrers if possible like in the above case (no, I do not FB), but what are the ramifications of this - isn't CORS meant to be a good thing for security? Or in a hardened uM/etc setup where all 3rd party is denied by default, would this be a much much lower risk - what is the risk?

Also, how would you add this rule to Header Editor? I need steps man, cuz I am useless with this stuff.

here's my lame attempt at research: https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by claustromaniac** [comment]
> I'm not very knowledgeable on these things, but is this a good or bad idea?

Neither am I.

Apparently, CORS is actually a way to [relax the same-origin policy](https://en.wikipedia.org/wiki/Same-origin_policy#Relaxing_the_same-origin_policy). That policy is what is good for security, while CORS provides some means for clients to access resources from different origins without giving up the security provided by it.

If I understand correctly, modifying that response header to always be `*` is like forfeiting (renouncing? mah engrish sucks) the same-origin policy altogether, which sounds pretty darn dangerous (at least in theory). 

Not sure how dangerous that would be in practice nowadays, though, since the policy became a standard like ages ago. I mean, if I was a bad guy I would have better vulnerabilities to target, I think. My victims would have to use a super outdated browser to be vulnerable to that kind of attack. This shit apparently dates back to the nineties, so it would have to be like... a frickin' relic of a browser.

So, to answer your question: I dunno. Maybe uBlock-user's method is worth the risk if applied in a limited manner. Like, using it only for some sites and such.. and not _everywhere_. That would require a custom function in Header Editor. I can write an example if you want, but I better do it when I'm fully awake.

BTW, I didn't search much, but I found a friendlier explanation of CORS [here](https://spring.io/understanding/CORS).

**Comment by claustromaniac** [comment]
Header Editor rule to allow XHR on www.example.com (didn't test it, but it should work):

**Rule type:** Modify the response header
**Match type:** All
**Execute type:** Custom function

```js
if (detail.type === 'xmlhttprequest' && detail.originUrl.startsWith('https://www.example.com/')) {
    for (let a in val) {
        if (val[a].name.toLowerCase() === 'access-control-allow-origin') { 
            val[a].value = '*';
        }
    }
}
```

I also found [an addon](https://addons.mozilla.org/de/firefox/addon/cors-everywhere/) for this, but it doesn't seem to have whitelist/blacklist support (didn't check myself). It does add a button to toggle it on and off, though.

**Comment by Thorin-Oakenpants** [comment]
AMO: https://addons.mozilla.org/firefox/addon/cors-everywhere/
GitHub: https://github.com/spenibus/cors-everywhere-firefox-addon

Wooo .. almost 18k users

q: you know what I'm talkin' bout! too many extensions modifying headers. I'm clueless on this stuff - I assume the header is sent once, and it contains lots of fields. What happens when too many extensions try to modify the header - eg this one with cors, and HE with etags, etc. If only we had someone like earthlng to help us :)

**Comment by claustromaniac** [comment]
> What happens when too many extensions try to modify the header

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders

> It is possible for extensions to conflict here. If two extensions listen to onBeforeSendHeaders for the same request, then the second listener will see modifications made by the first listener, and will be able to undo any changes made by the first listener. For example, if the first listener adds a Cookie header, and the second listener strips all Cookie headers, then the first listener's modifications will be lost.

In other words: all extensions get to modify the headers. As long as they don't touch the same headers it should be ok.

**Comment by claustromaniac** [comment]
(I edited my post above several times.) I already skimmed that extension's source code. It seems to allow XHR on a per-site basis based on a whitelist when it is "off" and it allows them globally when it is "on".

**Comment by Thorin-Oakenpants** [comment]
I am still non the wiser about any of this, but it all sounds like a bad idea and too messy
