### ISSUE TITLE
How to proceed: Delete storage folder or not?

### ISSUE THREAD

**Issue by Ratator** [ghacksuserjs/ghacks-user.js#455]
Hello everybody

It's about IndexedDB and other local databases on Firefox profiles:

The IndexedDB needs, no question. That's why private browsing is out of the question. Many websites do not work otherwise. **But - is that a possible solution:**

Can I delete the contents of this folder after each Firefox session or not?
C:\Users<username>\AppData\Roaming\Mozilla\Firefox\Profiles<profilename>\storage

I did some research on the web. I have the impression that there is no consensus in the communities.

A small statement in the wiki on this topic would really be important.

Many Thanks.

**Comment by earthlng** [comment]
Hi, well it's certainly possible but probably not the best idea - it depends on your setup. Addons and certain Firefox features also use IndexedDB for storing some stuff. 
Clearing Offline Website Data on shutdown (or manually from time to time if you leave FF open for long periods of time) should delete all the IDB set by websites while keeping all the IDB stuff from Addons and FF internals intact.
I'm sure there are Addons that let you clear IDB periodically or by the press of a button if you set it up that way but I'm not using one of these and wouldn't know which ones to recommend you.
Or you can use something like Temporary Containers and set it up to delete the containers as soon as you close the last tab of a certain domain (or delete it after x minutes in case you re-open it again and want to remain logged in or whatnot)
Or you can use private browsing for sites where you allow JS and which work without needing IDB.

Generally and unless you're super paranoid, deleting it on shutdown is probably the easiest and best solution for most people.

**Comment by Ratator** [comment]
Thank you very much @earthlng and

> A small statement in the wiki on this topic would really be important.

I'm very sorry, I overlooked the 4.1.1 section: https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1.1-Setting-Extension-Permission-Exceptions

**Comment by Thorin-Oakenpants** [comment]
Cookies control access to localStorage and IDB. If you deny a site a cookie, it cannot set any IDB (or localStorage). A strategy of blocking all cookies by default, and then whitelisting will limit the IDB entries. Note that uMatrix allow cookies in but blocks them going out - this is not the same thing.

I would not delete `profile\storage` as it contains several subfolders. The one you want is `default`, but that is also where it stored extension data (those folders starting with `moz-extension+++`). As as earthlng pointed out, this is cleared on close and manually with  OWD checked (and with the new Site Data UI).

> Do I really need an extension to delete my cookies

Personally I do not use one. It depends on your strategy. Most cookies I allow are "allow for session" (and my default is to deny). The problem with extensions is that they cannot properly clear all data (by host or time range) due to API limitations - eg its not enough to remove the cookie and localStorage - what about SW cache, IDB, cache, asmjs, etc (I call this orphaned web data). 

There is a new Quota Manager and Storage v2 coming, where it will unify all the sanitizing - along with numerous fixes (eg "forget a site" now clears all data including site permissions for that site). Here are some tickets

https://bugzilla.mozilla.org/show_bug.cgi?id=1286798
https://bugzilla.mozilla.org/show_bug.cgi?id=1147820
https://bugzilla.mozilla.org/show_bug.cgi?id=1421690

When clearing IDB by host/time-range is done (or even if not, since they can clear IDB on close), then PB mode might even get (and it should) IDB enabled

https://bugzilla.mozilla.org/show_bug.cgi?id=781982

**Comment by Ratator** [comment]
> Note that uMatrix allow cookies in but blocks them going out - this is not the same thing.

What do you think about allowing uMatrix to do everything and just use uMatrix for the cookie curfew?

When googling on the web, etc. uMatrix is a burden. Constantly you do not know if the website is working properly or not. And constantly you have to whitelisten. Do you have a recommended procedure here?

**Comment by 2glops** [comment]
The "howtos" could help :
https://github.com/gorhill/uMatrix/wiki

**Comment by crssi** [comment]
@Ratator I am using uM like you suggested with addition to block lists with the domains that are big no no.
For others I am using uBO.
You should be aware that the best solution is the @Thorin-Oakenpants approach. But it is for "geeks"... for example my folks would be lost in that case.
Well see what will bring storage v2, I guess.

**Comment by crssi** [comment]
TC has also some problems: `https://github.com/stoically/temporary-containers/issues/127`

**Comment by Thorin-Oakenpants** [comment]
^^ as I said

> And even if something wasn't cleared ... the hardened config of TC means even a new instance of a 1st party is re-isolated

I am aware that TC is not perfect (yet). I haven't had a chance to even try it out, because of time issues and my set-up / strategy means I would not benefit from it right now, not even the 1st-party-revisit (I am not behind a VPN for starters). I saw that issue and I wish the OP was clearer with STR.
