### ISSUE TITLE
0850d: autofill

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#478]
earthlng said
> IMO we can also remove `browser.urlbar.autoFill.typed` because `browser.urlbar.autoFill=false` disables `.typed` as well and people who want autofill probably also want typed stuff autofilled. (removing it instead of moving to 9999 for the FF62 diffs)

**Comment by Thorin-Oakenpants** [comment]
Unless someone provides the answers before I get around to checking it out...

```js
/* 0850d: disable location bar autofill
 * [1] http://kb.mozillazine.org/Inline_autocomplete ***/
user_pref("browser.urlbar.autoFill", false);
user_pref("browser.urlbar.autoFill.typed", false);
```

But does `browser.urlbar.autoFill`=`true` and `browser.urlbar.autoFill.typed`=false provide a different configuration? I'll have to look up *exactly* what they do.

I'm more in favor of providing correct info if it allows more customization/flexibility for end users, rather than just removing a pref.

**Comment by Thorin-Oakenpants** [comment]
without me having to look it all up .. can anyone chime in with what is the exact diff between these two? I mean .typed I get, but how else do you add chars to the urlbar except by paste? Or am I missing something here. eg pasted is same as "typed" and I'm way off the mark? (am lazy today, someone fill me in)

**Comment by Thorin-Oakenpants** [comment]
^^ cheat sheet : https://www.webfx.com/tools/emoji-cheat-sheet/

**Comment by Thorin-Oakenpants** [comment]
also, earthlng is suspiciously absent ... makes suggestions and fucks off for weeks on end, or ignores it afterwards. I hope this doesn't turn into another "disable IPv6" scenario :trollface: I mean, that one's been going for months and I have to clean it up

**Comment by earthlng** [comment]
What is it with the threatened cruelty towards animals here recently?
[E A R T H L I N G S](https://www.nationearth.com/) - watch it if you can stomach it, I dare you ;)

Okay back on topic ... the real question here is would anyone want autofill enabled for everything *except* **typed** stuff? I don't think so but whatever, we can just wait until we do the 62 diffs and move it to 9999 if you prefer that.

> makes suggestions and fucks off for weeks on end, or ignores it afterwards.

ultimately it's **you** who makes all the final decisions around here. I just make proposals and if you like them, great, and if not that's fine too. In this case I made my point to which you replied "I'll have to look up exactly what they do" because "I'm more in favor of providing correct info ... for end users" so the ball is in your corner.

**Comment by Thorin-Oakenpants** [comment]
> ultimately it's you who makes all the final decisions around here.

Sure. I drive the direction. But ultimately, because I value yours (and other people's) input, and always consider any suggestions (i.e I am not a closed book and nothing is set in concrete- I will always reconsider), and because many minds are better than one, etc ...  **you** have great power, and with that comes great responsibility. In fact, at times, I just OK changes because of your track record.

Anyway, you know I luv you :kiss: .. and we haven't resolved anything with this. So I'll do some thinking and try to understand what's going on

**Comment by Thorin-Oakenpants** [comment]
browser.urlbar.autoFill.typed - I think we'll just move this to deprecated with 62 diffs, so we have a record for when people ask about it, and the bugzilla for it's removal in the sticky etc
