### ISSUE TITLE
Can not open any Gmail message if I use Firefox browser with the latest settings

### ISSUE THREAD

**Issue by silviuapostolescu** [ghacksuserjs/ghacks-user.js#487]
Hi guys,
Please help/guide me to find why I can't open any Gmail message when I use Firefox browser with the latest settings.
When I try to open a message it says "is loading" and nothing happens after not even I reload it/F5.
If I use GoogleChrome (in which I avoid to use any e-mail or online banking account) it works.

**Comment by silviuapostolescu** [comment]
I deleted Profile and I add the latest files from you and now it works as
you see.
Ty again.

Silviu Apostolescu

2018-08-16 13:22 GMT+03:00 crssi <notifications@github.com>:

**Comment by earthlng** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting

> Before you go on to the laborious task of manual troubleshooting you should try our [troubleshooter script](https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/scratchpad-scripts/troubleshooter.js) first. In many cases it will be able to either directly identify the culprit or at least narrow it down to a more manageable number of prefs for manual troubleshooting. You can just run the script and follow the instructions but we strongly recommend to watch the [demo video](https://anonfile.com/6eZ9v9d9b6/troubleshooter_vid.zip) first (webm, 62mb, 16m26s).

In the demo video I recommended to do the testing in a fresh profile but you can also just run the script in your main profile if you suspect that the user.js is causing the problem.

> I deleted Profile

I guess you don't have any extensions? Deleting a profile seems like a pretty extreme way to solve a problem IMHO. If you still have the original profile around maybe you may want to experiment with my troubleshooter script and see if it's able to identify the problem for you. Just in case you run into another problem with another site later on, you'll already know how to better deal with it instead of having to delete your whole profile.

Either way, I'm closing this because apparently you were able to fix the issue.

**Comment by silviuapostolescu** [comment]
Ty.
You are right.
I chose the extreme way after I checked many culprits that are known (I
have a list in this respect). And I became upset and I did it.
I also recycled the old profile.
Regarding extensions, I have only three: Ublock origin, https everywhere
and duckduckgo privacy essentials. It took me 1 min. to reinstall them.
Now I'm going to watch the demo video in order to learn how to use the
troubleshooter script.
Thank you again.

Respectfully,

Silviu Apostolescu

2018-08-16 15:40 GMT+03:00 earthlng <notifications@github.com>:
