### ISSUE TITLE
[General]User.js version vs Firefox version

### ISSUE THREAD

**Issue by bitpixl** [ghacksuserjs/ghacks-user.js#488]
Hi,

I'm currently using (the latest stable release of )Firefox 61.0.2 and am wondering if the latest updated version User.js is the one to (always) use? Your latest User.js version is 62-alpha, so does this mean it's for the latest Firefox 62.x (alpha) build? 

I know with every Firefox release about:config entries get changed/removed, so that got me questioning if using the latest User.js version is actually the way to go or that it's best practice to keep using the User.js 61 version with Firefox version 61.x. (This is what I'm doing atm)

**Comment by Thorin-Oakenpants** [comment]
No, our alpha-beta naming has nothing to do with Mozilla

62-alpha just means we've archived off a legacy 61 "final" release and are working on 62 changes

We don't do any changes that would "harm" the current stable (61) until a day or so out from the next release (62) at earliest (eg moving items to deprecated). Any new things we add should have no effect (but we're mindful of it).

When we've covered all the diffs for 62 etc, we do a `62-beta` release - this is usually a couple days after FF's stable release. We continue to do things in this stage (tweaks etc) until we archive it off and start the next cycle

Does that make sense. My explanation is a bit scrambled, sorry.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/issues/54 - original setup, but we now use an additional stage

- `61` = archived off as a release
- `62-alpha` = means we're working on adding/editing/removing stuff *for when 62 lands*
- `62-beta` = means we've finished covering all the "changes" from diffs and *it's ready for 62 stable, which was just released*
   * we'll continue to make changes, as we come across them in this stage, which usually lasts 4 or 5 weeks
- `62` = archive it off as a release
- `63-alpha` = change to this on the next commit, since 62 was done as a release

nothing ever really happens in the 61, 62 etc stages. They are changed to that for ONE snapshot, to make a release. It's always alpha (working on it) or beta (ready for stable release)

**Comment by bitpixl** [comment]
Hi Thorin,

thank you for explaining things, I understand your release cycle now.

Pants came back on (trying to understand your humor as wel :P) when you said "We don't do any changes that would "harm" the current stable (61) until a day or so out from the next release (62) at earliest (eg moving items to deprecated). Any new things we add should have no effect (but we're mindful of it)."

So there's basically no further changes for firefox 61.x when you release the final 61 (archive) version? So what happens if a major security flaw is found in FF 61.x today and then fixed with a new release of FF 61.x? Will you update the 61 archive? or put it in the 62-alpha?

**Comment by Thorin-Oakenpants** [comment]
> So there's basically no further changes for firefox 61

Correct. 61 is finished, over, ended .. we're already on v62.*

> if a major security flaw is found in FF 61.x today and then fixed with a new release of FF 61.x? Will you update the 61 archive? or put it in the 62-alpha?

Assuming it had a pref that **needed** changing in order for users to be **safe**, I guess in this case I would do a 61-rev1 release (and maybe remove the 61 release - depends on how serious it is). But it would just be a snapshot of the user.js as it is right now, because the raw master is effectively always in sync with stable releases (even though the version number in the js says 62-alpha)

I doubt this scenario would ever come up. If it did, we'd come up with a plan
