### ISSUE TITLE
HTTPS allows user tracking by OCSP Servers

### ISSUE THREAD

**Issue by Atavic** [ghacksuserjs/ghacks-user.js#507]
[Here](https://github.com/ghacksuserjs/ghacks-user.js/issues/506) the Dailystar site is linked. As site opens, the browser queries an SSL Server (Amazon CloudFront).

> The key here is that many SSL certificates have a one-to-one relationship with a specific web site (i.e. not wildcard certificates), so a query to an OCSP responder for a web site certificate essentially tells the certificate issuer that you are accessing that site.

See: [zscaler article](https://www.zscaler.com/blogs/research/those-who-know-where-and-when-you-surf)

As the page is loaded, CSS Files are also fetched through HTTPS via CDN: Cloudfront is queried a second time and also 1e100.net (Alphabet Inc.) is queried. So Amazon and Google know that the user opened this site at a specific time.

DNT respecting sites, if delivered through HTTPS, make DNT useless:
https://cabforum.org/pipermail/public/2017-June/011346.html

IMHO HTTPS must be used only when the request include passwords and other personal information, otherwise big actors will track users browsing with ease.

Related to: https://github.com/ghacksuserjs/ghacks-user.js/issues/102

**Comment by KOLANICH** [comment]
OCSP stapling prevents this.

**Comment by Atavic** [comment]
I assume stapling goes by browser's session, so it's a mitigation IMHO

> server support is required

And admins must enable it, e.g. digicert SSL Certificate Checker says:

> Github OCSP Staple: Not Enabled

Related: https://github.com/ghacksuserjs/ghacks-user.js/issues/267
https://www.grc.com/revocation/ocsp-must-staple.htm

**Comment by ArchangeGabriel** [comment]
Yes, HTTPS has privacy implications currently, because of OCSP. But indeed OCSP stapling is solving the issue. It will takes time before this is generalised, but not using HTTPS is way worse: it means any machine on the network between you and the website or service you’re using knows everything you do. I’d rather much prefer some CAs to known that I went to this website at this time than anything I’ve just described.

One other thing you could do is disable OCSP while waiting for OCSP stapling to be widespread. Or disable it only when there is no stapling. But not sure if that is currently possible.

Also regarding ressources delivered by CDNs, this is a different topic. Either disable fonts/js/css (generally or through uMatrix for instance) and/or use Decentraleyes.

**Comment by Thorin-Oakenpants** [comment]
[Atavic said]
> IMHO HTTPS must be used only when the request include passwords and other personal information, otherwise big actors will track users browsing with ease

Did you really just say that? Almost everything you do on the internet is personal - do you really want your ISP knowing exactly every single page you visited rather than just the domain. And besides, one of the points of HTTPS is that you know the data sent and received hasn't been tampered with. Case in point: blocklists as Francois pointed out elsewhere

[ArchangeGabriel said] 
> Also regarding resources delivered by CDNs, this is a different topic. Either disable fonts/js/css (generally or through uMatrix for instance) and/or use Decentraleyes.

:+1: You already have tools to control your 3rd party shit.

---

OCSP stuff: as per the user.js (see `1211`), there is a trade-off here with privacy and security. If you want OCSP, then you have to connect to/ trust a 3rd party. 
```
 * It's a trade-off between security (checking) and privacy (leaking info to the CA)
```

Not sure what the point of this issue is. You have to connect to DNS to resolve IP addresses. You have to rely on a VPN or your ISP or carrier for internet. You have to rely on GPS for using real time maps on your phone etc. There's generally always a 3rd party. The internet was never designed with privacy (or security for that matter) in mind from the ground up. Ever since then, it's been bandaid after bandaid.

If your threat model requires it, use TBB.

**Comment by KOLANICH** [comment]
@Atavic, https://habr.com/post/247465/

**Comment by Atavic** [comment]
I see [valdikss](https://github.com/ValdikSS/GoodbyeDPI) created a solution [here](https://lists.cpunks.org/pipermail/cypherpunks/2015-January/006326.html). I'm following his GoodbyeDPI Repository, but I have barely scratched its surface.
