### ISSUE TITLE
screenshot feature

### ISSUE THREAD

**Issue by horusra** [ghacksuserjs/ghacks-user.js#512]
Is it true that this kills the screenshot feature? because I'm using the ghacks-user.js and I can't get the screenshot feature to show up even. 

Anyone know what I need to change to restore the screenshot feature?

I doubled checked and at least: extensions.screenshots.disabled = false already

**Comment by earthlng** [comment]
> Is it true that this kills the screenshot feature?

no, we don't disable Screenshots by default and never have

Maybe you deleted the screenshot system addon from the features folder in the install directory?
If that's not it, search about:config for `screenshot` and if necessary reset those prefs.

If that's not it either then maybe you're just looking for the icon in the wrong spot. AFAIK it now uses a page action icon in the address bar instead of a "normal" icon in the toolbar like most extensions.

**Comment by horusra** [comment]
yeah sorry, my firefox profile was borked
