### ISSUE TITLE
HTTP UserAgent cleaner (extension, XUL/XPCOM)

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#517]
for those of us running a FF fork that supports the older XUL/XPCOM extensions, i think HTTP UserAgent cleaner might be worth a serious look

this is not a simple UA cleaner, so don't be fooled by the name

it's no longer being developed for FF because of the limits imposed by the WebExtension API, though it should work with the Moon, Waterfox and also [Basilisk](https://www.basilisk-browser.org/), which i just now learned of - apparently this is a Pale Moon project that supports WebExtensions (all of my extensions installed fine it appears)

the advantage i see in HTTP UserAgent cleaner is that it makes it easy to toggle the static settings in the ghacks prefs config and since it works mostly at the header level, i believe one can avoid adding exceptions to the ghacks prefs (untested) - it can also potentially eliminate the need for several other extensions dealing with things like canvas, UA, cookies/storage, WebGL, push, fonts, web sockets, SSL, https, etc.

if i remember correctly, HTTP UAC works at the header level, like i said, and so it does not interfere with other extensions or prefs - so for example if you block cookies at an extension, browser prefs, or user.js level, but allow them in HTTP UAC, they will still get blocked and will not override the settings in the browser

regarding Basilisk, it appears from their [release notes](https://www.basilisk-browser.org/releasenotes.shtml) that they are keeping up with the latest security patches - i don't know if Waterfox does this? - there are also packages for it in the AUR repo

links for HTTP UserAgent cleaner...

* [AMO](https://addons.mozilla.org/en-US/firefox/addon/http-useragent-cleaner/) (depreciated)
* [website](http://huac.8vs.ru/index-1538066603-perm.htm)
* direct download (xpi): http://huac.8vs.ru/2.3.4-b05.xpi

there is no real EN documentation that i am aware of - with the """help""" (you will note the triple quotes) of the dev, i wrote an EN doc covering the add-on as thoroughly as i could (was on my site), but given the language barrier and the fact that he was so difficult to deal with i eventually canned the extension and deleted everything related to it - that said, i'm trying it out again on Basilisk 

apparently he plans on porting it to a WebEx if and when the required API's are made available

**Comment by atomGit** [comment]
oh shit, i see this should've gone here...
https://github.com/ghacksuserjs/ghacks-user.js/issues/492

sorry - can u move?

**Comment by Atavic** [comment]
> I don't know if Waterfox does this? 

According to the blog, Waterfox is patched with the ESR security fixes.

**Comment by Thorin-Oakenpants** [comment]
OK, lets get this over and done with .. with all due respect <sup>don't anyone get upset</sup> .. here is my position, and by extension (pun intended), this repo's stance

I do not care for FF forks (except TBB) for all the obvious reasons (do you really need me to list these?). My information may be slightly out-of-date, as I am not interested in wasting my time following them.

Waterfox is nothing more than a slightly tweaked FF (at least up until they stopped at 56 as a base, and since then it is only more divergent, also who gives a shit about legacy extensions - see next paragraph). Palemoon is so behind the curve it's re-DiCK-ulous, and there are a lot of dubious decisions IMO (I do not have the full picture, but take for example the removal of e10s and sandboxing - maybe it's because the code is so divergent, NFI and I don't care). Why would you run such a piece of junk? Basilisk can also go in the PM pile - why would you trust your most important <sup>probably</sup> piece of software in your system (you know, the one that connects to the internet all the time, and handles almost ALL your online shit) with a "one-man-band" (note the speech marks) unvetted browser. If you're willing to do this, then I have two rocks to sell you - they keep tigers away, very valuable.

Secondly, I do not care for legacy extensions. Except for a couple of things (eg NoRedirect, extensions able to see/control other extensions etc), nothing is lacking in FF except what I term workflow items - and my answer to that, is to work around them .. adapt or die. Some may come back, some definitely won't. What are you going to do, stick with legacy BS all your life?

I removed all the legacy extensions listed on the wiki. I and this repo do not care for FF forks and legacy BS - end of story.

/end of rant / lesson

Now, before anyone gets all upset, remember this -> :kiss: :heart:

**Comment by KOLANICH** [comment]
>I removed all the legacy extensions listed on the wiki. I and this repo do not care for FF forks and legacy BS - end of story.

I guess we need a list of extensions which should be pkrted to WebExt. Maybe exploiting WebExt experiments mechanism.
