### ISSUE TITLE
2701: cookieBehaviour has new descriptions and a new value

### ISSUE THREAD

**Issue by bogachenko** [ghacksuserjs/ghacks-user.js#526]
I updated to FF63
There appeared a new function blocking trackers cookies. The possibilities of FF have expanded, however you have the [old description](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js#L1345) from FF62.

that's what i found
`0=Accept cookies and site data; 1=Block third-party cookies; 2=Block all cookies; 3=Block cookies from sites not visited; 4=Block third-party trackers`

so when will we fix it?

**Comment by Thorin-Oakenpants** [comment]
> so when will we fix it?

We're in 63-alpha right now. It's been 6 days since Firefox v63 was released to stable - ~~we're~~ I'm a bit slow this time round (I am super busy and almost can't be arsed anymore, TBH), we tend to have it done a little quicker -> when we finish the diffs from 62->63 (and other things, like AS no longer being a system addon) etc then we do a 63-beta release. The beta is the release **ready** for that version (i.e is we covered all the diffs). Don't get me wrong though, the user.js is always being worked on.

Thanks for the heads up :+1: 

so others don't have to look it up, current  `2701` is (relevant lines only):
```js
/* 2701: disable 3rd-party cookies and site-data [SETUP]
 * 0=allow all 1=allow same host 2=disallow all 3=allow 3rd party if it already set a cookie ***/
user_pref("network.cookie.cookieBehavior", 1);
```

**Comment by bogachenko** [comment]
okay, close the thread

**Comment by earthlng** [comment]
PR: https://github.com/ghacksuserjs/ghacks-user.js/pull/527

**Comment by earthlng** [comment]
thanks @bogachenko, I totally forgot about that change

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/f8fc465d0aa30fc66282095199c892dce104358c
