### ISSUE TITLE
update/cleaner scripts - suggestions

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#529]
1) updater script shouldn't re-download identical version of local user.js without prompting
2) might be nice to add another choice to skip the update check and just append user-overrides - i use the script often for that myself cause i'm lazy
3) suggest changing the names of updater and prefsCleaner so they are positioned first in a file browser by prepending them with an underscore - makes them easier to spot :) -or- rename them userjs-updater and userjs-cleaner to stick them next to user.js

btw, i heavily updated my [FF config guide](https://12bytes.org/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs) - appreciate any feedback anyone might have - leave it in comments (don't have to log-on)

peace

**Comment by claustromaniac** [comment]
> updater script shouldn't re-download identical version of local user.js without prompting

Can you be more specific?

The updater.sh downloads the user.js once to check the version and then shows this prompt:
```
Continue Y/N?
```
...and finally downloads the file (again) to disk. Is that what you are referring to?

> might be nice to add another choice to skip the update check and just append user-overrides - i use the script often for that myself cause i'm lazy

Indeed. :thumbsup: I'll try to do this as soon as I can if @earthlng agrees. I'll also summon @overdodactyl and @ema-pe, just in case.

> suggest changing the names of updater and prefsCleaner so they are positioned first in a file browser by prepending them with an underscore - makes them easier to spot :) -or- rename them userjs-updater and userjs-cleaner to stick them next to user.js

The URLs to the raw content would change, and that would break the self-update feature and the links on the wiki (and everywhere else). You can rename your local copies yourself, though. The Windows version of the updater should work no matter what you name it, and the Linux/Mac version only needs to be `updater.sh` if you use the self-update feature, otherwise you can rename it.

**Comment by atomGit** [comment]
>>  updater script shouldn't re-download identical version of local user.js without prompting
> 
> Can you be more specific?
>
> The updater.sh downloads the user.js once to check the version and then shows this prompt:

ah, right - it needs to grab the script to check the version - probably isn't worth mentioning give it's a minor issue, but what i would do is just keep a text file in the repo with a version string in it and have the updater grab that, compare versions, then offer a choice if a new version is available, assuming you can do a compare in a script

thanks!

**Comment by overdodactyl** [comment]
>what i would do is just keep a text file in the repo with a version string in it and have the updater grab that

Since both updaters are under 10 KB (4.1 for *nux, 9.46 for windows), I don't think the benefits of keeping a versioning file would be worth it for the following reasons:

- It clutters the main repo
- Whenever an update is made, the version would have to be changed in multiple locations.  In my mind, this is unnecessary maintenance and error prone (unless we write *another* script to automate version bumps, but again, not worth the effort in this case I don't think)

**Comment by ema-pe** [comment]
Thanks @claustromaniac for the ping!

> 1. updater script shouldn't re-download identical version of local user.js without prompting

I agree with you. The script should download the `user.js` to a temporary file (using `mktemp`), and then compare the local version with the downloaded version. But the `user.js` itself is a small file, so I don't think that this way worth it.

> 2. suggest changing the names of updater and prefsCleaner so they are positioned first in a file browser by prepending them with an underscore - makes them easier to spot :) -or- rename them userjs-updater and userjs-cleaner to stick them next to user.js

This would breaks existent scripts and all links pointing to them. It's a terrible idea!

**Comment by earthlng** [comment]
1. has already been answered: it needs to grab the user.js to check the version
2. just run `cat user-overrides.js >> user.js`. I don't think we need an option for that
3. we're definitely not renaming the files
