### ISSUE TITLE
FYI: TLS1.2 + 1.3 SuperCooKey

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#536]
Article: https://www.privateinternetaccess.com/blog/2018/11/supercookey-a-supercookie-built-into-tls-1-2-and-1-3/
Reddit: https://old.reddit.com/r/firefox/comments/9xd0d5/supercookeys_a_supercookie_built_into_the_tls_12/

Still digesting it...

Edit:

> To mitigate this, you need to be able to disable both TLS 1.2 and TLS 1.3 session resumption. There are four settings related to this scenario that we have to change to fully address the problem.
> 
> security.ssl.disable_session_identifiers (hidden feature)
> security.ssl.enable_false_start
> security.tls.enable_0rtt_data
> privacy.firstparty.isolate

- :heavy_check_mark: `1203` : security.ssl.disable_session_identifiers = true
- :x: security.ssl.enable_false_start = false
- :heavy_check_mark: `1205` : security.tls.enable_0rtt_data = false
- :heavy_check_mark: `4001` : privacy.firstparty.isolate = true

**Comment by Thorin-Oakenpants** [comment]
OK, @tomrittervg says (via email) the article is so riddled with errors that he doesn't even want to begin debunking it for fear that he'll have to correct em all

**Comment by tomrittervg** [comment]
The crux of it - that TLS features like 0rtt and Session Resumption can be used as persistent identifiers - is true.  But FPI isolates them. (And doesn't block requests as the article says!) And Private Browsing Mode also has the expected protections. 

False start has nothing to do with persistent identifiers.

**Comment by earthlng** [comment]
FPI isolating them is great but there are other issues with 0rtt, namely replay attacks and breaking forward-secrecy. Even passive attackers without the ability to inspect https traffic can do replay attacks according to the [DEFCON presentation](https://www.youtube.com/watch?v=ZY-MYd_OvwE) about 0rtt.

I really hope mozilla won't remove that pref any time soon (or really EVER) because "it's been enabled for x releases"

**Comment by Thorin-Oakenpants** [comment]
> But FPI isolates them

I totally get this, but FPI doesn't protect from repeat first party visits. It would be nice if SSL sessions (and all related data) expired (outside of closing FF, or closing the last PB mode window) after x minutes or seconds, instead of the current 2 days ... TWO DAYS :-(

**Comment by JohnWooo** [comment]
According to [this article](https://arxiv.org/abs/1810.07304) (see 2.3 and figure 2.c), do I understand correctly that the 1-RTT variant of TLS 1.3 session resumption allows tracking exactly like the session resumption mechanisms anterior to TLS 1.3 that used session IDs or session tickets ?
Is it also correct that contrary to those anterior tracking mechanisms, that could be disabled by setting
security.ssl.disable_session_identifiers = true ,
there is no about:config pref to disable this 1-RTT TLS 1.3 session resumption tracking ? Or does this pref work for TLS 1.3 too ?

**Comment by Atavic** [comment]
The PDF link [here](https://old.reddit.com/r/firefox/comments/9xd0d5/supercookeys_a_supercookie_built_into_the_tls_12/e9rfe0f/) gives an idea of how this feature can be weaponized by holding session tickets for 60 days (as Yahoo and Yandex do).

It's on page 6. A common abuse from cookies to JS to any new API...

**Comment by Thorin-Oakenpants** [comment]
TC (temporary containers) should mitigate this (but I'd have to check)

**Comment by Thorin-Oakenpants** [comment]
> by holding session tickets for 60 days (as Yahoo and Yandex do)

Data is session only. Not many people would have their browser open that long :) or use Yahoo :trollface:

**Comment by JohnWooo** [comment]
@Atavic I meant section 2.3 of the article I linked, but yes, the one about TLS version 1.3.
I was talking about tracking by the server using 1-RTT TLS 1.3 session resumption as a supercookie, not about forward secrecy and other cryptographic improvements of TLS 1.3.

**Comment by Atavic** [comment]
Ok. As noted by Ritter above "supercookie" isn't the best term, BTW I generally agree with respecting Forward Secrecy in TLS handshakes. RTT doesn't do that.

RTT is being promoted for faster connections and lower server loading, but most of that improvements are really negligible. 

Old issue: https://github.com/ghacksuserjs/ghacks-user.js/issues/516

**Comment by JohnWooo** [comment]
> As noted by Ritter above "supercookie" isn't the best term

I used this term because TLS session resumption can be used as session cookies even when session cookies are disabled ; maybe some people reserve the word for tracking that persists across sessions ?

> BTW I generally agree with respecting Forward Secrecy in TLS handshakes. RTT doesn't do that.

According to the article I referenced, second half of section 2.4, TLS 1.3 0-RTT resumption does never respect forward secrecy, while TLS 1.3 1-RTT resumption can optionally (which may not be enough).

To clarify my question : the article in the OP says that the 1203 pref disables session resumption for TLS<1.3, and 1205 disables 0-RTT resumption for TLS 1.3, but nowhere it talks about how to disable 1-RTT resumption for TLS 1.3, that allows session tracking by the server (and may break forward secrecy). And considering this article contains errors apparently, I don't even trust it when it says that the 1203 pref is limited to TLS<1.3, hence my question.

I asked Mozilla too here:
https://www.reddit.com/r/firefox/comments/9xypc9/question_about_tls_supercookies_blocking/

**Comment by Thorin-Oakenpants** [comment]
FYI: https://trac.torproject.org/projects/tor/ticket/28536

Given TBB uses FPI (and PB Mode) and uses Tor (changing circuits etc), I doubt this is in their wheelhouse

**Comment by StanGets** [comment]
@tomrittervg wrote,

> False start has nothing to do with persistent identifiers.

But what what does false Start have anything to do with? I've searched and couldn't find an explanation of `security.ssl.enable_false_start`, hardly an old article mentioning that Google had abandoned it at the time because it figured out that too many servers weren't responding correctly... that was years ago. Now, in 2018, what exactly does SSl False Start perform? Why enable it (default), why disable it (if any reasons)?

**Comment by Atavic** [comment]
[This document](https://tools.ietf.org/html/draft-bmoeller-tls-falsestart-00) specifies an optional behavior of TLS implementations, dubbed False Start: It's one of the google pushes included in [spdy](https://www.chromium.org/spdy), precursor of HTTP/2.

**Comment by StanGets** [comment]
Thanks @Atavic , no idea why I missed the link you provide when searching, or maybe had I ignored it too quickly when noticing the document is dated June 2010.

You write,  

> It's one of the google pushes included in spdy, precursor of HTTP/2.

SPDY replaced by HTTP/2 .... any sense in wondering if disabling the latter leads to an irrelevant SSL False Start?

I'm guessing most of you guys are beyond this quest of definitions. I'm not refueling the debate, only trying to better understand. The IETF document brings some answers. Thanks again.

**Comment by tomrittervg** [comment]
False Start is a hack-optimization for TLS 1.2 and below which sends application data before the TLS Handshake is completed. It has some compatibility problems, because this behavior goes against spec, but it works in the overwhelming percentage of cases. However I believe Google still disabled it for the vast minority of problems it caused.

The security concern is that an attacker could downgrade the negotiation so you wind up encrypting data with a weak ciphersuite that could lead to decryption. Thus false start is prohibited if a weak cipher is negotiated. 

From memory, TLS 1.3 codifies false start into the normal operation of the protocol.

Unless you are facing compatibility problems with a weird network appliance that can't handle false start; there is no reason to disable it.

**Comment by Atavic** [comment]
> dated june 2010

That's the draft, the actual RFC is [here](https://tools.ietf.org/html/rfc7918)

> there is generally no way to be sure that communication with the expected peer is indeed taking place during the False Start.

...from page-6 above.

> wondering if disabling the latter leads to an irrelevant SSL False Start?

False Start applies to TLS Protocol Version 1.2 and will be deprecated in TLS 1.3 while HTTP2 applies to TCP connections: they are different protocols.

**Comment by StanGets** [comment]
Thanks @tomrittervg ,

> Unless you are facing compatibility problems with a weird network appliance that can't handle false start; there is no reason to disable it.

I hadn't encountered any obvious compatibility problem but I'm disabling it nevertheless `pref("security.ssl.enable_false_start", false);` because your very explanation, as I understand it, confirms what I perceive as a speculative hacking : "it works most of the time, let's keep it" or not, according to Google. You do state yourself that there is a security concern, maybe negligible (speculation) but not false.

Or I may be exaggeratedly technically idealist : nothing being perfect the idea is to allow a good ratio of advantages/risk. I have SSL False Start disabled and perceive no slowdown. In the same way I perceive no slowdown with http2 disabled. My feeling is that connection quality depends at 90%+ of one's OS connection quality (speed, ping ...)  and much much less on these hacks which often hit security for the sake of a hypothetical thousands of a second sped gain.
