### ISSUE TITLE
getting folks involved

### ISSUE THREAD

**Issue by claustromaniac** [ghacksuserjs/ghacks-user.js#539]
I started this small discussion in #528 and I was going to reply there, but since my reply got somewhat long, I decided to open a separate thread to avoid hijacking that one (further).

[Le me said:](https://github.com/ghacksuserjs/ghacks-user.js/issues/528#issuecomment-439502005)

> what do you guys think about asking for more feedback? Adding some lines in the wiki and/or maybe in the updater scripts might help with that.

[Le :jeans: replied:](https://github.com/ghacksuserjs/ghacks-user.js/issues/528#issuecomment-439506039)

> Not sure re asking for contribs/feedback. I def wouldn't add anything to the updater scripts (without looking I assume it has a link to this repo). The user.js already lists this repo (and surely people can see that its github and they can open issues and ask questions).

My current reply:

I was thinking mostly about giving #438 more visibility, but reminding folks that feedback in general is welcome is as simple as adding a single line here and there anyway. 

My reasoning is the following: this user.js + wiki + scripts/tools are all ~~great~~ **awesome**:exclamation: by themselves, but the discussions we have here can be super informative, IMO. I'm glad I'm curious because that got me involved to an extent (and I've honestly learnt a lot from everyone else involved), but if I wasn't as curious, I could have missed on that opportunity altogether. Those who land [here](https://github.com/ghacksuserjs/ghacks-user.js) can just move to the wiki from there, or simply DL the files and leave, never bothering to take a look at the issues. I wouldn't be surprised if many did just that. Encouraging folks to get involved might be worth it, that's all I'm saying.

Similarly, more (unnecessary) recursive links on the wiki would likely get more people to read the stuff. Links are more powerful tools than it seems. Actually, *there are* already some unnecessary (but useful) links in there, but there could be more. When I have time, I can help with that if you want. I can mirror the wiki on my fork and do some changes there to show you what I'm talking about.

Anyway, it's just something that crossed my mind. Feel free to close this issue if you disagree. It's OK with me if you are feeling lazy and don't even want to reply :thumbsup:

**Comment by Thorin-Oakenpants** [comment]
@earthlng check yur mail

**Comment by earthlng** [comment]
Sounds great. I'm glad you were curious and found us here in the 1st place because your contributions have been (and continue to be?) really awesome. If we could find a few more guys or gals like you that'd be great

**Comment by Thorin-Oakenpants** [comment]
Every ~~good~~ great repo needs a :cat2: I echo earthlng's sentiments. Outstanding contribs and a little something for you, if you want it, in your email. No pressure :) but you'll be able to do MOAR, if you want. It's not compulsory. I trust you, and your sound judgements :kiss:

**Comment by StanGets** [comment]
@claustromaniac wrote 

> Encouraging folks to get involved might be worth it

The intention is worthy but I'm not sure encouragements, incentives are what will motivate a user to dig any deeper than what is own, personal temperament leads him to. My opinion is that those among us, the non-savvy, who were sufficiently open-minded, curious to find this great _Ghacks-user.js_ tool, then to read it without applying it blindly and discover the links to this GitHub repository are unlikely to be over-motivated, encouraged : you can inform people but I don't think you can take them by the hand towards a better world. This said, I do believe in sharing the availability of tools such as _Ghacks-user.js_ , whenever the opportunity, in life, on chats, forums, blogs, but that being done it'll be a personal choice to travel with the handed ticket.

**Comment by Thorin-Oakenpants** [comment]
>  you can inform people but I don't think

So what you're trying to say is ~~*"You can lead a whore, to culture but you can't make her think"*~~ *"You can lead a horse to water, but you can't make it drink"* ?

**Comment by StanGets** [comment]
I'm trying to say is that IMHO informing is valid when proselytism is less or not. If someone asks, inform; if you feel there's an opportunity to inform regarding the context then inform. But after that it's up to the winner to validate or not the ticket, which is good if you consider you might be mistaking and bad if you're convinced of being right. Beyond that, you don't change people, but you can inform, for sure.

**Comment by Thorin-Oakenpants** [comment]
^^ yeah, I got all that. I was just injecting some humor and my spin on it (the quote by the way, is from [Dot Parker](https://en.wikiquote.org/wiki/Dorothy_Parker), but the word used was *horticulture*). I always aim to just inform. The whole browser & web tech thing is so complicated and vast, and so many options available, that no one size will ever fit all, which is why I've pushed the point that it's a template, and tried to keep explanations as simple as possible (and provide relevant links). Information is power. And we encourage users to use overrides. On a personal level, I generally don't trust anyone or anything, and always want to check it out myself (which ironically often means I have to eventually trust someone!)

**Comment by StanGets** [comment]
Humor is both a reference to good sense quite often and good medicine for all. When some wonder if angels have a sex I rather wonder if they have humor.

Anyway, concerning this balance you implicitly evoke between complexity, understood then explained and considering settings which may be appreciated differently from one user to another (commented settings and explained why they are commented) no doubt -- and everyone know it -- you're doing a great job.

Echoing the personal level I'm as well so far from naivety that I sometimes flirt with suspicion. There again the quest of the right balance. Confidence is good, when deserved, relaxes. There are still people, places worth our confidence, fortunately.

I'm tuned here, more as a reader than actively because I learn far more than I could otherwise share.
Appreciated and, nowadays, worth being emphasized.

**Comment by claustromaniac** [comment]
@:jeans:,

First, I have to say I'm humbled by your invitation, and I'm grateful.

That being said, I have some questions:

1. Is it just so I can edit the wiki and such? If that is the case, wouldn't it be better to allow everyone to edit the wiki?
2. Is it supposed to feel like I'm somehow walking into a trap? Some part of me can already feel the :trollface:'s coming...
3. If there is some intent to motivate me to contribute more, is it not likely for this to backfire and make other collaborators/contributors feel underappreciated?
4. Am I overthinking it?

...and, finally:

5. Do you understand and accept that the first thing I'll do as a member is to add a new [NEEDS JESUS](https://github.com/claustromaniac/detect-cloudflare-plus/issues/15) label?

P.S.: I must admit that not getting locked out of discussions as easily anymore is tempting... :trollface:

@StanGets,

I concur.

Maybe my initial choice of words wasn't ideal. I was merely thinking of it as I believe a web developer would: in practical terms. Redundant and/or recursive links simply give visibility and ease navigation (when used well). That to me is an indirect way of informing. It's merely a matter of design, really. I didn't specify how I'd do this, but I wasn't thinking of adding any long or overly wordy statements. On the contrary, well done recursion leads to less repetition, which leads to more compact information overall.

In my opinion, such efforts would be wasteful in many other repositories because not all repos share the same dynamic sort of discussions. It seems to me that GitHub users are generally expected to open issues and otherwise interact with each other mostly to provide feedback on the project(s) in question, but in this repository there are many *FYI* discussions that I think many can easily miss because it's simply not something they would normally expect to see. That's what I was trying to get at, for the most part.

**Comment by StanGets** [comment]
@claustromaniac I do understand your idea of bringing some sort of signposts in an area which adds the imperatives of the owner (GitHub) to the relative organization possibilities of the tenants so to say. I pointed out users motivations rather than the pertinence of your idea.

You know the place and the area, not me. I'm a basic user and read as I wrote above rather than actively participating. You're far more entitled than me to be legitimate when proposing and it's by the way none of my business. As I said I have in mind users, basic users in the same way your idea was to facilitate their travel here, but IMO there's enough organization for even a basic visitor as myself to make his way... provided a minimum of efforts and i'm not sure more "panels" would bring much more. An example : myself, when in another thread I had asked for information regarding an extension which was already discussed in the very thread... so I know what I'm talking about!

Organization is tedious because topics often belong to different categories, which is why, IMO, excessive organization may lead to less understanding. Be it here or in any other "populated" GitHub domain there are always people who mistake on where to find and on where to write.... even when topics are clearly mentioned.

You know, that was just a quick thought, nourished by no experience really of the place, only meaningful maybe because of that : how a non-initiated moves around here and finds or not his way, and my opinion was that it is most often the hurry or laziness that drives to the wrong topics, anyhow when the fundamentals are clear enough without being overdone, as it is here, again IMHO!

I come quite often but most of the time for the same reasons. Should I take the time to visit each topic that I'd certainly be more "right to the point", but it's my effort (ours, those who discover) than a lack of "panels".

That's all that I meant to say. I have no prerogative here! I use, I like Ghacks-user.js and if I take the time and effort I can certainly gain much more here than I actually do. You see this "users" includes myself!

**Comment by Thorin-Oakenpants** [comment]
> That being said, I have some questions:

1. Not just so you can edit the wiki. If that were the case I could simply change your existing permissions. And hell no, not opening the wiki up to everyone
2. No trap. No obligations.
3. You're already motivated. Again, no obligations.
4. Yes
5. Amen, brother.

I don't really want to spew this all over github for the public...

This is not a reflection on anyone else. I spoke with The Big E, and he's good with it too. I'm not sure you realize (no idea what the email said), but this is not just being a "member" (there are multiple roles). End of the day, your work, ideas, logic etc are awesome. We trust you to make sound decisions, e.g. editing the wiki, pushing commits, discussing first, etc. Again, no pressure or obligations - just do what you can when you can, if you want to. It's also about having fall backs in case I disappear (death from old age, I get parkinsons, batman catches me). Entirely up to you - you can always vacate it later

**Comment by Aeriem** [comment]
Hello again! (I really hope I'm not bothering you, this seems to have become somewhat of a private discussion, I just want to react to the OP's post.)
On the matter of involvement, maybe another option could potientally be viable.
I regularly see Thorin being held back by the big E from defenestrating herself (Hope I'm gendering you corrrectly, I read you are a woman on one of your ghacks.net comments, anyway, just correct me if I'm wrong.) because of people just dropping thousands-of-lines-long preference lists.
Maybe you could, possibly, if you wished, delegate!
I truly find this repo amazing, and I really want to help but I don't even how or where to start.
One possible thing you could do without giving anyone any kind of "rights" on the git (French here, what I mean by "rights" is the ability to commit, close issues, edit the wiki, merge forks, etc) could be to create a sticky issue called "Please help I want to die when I see this to do list" (or anything else, up to you really, more seriously, maybe a "Help wanted" or some kind of tag) and update it regularly with things you'd let others check for you.
One of the first things you do with the pref drops you often get is checking for deprecated prefs, conflicts with RFP and such. People could do this kind of work and then split the remaining interesting prefs among the people willing to do some deeper digging on the prefs that passed the first sieve.
You could list some other stuff such as "testing wanted for this particular conflict between two prefs or extensions", "info wanted on this particular fingerprint vector (is it viable or just theorical?)" and such!
The wiki could benefit from additional sources, just as the 🐱 said, so I think it's super duper cool if he gets a possibility to add that, and maybe fatten some of the thinnest sections (those year-old placeholders to be filled, you know what I'm talking about).
Additionally, some sections could also benefit from either an upgrade for the preexisting ones or from the creation of a "summary" compiled from different sources you already linked in your wiki.
(Really feels weird because I feel like I've """known""" you three for months, reading the issues, comments and commits on this git but I litteraly am just coming out of nowhere calling you by your nicknames please don't think I'm a creepy stalker I swear I'm nice. :anxiety:)
Anyway, have a nice evening, I hope this was somewhat helpful or interesting and I won't be spamming you any further tonight!

**Comment by claustromaniac** [comment]
> Maybe you could, possibly, if you wished, delegate!

I'm sure he/she/it(alien?) wishes to, but I suppose :jeans: would never ask anyone to help out directly, and instead just *hopes* someone will (and ends up bitching after a while when no one does). I agree that sticking `help wanted` (or such) labels wouldn't hurt though... well, maybe they would fuel Pants' frustration more if they change nothing, but that's an acceptable risk IMO (?). Or maybe something like a `help wanted` label is never added because it is being left as implicit? as in, people is being expected to assume that help is wanted? :thinking: 

> info wanted on this particular fingerprint vector (is it viable or just theorical?)

These have been tackled one at a time in different issues so far, and they are exactly the kind of discussions that I think deserve more visibility. Not everyone is a tech savvy, or wants to be, but still.

IMO, the difficulty with helping these two is that they have pretty tight workflows and they are damn efficient. I sure want to help out if I can, when I can (and I'm 100% positive I'm not alone on this) but TBH I can't keep up with everything! They've been doing this for who knows how long, the geeks. So, I've tried to help a little in other areas, when I could.

I'm glad this issue got some people's attention, though. I hope other creepy stalkers follow your lead and come out of the shadows, for a while at least. :trollface: Thanks!

**Comment by Aeriem** [comment]
> something like a `help wanted` label

It exists, I checked, it just was **literally** never used. 🤣
Anyway, I'll check the issues regularly and help out where I can!
We'll leave it up to those two to ask for help, if that ever happens. 😆

> I've tried to help a little in other areas

Yes and I see you'll keep at it with the wiki, that's really cool!
I was a little overwhelmed at first, the wiki is what helped me, and the better the wiki, the more it becomes accessible to everyone!

P.S.: I am **_NOT_** a creepy stalker! :crying a river:
That's not how I want to be known here, nor what I want to be associated with! :the river became an ocean: :where will it end: :nobody knows:

**Comment by Aeriem** [comment]
Oh, sorry! Couldn't find an issue under `is:issue label:"help wanted"`, that's why I said that, nevermind then!

> I don't know you but I already like you

Me: is crying, so happy to finally have found a place where he belongs, where he will never be rejected again, where he will-

> you creepy stalker

Me: is attempting defenestration

Seriously though, the feeling's mutual, thanks for the warm welcome! 😃
You guys are so nice. :muchappreciation: :suchwhoah: :verykindness:

**Comment by Thorin-Oakenpants** [comment]
@claustromaniac 
![needsjesus](https://user-images.githubusercontent.com/16656956/48965183-61451500-efb0-11e8-8797-bbe8a44eed0f.png)

**Comment by Thorin-Oakenpants** [comment]
hey :cat2: .. don't get any [silly ideas](https://www.schneier.com/blog/archives/2018/11/distributing_ma.html)

**Comment by claustromaniac** [comment]
Aw man! Why wouldn't they just keep quiet about it a bit longer.

**Comment by earthlng** [comment]
> infecting millions of users

Aw man, you picked the wrong project

**Comment by Thorin-Oakenpants** [comment]
closing this or we'll just go round in circles and ponder humanity, eventually asking "Is there a God" (when Jesus never shows up) and "Are we alone in the universe"

**Comment by StanGets** [comment]
> closing this or we'll just go round in circles and ponder humanity, eventually asking "Is there a God" (when Jesus never shows up) and "Are we alone in the universe"

Oh well, that's 75% of my interests in life, lol. But indeed these topics belong elsewhere, one step beyond, closer to the twilight zone than to a coder's universe!
