### ISSUE TITLE
Pants, FYI - atomGit jumps ship!

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#55]
looks like you guys have allot going on right now, so sorry to bother you with this

after thinking about what i was doing with my fork of your code, it didn't make sense that it should have been forked in the first place since i am leaving your code untouched and just appending my own prefs - with that in mind, i deleted the forked repo and started a new one...

https://github.com/atomGit/Firefox-user.js

thanks guys!!!

**Comment by earthlng** [comment]
That's great - now we have more data on preferred settings from other users.
We can use this to maybe relax or slightly change certain prefs, to make our defaults more in line with what users prefer. Most notably the ones under `=== 12BYTES.ORG GHACKS DIFFS ===`

@atomGit
* browser.newtab.url -> pretty sure this is deprecated, unfortunately (bad mozilla! bad!)
* browser.fullscreen.animateUp -> isn't this `browser.fullscreen.animate` now?

@Roman-Nopantski
for starters IMO we can change these
* ui.submenuDelay;150 -> instead of our 75. I also use 150 in my user.js
* layout.spellcheckDefault;2 // enable spell-check for single line inputs -> I also use 2
* full-screen-api.enabled -> comment this out by default, and either move it to the Personal section or move 3001a near the .enabled. Plus activate 3001a, regardless of .enabled
* the 5 browser.urlbar.* -> comment them out -> I use the same values as @atomGit

**Comment by atomGit** [comment]
@earthlng - regarding 2 depreciated prefs, yes, it appears you're correct - thanks :)

regarding personal preferences such as ui.submenuDelay, etc., etc...

i realize this config started off as @Roman-Nopantski personal config with a focus on security/privacy and i was interested to see what direction it would take when it was published ti GitHub

my most humble and personal opinion is that you guys may want to consider splitting this into separate projects, or dropping prefs that are not security/privacy related if your focus is on security/privacy

if you include benign, personal prefs, i suspect you will always be getting requests to toggle this to 'true' and that to 'false' and someone else will want something different, etc.

if you guys want this to be exactly what it is -- a combo of your own personal and security/privacy prefs -- then by all means, ignore what i just said, but if you want to avoid potential extra work and narrow the focus, then perhaps you might consider splitting the project or just dropping the personal/UI prefs completely

whatever the case, you guys are and have been doing one hell of a great job with all of this and i congratulate you on your efforts - thanks much for your work

**Comment by Roman-Nopantski** [comment]
@atomGit Absolutely no worries buddy. I haven't done the readme yet, and I read your comment about the wiki quickie - your site will be accredited and acknowledge my friend, especially since it nicely covers items such as uMatrix, uBo, NS and has pictures.

As for the personal section - that will be getting an overhaul - most likely to 100% commented out and all values set at default (except a couple maybe). I do not wish to discard them as most are a reference to settings not found in the UI.

**Comment by Roman-Nopantski** [comment]
@earthlng We can do a discussion: redo 3200 personal (in a weeks time or something). see comment above. The settings where not commented out, are actually what I use, cuz, well, it was my js, and myu live copy was my master rather than a template, so to speak. Now its here, *everyone* can treat it as a template. In the new redo issue discussion, we can talk about the merits of making them active or default or recommended etc. I would like to ignore those 3 patches and overhaul the entire section. We can revisit the values, if that's ok. We can also add @atomGit 's repo as a link for more personal settings as a reference. Also, the more we both use the same values, the better too :) So I like your idea of those value changes.
