### ISSUE TITLE
can't get search engines in urlbar dropdown [solved: see edited first post]

### ISSUE THREAD

**Issue by Theergn** [ghacksuserjs/ghacks-user.js#559]
In order to get the urlbar's suggestion drop down to function **at all**, you need to enable
- 0850a: `browser.urlbar.autocomplete.enabled`=true

- If you set that pref above as true, one (or all) of these must be true (0850a)
   * user_pref("browser.urlbar.suggest.history", true);
   * user_pref("browser.urlbar.suggest.bookmark", true);
   * user_pref("browser.urlbar.suggest.openpage", true);

Then to get the search engines show up on the bottom line yo need to enable
- 0850e: `browser.urlbar.oneOffSearches`=true

----

## Original post

Not sure if the purpose is to have users use the search bar to search via their own search engine preference is the intended purpose. I tried another user.js and it's not giving me this issue of setting a default search engine. Troubleshooting via Firefox portable also gives me the same result.

This is all I get and cannot set anything via about:config or prefs
![default page](https://user-images.githubusercontent.com/45408274/49119111-03951f00-f275-11e8-91f6-98132fd4c6f3.png)

**Comment by Theergn** [comment]
Through there I set the homepage and it just resets everytime. Tried looking for setting that effects the search engine change in the script as well as about:config.

**Comment by Thorin-Oakenpants** [comment]
If people could stop opening new tickets, I might one day get round to the relaxed and hardened stickies .. I was sooooo close one time

**Comment by Thorin-Oakenpants** [comment]
AFAIK the ghacks user.js doesn't (and has never) meddled with people's search engines, because search engines are localized (think Cyrillic, Japanese etc)

For search engines, go to about:preferences#search and set `Google` as your default search engine, then delete every other search engine. Did you do that? Because the user.js doesn't have anything to do with this - this info is actually stored inside the `search.json` file, AFAIK (I am not an expert on this). The ``search.json.mozlz4` file contains all the defaults if you reset your search engines.

Or are you talking about not having search engines displayed in the last line of the dropdown from the urlbar. Or are you saying you that when you type "search for this" in the url bar and hit enter it doesn't search google? You need to be more specific as to exactly WHAT you problem is

**Comment by crssi** [comment]
Did I say it is? I just write what I have in mine about that section.
That's why I have them under `0000`.
:heart: :kiss:

**Comment by Thorin-Oakenpants** [comment]
Nope, you didn't say that. But it's not very clear, and people might think/assume it's what this repo has. Just want to clarify that - and I did that in your post, at the source

**Comment by crssi** [comment]
I sad

> I have those **overrides**

Don't know how to be clearer, but I can sense a lot of tension today. :cry:

**Comment by Thorin-Oakenpants** [comment]
Well to be technical .. OVERRIDES are to override (literally) items in the ghacks user.js. As I said, it's not very clear. Might be to you, but we have to assume a low threshold :)

**Comment by Theergn** [comment]
> > Troubleshooting via Firefox portable also gives me the same result.
> 
> with the troubleshooter.js? That's only for helping to fix problems with **websites**.

Troubleshooting with another semi strict user.js and changing browser/homepage lines in user.js to no effect.

> > every time you restart Firefox? Do you understand the basics of a user.js?
> 
When I open a new tab it resets. It sets my omni bar to google as mentioned, but
> 

> Or are you talking about not having search engines displayed in the last line of the dropdown from the urlbar. 

This.

Or are you saying you that when you type "search for this" in the url bar and hit enter it doesn't search google?

That's another issue, it only allows me to use Google.

**Comment by earthlng** [comment]
0850e: `browser.urlbar.oneOffSearches`

**Comment by earthlng** [comment]
:jeans: maybe xe would have more easily found the problem if we had a list with all the section titles at the top of the user.js

**Comment by Thorin-Oakenpants** [comment]
In order to get the drop down to function **at all**, you need to enable
- 0850a: `browser.urlbar.autocomplete.enabled`=true
- at least ONE of these
   * user_pref("browser.urlbar.suggest.history", true);
   * user_pref("browser.urlbar.suggest.bookmark", true);
   * user_pref("browser.urlbar.suggest.openpage", true);

Then to get the search engines show up on the bottom line yo need to enable
- 0850e: `browser.urlbar.oneOffSearches`=true

**Comment by Thorin-Oakenpants** [comment]
Because I didn't set mine up, maybe Earthlng can work it out or knows, but you can use keywords. You only have the one search engine (apparently) but I'm sure you bypass the dropdown altogether and just use a bang or something

eg !g goat porn

**Comment by earthlng** [comment]
see, that's waaay too complicated. We should really make 0850a inactive IMO

**Comment by earthlng** [comment]
0850a: `[WARNING] If all three suggestion types are false, search engine keywords are disabled`

I would never want to use Firefox without the dropdown or without search engine keywords and I'm sure I'm not the only one. It's just stupid that we disable this by default

**Comment by Thorin-Oakenpants** [comment]
^^ I'm the opposite. It's so fucking distracting. I'm playing with it now. I reduced it to just history (and hid the search engines bottom line), and as you type letters, as fast as you can, it still finds enough for 10 entries and then rapidly reduces down to one or two, with a a minimum top line of "visit: xxx" (which is stupid, becaue you can hit enter)

I don't get it. `It's so geocities` .. I do understand the functionality of it, but man, it's horrible to me at least.

The awesome bar is getting revamped anyway, again. In the next few releases IIRC, and a lot of this is getting junked I think
