### ISSUE TITLE
Setting change?

### ISSUE THREAD

**Issue by QRWN** [ghacksuserjs/ghacks-user.js#570]
Why are these enabled??

```
experiments.enabled
experiments.supported
```

Also why are the below set to 0? Shouldn't they be set to 2?

```
network.cookie.lifetimePolicy and 
network.http.referer.trimmingPolicy 
network.http.referer.XOriginTrimmingPolicy
```

These are set to 1 as well. Also be 2.
```
network.http.referer.XOriginPolicy
network.cookie.lifetimePolicy
```

If breakage just have `network.http.referer.XOriginPolicy` at 1 and `network.http.referer.XOriginTrimmingPolicy` at 2.

**Comment by crssi** [comment]
`https://github.com/ghacksuserjs/ghacks-user.js/issues/5`

**Comment by bogachenko** [comment]
> Why are these enabled??
> experiments.enabled
> experiments.supported

what?

**Comment by Thorin-Oakenpants** [comment]
`experiments.enabled` and `experiments.supported` are **NOT** enabled. They are commented out and in the deprecated section. They were removed in FF60. See https://bugzilla.mozilla.org/buglist.cgi?bug_id=1420908,1450801

---

`network.cookie.lifetimePolicy` is not needed because it is redundant with `privacy.clearOnShutdown.cookies`, where clearing them on close = **they are effectively session only**. Also, if we enforced this pref, it would be just yet another pref to change/troubleshoot for those who e.g. use FPI and/or extensions to manage cookies, and/or use FF internals to control all persistent storage.

---

`network.http.referer.trimmingPolicy`

Read the section header: "Only *cross domain* referers need controlling and XOriginPolicy (1603) is perfect for that". There is no need to fiddle with this pref.

`network.http.referer.XOriginTrimmingPolicy`

Read the section header. We `tweak 1603 and 1604` to slightly tighten referers because otherwise the web breaks like crazy. The we said "To harden it a bit more you can set XOriginPolicy (1603) to 2", which is what you just asked.

Section header says to use an extension (eg uMatrix or SmartReferer) for per domain solution: default spoof, then whitelist.
