### ISSUE TITLE
What about network.http.enablePerElementReferrer ?

### ISSUE THREAD

**Issue by zymase** [ghacksuserjs/ghacks-user.js#59]
_network.http.enablePerElementReferrer_ is commented out in _user.js [ghacks]-0.11.js_ as well as in, here, _ghacks-user.js-51.0_ but with no additional information.

I read at https://www.anonymous-proxy.eu/firefox-privacy-tuning.php (mentioning this page because info on above setting is hard to find), 

> Mozilla's Firefox has introduced an experimental "per-element referrer" feature which is transmitting HTTP referrer for particular elements such as:
> Hyperlink
> Picture
> Frame
> Clickable area

That sites advises to set it to false (default=true). But not sure the setting is still experimental and not sure as well that site is right.

I've set it to false,
```
// Disable per-element HTTP referrer (HTTP referrer for particular elements such as Hyperlink, Picture, Frame, Clickable area)
// https://www.anonymous-proxy.eu/firefox-privacy-tuning.php
user_pref("network.http.enablePerElementReferrer", false); // Default=true
```
What would the experts say?

**Comment by atomGit** [comment]
https://developer.mozilla.org/ru/Firefox/Releases/42#HTML

> Experimental support for the referrer attribute of the <img> (bug 1166910), <iframe> (bug 1175736), <a> and <area> (bug 1174913) has been added. There is no effect by default, the network.http.enablePerElementReferrer being false by default.

the default is 'true'

you're right in that there seems to be little info regarding this

just reading the pref name, i might interpret it as meaning that, when you, for instance, click on an embedded object that links to elsewhere, the referrer sent would be the source of the embedded object rather than the site the object is embedded in, but i think it could be interpreted differently as well

if that scenario is correct, then, from a privacy POV, it would seem to make sense to leave it at it's default value (true)

not an expert though :)

**Comment by zymase** [comment]
> if that scenario is correct, then, from a privacy POV, it would seem to make sense to leave it at it's default value (true)
Indeed. The problem is the "if". Amazing. A browser includes a setting which is tougher to interpretate than a woman's smile. Far from a near past where everything was classified. Now you have to guess.
Amazing.

**Comment by fmarier** [comment]
That feature is no longer experimental. It's now part of the [specification](https://www.w3.org/TR/referrer-policy/#referrer-policy-delivery-referrer-attribute).

It can be used to change the default referrer policy to either include **more** or **less** information in the referrer. So ignoring them could actually *increase* the amount of information leaked via the `Referer` header.

However, the user controls like `http.referer.XOriginPolicy` take precedence over this, so it's actually unnecessary from a user point of view. I suspect we will remove that pref at some point (given the feature is no longer experimental).

**Comment by zymase** [comment]
@fmarier are you sure you're not mistaking with network._http.referer.XOriginTrimmingPolicy_? The specification page you mention doesn't state _network.http.enablePerElementReferrer_

I'm not an expert, just trying to make my way through a myriad of header settings ...
```
network.http.referer.XOriginPolicy
network.http.referer.spoofSource
network.http.referer.trimmingPolicy
network.http.referer.XOriginTrimmingPolicy
network.http.sendRefererHeader
network.http.enablePerElementReferrer
network.http.referer.userControlPolicy (FF 53+)

They are well detailed in ghacks-user.js-51.0 yet, for a non-expert, appear as a chaotic soup.
```

**Comment by Atavic** [comment]
@zymase > https://github.com/ghacksuserjs/ghacks-user.js/issues/5

**Comment by earthlng** [comment]
@zymase, first of all, welcome on board here :)

> are you sure you're not mistaking with `network.http.referer.XOriginTrimmingPolicy`?

we had quite the birth struggle with revamping the Referrer section.
@Atavic already linked to it, if you want to read thru some of it.
Towards the end there, you can see why we decided to only use `XOriginPolicy` for our "recommended Referer policy" for this user.js. We also came up with 3 recommended options for you to use, one of which (Option 2) can also be made more secure but with the risk of more breakage. We decided to go with the "less breakage" Option 2 as our default policy.
When `network.http.enablePerElementReferrer` is true, sites can use the "per element referrer" to better protect their users when they click on links, etc on that site. But it can also be used to lessen the protection!
But if you have a good setting for Referrer's, then it doesn't matter what the site does or doesn't do. That means if you're using one of our 3 recommended options, you can safely ignore `network.http.enablePerElementReferrer`, or you can set it to `false` if you want - it doesn't matter.

I personally also have `enablePerElementReferrer` set to false, if that helps your decision making :)
I looked at the code for some of it's implementation (namely [this](https://hg.mozilla.org/mozilla-central/rev/78d7963ccfb0) for [Implement <img> referrer attribute](https://bugzilla.mozilla.org/show_bug.cgi?id=1166910)), and the changes are minuscule and unlikely to be exploitable, but call me paranoid if you want - it does run extra code and since I don't need the feature anyway, I might as well disable it.

**Comment by fmarier** [comment]
> The specification page you mention doesn't state `network.http.enablePerElementReferrer`

The spec doesn't mention this because it's an implementation detail. It's a Firefox feature flag that was used to control when we rolled out this part of the spec.

**Comment by zymase** [comment]
@earthlng I'me using Option 2 and many thanks for developing this topic in latest _ghacks user.js ver.52 Section 1600_, which makes it easier to choose and, for a non-techie, makes related settings a bit easier to understand. What is confusing in this sum of header settings is their interaction, otherwise it wouldn't be more problematic than any other setting. Thanks as well for re-opening my thread. I ignored a dedicated thread existed here for such concerns.

@fmarier I was about to say merci! peerhaps presuming on a culture given a name. Thanks as well. The implementation detail explains your knowledge and my ignorance. You learn every day.

At the end my -- our! -- enablePerElementReferrer remains controversial to the point of inducing a margin of subjective appreciation, which is normal since true and false have both the best and worst implications. That very point is a pain but it's the lot of our computer world when an innovation has been driven for the best and gets manipulated for the worst. We have to do with it.

Fine. Thanks guys.

**Comment by earthlng** [comment]
> Thanks as well for re-opening my thread

np, I know Pants can be a PITA sometimes ;)

> Fine. Thanks guys.

So no more questions? This is your ticket so please feel free to close this yourself

**Comment by zymase** [comment]
No more questions that I'm aware of for the time being (to make it long).
I thouhjt It was  Roman-Nopantski who had closed the thread.
Whatever the pages of Github I haven't correctly understoof of opening/closing a thread. In my mind I don't close doors of a house which isn't mine :) So the idea is that the registered can close the threads he opened himself only and the admin can close any thread? (that's an off-topic question!). Whatever I couldn't imagine closing someone else's thread, that would be rude, or wouldn't it considering the protocol of Github is not that of a private propriety, strico sensus! You learn every day, some faster than others (some users that is). 

OK, I'll close the door!

**Comment by earthlng** [comment]
Pants was @Roman-Nopantski's nickname on ghacks.net before we moved this project to github.

> So the idea is that the registered can close the threads he opened himself only and the admin can close any thread? 

Yes that's correct. And I think we should handle it that way, unless we (as admins) close something with `wontfix` for example. I agree, it's rude to close someone else's thread and if we want something closed, we should ask them to do it themselves.
We are also new to github and also still learning :)
I'm not entirely sure, but I think the original thread-creator can still comment even if we close an issue (wontfix for example) - feel free to test and confirm this, should it ever happen again ;)

**Comment by zymase** [comment]
I had in mind, would be rude a user closing another user's thread, not the admin (owner, whatever the denomination) of the Github "room" (I definitely lack the terminology). Old school here, "the boss is always right even when he's wrong" :)

Anyway, nice to discover this Ghacks-user.js dedicated Github "room". I read Pants' comments on Ghacks but I confess not having noticed a name, his, squeezed between Roman and Polanski. Perhaps was I expecting plain Pants, ironed :)

OK, OK. Well, the best to you, to us all, to a finely tuned Firefox to which you contribute in a much appreciated way.

**Comment by Atavic** [comment]
Every member of this ghacksuserjs organization can close issues.

**Comment by Roman-Nopantski** [comment]
my avatar has nopants on

**Comment by zymase** [comment]
@Atavic I had just that in mind after my last comment and as I was lost in musical-driven thoughts, the fact that earthing had been able to close my thread even though he isn't administrator ... now I understand.

**Comment by earthlng** [comment]
I really hope your name is Roman or that you're a fan of that guy's movies and not his butt-fucking-teenager(s) episode(s) :)

**Comment by Roman-Nopantski** [comment]
Whats with all the opening and closing. @zymase : regardless of who started the issue, anyone can still comment in a closed thread unless it is locked.

**Comment by Roman-Nopantski** [comment]
@earthlng No, it came from a cracked.com article's image caption (3 or 4 years ago) and, well, it cracked me up. Also, I used the handle pants because, well, it's a very common word - go search for pants hack or private pants. Been using, in this MO, various pants related handles all over the net.

William Makepants Fappery, Otto von Pantsmarck, Benedict Cumberpants, Attipants Finch  :)  PS: u won't be able to trace me, I have 1000's of these and they're all throwaway

**Comment by earthlng** [comment]
> Been using, in this MO, various pants related handles all over the net.

nice OpSec :)

**Comment by Roman-Nopantski** [comment]
Nah, its a silly MO. I also just use random stuff. At Bruce Schneier's site I use a random object (usually a fruit or vege) and add a couple of adjectives like The Hairy Pink Banana, or The Massive Coconut of Doom

**Comment by zymase** [comment]
@Roman-Nopantski , that's what I figured out after Atavic's comment : 
_regardless of who started the issue, anyone can still comment in a closed thread unless it is locked._

_Otto von Pantsmarck_ sounds nice, requires a monocle!

I don't care tracing you, Pants, even if I could. But true as well that when someone seems to have a strong character he/she triggers curiosity. What where, when and so on. I'd appreciate meeting you in a pub, discovering you are the Pants we know, and chat around a pint or two. i'm sure it'd be most interesting. But here we are, more or less anonymously and it's just fine when the topics concern less ourselves then our thoughts, mainly about computer stuff.

Re-opened just to answer. I won't close this time!

**Comment by Roman-Nopantski** [comment]
There's hardly a name or sentence that can't have the word `pants` substituted in that doesn't make people smile - the chances of running out are slim to none. But ... it's also not 100% random then, is it. Horatio Pantsblower - i mean, come on .. a pantsblower! sounds like fun.

@zymase But the topic should be closed. I think you lost track of what you were doing.
