### ISSUE TITLE
Addon Save Page WE stopped working

### ISSUE THREAD

**Issue by Pilford** [ghacksuserjs/ghacks-user.js#592]
Thorin reminder
* [x] add console tip to troubleshooting wiki (I am so guilty of skipping this step myself!)
* [x] add this info our [sticky](https://github.com/ghacksuserjs/ghacks-user.js/issues?q=is%3Aissue+is%3Aopen+label%3A"sticky+topic") on extension breakage due to prefs `#391`
* [x] test: layout.css.font-loading-api.enabled=false causes the problem as far back as FF57

---

Original Post

I’m using FF64. After updating user.js the addon Save Page WE (https://addons.mozilla.org/en-US/firefox/addon/save-page-we) stopped working. It hangs when trying to save a page.

When I delete both prefs.js and user.js Save Page WE runs fine, but when I add user.js it doesn’t work anymore.

**Comment by Thorin-Oakenpants** [comment]
^^ we should add that to the troubleshooting steps

**Comment by Pilford** [comment]
Thanks for the narrowing tip! I figured out the problem.

layout.css.font-loading-api.enabled should be true (default setting) instead of false.

**Comment by Thorin-Oakenpants** [comment]
Thanks for working it out :+1: That's interesting, because we didn't change that, we've enforced it false for ages. When I get time (**so don't close this issue**) I will

- add console tip to troubleshooting wiki (I am so guilty of skipping this step myself!)
- add this info the the Prefs vs Extensions sticky we have
- test this issue in FF63 vs FF64

**Comment by Just-me-ghacks** [comment]
> we didn't change that
yes, we did

**Comment by Thorin-Oakenpants** [comment]
OK, so I'm getting around to testing this now, and it occurred to me that I need two tests/pages - one that uses, and one that doesn't use .. the css font loading api

- @claustromaniac @earthlng @Atavic - can you point me at a simple web page which uses the css font loading API
- or @Pilford can you point me at a web page that fails to save for you

TIA

**Comment by Thorin-Oakenpants** [comment]
^^ nvm. It fails in FF63 on a basic html page

FF63.03
My reset profile: 
 - nilla profile
 - auto install of updates off
 - save page as extension added
 - two bookmarks for pages to save
    * Bookmark1 = http://asmjs.org/ (its just text)

Testing it works in my reset profile, and viola, it fails with the following console error
 - `Save Page WE - document.fonts is undefined background.js:1129:10`

So not sure how OP got it working in 63?

**Comment by Thorin-Oakenpants** [comment]
:small_red_triangle_down: FF63.03 (it fails in 63, so no need to test 64)

#### Test profile: 
 - brank spanking shiny new profile
 - auto install of app updates off
 - "save page as" extension added
 - using extension options (Save Basic)
 - bookmarks for pages to save
    * Bookmark1 = http://asmjs.org/ (its just text, no fonts defined)
    * Bookmark2 = https://ghacksuserjs.github.io/ghacks-user.js/

#### Test1: `layout.css.font-loading-api.enabled`= default true
 - BM1 saves
 - BM2 prompts to save as 1 of 10 resources can't be loaded, and saves if you go ahead
    * no console error during save, but loading the page has warning about favicon

#### Test2: `layout.css.font-loading-api.enabled`=false
 - BM1 fails to save
 - BM2 fails to save
 - Console error for both: `Save Page WE - document.fonts is undefined background.js:1129:10`

---

Intrigued how OP had this working in 63

- Searched this repo for the pref, found nothing where it was changed or added. Went back to our first published version here, v51 (Feb 18 2017), and `layout.css.font-loading-api.enabled` was active at `false` back then.
- The extension had a version update on Dec 8th to `12.6`. Redid `Test2` with the previous version `12.5`. Nope that fails as well

I guess it's always been broken? And OP just didn't realize he had somehow overriden the pref? IDK, OP said he "updated" the user.js. Maybe that wiped out any previous overrides (how did he update it? manually?). IDK, I'm not there. I can't re-producing it the extension working in 63 with font-loading=false.

I'm tempted to go back to FF52 or something just to scope it out. Hell, why not

**Comment by Thorin-Oakenpants** [comment]
I went back to FF57.0.4. I don't see any point in testing further back pre Quantum.
- 57 was first released Nov 14 2017
- the first version of the "Save Page As" web extension to specially state `52 or newer` was version 10.0 released May 22 2018. So I went with those
- used extension settings to "Save Basic"

Redid the tests. With the pref at true, it all works. With the pref at false, it all fails with the same console warning.

@Pilford Thanks for coming across this and letting us know. At the very least someone should tell the extension dev, so 1) he's aware 2) maybe he can add the information to his wiki or troubleshooting guide or whatever, and 3) maybe he can code a warning /fallback / workaround.

I'll add this to our sticky extension breakage due to prefs.

**Comment by Thorin-Oakenpants** [comment]
..aaaand we're done. Just updated the [wiki](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting) page, in which I also added that users can check the extension breakage due to prefs sticky

PS: I will leave it up to someone else to contact the dev, you know, like a user of the extension :)

**Comment by Thorin-Oakenpants** [comment]
the pref was removed in AF v67, removing answered label
