### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Just-me-ghacks** [ghacksuserjs/ghacks-user.js#594]
inconsistent usage:
- [ ] youtube, github, facebook, wordpress, gmail, mozilla, google but Cloudflare, Vimeo, Bugzilla
- [ ] (15 secs) but (30sec)
- [ ] Google-Analytics vs Google Analytics

typo:
- [ ] extenion - extension

- [x] "regional preferences [FF56+] " - unneeded blank space at the end - https://github.com/ghacksuserjs/ghacks-user.js/commit/04b797f1aa2271ae561cffddb963912b0b61f96e

**Comment by Thorin-Oakenpants** [comment]
and same line has (1min) .. should be consistent with the spacing I guess

**Comment by Thorin-Oakenpants** [comment]
propercasing those google etc names. Often it's a case of distinguishing between a company (Mozilla) and a service/website (google) .. or something. Google is now ALphabet but people wouldn't understand that. Except for Mozilla, I'll just lowercase them. Bugzillas, yup two of em, got em!

**Comment by Thorin-Oakenpants** [comment]
Actually, google/mozilla are special cases. Here are all the instances of google

- `0210` use Mozilla geolocation service instead of Google when
- `0620` (uses Google-Analytics) <- I'll remove the hyphen.
- `0400 section header` (Google for SB and Disconnect for TP)
- `0410s section header` being sent to Google from... is never sent to Google... etc
- `0413 disable Google safebrowsing
- `0414` ... being checked by Google 

So in fact, all `google` 's are/were proper case, and in all cases refer to as a company, vs compared to `www.google.com` etc website. Capitals for GA too since it's an acronym.

310 matches for mozilla .. *sigh* .. ok, I F3'ed thru those checking the ones that weren't links etc. All capitalized and treated as a company.

Vimeo x1, Cloudflare x1, Bugzilla x2 = now lowercase
Google, Mozilla are consistently capitalized and treated as entities (often in full sentences too)

Not sure if that will satisfy you - my half-arsed BS reasoning :). I'll do a commit shortly. But any probs, just sing out
