### ISSUE TITLE
question regarding dom.workers.enabled and security

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#60]
As far I can see `dom.workers.enabled` was security problematic and fixed in previous versions of FF.
Is this one safe to be true now?
Not asking for a change. I have a few pages (fe. https://regex101.com/r/bR8lT1/1) where I would need workers and asking if it is safe to enable in my user.js.
Thank you gang

**Comment by earthlng** [comment]
IMO, no. The FBI exploit used workers and I assume other exploits do too.
I wouldn't advise setting it to true for all pages. (ie. in the user.js)
I'd recommend to either temporarily enable it in about:config before loading those pages, or setup a second profile for those pages if you visit them regularly.
Just my 2 cents

**Comment by zymase** [comment]
What I have experienced is that Google Street View requires it (Street View only, not maps), requires it means set to true (default). How not to agree with earthlng? But at the same time enabling/disabling on a per-site basis is cumbersome given the sites requiring it are numerous and/or frequently called. There are several add-ons which resume to a toolbar button to simply toggle an about:config setting but unfortunately none that I know that handle this `dom.workers.enabled.`

On another hand I've encountered no issue setting `dom.serviceWorkers.enabled` and `dom.workers.sharedWorkers`.enabled to false.

**Comment by Thorin-Oakenpants** [comment]
I'm of the same opinion as earthlng - although we need to revisit the entire js for a quick check of what could be relaxed, and conistently (eg separation of os and browser, context menu, etc). Things like google street view, twitter and all the other social media sites (IDK cuz I don't use them, but snapchat, instagram, whatever whatever) - this is going to gain traction, and quite frankly, it can be left off, except in a LITE branch version. People can use multiple profiles (and yes, that's all coming .. just need the horse before the cart, ok)

**Comment by Thorin-Oakenpants** [comment]
@zymase Almost forgot. Thanks for the info about google street maps. I don't use these sorts of things, so that's good info.

**Comment by crssi** [comment]
Just to add another example [https://regex101.com/r/bR8lT1/1](https://regex101.com/r/bR8lT1/1)

**Comment by zymase** [comment]
@crssi indeed.
Well, if it appears that this dom.workers.enabled is really better set to false than I might very well follow the advise which seems argumented (earthlon: 

> The FBI exploit used workers and I assume other exploits do too

)

I'd use the `about:config?filter=dom.workers.enabled` to quickly set it to true when required by a site (Google Street View, regex101.com ...). Cumbersome but again, if that important then perhaps better to false. I'll add an _internote_ (provided by the eponymous FF add-on) to remember.

**Comment by crssi** [comment]
That's why I have asked :)
Since the reported CVEs were already fixed by FF if I am correct...  I know, I know, there might be (and sure are) some unknown exploits.

**Comment by zymase** [comment]
As I see security/privacy settings (mainly privacy nevertheless) -- and that as all is always personal -- as much as I strive to ensure best values are set, as much these should not bother me excessively when surfin' (USA or elsewhere!). What I mean is that weighing pros and cons does interfere in my choices. No absolutism here, but I may be wrong.

**Comment by earthlng** [comment]
There are often alternatives that work without it: http://regexr.com/
No idea if it's as good as the other one, but if something doesn't work for me I'll find something else that does.

**Comment by crssi** [comment]
I am using normally exactly the one you have stated... the one one was stumbled over some github content and I have given it as a sample to test drive.

**Comment by earthlng** [comment]
Looks like the Pwn2Own exploit also used workers. If you need anymore reasons not to enable that shit - well, I'm sorry that's all I got ;)

**Comment by crssi** [comment]
We, we have exploitations everywhere: workers, fonts, images, js... etc.
I always suggest extra layer of security boundary with [sandboxie](https://www.sandboxie.com/)
I haven't mentioned this one under addons... since its not FF addon.

**Comment by nodiscc** [comment]
> https://www.sandboxie.com/
> Trust No Program
> Closed source software

Check [Firejail](https://firejail.wordpress.com/) on Linux (it has a premade Firefox profile)

**Comment by zymase** [comment]
FYI there is (at least) a Firefox add-on which will not perform correctly with `dom.workers.enabled` set to _false_ : **Country Flags & IP Whois**

I've had difficulty finding the culprit when I noticed that _Country Flags & IP Whois_ wasn't displaying the country flag & IP address in the urlbar because switching `dom.workers.enabled` to default = true waouldn't make it before restarting Firefox.

If it is possible, and that's what I was doing, to set `dom.workers.enabled` to true on a per-site basis (_Google Street View_ mainly, here) it leads to a choice setting vs. add-on when an add-on won't run if set to false. I'm keeping the add-on in this case because I really use it quite a lot.

**Comment by Thorin-Oakenpants** [comment]
> If it is possible, and that's what I was doing, to set dom.workers.enabled to true on a per-site basis

When XUL goes, AFAIK, web extensions will not allow add-ons to change (maybe even to read) preferences that are not their own. Extensions to flip prefs will be obsolete. That said, we have until 57 (and after that the ESR extended life). Also e10s is almost enforced, just to make matters a little tougher.

There are quite a few add-ons that flip prefs with whitelists. Maybe you can hunt one down and all it would need is a little code change. Or even easier, a simple toggle button extension of which there are hundreds of these, but no idea if any are e10s compliant.

**Comment by zymase** [comment]
If it weren't this _Country Flags & IP Whois_ Firefox add-on which requires `dom.workers.enabled` set to its default _true_ value  to perform I'd include `dom.workers.enabled` to a Custom Buttons (Firefox add-on itself) button called Pref Toggler (http://custombuttons.sourceforge.net/forum/viewtopic.php?f=4&t=381) which allows a quick access to about:config settings chosen by the user. But as I said when it comes to an add-on which requires a default about:config setting to be left unchanged then it's either the add-on or the setting when this add-on runs and performs on each and every Web page.

I'll add that I was surprised that a very add-on depended on `dom.workers.enabled`, when I thought up to now that this setting concerned Web sites only.

**Comment by Thorin-Oakenpants** [comment]
FWIW: [Flagfox](https://addons.mozilla.org/en-US/firefox/addon/flagfox/) does all this and more, and is e10s. I'm always wary of these sorts of things (yes I know country data is local csvs etc) - you want to be careful what data is being sent to who (and how, is it https) in order to look info up (and is it automated or only when you go to check?).

**Comment by zymase** [comment]
The country flag and server IP is performed automatically, the DB is local (included in the add-on) but the IP Whois is only performed on demand. So there's no automatic external call.

Concerning the IP Whois the one used by the add-on is, IMO, clumsy. I've mentioned this together with an improvement proposition for performing Whois with another site, on the add-on's GitHub page at https://github.com/andy-portmen/country-flags/issues/1

I really like this add-on, runs fine and allows the user to have quick info about the visited site .... but it needs `dom.workers.enabled` set to _true_ ...

**Comment by earthlng** [comment]
Unless there's something more we can help you with here, please consider closing this @crssi

**Comment by Atavic** [comment]
@zymase Good hints!
@earthlng Letting this opened will eventually give us more hints. I see there's a quick decision to close issues here. There are a few ones opened now and you can have up to 25 opened issues before the list generates a second pagelist with a bottom link.

I think opened issues colud give more followers, imho.

**Comment by zymase** [comment]
What is an issue and when is an issue ever closable?

Under the label  _issue_ there is sometimes more a debate over a questionable feature and in that case the issue may not be closable as long as related questions arise (pertinent to the scope of the thread).
A true issue, that is a precise problem with a unique answer, becomes closable once the answer provided of course.

Here, given the nature of the root (FF about:config settings) my belief is that a so-called issue may sometimes take time to meet all users' understanding of the problematic when applicable.

Take this thread, for example, _question regarding dom.workers.enabled_, well, sice its start we discovered true issues related to this setting being set to false. Seems to me that more users' comments of their experience with the setting set to false may improve the final recommendation, fed by the cons as well as by the pros.

Some settings are obvious, othere are not. In the latter case my very humble opinion is that the thread is welcomed to stay opened.

**Comment by Thorin-Oakenpants** [comment]
I'm happy to leave this issue open, because it will remind me to revamp the service workers section to be more user friendly - maybe split 2301 (workers and serviceworkers) and to investigate more about them - not just for myself, but to impact any knowledge.

As for closing issues, I close them when they have been dealt with. eg, someone asks a question, I answer it and if nothing else needs doing, I will close it. If it requires a rethink, I'll comment and let it linger. A number of these have lead to changes, for the better. I will say though, that I do like short lists and closed tickets. To me its a ToDo list and the less on it, the better.

**Comment by Atavic** [comment]
Websockets should be discussed in _3. Scripts_ wiki section, as gorhill addons treat the mell.

**Comment by Thorin-Oakenpants** [comment]
@Atavic Is there some script u want to add? If so, this should be brought up in the wiki stiki

**Comment by earthlng** [comment]
I don't mind keeping this issue open, but I agree with Pants in that I think unique issues for every problem are better. Otherwise we may end up with 100s of comments in a single issue and nobody likes to read thru that if they are looking for a fix for their problems.
I'd prefer a "dom.workers.enabled;false breaks 'Country Flags & IP Whois' add-on" issue for example.

**Comment by nodiscc** [comment]
> I think unique issues for every problem are better. Otherwise we may end up with 100s of comments in a single issue and nobody likes to read 

For the record this is why I don't read issues anymore in this repo. Having a large number of issues is not a problem when it is clear what each is about. Bonus for properly tagged issues. See another project which I help maintain: https://github.com/shaarli/shaarli/issues. Issues with 10's of comments on unrelated aspects are simply unfollowable for outside eyes, I tend to unsusbcribe or simply stop reading them.

Don't be afraid of breaking down issues into smaller ones and closing original, generic issues. Originals can still be referenced/quoted.

**Comment by earthlng** [comment]
Thanks @nodiscc. That github page does indeed look very neat - and so colorful, makes me want to go out and protest for gay rights :)

You're clearly a githubber for longer than we are - I'm still in the phase where I'm a bit hesitant to edit other users comments to remove off-topic stuff etc, or to completely delete a comment. It should get better over time

**Comment by nodiscc** [comment]
> edit other users comments

I would avoid doing that still. If I ever edit a comment, it's to move it to another, more appropriate issue (quoted, with a reference `moved from #xyz`)

**Comment by zymase** [comment]
The eternal problematic of organization, hierarchy. Interesting but at one point dependent of subjectivity.
I have my feeling of course but I'd pain to find an objective argument to even imagine it could prevail.

As I see it, organization depends of the entity (here, FF about:config settings towards user.js) and to what a topic (called "issue" on GitHub) includes, basically and related. Optimization is dynamic and @earthlng describes this when he writes,

> [...]and if someone then comments with "it also breaks this or that add-on" we can rename the issue to "add-on's that break due to dom.workers.enabled;false"

It's really problematic because if the approach aims to optimize then it must be dynamic, but if it is dynamic then the topic/issue, renamed, may appear unclear to those who previously referred to a past denomination of the issue. Especially when I was thinking of the opportunity to include a link in the user.js problematic settings to the issue here that explains/debates over them. Don't know what you think about it.
Very personal : I'd conceive a less specific topic/issue denomination but static, i.e., either
- One topic for one setting : dom.workers.enabled
or
- One topic for settings having an impact on add-ons ("add-on's that break due to dom.workers.enabled;false")

But renaming an issue is not my favorite, and a group (issue) handling too few items (users' concerns) is not valid either.

I remain at this time interested by:
- No renaming of issues,
- One issue for one setting

Need to say the number of problematic settings is a minority compared to all settings which are obvious and have no impact other than privacy/security.

Maybe, in the user.js file, group all problematic settings (already done, but not grouped) and add a link to their issue, or impact/consequence, here on GitHub?

It's really not obvious and it'll be up to the Big Boss to decide. 

-

**Comment by nodiscc** [comment]
Definitely don't rename issues (except if the title is wrong from the first 1 or 2 messages - eg. this issue could be renamed `is dom.workers.enabled safe to enable?`). If investigation on a particular issue leads to another one, open a new GH issue (and close the first one - if it's solved).

**Comment by earthlng** [comment]
@zymase, I'd recommend you add a link to https://github.com/ghacksuserjs/ghacks-user.js/search?q=dom.workers.enabled&type=Issues instead of an issue directly

**Comment by nodiscc** [comment]
> group all problematic settings

A `NOTICE:` field like we did in http://github.com/pyllyukko/user.js/ for each problematic aspect of a pref should be enough, but remind users to search for the pref name in your [issue tracker](https://github.com/ghacksuserjs/ghacks-user.js/issues/) if they want to know more.

**Comment by zymase** [comment]
OK, @earthlng but pages over at Ghacks may not be as fresh (recent) when it comes to users' concerns.

**Comment by zymase** [comment]
One could imagine:
Problematic settings : NEW
Problematic settings : dom.workers.enabled
Problematic settings : setting 2
Problematic settings : setting 3
etc ...
This way a new user could quickly find if his concern is already listed and otherwise go to NEW and comment his problem with another setting. If this issue becomes important then create a new issue with
Problematic settings : (the new setting).

Just an idea.

**Comment by Thorin-Oakenpants** [comment]
Only a few issues have gone off topic, and now this issue has gone completely off topic talking about going off topic. Oh the irony. Yes, I just added to it.

Topic titles are already pretty well damn spot on, thank you very much

I am not going to list problematic settings. I already have warning and setup tags in the js. It used to have a troubleshooting section at the top, but seriously, all it was just a list - people still needed to find that pref and read the warning bit. Every setting has the potential to be troublesome, but the reality is it is only a handful. Seriously, it's like 5-10 items/numbers at most

The whole point is that the user.js should hold everything people need to know about each preference and it's ramifications (and no, I do not mean lists of stuff that break). The whole point of the github issues is to get feedback and continually improve the js. No lists are required, I want a singular place for all info, not duplication and extra work.

**Comment by Thorin-Oakenpants** [comment]
> A `NOTICE:` field like we did

Oh you mean like the warning tags that have been in the ghacks version for almost 18 months.

**Comment by earthlng** [comment]
I *moved* the comments regarding the broken addon into a new issue [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/70)

**Comment by earthlng** [comment]
should I move the "how to handle issues and when to close them" into a separate issue too?

**Comment by zymase** [comment]
> I moved the comments regarding the broken addon into a new issue here

OK. But just wondering: if I or anyone else encounters an issue between `dom.workers.enabled` and another add-on, what to do? Open a new issue or add the comment to dom.workers.enabled;false breaks 'Country Flags & IP Whois' add-on #70 ?

And if an issue between `dom.workers.enabled` other than with an add-on?

You decide but with one issue per problem you may well get overloaded ... whilst one issue for one setting would have been far more obvious. You decide ...

**Comment by Thorin-Oakenpants** [comment]
> should I move the "how to handle issues and when to close them" into a separate issue too?

“It seemed to me,' said Wonko the Sane, 'that any civilization that had so far lost its head as to need to include a set of detailed instructions for use in a package of toothpicks, was no longer a civilization in which I could live and stay sane.” - Douglas Adams, *So Long, and Thanks for All the Fish*

**Comment by Thorin-Oakenpants** [comment]
zymase, use some common sense: if it breaks an addon then perhaps simply add it to the one that talks about it breaking an addon. You know like this "Just FYI guys, it also breaks this XYZ addon" - I mean what other purpose would it serve except as a FYI. We can't fix the add-on. Its info only.

**Comment by earthlng** [comment]
I just think @nodiscc made a very valid point about having too many comments in an issue. I wasn't aware that it was so bad that it lead him to not read here anymore. Not reading = no help. We should try to avoid that.

@Thorin-Oakenpants so what do you suggest? leave the 15+ offtopic comments in here instead?
I mean we could start the issue off with TL;DR: please open a new issue if it's even slightly off-topic from an existing issue, to keep the comments to a minimum.

ok, locked - closed - I guess that answers my question - we don't give a fuck if we turn people off due to stupidly long comments in an issue with most of it being off-topic. Whatevs

**Comment by Thorin-Oakenpants** [comment]
I will prune all the OT later. We do not need a topic on how to deal with topics. Sheesh.

Nodiscc hasn't made a single decent suggestion here - he's made a handful of comments and his suggestions are duplicitous or downright at odds. All he has EVER wanted (and not a single thank you for bringing this to github, or manually doing the compare for the monster diff) and all he EVER does is care about PK's js. It's like he saw what we have and suddenly it's lit a rocket under his ass, to the point where he's inspired to copy features (subconsiously?) - that comment about adding `NOTICE` like *they* did really gets up my goat.

**Comment by Thorin-Oakenpants** [comment]
For a section 2300 revamp discussion that covers security/privacy implications and what web workers actually are, use #71
