### ISSUE TITLE
Is it working? What add-ons?

### ISSUE THREAD

**Issue by FlailAway** [ghacksuserjs/ghacks-user.js#632]
Hi, just found this and have a few problems. First off, I could not find how to use user.js after reading the wiki things and cautions, I am assuming I add it into the .mozilla/firefox/[profile-name] folder?

I deleted all profiles (yes I have backups) except the one that is dated today; on the assumption that is my current default Profile and added user.js into that folder. So, how do I know it is working? I do not have the skills to mess with the contents so I am happy to use whatever is in user.js and work on adjustments if/when something screws up.

I noticed a mention of including uBlock origin and I already have that installed, but several others as well. What add-ons do I need and what can I get rid of? Currently HTTPSEverywhere, Privacy Badger, PureURL and NoScript.

Thanks

**Comment by crssi** [comment]
Welcome...

> Hi, just found this and have a few problems. First off, I could not find how to use user.js after reading the wiki things and cautions, I am assuming I add it into the .mozilla/firefox/[profile-name] folder?

Yes

> So, how do I know it is working?

Open `about:config`
Enter `_user.js.parrot` (or just `user.js`, or just `parrot`) into search field.
If it exists with a value, something like `SUCCESS: No no he's not dead, he's, he's restin'!`, then you know its working.
NOTE: user.js is a very very good TEMPLATE. But you might have a need to make some changes for your need.

You can immediatelly ditch Privacy Badger and NoScript.
I do not believe in HTTPSEverywhere... anyway almost none of the pages I visit frequently even exists in HTTPSEverywhere database.
Replace PureURL for Neat URL.
NOTE: This is just my personal opinion and not everyone agrees. Even here we have different approach, since we have different needs. You also can peek into my repository.

**Comment by Atavic** [comment]
There are some similarities on various privacy repositories, most of them trust gorhill uBo and uM the most. Then many use EFF Privacy Badger and HTTPS everywhere, but the 1st one is surpassed by uBo features while the 2nd one has some lighter alternatives. Noscript (Legacy version) is discussed [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/319). DecentralEyes is a must have IMHO

**Comment by kgbm3** [comment]
SUCCESS: No no he's not dead, he's, he's restin'!
> Open `about:config`
> Enter [..]
BTW., to access **about:config** settings directly, from the URL bar: 
<blockquote>about:config?filter=_user.js.parrot</blockquote>

**Comment by Thorin-Oakenpants** [comment]
@FlailAway Have you read the wiki?

**Comment by kgbm3** [comment]
> @FlailAway Have you read the wiki?

That's a great question (lolz)! xD

https://addons.cdn.mozilla.net/user-media/previews/thumbs/137/137406.png

> DecentralEyes is a must have IMHO

... Decentraleyes beautifully (!?) on Android, **FTW**
@
![Alt text](https://i.ibb.co/ZH8CJRm/Screenshot-20190205-031921.png "DecentralEyes")

**Comment by Thorin-Oakenpants** [comment]
> BTW., to access **about:config** settings directly, from the URL bar: 
> <blockquote>about:config?filter=_user.js.parrot</blockquote>

@kgbm3 : I believe that is no longer possible when the about:config drop XML/XBL or whatever it is - slated for FF67

**Comment by Thorin-Oakenpants** [comment]
Yup, decentraleyes is awesome. But we don;t need giant pics of it :)

**Comment by kgbm3** [comment]
> [..] slated for FF67

OMG., no, say it ain't so!.. You know, I'm willing to bet *right now* that it's ~~just~~ the begging (of the end!) of Mozilla going to shut-off half of the things we **need**!!

Gonna check up on it, but ~~literally~~ just going on intuition (LOL), wouldn't be scared to guess - how *since* they're messing with that - that Mozilla are planning to unleash some user-unfavorable (corporate?!) agenda, which will totally **ruin** our day. 

^^ Not to say *life*, blah, but it'll destroy the browser. It has already gotten SO shaky - for example, with the ~~atrocious~~ factory, built-in, Add-ons - which they've tried to slip-in with the move to WebExtensions - and it can't take much moar... 

Still on F-Droid Fennec here and it's brain: 64.0.2, btw

**Comment by KOLANICH** [comment]
>anyway almost none of the pages I visit frequently even exists in HTTPSEverywhere database.

I usually add own rules in these cases. The bigger problem is that some sites don't support https at all.

**Comment by crssi** [comment]
@FlailAway 

> but for now it is starting up as a smallish window in the screen centre

That is because of resistFingerprinting.

On Windows... To overcome fixed size Firefox window annoyance at Firefox start, right-click on Firefox shortcut -> Properties -> "Shortcut" tab -> select "Maximized" under "Run" property

Cheers

**Comment by FlailAway** [comment]
> @FlailAway Have you read the [wiki](https://github.com/ghacksuserjs/ghacks-user.js/wiki) 

Thanks for the detail, yes, I did, well, some of it, but not all of it. But I had read 1.1 and 1.3.  How to setup my preferences was not obvious but I will try messing with the //OVERRIDES

But, it is a little out of my scope of knowledge this deep into the workings of firefox javascript. I was looking for a simple fix to protect privacy. I am not so concerned about tracking beyond what firefox already offers. In a new installation I always set "Custom History" and clear History, Cookies etc on closing. 

I do need Netflix and Amazon movies to run and it seems difficult to attain that at this stage. Is there a trimmed version that allows that or some boilerplate "//OVERRIDES" that I can just attach?

I appreciate all the effort you have invested in this project, but I cannot see me spending weeks learning the technicalities of javascript and firefox. If that means I do not deserve your user.js then I guess so be it. But, for this to be useful to me and I am sure many other newbies, major options like  widevine inclusion is a must.

The wiki seems comprehensive and you have done a lot of work and are to be lauded for it. But, it is way too complex to understand for non technical people. We dunces need a user.js that protects us from ourselves, but still allows for simple adjustments.

Try as I might I am still not able to get Netflix and  Amazon videos to run. So, I guess it is back the the word of tracking and abuse of our privacy. :)

Thanks anyway.

**Comment by Thorin-Oakenpants** [comment]
from crrsi
> On Windows... To overcome fixed size Firefox window annoyance at Firefox start, right-click on Firefox shortcut -> Properties -> "Shortcut" tab -> select "Maximized" under "Run" property

I told you not to believe his lies :trollface: 

Don't do that. The whole reason your browser sizes itself under RFP is to make your screen + available screen + browser + inner window measurements the same, and to use a standard size. If you want to maximize or go full screen (e.g to view a netflix show or movie) then that's fine, you are already logged into netflix. Just restore the window size afterwards.

**If you want a bigger browser size, then use the two prefs I already outlined** - which is not ideal, but at least the example I gave you is a common screen res. Otherwise, do not use RFP if you can't live with some changes - timezone spoofing is the other one that can affect things unexpectedly. In which case you would want to enable section 4600

Or you could wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1407366 to land and it's the viewport that gets resized, not the browser

**Comment by Thorin-Oakenpants** [comment]
There are 430+ prefs for the current Firefox. Of these 115 are inactive (commented out). That leaves 315. Of these 315 quite a few are enforcing the default value (I count 24 active prefs at default, and there are others .. lets call it 35). So that leaves maybe 280 prefs we change

Of these 280 prefs, only about 50 would cause some web-site breakage. Some very rarely, others all-the-time (e.g you will need DRM/Widevine or whatever for Netflix), and of course some in between depending on your web habits. If you use gmail, youtube, google maps etc, you might have trouble - our users don't usually use google services, and to overcome that if they do, they would use a secondary profile or browser. reCapcha is not a fan of anti-fingerprinting etc, as an example, and google hates it when you disrupt the way they are used a login for otehr sites. I would guess Facebook also wets the bed with this user.js

THAT SAID .. there are only about 50 prefs you need worry about. And you won't need to worry about them all. Just report what doesn't work, and we'll tell you what to change (e.g Netflix etc - I'll post that shortly)

> But, it is a little out of my scope of knowledge this deep into the workings of firefox javascript.

It's REALLY SIMPLE .. and I can help you. The user.js file is a TEXT file, just open it in Notepad or something similar. Any of the 30 to 50 prefs that cause you grief, then you add them to the end of the TEXT file as an override - and restart Firefox. It's THAT simple.

What you're calling hard is that fact that if you want to increase your privacy etc, then you do have to go thru and evaluate what suits you, and only YOU can do that. But it's a ONE TIME thing to do.

> I do need Netflix and Amazon movies to run and it seems difficult to attain that at this stage. Is there a trimmed version that allows that or some boilerplate "//OVERRIDES" that I can just attach?

Well I can fix that for you, and you can still use the user.js .. remember, you probably only need to look at 30 or so preference changes in total you get things the way you want. But ... you said

> So, I guess it is back the the word of tracking and abuse of our privacy. :) Thanks anyway.

It seems like you've given up. Not prepared to put in a little one time work to get a few things changed (which only you can do), despite me offering to point them all out to you (e.g Netflix etc)

When you're ready, feel free to come back.

---

> We dunces need a user.js that protects us from ourselves, but still allows for simple adjustments.

As already said, it's about 50 prefs that seem to cause almost all "issues" for people. A lot are already tagged in the user.js - search for `[SETUP-`. And we are going to provide a `relaxed` overrides at some stage - basically those 50 odd prefs
