### ISSUE TITLE
RFP and new Accept headers

### ISSUE THREAD

**Issue by gracefulshark** [ghacksuserjs/ghacks-user.js#634]
When RFP is active (default for ghacks-user.js) Firefox identifies itself as FF60.

Problem is there are differences (read fingerprinting points) between the request headers that FF60 and FF65 are sending.

**image.http.accept**

* FF60 - \*/\*
* FF65 - image/webp,\*/\*

**network.http.accept.default**

* FF60 - text/html,application/xhtml+xml,application/xml;q=0.9,\*/\*;q=0.8
* FF65 - text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,\*/\*;q=0.8

**network.http.accept-encoding.secure**

* FF60 - gzip, deflate   
* FF65 - gzip, deflate, br

Should we set those settings to emulate FF60 more genuinely?

Edit: now I'm not sure about network.http.accept-encoding.secure, maybe I'm wrong and FF60 supports this new compression

**Comment by Thorin-Oakenpants** [comment]
I'll explain in the next post why there is nothing to do and even with differences why it is silly to even try. But first, lets look at the differences:

I have a test suite here of 8 FF versions (ESR60*, FF60-66) and Tor Browser.

Test pages:
- https://whoer.net/
   * see the top right hand side of results: shows header + JS use agent
   * click Extended, scroll down to see on the left, HTTP Headers > HTTP_ACCEPT
- https://httpbin.org/#/Request_inspection/get_headers
   * then click on `GET/headers`, `Try it out`, `execute`, and then scroll down a little to see the `response body`
   * note: you are on a secure site (HTTPS)

Here are the results (excluding Tor Browser)

<details><summary>gently finger (or mouse) me to make me grow</summary><p>

```
ESR60 nilla + RFP
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
gzip, deflate, br

FF60 nilla + RFP
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
gzip, deflate, br

FF61 nilla + RFP
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
gzip, deflate, br

FF62 nilla + RFP
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
gzip, deflate, br

FF63 nilla + RFP
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
gzip, deflate, br

FF64 nilla + RFP
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
gzip, deflate, br

FF65 nilla + RFP
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
gzip, deflate, br

FF66 nilla + RFP
Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0 
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
gzip, deflate, br
```

</p></details>

---

**network.http.accept-encoding.secure** has not changed

**network.http.accept.default** changes from FF65+ because Firefox added `webp` support (no idea why my up-to-date FF66 Dev does not have this. I expect when 66 hits stable it will be there)

**user agent** - see next post

**Comment by Thorin-Oakenpants** [comment]
Just realized that the UA was not in OP, but it's so relevant that I auto-built it in my tests and replies. So imagine "fixing" the `webp` "issue" from OP, in FF66 you'll also have to "fix" the user agent header (to keep looking like ESR), not to mention all the other changes that "leak" since FF60. And of course, you can't do all of them.

Just to clarify. RFP aims to make a **set of users** look the same. That set of users depends on the browser
 - RFP changes with every FF release (new protections, tweaks to old ones etc)
 - every FF release has changes (and some you cannot hide)
 - it is expected that users keep up to date with browsers
 - ESR is a release that only gets security updates (it doesn't get all of them, btw)
 - RFP is not interested in backporting changes to older versions (see point 2 about users should be up to date)
 - RFP likewise, is not interested in backporting to ESR (they do consider some of them from time to time), especially as they diverge more and more.

once more, with feeling ... **RFP is not trying to make you the same as ESR**

Thanks for putting up with my massive pages of text :rocket:

**Comment by KOLANICH** [comment]
>maybe I'm wrong and FF60 supports this new compression

FF supports, but IDK if it was enabled by default. On ~~Aurora~~DevEdition of that version it was enabled.

**Comment by earthlng** [comment]
Thanks Pants! So FF66 over Tor matches TB header-wise atm? That's nice

Q: 1st you said "TB now allows JS by default in the safest slider setting" but later "And those on the safest slider setting = no JS". Did they really remove JS blocking from the safest setting?

**Comment by Thorin-Oakenpants** [comment]
whoops .. need MOAR sleep .. the default setting is "standard", the more secure one is "safest"

it's the standard slider setting, the default one, which allows JS by default - I'll edit my post

**Comment by Thorin-Oakenpants** [comment]
> Did they really remove JS blocking from the safest setting

Yup. Open the slider and flick the settings to see the diff.
- Standard: nothing re JS
- Safer: "JS disabled on non-HTTP sites" - which is fast becoming irrelevant
- Safest: "JS disabled on all sites"

NS does not save settings either between sessions/identities. So if you want to be on the safest slider (most secure etc) and have JS disabled, then it becomes a PITA when revisiting sites that require it

**Comment by earthlng** [comment]
Oh okay. But still, "TB **now allows** JS by default..." was doubly confusing because it was always like that, wasn't it?

**Comment by Thorin-Oakenpants** [comment]
^^ Not to my knowledge. I have a last version 7.5* here, I'll have a look

**Comment by Thorin-Oakenpants** [comment]
^^ OK, so the slider settings were the same for JS in 7.5* last release before v8. Could have sworn it was disabled by default at some stage ... fuck I'm old, it was probably version 1 and I never noticed the change :grin:

**Comment by Thorin-Oakenpants** [comment]
> So FF66 over Tor matches TB header-wise atm

@earthlng .. yes, someone opened this ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1509829

**Comment by Thorin-Oakenpants** [comment]
@earthlng https://old.reddit.com/r/TOR/comments/anw010/javascript_is_enabled_by_default/efwfbiv/

So JS was allowed by default in at least TB v2.* ...

**Comment by Thorin-Oakenpants** [comment]
> network.http.accept.default changes from FF65+ because Firefox added webp support (no idea why my up-to-date FF66 Dev does not have this

Ahh . because `network.http.accept.default` is removed in FF66+ : see [1417463](https://bugzilla.mozilla.org/show_bug.cgi?id=1417463) and the accept headers are determined by what type of "object" you are requesting
