### ISSUE TITLE
DNT - is it still relevant?

### ISSUE THREAD

**Issue by seanob86** [ghacksuserjs/ghacks-user.js#636]
Recent articles of Apple removing DNT in latest beta of Safari. 

https://www.macrumors.com/2019/02/06/apple-removes-safari-do-not-track-option/

Is DNT still relevant today even with RFP and utilising extensions such as ublock origin in “medium” mode?

I’ve also read that DNT can be used for fingerprinting. 

The current version of user.js has DNT set to true. Are there any plans to reconsider this option?

**Comment by Thorin-Oakenpants** [comment]
Forget about what apple or google or microsoft etc do - because this is only about Firefox: i.e you are easily distinguishable as a Firefox user - so what anyone else does is irrelevant.

DNT is a mess, let's be honest. For starters it must be opt-in: that was the only way to get advertising networks on board. And then basically no advertising networks came on board - so it is essentially useless .. BUT .. since the [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) came into affect, it may have some bearing, IDK. I read somewhere that a study found tracking in the EU dropped around 30% (not from DNT, just overall as companies made themselves compliant).

Anyway .. back to DNT. So this has uses in Firefox (remember: forget about other browsers) - it is actually used to NOT allow GA (google analytics) in some places: I think this is correct. e.g an AMO (mozilla addons site), in activity stream?, etc. Not that I am concerned with that per se, because there are other ways to make extensions block GA etc on AMO, and to hide the "Get Add-ons" panel in about:addons, and to not use Activity Stream etc. But it does have a role in Firefox - e.g it is enabled regardless of the DNT setting in Private Browsing windows (the opt-in is implied because you choose to use PB mode even though the landing page for PB mode doesn't mention it - not sure how that's meant to work)

In fingerprinting terms, it can have three states: undefined, true (on), false (off). That's not a lot of entropy, but it's still entropy. Don't believe a single stat on this from sites like Panopticlick etc - all of which seem to suggest the figure is 50/50. 95% of the world wouldn't even have a clue what it is and have never changed it.

We used to have it on for a while back in the dark ages. Then it was off for 3 years, because, yeah, it's useless and the feeling was it would just increase entropy. Then we recently decided to enable it because it can do some good, and FP'ing is not really the issue - everyone is already unique if you dig deep enough, and you control most FP'ing by controlling the attack surface (3rd party etc) at this point.

That said, it is entropy and we're quite happy to wait and see what RFP does with it - see https://bugzilla.mozilla.org/show_bug.cgi?id=1466025 .. and it's a little bit of a shit storm because GK (Georg Koppen) from Tor is really anti DNT (fair enough), but everyone agrees that it can be unified under RFP, but then it gets complicated if the choice is to disable it in Firefox because FF uses it (e.g in PB Mode and Tor opens in PB Mode, e.g for AMO etc) so it can't really be disabled in FF, but Tor Browser can do what they like.

So when they all stop squabbling, RFP in FF should enforce it, and Tor Browser can disable it - and they just need a new pref like `privacy.resistFingerprinting.DNT`. But it's probably not as simple as it sounds, given DNT is buried in PB Mode, Content Blocking and other places AFAIK.

DNT sucks. I wish it had never been invented

**Comment by beerisgood** [comment]
Sorry to reanimate this, but W3C is also against DNT:
https://www.w3.org/TR/tracking-dnt/#privacy.fingerprinting

**Comment by beerisgood** [comment]
The (german) [Privacy-Handbuch](https://www.privacy-handbuch.de/changelog.htm) also recommend disable DNT and also "privacy.trackingprotection.enabled" because it's bundled - as written in gHacks user.js

Any opinions?
@Thorin-Oakenpants

**Comment by Thorin-Oakenpants** [comment]
no opinions at all - criticized if we enable it, criticized if we don't

So they set `privacy.trackingprotection.enabled` = true, which means TP is enabled on all windows, and thus DNT is sent regardless of the pref (AFAIK - this used to be the case, but DNT is a fucking mess and no-one at Firefox that I know of cares about it so who knows how it works anymore). And AFAIK, Mozilla are going to flip TP on all windows soon.

**Comment by rusty-snake** [comment]
> So they set privacy.trackingprotection.enabled = true,

Nope, to false https://privacy-handbuch.de/handbuch_21d1.htm#17_12_19

**Comment by Thorin-Oakenpants** [comment]
OK. Sorry - I'm just not interested in this, or them. I typed out a long reply, but removed it, since I'm also not interesting in justifying myself to everyone

**Comment by rusty-snake** [comment]
@beerisgood you can use [Header Editor](https://addons.mozilla.org/de/firefox/addon/header-editor/) with a drop DNT rule:

```json
{
	"request": [],
	"sendHeader": [
		{
			"enable": true,
			"name": "Drop DNT",
			"ruleType": "modifySendHeader",
			"matchType": "all",
			"pattern": "",
			"exclude": "",
			"group": "Ungrouped",
			"isFunction": false,
			"action": {
				"name": "dnt",
				"value": "_header_editor_remove_"
			}
		}
	],
	"receiveHeader": [],
	"receiveBody": []
}
```

[HE_Drop-DNT.json.txt](https://github.com/ghacksuserjs/ghacks-user.js/files/4082950/HE_Drop-DNT.json.txt)

**Comment by rusty-snake** [comment]
Revert, this is for idiots. `navigator.doNotTrack` is still 1.
