### ISSUE TITLE
Violentmonkey vs Greasemonkey

### ISSUE THREAD

**Issue by tya99** [ghacksuserjs/ghacks-user.js#639]
After my brief discussion with @Thorin-Oakenpants https://github.com/ghacksuserjs/ghacks-user.js/issues/329#issuecomment-461283439 

I decided to open an issue on this so that we may do a comparison [as he suggested](https://github.com/ghacksuserjs/ghacks-user.js/issues/329#issuecomment-461320194).

Note I have decided not even to talk about Tampermonkey, because the source [code is not available for any modern version](https://github.com/Tampermonkey/tampermonkey).

So I will start with a comparison of Greasemonkey vs Violentmonkey what I had  been using in the past. I haven't really written any scripts so I'm not talking about the actual engine, though I would be curious to hear anyone who has anything to say about that.

## Greasemonkey

1. Permissions wise Greasemonkey has two extra permissions:
  - Download files and read and modify the browser’s download history
  - Access browser activity during navigation

2. The source is easily auditable, and does not seem to be optimized in any way when you download the .xpi from AMO and unzip it.

## Violentmonkey

1. Has a much better UI, particularly the script management part. 
2. Can do a few things like Syncing to cloud if you want it to.
3. After [reading this thread](https://old.reddit.com/r/firefox/comments/9uemks/greasemonkey_tampermonkey_violentmonkey_which_one/) and looking at the [privacy policy](https://violentmonkey.github.io/privacy/) in detail I don't think there's any issues.

I get the feeling that any personal information would be  because you initiated a support request:
> While using our Service, we **may** ask you to provide us with certain personally identifiable information that can be used to **contact** or identify you.

This portion could relate to two, things. Firstly that it is on Github and secondly that the site uses Google Analytics. For contrast the Greasemonkey site is hosted on Google's [blogger.com](https://en.wikipedia.org/wiki/Blogger.com) platform.
> We may employ **third party companies and individuals** to facilitate **our Service, to provide the Service on our behalf**, to perform Service-related services or to assist us in **analyzing how our Service** is used.
> These third parties have access to your Personal Information only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose. 

This is kind of obvious.

**Comment by Thorin-Oakenpants** [comment]
Links:
- https://github.com/violentmonkey/violentmonkey 4.5 stars on AMO, 58 open issues
   * current version 2.10.1 (last updated 1 month ago)
   * has released 7 versions since GM's last one
   * https://github.com/violentmonkey/violentmonkey/commits/master - stuff being improved All. The. Time.
- https://github.com/greasemonkey/greasemonkey 4.1 stars on AMO, 93 open issues
   * current version 4.7 (last updated 5 months ago)
   * https://github.com/greasemonkey/greasemonkey/commits/master - nothing since that 4.7 release

BTW .. for all the bitching (for lack of a better word) about VM's privacy policy (which to me is standard boilerplate and covers the syncing thing, and someone even says it came from a generator) .. I can't even find one for GM

GM home page: https://www.greasespot.net/ - last updated 5 months ago: as you can see a lot of activity: may 23, jun 28, jul 12, aug 28 .. because they were still catching up with getting a web extension verion going. They were very very very late to the party with getting webext.

Look, I get it that people are busy. I don't know the GM guy(s). From my experience, gerald has been nothing but awesome. When we rode the trains during the transition to FF57 and the lost of legacy extensions, there were a lot of weird things going on - seriously weird, such as images getting blocked, emoji's not rendering, and so on. Essentially it came down to legacy & web extensions having hissy fits existing side by side. GM wasn't even in the market - they hadn't done anything. The only alternative was VM. Once that was in, then webext uBO and uM etc all started to play nice.

Months after VM, I was still seeing tickets for GM about unable to add scripts, and button missing, and other things. I'm sure those got sorted out eventually, IDK. I gave up on GM because they weren't there when they were needed. AFAIC, GM is practically abandonware. That's my opinion.

But, it may be quite mature, IDK. I just can't be fucked with them. VM & gerald get my vote.

That said, technically, I am not in a position to say which is better at doing the job required, as I only use VM for two simple scripts, which I hope to do away with. Another thing I am not sure about is that GM/VM can use CSP script injection or something?

Probably the person who knows the most about this sort of thing (GM vs VM and the CSP stuff) is @earthlng  - I think he actually uses GM

**Comment by Thorin-Oakenpants** [comment]
> So I will start with a comparison of Greasemonkey vs Violentmonkey what I had been using in the past. I haven't really written any scripts **so I'm not talking about the actual engine** though I would be curious to hear anyone who has anything to say about that.

Well, if anyone wants to actually state a case for why GM should be included in the recommended extensions (as well as, or instead of VM), or enlighten everyone to the differences in abilities, then feel free to re-open

**Comment by ReporterX** [comment]
(Note: I simply summarized what others mentioned)

### Privacy concerns about Violentmonkey

### Obfuscated codes

Even though it is open source, some pointed out Violentmonkey is using obfuscated codes. The code of the addon uploaded to AMO has been processed in such a way that makes it difficult to read and understand what, exactly, it does.

On the other hand,  Greasemonkey does not use obfuscated codes.

About Mozilla policy: Add-ons may contain transpiled, obfuscated, minified or otherwise machine-generated code, but Mozilla needs to review a copy of the human-readable source code. The author must provide this information to Mozilla during submission as well as instructions on how to reproduce the build.

### Author stance on privacy concerns

When taking about its privacy policy, the author uses phrases like "it does not collect any other information **at the moment**" and "There is no plan to collect personal information **at the moment**" which sounds like the author wants to keep those options open. See https://github.com/violentmonkey/violentmonkey/issues/406

**"Are there any plans to expand data collection?"**  
Author: There is no plan to collect personal information **at the moment**. If things change in the future, I'm **pretty sure** there will be something like a popup to let users make their choices.

**"If so, will it be monetized?"**  
Author did not answer.

----

### Conclusion

I won't say one must use or not use Violentmonkey, but I think we should inform users about that and let them decide.

If the author can make open statements to promise with strong words like "never monetize", "never collect user data without explicit consent", I would say it would be much better to clear some peoples' doubt about that and restore their trust.

**Comment by KOLANICH** [comment]
As I have said, GM is the only addon that works in my setup. IDK why. Probably something `about:config` related: VM works neither on Android, nor on desktop. So I keep using GM.

**Comment by tya99** [comment]
This was published today: 

- [Mozilla announces ban on Firefox extensions containing obfuscated code](https://www.zdnet.com/article/mozilla-announces-ban-on-firefox-extensions-containing-obfuscated-code/) - Mozilla also plans to be more aggressive towards taking down extensions that break its policies, with a focus on security issues.
- https://news.ycombinator.com/item?id=19809868

Obfuscation should also not be confused with minified (compressed) code. Minification or compression, refers to the practice of removing whitespace, newlines, or shortening variables for the sake of performance.

> Minified code can be easily de-minified, while deobfuscating obfuscated code takes a lot of time, and using it in the first place has no performance benefits --with its main benefit being of hiding malicious code from source code reviewers.
> 
> "We will no longer accept extensions that contain obfuscated code," said Caitlin Neiman, Add-ons Community Manager at Mozilla.
> 
> "We will continue to allow minified, concatenated, or otherwise machine-generated code as long as the source code is included. If your extension is using obfuscated code, it is essential to submit a new version by June 10th that removes it to avoid having it rejected or blocked."

**Comment by Thorin-Oakenpants** [comment]
FWIW: https://www.greasespot.net/p/privacy-policy.html - last updated 2012

IN one section it says
> We do not collect personal identification information from Users

And then in another section it says
> Greasemonkey may collect and use Users personal information for the following purposes:
>
> * To improve our Application : We may use feedback you provide to improve our products and services.
> * Updates : We may use stored information in order to check for and/or install updates.
> * Synchronization : We may share collected information for the purpose of synchronization across devices, via the standard Firefox Sync feature.

To me that doesn't say anything different to what VM says. While VM may say **at the moment** etc, GM says "Greasemonkey has the discretion to update this privacy policy at any time." . This is all standard terminology IMO.

Put it this way. If VM (or GM) starting sending PII data (or unexpected data: e.g VM doesn't need to connect to any sites in my setup: the scripts are all custom written by myself, no need to look for script updates, and I do not sync), don't you think given the number of users, that it would be found out? And why would the developers risk the wrath and fallout from end-users when it becomes known.

**Comment by KOLANICH** [comment]
>And why would the developers risk the wrath and fallout from end-users when it becomes known.

I guess they consider that they may want to stop their development somewhen and transfer the addons to an another dev. And there were cases when a new dev of something popular asked for control only to insert malware into that software.

**Comment by Thorin-Oakenpants** [comment]
Sure, if they sell the product - which then gets monetized. But the same principle applies - it would get noticed: e.g look at Stylish

**Comment by KOLANICH** [comment]
When this gets noticed it is usually too late.

**Comment by Thorin-Oakenpants** [comment]
That's the nature of anything though. It has to be done first to get found out.

This is why I only use "trusted" and proven work/people: think gorhill, Thomas Rientjes (decentraleyes), kkapsner, et al. Now what "trusted" means depends on the person: I have my defintition, and that includes how active they are, how fast they respond, and a dozen other metrics including longevity and quality of product.

**Comment by KOLANICH** [comment]
`arantius` is known to be maintaining GM for pretty long time, I am using GM at least since ~2010 and I remember that he was the maintainer in 2008.

**Comment by KOLANICH** [comment]
But of course it doesn't mean that a GitHub account cannot be bought or hijacked.

**Comment by Thorin-Oakenpants** [comment]
Yup. Just to be clear, I'm not implying that arantius / GM isn't trustworthy

**Comment by itsmeboy0** [comment]
> The Dev @erosman is very responsive. He was tremendously helpful and patient answering me lot of questions, and solving issues in few hours.

Except for setting up a git repository for the source code apparently (https://github.com/erosman/support/issues/234) 😕

**Comment by Thorin-Oakenpants** [comment]
I can't find that quote on this issue. Please do not hijack my repo for your own whining. As for the linked issue, that has nothing to do with being helpful and patient and answering questions - you are conflating that with YOUR solution. Erosman can do as he likes and make his own decisions, and while you can dislike it, or try to persuade him otherwise, that is not the same as NOT GETTING YOUR OWN WAY and throwing ~~a temper tantrum~~ ketchup on the walls like a giant trump baby

[1] not implying that you are a giant trump toddler, but don;t fucking hijack my repo

**Comment by Thorin-Oakenpants** [comment]
PS: Arkenfox does not recommend any extensions to inject scripts or change styles: VM, GM, TM, Stylus etc
