### ISSUE TITLE
NSFW thumbnails not loading [solved: RFP - use a secondary browser/profile]

### ISSUE THREAD

**Issue by Chippel** [ghacksuserjs/ghacks-user.js#640]
This might be a stupid question but I can't figure out how to fix that. On a popular NSFW site which is called P***ub I got problems with the thumbnails. It seems like the site is loading like 20 thumbnails of videos but as I scroll further down they will dissapear and be replaced with black boxes. Do you guys know what setting I need to change in order to get all the thumbnails?

I tried a clean install and I've figured out that resist browser fingerprint is the issue when enabling just that on a clean install. But I got the same issue with the ghacks profile even if I disable fingerprint.

**Comment by crssi** [comment]
Tried out now and it was the 1st guess: `privacy.resistFingerprinting`

**Comment by Chippel** [comment]
Why that? What else could I do in order to fix that problem?

I did disable it when using the user.js over about:config and I did a restart but it didn't work. Did I forgot something?

**Comment by crssi** [comment]
Set it to false... do not restart. Try out.
When you restart, it get set back to true by user.js directive.

**Comment by crssi** [comment]
Just checked AMO... look what I have found: [Resist Fingerprinting](https://addons.mozilla.org/firefox/addon/resist-fingerprinting/)

OT: I was sure that WE cannot mess with the prefs. I guess I was wrong.

**Comment by KOLANICH** [comment]
WE can mess only with the ones they are explicitly allowed to mess via API and permissions.

**Comment by Chippel** [comment]
Thanks for the help. Let's assume I want to keep resist fingerprint activated. Anything I can do except turning it off to fix the problem?

**Comment by crssi** [comment]
No problem. For sure you want this pref to be `true`. This pref is very powerful and I doubt that you can achieve same level of resisting fingerprinting without it.
So only workarounds I could make of is to use the WebExtension from upper post to temporary disable it when needed, which would be a rare occasion (actually I haven't have any problems with it and your example was first breakage, at least known to me).
The second option is to have another browser just for that purpose and nothing else.

Cheers

**Comment by Chippel** [comment]
Thanks. I'm thinking about using another Browser for that purpose. So another thing I don't like is the tiny window when opening the Browser. Is it possible to maximze it or do I lose fingerprint protection since I changed the window size?

**Comment by crssi** [comment]
Here https://github.com/ghacksuserjs/ghacks-user.js/issues/632#issuecomment-460891261 is a way and also the reason why not to do it. @Thorin-Oakenpants is right (as usual :smile:), but on the end you can decide for yourself. :wink: 

Cheers

**Comment by crssi** [comment]
You should also read section 4500:
https://github.com/ghacksuserjs/ghacks-user.js/blob/de0ebbed2120787ada6f5455639741c4f3ae1466/user.js#L1562
and the section 4600:
https://github.com/ghacksuserjs/ghacks-user.js/blob/de0ebbed2120787ada6f5455639741c4f3ae1466/user.js#L1642

Cheers

**Comment by Chippel** [comment]
Thanks. I've decided to deactivate it because the window is too small and it destroy some sites I visit regularly. 

Is it correct to reenable section 4600 if not using RFP? How do I do it? I've ran the script but it seems like all the values are still the same. Did I forgot something?

**Comment by KOLANICH** [comment]
@Chippel, before deactivating RFP you may want to do some investigation on the causes of the problems. Do you see any strange icons like ![this one](https://dxr.mozilla.org/mozilla-central/raw/browser/themes/shared/notification-icons/canvas-blocked.svg) in your urlbar?

**Comment by crssi** [comment]
@KOLANICH the icon link does not open.
@Chippel  I am sorry, but I don't feel competent to answer that, since I am using RFP and haven't investigate further. If not anyone, then @Thorin-Oakenpants or @earthlng would for sure be the best to answer you.

**Comment by Chippel** [comment]
How in the world got your guys used to that small window? That's a huge difference IMHO

**Comment by KOLANICH** [comment]
@crssi, I have replaced the link with the direct one, now should work.

**Comment by crssi** [comment]
> If you do, you may want to open debugger and search by the keywords like `getImageData` and `toDataURL` and `getContext("webgl")` (try both single and double quotes).

What to do with that?

**Comment by Thorin-Oakenpants** [comment]
> WE can mess only with the ones they are explicitly allowed to mess via API and permissions.

To elaborate on that: a few prefs are accessible for extensions to change thru the [Privacy API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy) - here are some of them: assuming the documentation is up to date

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites
cookieConfig
firstPartyIsolate
hyperlinkAuditingEnabled
protectedContentEnabled
referrersEnabled
resistFingerprinting
thirdPartyCookiesAllowed
trackingProtectionMode

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/network
networkPredictionEnabled
peerConnectionEnabled
webRTCIPHandlingPolicy

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/services
passwordSavingEnabled

**Comment by Thorin-Oakenpants** [comment]
Using an extension to toggle RFP on/off is not a good idea IMO. 3 problems I see:

- at least one of the RFP measure requires a restart  and there may be others - Time Zone spoofing
   * start FF with RFP, your time zone is UTC, then change privacy.ResistFingerprinting to false - your timezone is still UTC
   * however, I just did a test. If RFP is not set on startup, then it seems to work
   * [1491343](https://bugzilla.mozilla.org/show_bug.cgi?id=1491343)
   * NOTE: I am not using multiple FF profiles at the same time in my tests - so my test is not the same as the bugzilla. I'm just pointing out that the environment variable is set on start, and RFP has trouble unsetting the spoofed value

- you will FUCK UP at some stage
   * ooh, porn time ... disable RFP .. watch porn ... enable RFP .. go back to doing some work (assuming your work is not porn)
   * ooh, porn time ... disable RFP .. watch porn .. **forget** to enable RFP
   * ooh, porn time ... disable RFP .. watch porn ... pause porn, check your gmail or something

- JS can run when it wants, it doesn't just have to be when you load a website. So if you have multiple sites open, and then you toggle RFP off, you run the risk that JS can then grab info

----

I had a play around at pornhub, as I thought it might be the canvas component of RFP, but it has nothing to do with that (canvas has a per site permission if you need to override it). Not sure entirely what the cause is.

----

Not using RFP because of one site and due to the size on opening (which has solutions) is a bit silly IMO.

Pornhub solution: use a secondary browser (or profile). You can use a portable Firefox, just for Pornhub. Call it Pornfox :) .. change the theme so it's easier to differentiate. ONLY use it for pornhub. Note: in out wiki we have all the instructions and pretty pictures for you to run multiple Firefoxes concurrently if you want.

THATS the godamn solution, rather than compromising all the good that RFP does because of one site.

The solution to the size on open has already been linked to. See a larger size using the prefs in 4502

eg
```js
// my overrides
user_pref("privacy.window.maxInnerWidth", 1600);
user_pref("privacy.window.maxInnerHeight", 900);
```
