### ISSUE TITLE
Redux - Round two :)

### ISSUE THREAD

**Issue by FlailAway** [ghacksuserjs/ghacks-user.js#641]
Thorin, our posts must have crossed in the Round two thread. See my last post in the now-closed Round two. SSD crapped out on me. 

Still here and will help with a relaxed version. I don't scare that easily. Let me straighten a few things out. I have been programming for 40-years. As you so kindly observed, I am not an idiot and far too many people these (dare I suggest "idiots?") days draw conclusions on very little **known** information. We have just seen that in action in the closed thread. But, thank you very much for hanging in there and also leaping to my defence when the flock was circling. :)

Many many years back when Sun first announced Java I looked at it, couldn't see a need for it in my world so never looked again. I am retired and busier now than when I was working and do not have the time nor inclination to learn and understand Javascript just for this browser functionality, so I am the true neophyte to this paradigm for me. 

I will get to the user.js later today or tomorrow. Thanks again.

**Comment by bodisor** [comment]
> I am retired and busier now than when I was working and do not have the time nor inclination to learn and understand Javascript just for this browser functionality

What have you retired from, kindergarten? Calling others idiots and flock doesn't sound like a grown-up response to what I wrote.
Also, this is not javascript per se. What have you been programming if you cannot tell the difference?!?

I'm sorry for this off-topic replay to his (so far) off-topic post (and new thread). And I apologize to all who read these issues for help or to offer help. I just wanted to show that there's more than one way to look at his requests.

Feel free to hide/delete my post, as it offers nothing to others. I won't replay further.

**Comment by Thorin-Oakenpants** [comment]
Let's not get derailed here.

- Java is not Javascript (JS). They are entirely different.
- The user.js is a JS file, but it's not exactly using any coding - it's just formatted for JS.
- The only JS lines are `pref(` lines and the rules are as simple as it gets

see https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview#small_orange_diamond-working-with-a-userjs

It cannot get any easier. No one is being expected to learn JS. Just follow the formatting (and use a decent IDE to color code, it makes life easier)

And no-one is expected to know everything about web tech and the inner workings of Firefox. It's a massive complex beast, and even Moz devs I talk to about some things, have to refer me and forward my emails to others.

This is why the user.js has a bunch of `[SETUP*` tags, and easy-as-possible non-technical descriptions etc. Admittedly, the tagging needs to be finished, and a relaxed overrides sticky done. I'll get there. That said, it's still a template, and the combinations are astronomical - end users **have** to go thru and work out what suits them best - for a lot of people that could be, run with it and then start *unbreaking things*, or it could be just add a few sections every few days. Or it could be they actually read it and edit it before trying it out. There's no right or wrong answer.

@FlailAway : I thought you had run away, and I hate open tickets. Rather than keep opening new issues, just re-open the current one, if it still pertains to the subject matter. We've now got three issues all for you on the same thing.

Closing this, and re-opening the old one which has the info on your Netflix/Amazon overrides
