### ISSUE TITLE
FPI and security.ssl.disable_session_identifiers

### ISSUE THREAD

**Issue by Kraxys** [ghacksuserjs/ghacks-user.js#643]
In userjs, the preference 1203 _security.ssl.disable_session_identifiers_ is set to _true_ in order to avoid tracking via TLS Session Resumption. But on the other hand, this preference make the user more identifiable ( [Qualys](https://www.ssllabs.com/ssltest/viewMyClient.html) for example sees that there are no session tickets). The point is, **enabling FPI renders 1203 useless** as noticed on [Tor Project](https://trac.torproject.org/projects/tor/ticket/17252) (and currently TBB no more uses this pref). So when enabling FPI (as the userjs does), 1203 only produces the slight disadvantage of an increased entropy. I think this should at least be indicated in section 4000 (First Party Isolation), and that setting _security.ssl.disable_session_identifiers_ to _true_ should be presented as optional, being only useful when FPI is not enabled.

**Comment by Thorin-Oakenpants** [comment]
SSL Session IDs are session only. Just to make that clear. Closing the browser clears them.

enabling FPI renders SSL Session IDs **in Tor Browser** useless (although I kind of dispute that) because first of all TB uses a different protocol, and has enforced mechanisms in place to remove persistent data.

In TB, when you chose a New Identity, everything is cleared. During your Identity session, you are already linked to some degree by the IP (exit node) and maybe a few other FP'ing items such as detecting the real OS (which is totally doable, even if JS/navigator didn't already leak it). And Tor Browser could choose to not use SSL Session IDs, because they can **enforce** that setting on everyone - so their subset of users are a captive audience - TB can do what they like.

There is also another reason they allowed it (along with HTTP2 and AltSrc, and that was to work with Cloudflare IIRC).

**Firefox is NOT Tor Browser**. It doesn't use Tor, doesn't have a captive audience, and doesn't have a comprehensive enforced sanitizing.

Picture this: You do a google search and get a SSL Session ID, then you change VPNs, and return to google and search for something else. The SSL Session ID **absolutely tracks you 100%**, whereas disabling it, only makes you part of a **very very small group** (if used for tracking: and it is server side).

Also consider that Firefox keeps this for up to 24 hours, which is outrageous IMO. Other browsers are **much** quickly at releasing them

Related issues:
https://github.com/ghacksuserjs/ghacks-user.js/issues/571
https://github.com/ghacksuserjs/ghacks-user.js/issues/548
https://github.com/ghacksuserjs/ghacks-user.js/issues/107

also note that we have already added `[SETUP*` tags
```
 * [SETUP-PERF] Relax this if you have FPI enabled (see 4000) *AND* you understand the
 * consequences. FPI isolates these, but it was designed with the Tor protocol in mind,
 * and the Tor Browser has extra protection, including enhanced sanitizing per Identity.
``

**Comment by Kraxys** [comment]
> 
> 
> SSL Session IDs are session only. Just to make that clear. Closing the browser clears them.
> 
> enabling FPI renders SSL Session IDs **in Tor Browser** useless (although I kind of dispute that) because first of all TB uses a different protocol, and has enforced mechanisms in place to remove persistent data.
> 
> In TB, when you chose a New Identity, everything is cleared. During your Identity session, you are already linked to some degree by the IP (exit node) and maybe a few other FP'ing items such as detecting the real OS (which is totally doable, even if JS/navigator didn't already leak it). And Tor Browser could choose to not use SSL Session IDs, because they can **enforce** that setting on everyone - so their subset of users are a captive audience - TB can do what they like.
> 
> There is also another reason they allowed it (along with HTTP2 and AltSrc, and that was to work with Cloudflare IIRC).
> 
> **Firefox is NOT Tor Browser**. It doesn't use Tor, doesn't have a captive audience, and doesn't have a comprehensive enforced sanitizing.
> 
> Picture this: You do a google search and get a SSL Session ID, then you change VPNs, and return to google and search for something else. The SSL Session ID **absolutely tracks you 100%**, whereas disabling it, only makes you part of a **very very small group** (if used for tracking: and it is server side).
> 
> Also consider that Firefox keeps this for up to 24 hours, which is outrageous IMO. Other browsers are **much** quickly at releasing them
> 
> Related issues:
> #571
> #548
> #107
> 
> also note that we have already added `[SETUP*` tags
> 
> ```
>  * [SETUP-PERF] Relax this if you have FPI enabled (see 4000) *AND* you understand the
>  * consequences. FPI isolates these, but it was designed with the Tor protocol in mind,
>  * and the Tor Browser has extra protection, including enhanced sanitizing per Identity.
> ``
> ```

Many thanks for your in depth explanation. Your example is enlightening. But precisely: For what I understand of what you said, the choice is between to be seen to belonging to a "very very small group" and to belonging to a very very very small group (reduced to one people: me). The first alternative is surely better than the second, but not that much. So, what about using FPI in conjunction with e.g. Temporary Containers? In that case, the first party tracking risks (highlighted in your example) is avoided. In that case, wouldn't it be best to not set _security.ssl.disable_session_identifiers_  to _true_?

**Comment by Thorin-Oakenpants** [comment]
https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers#Implementation_Details
^^ This is now over a year old, so not sure on where a few things stand.

Containers are an OA (Origin Attribute). So is FPI (it was based on container work). The third OA is PB Mode (private browsing). OA's can be combined. You can have FPI+Containers, and FPI+PBMode, but you can't have Containers+PBMode.

TC in a hardened config is pretty awesome and FPI is largely redundant (there are some things it doesn't do). If every new instance of a domain/tab is a new contextual id, then it's isolated, and that includes anything that is already OA'able (including SSL Session tickets)

^^ **but**, it would depend on how you set up TC, because a perisistent contextual id will undo that (but may not matter - eg if you set up a permanent container for GitHub, you're logging in anyway).
