### ISSUE TITLE
Site data not being deleted (modified user.js)

### ISSUE THREAD

**Issue by jotyGill** [ghacksuserjs/ghacks-user.js#658]
Hi ghacksusersjs team,

First of all, I can't thank you guys ( Thorin-Oakenpants, earthlng, claustromaniac) enough. The importance and quality of the work you guys are doing can not be overstated :)
(I am working on a setup that now uses ghacksuserjs, more on that later)

I just realised that with the current preferences, all sites data is persistent (big nope for me). Is this intentional?
the responsible pref  user_pref("network.cookie.lifetimePolicy", 2) is commented out.
As per the description this pref is not needed if "network.cookie.cookieBehavior" is set to 2.
I believe it was the case in ghacksuserjs a while back. Now that we are only blocking third party cookies, shouldn't we enable "user_pref("network.cookie.lifetimePolicy", 2)"? or is there a reason for it.
Cheers

**Comment by Thorin-Oakenpants** [comment]
/* 2703: delete cookies and site data on close
   // user_pref("network.cookie.lifetimePolicy", 2);

/* 2803: set what history items to clear on shutdown
user_pref("privacy.clearOnShutdown.cookies", true);
user_pref("privacy.clearOnShutdown.offlineApps", true); // Offline Website Data

^^  **Offline Website Data** includes appCache (2730), localStorage (2710),
       Service Worker cache (2740), and QuotaManager (IndexedDB (2720), asm-cache)

**AFAICT, site data is not persistent**. In FF62 (see #500 ) we changed cookie behavior from block all (and don't delete on close) to allow 1st party (and clear on close). The 2703 pref wouldn't really do anything IMO (there may be some difference in the code on how/what it clears - e.g maybe it doesn't use the quota manager, or misses SW cache, IDK - maybe it ONLY clears the cookies)

Can't remember the exact reasons why (and I use overrides to stick to the previous way), but I think the old way was rather hard (not many people would do it that way) and causes site breakage (I guess? I never see any really, but I'm just one person). On top of that there is FPI. So sure, you could be tracked by persistent storage methods by first party, but only within a session.

**Comment by Thorin-Oakenpants** [comment]
PS: I suspect that (some of) the items in 2803 (and 2804) will get removed. Mozilla are moving all things cookie/storage related (website related) to the UI section about `content blocking`, rather than `history`. 

2703: [SETTING] Privacy & Security>**Content Blocking**>Custom>Choose what to block>Cookies
2803: [SETTING] Privacy & Security>**History**>Custom Settings>Clear history when Firefox closes>Settings

It's duplicitous right now. I expect those two 2803 prefs to get deprecated and the 2703 to apply instead

**Comment by jotyGill** [comment]
Thank you for the info. (I am still new to this, trying to learn)
I found that `user_pref("network.cookie.lifetimePolicy", 2)` directly corresponds to the gui option "Privacy & Security > Cookies and Site Data > Delete cookies and site data when Firefox is closed".
I am using the following from ghacksuser 
```bash
user_pref("privacy.clearOnShutdown.cache", true);
user_pref("privacy.clearOnShutdown.cookies", true);
user_pref("privacy.clearOnShutdown.formdata", true); // Form & Search History (even tried this now)
user_pref("privacy.clearOnShutdown.offlineApps", true); // Offline Website Data
user_pref("privacy.clearOnShutdown.sessions", true); // Active Logins
```
And it would still show persistent data under ""Privacy & Security > Cookies and Site Data".
And when I used `user_pref("network.cookie.lifetimePolicy", 2)` it cleared everything.
This is what lead me to believe that this perticualar preference is required. This leak is specific case with my modification because I do not have
`user_pref("privacy.sanitize.sanitizeOnShutdown", true);`

so either
`user_pref("network.cookie.lifetimePolicy", 2)`
or
`user_pref("privacy.sanitize.sanitizeOnShutdown", true);` 
works.

Hold up. are privacy.clearOnShutdown.* even working??
I also tried using `user_pref("privacy.clearOnShutdown.history", true)` it doesn't clear history on shut.
I am on Firefox 65.0.1 on Ubuntu

**Comment by jotyGill** [comment]
I just confirmed it again by creating a new profile, downloading fresh copy of ghacks user.js, commented out  `user_pref("privacy.sanitize.sanitizeOnShutdown", true);`. Indeed storage remains persistent, the cookies are still there. for some reason "privacy.clearOnShutdown.*" are not working.

**Comment by Thorin-Oakenpants** [comment]
> directly corresponds to the gui option

Indeed. That info is in the user.js

> [SETTING] Privacy & Security>Cookies and Site Data>Delete cookies and site data when Firefox is closed
> // user_pref("network.cookie.lifetimePolicy", 2);

---

> This leak is specific case with my modification because I do not have `user_pref("privacy.sanitize.sanitizeOnShutdown", true);`

Well, the user.js by default **does** have that, which then allows all the clearOnShutdown.* items to function.

Read what 2801 actually says
```js
/* 2802: enable Firefox to clear history items on shutdown
 * [SETTING] Privacy & Security>History>Custom Settings>Clear history when Firefox closes ***/
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
```

If it is NOT set as true, then nothing gets cleared on shutdown. "**history items**" are all the things listed in 2803: cache, cookies, downloads, formdata, history, offlineapps, sessions, sitesettings

**Comment by jotyGill** [comment]
ahh I see. I misunderstood the mechanism.
"[SETTING] Privacy & Security>History>Custom Settings>Clear history when Firefox closes" I believed meant "Clear browsing history". 
Perhaps a line saying that privacy.clearOnShutdown.* options only kick in if we use
`user_pref("privacy.sanitize.sanitizeOnShutdown", true);` might make it more clear to users? or i am just extra dumb today. Again thank you for explaining. you can close this :)

**Comment by tom709** [comment]
I noticed in FF75 that when
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
and
// user_pref("network.cookie.lifetimePolicy", 2);
is commented out, dom storage is *not* cleared when quitting Firefox. Some sites like onvista.de now seem to use dom storage for the login instead of cookies. Likewise it can also be used for tracking.

I would argue that ghacks-user.js should set
user_pref("network.cookie.lifetimePolicy", 2);
by default to clear do storage on exit in the same way it handles cookies.

I was quite shocked when I found that quitting Firefox did not log me out of Onvista even though I thought I would be deleting cookies and all other data.

**Comment by Thorin-Oakenpants** [comment]
Turn on LSNG (dom.storage.next_gen), restart and test again

The problem with lifetimePolicy is that cookies then become session only: and session cookies break things: e.g. a session cookie does not allow shared or service workers (last time I looked). I would have to test to see how Firefox actually treats cookies set this way: I'll have a quick guess and suggest that it just strips any expiry date = exactly the same as a session cookie

**Comment by tom709** [comment]
But dom.storage.next_gen is not in ghacks-user.js as of now. It seems to be off by default in a new profile too.

**Comment by Thorin-Oakenpants** [comment]
But did you try it?

**Comment by tom709** [comment]
I tried it now and yes, dom.storage.next_gen seems to fix the problem too.
So with a new FF profile and putting ghacks-user.js from latest commit into it, quitting FF does *not* log me out of onvista.de.
But if I add "user_pref("dom.storage.next_gen", true);" as the last line into user. js, it does!
Even though I don't understand the details, this seems to be a working substitute for user_pref("network.cookie.lifetimePolicy", 2);.

**Comment by rusty-snake** [comment]
I think mozilla will flip it once they fixed a few bugs. (It was true for FF72 or so, see the diffs).

**Comment by Thorin-Oakenpants** [comment]
> Will you make dom.storage.next_gen=true part of ghacks-user.js?

No. I will wait for them t flip it on their own - because there are potential issues with it (hence why it's not flipped on yet). It was flipped for FF71 but they backtracked, and it's been that way ever since.

From memory (not that I've followed it too deeply) - some users can have issues with existing persistent storage. So if you were to clear all data (ctrl-shift-del, check everything, select for all time, and clear), flip it, and restart: you should be good. I've been using it for the last 3 or 4 releases.

The other issue (and this may be fixed - @gwarser  ) is that LSNG affected some extensions storage - namely: I saw reports about uBO/uMatrix. I've never had that issue.

FYI: Storage management/quota management etc is all a bit wonky with **arbitrary async timing** - which is why your localStorage is not getting cleared on close. I have been able to reproduce this consistently (95% of the time) since FF62 - using new profiles and [this](https://ghacksuserjs.github.io/TorZillaPrint/sanitizing.html) test I made. I have vanilla Firefox profiles from ESR60, ESR68 and FF60 thru to Beta and Dev and Nightly where I can do tests. To test you simply load the test, close the browser (assuming your settings are to sanitize), restart, reload the page: if you have the same problem as me: localStorage doesn't get cleared: note it does when done manually, its just in the sanitize on shutdown process = 95% of the time.

We have an issue about it somewhere. LSNG solves this problem (and other problems such as sharing data between tabs via workers etc) by making it all **a lot** more robust

**Comment by tom709** [comment]
One interesting observation: before clearing dom storage (I must have been accumulating things in there for months without knowing), my ReCaptcha score was 0.3. Now after clearing dom storage, it is 0.1. This is a clear indication that Google is using dom storage for tracking already.
See here: https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php
