### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Just-me-ghacks** [ghacksuserjs/ghacks-user.js#66]
1. `user_pref("browser.backspace_action", 2);` - if it's not a privacy issue, can I set it to 5-6?

2. `user_pref("browser.privatebrowsing.autostart", true);` - why is this commented out?

3. `user_pref("browser.sessionhistory.max_total_viewers", 0);` - is it a privacy / security issue living this commented out?

4. `user_pref("clipboard.autocopy", false);` - is this Linux only?

5. Is commenting out
`user_pref("media.eme.enabled", false);`
`user_pref("browser.eme.ui.enabled", false);`
`user_pref("media.eme.apiVisible", false);`
good for entropy? Do they pose a privacy / security risk if left enabled?

6. **I removed these from my user.js because I think they raise your entropy:**
(please let me know if I got it wrong)

user_pref("media.flac.enabled", true);
user_pref("media.mediasource.enabled", true);
user_pref("media.mediasource.mp4.enabled", true);
user_pref("media.mediasource.webm.audio.enabled", true);
user_pref("media.mp4.enabled", true);
user_pref("media.ogg.enabled", false);
user_pref("media.ogg.flac.enabled", false);
user_pref("media.opus.enabled", false);
user_pref("media.raw.enabled", false);
user_pref("media.wave.enabled", false);
user_pref("media.webm.enabled", true);
user_pref("media.wmf.enabled", true);
user_pref("security.ssl3.dhe_rsa_aes_128_sha", false);
user_pref("security.ssl3.dhe_rsa_aes_256_sha", false);
user_pref("security.ssl3.ecdhe_ecdsa_aes_128_sha", false);
user_pref("security.ssl3.ecdhe_ecdsa_rc4_128_sha", false);
user_pref("security.ssl3.ecdhe_rsa_aes_128_sha", false);
user_pref("security.ssl3.ecdhe_rsa_rc4_128_sha", false);
user_pref("security.ssl3.rsa_des_ede3_sha", false);
user_pref("security.ssl3.rsa_rc4_128_md5", false);
user_pref("security.ssl3.rsa_rc4_128_sha", false);

**Comment by Thorin-Oakenpants** [comment]
1. That's why its in the personal section
2. Because private browsing has consequences and its own rules / containers etc - it is better left as a user choice. Note that it also breaks add-ons (such as self destructing cookies, it also currently breaks containers, and so on - in effect it is at odds with this js which is a more middle ground. It will be turned on in a hardened branch
3. It is commented out, but included for information, because it is best left alone - we just redid the 1000 section and this got a description update. You can read the issue - its in closed issues under discussion: redo 1000s
4. clipboard.autocopy - apparently so
5. media.eme.enabled etc - this is DRM bullshit and using DRM crap opens you right up to FP'ing and abuse. Didn't we discuss all this on ghacks? YES they are a security risk in the sense that you shoudl read EFF and how reporting on security flaws in this DRM etc is highly discouraged, even punished and more, because copyright cartels. YES, absolutely privacy invading potential, in fact, DRM by its very nature is. Probably haven't answered that very well. All the GMP stuff is basically the new wave of flash, plugins wrapped in a new cloak.
6. I'm not looking all that up. The ciphers, we only have currently ones in the js. The 1200s was just revamped (but no pref active changes). The deprecated section holds a handful more. The section description for 1200 explains cipher suite fingerprinting which is server side. Quite frankly, you control as much JS and XSS as possible. To truly defeat FP'ing (and there are sooo many holes right now it's useless, but we try), you use OpSec (and it depends on who you're trying to defeat - we could write books on this topic- nuff said). The media ones were added (under media) because some reason - they're not security risks AFAIK, and they should probably be all moved to personal. I had this conversation with Earthlng months ago. As for the media ones raising your entropy, probably - which ones differ from default, and can those types be AUTO-played or can your browser be detected as accepting them? I don;t usually browse sites with media in them - but I have seen sights where an mp3 will auto-start. So yeah, that's a bit - if other files can do the same (tiny wee files in a hidden frame or something), that's more bits. But only the bits that differ from default. Anyway, you're already highly FP'able - just less so with a lot of the attack surface removed.

Maybe I need to write a wiki article on FP'ing :)

**Comment by Thorin-Oakenpants** [comment]
It's worth noting that [MediaError.message](https://developer.mozilla.org/en-US/docs/Web/API/MediaError/message) lands in 53 (there is no pref behind it), and this could be used for fingerprinting (empty tor ticket [here](https://trac.torproject.org/projects/tor/ticket/21792)). Full source is [here](https://github.com/mdn/dom-examples/tree/master/media/mediaerror).

> The read-only property MediaError.message returns a DOMString which contains a human-readable string offering specific diagnostic details related to the error

I do not know if this limits the strings to pre-defined ones or may leak system information.

**Comment by Just-me-ghacks** [comment]
Thanks, Pants!

1. My bad, I'm perfectly fine with `user_pref("browser.backspace_action", 2);`
I wanted to ask about `user_pref("browser.sessionhistory.max_entries", 2);` - if it's not a privacy issue, can I set it to 5-6?

2. I don't have (any) problems with it so it remains active in my user.js

3. OK here is the [discussion](https://github.com/ghacksuserjs/ghacks-user.js/issues/51) for anyone else interested.

4. If it has no effect in Windows I may as well remove it.

5. OK, I will use the recommended settings. You're right about FP'ing.

6. I won't mess with the default Firefox ciphers and media settings because one can never put too much emphasis on FP'ing. Oh, wait...

**Comment by Thorin-Oakenpants** [comment]
`browser.sessionhistory.max_entries` is currently set at 10. I learned to live with 4 and that's what it was before the 0800 revamp (do try to keep up justme, my old dearie :smile: ). But to be a bit more user friendly, and you can also obfuscate the number using greasemonkey (see the wiki), we raised it to 10 which is probably much more practical.

**Comment by earthlng** [comment]
> It's worth noting that MediaError.message lands in 53

It landed in [FF52](https://developer.mozilla.org/en-US/Firefox/Releases/52#AudioVideoMedia)
Man! why the fuck would they remove the pref??!!! Makes absolutely no sense to me - now the TBB guys need to patch it out again. That goes against everything they try to achieve with the TOR Uplift project.

**Comment by Thorin-Oakenpants** [comment]
Soz, they pushed it thru to 52 then, by a whisker. I can;t see a pref. They even use the words [Don't hide MediaError::message behind a pref](https://bugzilla.mozilla.org/show_bug.cgi?id=1322606#c9)

You said "why would they remove the pref" - so what was the pref you're talking about?

**Comment by Thorin-Oakenpants** [comment]
> I do not know if this limits the strings to pre-defined ones

I see now .. MediaError.number is the pre-defined ones. MediaError.message is user defined

**Comment by Thorin-Oakenpants** [comment]
Hah .. dom.MediaError.message.enabled

**Comment by Atavic** [comment]
By spelunking [here](http://ftp.mozilla.org/pub/firefox/releases/55.0b8/) I found these directories:

**mac-EME-free
Win32-EME-free
Win64-EME-free**

GNU Icecat and Pale-moon are free from this DRM implementation, btw

Info: https://github.com/pyllyukko/user.js/issues/325
