### ISSUE TITLE
Wiki uBlock/uMatrix confusion

### ISSUE THREAD

**Issue by 4Y8Yp8P2EyrkA3VNnBfYfVYnZYigXC5i** [ghacksuserjs/ghacks-user.js#662]
Hi, first time making an issue here. People seem to be using this place to ask some questions so I thought I might as well. (Forgive me if I'm mistaken)

Currently, I feel like the following pages
https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.2-uBlock-Origin
https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.3-uMatrix
are kind of confusing.

Under the assumption that one is using uMatrix, is there any point in making uBlock-Origin Hard Mode?
I read some articles stating how dynamic filtering is essentially redundant with uMatrix. And the only thing it says to do is to turn the "Block remote fonts" on. Am I correct to assume that this means rules such as "Prevent WebRTC" is already redundant with user.js?

Also, about this rule:
>\* 127       * block    ### block access to IPv4 localhost 127.x.x.x
>\* localhost * block
>\* [::1]     * block    ### block access to IPv6 localhost
>\* 192.168   * block    ### block access to LAN 192.168.x.x

Does this mean theses rules are recommend? Or is this merely an example of what people can do with uMatrix?

The wiki also states on the uBlock Origin page:
> Best practice is to default deny-all, then whitelist.

If that's the case, shouldn't there be a guide on how to turn on what is essentially Nightmare Mode in uMatrix? (Although maybe it's not there due to the ease in merely changing global rules)

And finally, I use three other extensions, CookieAutoDelete, Decentraleyes, and HTTPS Everywhere. (list of extensions taken from this site called privacytools.io. I dropped NoScript and Privacy Badger as they seemed useless)

As for CookieAutoDelete, is there a point in using it if I set the "Delete non-blocked cookies" to "NaN" in uMatrix? (Aside from the fact that CookieAutoDelete can whitelist cookies to delete/not delete, and also delete cookies being used, if it wishes to.)

As for using Decentraleyes, is there a point in adding the following rules?
>\* ajax.googleapis.com * noop
\* ajax.aspnetcdn.com * noop
\* ajax.microsoft.com * noop
\* cdnjs.cloudflare.com * noop
\* code.jquery.com * noop
\* cdn.jsdelivr.net * noop
\* yastatic.net * noop
\* yandex.st * noop
\* apps.bdimg.com * noop
\* libs.baidu.com * noop
\* lib.sinaapp.com * noop
\* upcdn.b0.upaiyun.com * noop
\* cdn.bootcss.com * noop
\* sdn.geekzu.org * noop
\* ajax.proxy.ustclug.org * noop

The following rules are apparently recommended with uMatrix, but it only helps if I need to use the following scripts in order to run a page without breaking it, right? If I can fully utilize what I want within a page without allowing these rules, is there a point in making these _global_ noop rules?

Once again, sorry if this is the wrong place for questions. Also would like to say thanks for the wonderful pref config.

**Comment by Thorin-Oakenpants** [comment]
> Best practice is to default deny-all, then whitelist.

Indeed. "best" might be subjective, but a default deny means nothing gets thru and you don't have to rely on lists. The onus of mistakes then falls on the human. A hardened approach is not for everyone, but block-all will always be the most secure/safest default mode by it's very nature.

As for "If that's the case, shouldn't there be a guide" - hell no. Go use uBO's or uMatrix's wiki's and reddit forums etc, or articles like the one we linked in the readme: https://12bytes.org/articles/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs

---

> As for using Decentraleyes, is there a point in adding the following rules

The [wiki extensions](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1-Extensions) page says this under Disconnect
> :exclamation:  uBlock Origin users should add the [following rules](https://git.synz.io/Synzvato/decentraleyes/wikis/Frequently-Asked-Questions)

If you are just using uBO in default config (easy mode) then you won't have any issues - these are not advertising trackers etc. But if use uBO in any other config (e.g block all by default like I do), then you should whitelist them in uBO, so that Decentraleyes can detect the request and substitute local versions.

Your list above does not match the one from Decentraleyes own pages, btw.

If any user wants to change uBO or uMatrix to a hardened mode, then it's up to them to know what they are doing, IMO

---

> Currently, I feel like the following pages ...  are kind of confusing.

They seem pretty straight forward to me. We're not recommending anything - it's up to the end user.

---

> As for CookieAutoDelete, is there a point in using it if I set the "Delete non-blocked cookies" to "NaN" in uMatrix? 

uMatrix only controls cookies via HTTP headers (it lets them in, but blocks them going out). JS can still set and read cookies. Personally I am not a fan of CAD at all (or any cookie extensions) due to the fact that they can leave orphaned persistent local data - I personally think that FF with FPI (and/or Temporary Containers) and internal data control mechanisms and sanitizing is enough - BUT .. everyone has different requirements, so it's up to you.

You first need to work out what **you're** trying to achieve. WTF does NaN mean -I know it means not a number, but does that mean in regards to uM? I assume you mean you block the cookie, because what else could it mean.
