### ISSUE TITLE
Facebook Video loading issue [solution: see issue 635]

### ISSUE THREAD

**Issue by AMihail1** [ghacksuserjs/ghacks-user.js#663]
Anybody know which setting is affecting this? I can get the player to load but when I press play it goes to start the video then refreshes the page bringing me back to the play button.

uBlock doesn't seem to be the issue.

**Comment by Thorin-Oakenpants** [comment]
Need more info. I assume you're using our template? Did you try any overrides (pref changes)? Have you followed [this](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting) ?

In other words. In a new profile with just the user.js (or rather your user.js with changes), does the problem still occur?

As for video: it's usually a combination of settings: I have no idea what Facebook uses

read: https://github.com/ghacksuserjs/ghacks-user.js/issues/635

**Comment by AMihail1** [comment]
> 
> 
> Need more info. I assume you're using our template? Did you try any overrides (pref changes)? Have you followed [this](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting) ?
> 
> In other words. In a new profile with just the user.js (or rather your user.js with changes), does the problem still occur?
> 
> As for video: it's usually a combination of settings: I have no idea what Facebook uses
> 
> read: #635

Thanks - fix was posted in 635 :+1: 

// MY OVERRIDES

user_pref("media.gmp-provider.enabled", true); // 1820
user_pref("media.gmp.trial-create.enabled", true); // 1820
user_pref("media.gmp-manager.updateEnabled", true); // 1820

user_pref("media.gmp-widevinecdm.visible", true); // 1825
user_pref("media.gmp-widevinecdm.enabled", true); // 1825
user_pref("media.gmp-widevinecdm.autoupdate", true); // 1825

user_pref("media.eme.enabled", true); // 1830 - enable EME for Netflix, etc

**Comment by AMihail1** [comment]
False alarm - worked for 1 refresh then began refreshing the page on pressing play again.

**Comment by KOLANICH** [comment]
```javascript
user_pref("media.gmp-widevinecdm.enabled", true); // 1825
```

Does YouTube use Widevine?

**Comment by earthlng** [comment]
Hi

> I can get the player to load but when I press play it goes to start the video then refreshes the page bringing me back to the play button.

1st of all, load the browser console (Ctrl+Shift+J), clear the log and then refresh the page with the video and try to play the video and see if it gives you any hints about what could be wrong.

Some other overrides you can try in addition to the ones you already have:
user_pref("media.autoplay.default", 0);
user_pref("privacy.resistFingerprinting", false);

instead of adding them to your overrides file right away you can just toggle them in about:config and see if it helps with your problem.

Do you have Flash installed? If so, you might have to reset some prefs in the Plugins section (1800)

If none of that works, you can try our troubleshooter script. In the 1st step it will reset all the prefs it has in its list and ask you to test the page again and confirm whether it works now or not. If the video works at that point you can follow the script instructions and it'll try to narrow it down to as few prefs as possible.

**Comment by crssi** [comment]
@AMihail1 can you provide sample URL?

**Comment by AMihail1** [comment]
> 
> 
> @AMihail1 can you provide sample URL?

I can only get the problem to reproduce intermittently, which I can't understand. Any video on facebook.com/videos - it will show the play button and when I press it refresh the whole page and loop back to the play button making the video unwatchable.

**Comment by crssi** [comment]
Now you made me go to FB crap site and find some video.
Everything is playing here nice and fine.
Did you try with all extensions disabled?

**Comment by AMihail1** [comment]
Unable to reproduce this anymore.
