### ISSUE TITLE
discussion: move 2025 media types to personal section

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#67]
This section IMO doesn't really belong in the main js, which is meant to be for privacy, security, FP'ing tweaks. I originally added webm as the default differed (but not any more) and I wanted to view them occasionally. Then feature creep happened - partly because of the changes and migration on the web from flash to html5 (I wanted to make sure all the youtube boxes came up ticked, so users can ditch flash more comfortably), and now it's expanded to include flac and so on. It ended up under the "media" section over the course of it's lifespan so far. I think it's still good information to have, but I see no security issues here.

In FF52 the defaults for all are true, so we differ on 5 of them. Is this FP'able in any way? Does it really matter?
```js
/* currently as in the user.js ***/
/* 2025: enable/disable various media types [SETUP] ***/
user_pref("media.mp4.enabled", true);
user_pref("media.flac.enabled", true); // (FF51+)
user_pref("media.ogg.enabled", false);
user_pref("media.ogg.flac.enabled", false); // (FF51+)
user_pref("media.opus.enabled", false);
user_pref("media.raw.enabled", false);
user_pref("media.wave.enabled", false);
user_pref("media.webm.enabled", true);
user_pref("media.wmf.enabled", true); // https://www.youtube.com/html5 - for the two H.264 entries
```

I propose setting the lot to true, commenting them all out, and moving to the personal section. At the very least, this removes ambiguity over privacy/security concerns, and reduces any possible breakage.

**Comment by 2glops** [comment]
IMO we can leave these prefs as FF52's default, all true.

**Comment by crssi** [comment]
If there is no other issues, I am voting for default also.

**Comment by zymase** [comment]
> [...] setting the lot to true, commenting them all out, and moving to the personal section
I agree. Moreover that besides personal considerations untied to privacy and security (as far as I know) I see no reason for disabling these settings, so left as default (true) and commented out seems pertinent, leaving the information raw for a user who might have his reasons to disable one or another.

**Comment by Thorin-Oakenpants** [comment]
well that's 4 of us so far (and I bet @Just-me-ghacks would be in as well) in favor of a move, default values and commented out. Wonder what @earthlng thinks.

**Comment by earthlng** [comment]
it makes more sense to set them all to FALSE and comment them out. Otherwise we might as well remove them all together.

re: security - there have been exploitable flaws in the past in some media formats fe. see [here](https://www.opswat.com/blog/can-video-file-contain-virus). But they are probably way to hard to find and exploit for most "attackers". On linux (and mac?) there's maybe more of a risk because flaws in FFmpeg are likely easier to find.
I'm not aware that the CIA's Vault7 leaks made any mention of media format exploits but we'll only know for sure once those exploits are made public.  So I'd agree the risk is atm slim to none with keeping FF's default values. 
I personally will probably never need the raw and wave formats for example, so I'll keep those disabled.

re: FP - the fact that the youtube HTML5 page can detect which formats you support without even loading a video is a pretty clear indicator that those things can be fingerprinted.

> Does it really matter?

probably not - we're already easily fingerprinted and I'm okay with whatever you guys want to do with it

**Comment by crssi** [comment]
> re: FP - the fact that the youtube HTML5 page can detect which formats you support without even loading a video is a pretty clear indicator that it can be fingerprinted.

In that case should be set to default or even better, as @earthlng  proposed to comment them out, since it will lower entropy, as far as FP is concerned.
I don't have a personal opinion on security part, yet.
I know FP resistance is a bit futile, but I don't have government grade FP in mind... just want to make a "noise" to commercial ADV databases.

**Comment by Thorin-Oakenpants** [comment]
The exploit part - the problem with those in the past was the software used, not the protocol/format. Remember when media files could exploit WMP? So I really don't think there is a security risk, especially not these days (or as Earthlng says slim to none). Personally I don't use flack or ogg or raw or wave. I guess part of the idea in the past was to reduce the attack surface, and group these things together as people suggested them, but in all reality, we could probably just ditch them

I'll move em to personal, at default, commented out and when we overhaul the personal section (which won't be soon, don't panic) we can deal with it then.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/fd04f6666b1a61054e7967ab1690661d049a1e76

Made em all false, so its easy for end users to uncomment to change from default. That should make *everyone* a happy camper
