### ISSUE TITLE
FF 66 autoplay behaviour changed on Youtube and Netflix?

### ISSUE THREAD

**Issue by seanob86** [ghacksuserjs/ghacks-user.js#670]
On my previous installation of FF 65 and with the user.js latest release autoplay was disabled on websites I frequently visit such as youtube and netflix. For instance if I wanted to watch a youtube video or stream a netflix show I would need to interact with the player and click on play. Loading the video would start in a paused state.

Now I have just updated to FF 66 and now the behaviour has completely changed. Youtube videos automatically start playing as well as Netflix content. The complete opposite behaviour as per 65.

Attaching my autoplay configs from about:config below. 

<img width="620" alt="Screen Shot 2019-03-20 at 09 58 31" src="https://user-images.githubusercontent.com/45988261/54651590-77209d80-4aab-11e9-9809-dda7a6c73050.png">

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1520088

This looks similar, but says fixed in 66. That's what I got when I searched for that blacklist string.

Make sure you have no exceptions
-  Privacy & Security>Permissions>Block websites from automatically playing sound > Exceptions
- uncheck then recheck the option to block
- restart browser

When I get time I might have a look in a nilla profile

**Comment by seanob86** [comment]
Yeah I did check that but I have no exceptions.

**Comment by Thorin-Oakenpants** [comment]
ok .. I'll test .. gimme a cool youtube link

**Comment by seanob86** [comment]
So just some extra info. If I search for a youtube video (my search engine is startpage) and click on one of the results the video starts in a paused state.

But if I go to youtube.com and just click on any of the videos on the homepage, the video auto plays.

Video that disables autoplay when I have searched for a video via search engine:
<img width="96" alt="Screen Shot 2019-03-20 at 10 26 19" src="https://user-images.githubusercontent.com/45988261/54652592-4d697580-4aaf-11e9-9b66-0208c157e382.png">

Video that autoplays when clicking on a video on the youtube.com homepage:
<img width="86" alt="Screen Shot 2019-03-20 at 10 26 36" src="https://user-images.githubusercontent.com/45988261/54652626-62de9f80-4aaf-11e9-9ae9-4d593cabba8f.png">

**Comment by Thorin-Oakenpants** [comment]
I used this one about some cute kittens or something: https://www.youtube.com/watch?v=cbP2N1BQdYc

nilla profile
- test video started playing
- changed option to block autoplay (i.e media.autoplay.default = set as 1 ) - I did this from the options interface
- test video didn't autoplay, but did seek to where I had left it
- cleared everything from all time (ctrl-alt-del) & restarted browser
- test video did not autoplay

added user.js
- cleared everything, closed browser, added user.js, restarted browser
- note: user.js I removed the entire 1800 section (drm, eme, gmp, cdm etc)
- test video did not autoplay

I can't seem to replicate your problem

**Comment by seanob86** [comment]
Thanks for testing.
I have contributed to the following reddit post - https://www.reddit.com/r/firefox/comments/b35aed/is_mediaautoplaydefault_no_longer_supported_after/

Another user has the same problem but it seems as though the behaviour depends on how you first launch the video.

Just confirming did you launch the youtube.com homepage and just click on a random video on the homepage?

**Comment by Thorin-Oakenpants** [comment]
OK, that makes sense now. I replicated what you did. If you click a link from within YT then it isn't auto-blocked, but if you are coming from a different domain, then it is

This will be because Firefox differentiate between 1st/3rd party or whatnot (e.g embedded videos), or that it is same domain and user initiated - i.e if you click on a video link, you probably want to see it, so the autoplay blocking is not used. I'm probably not wording that right, but I think it's Mozilla finding a balance between frustrated users having to click play all the time, and being able to stop unwanted background noise, or embedded vids/ads playing etc

**Comment by Thorin-Oakenpants** [comment]
> Another user has the same problem but it seems as though the behaviour depends on how you first launch the video.

Yeah, that's exactly it. In my initial test I just quickly bookmarked the cat vid, so it was a direct page load, not from within YT at all

**Comment by seanob86** [comment]
> This will be because Firefox differentiate between 1st/3rd party or whatnot (e.g embedded videos), or that it is same domain and user initiated - i.e if you click on a video link, you probably want to see it, so the autoplay blocking is not used. I'm probably not wording that right, but I think it's Mozilla finding a balance between frustrated users having to click play all the time, and being able to stop unwanted background noise, or embedded vids/ads playing etc

Yeah that does make sense. Thanks again for testing 👍

**Comment by earthlng** [comment]
Hi, I think what you're describing is due to the new pref `media.autoplay.enabled.user-gestures-needed`.
AFAIK this makes it so that when you interact with a page (ie clicking a video on youtube), it'll allow autoplay and apparently ignores/overrides the "master" pref `media.autoplay.default`.
Setting it to `false` should probably revert to the old behavior but I haven't tested it.

**Comment by seanob86** [comment]
> Hi, I think what you're describing is due to the new pref `media.autoplay.enabled.user-gestures-needed`.
> AFAIK this makes it so that when you interact with a page (ie clicking a video on youtube), it'll allow autoplay and apparently ignores/overrides the "master" pref `media.autoplay.default`.
> Setting it to `false` should probably revert to the old behavior but I haven't tested it.

Thankyou that works! well setting that pref to false returns FF to 65 behaviour.

**Comment by Thorin-Oakenpants** [comment]
@earthlng - I think we should add that to the user.js as active false - I'll make a note in the diffs issue
