### ISSUE TITLE
Blank white page after scrolling on Github [solved: layers.acceleration.disabled]

### ISSUE THREAD

**Issue by AMihail1** [ghacksuserjs/ghacks-user.js#673]
Not sure if this is user.js related but seems to have only started happening recently and I use your user.js file ... if I click on user.js to open the window with all the code in it, CTRL+F to find a certain section then go to scroll the page goes white - is this some sort of new bug on FF 66?

----

### Update from Thorin:
- This is caused by `layers.acceleration.disabled`=`true` : if you're toggling this pref, you need to restart Firefox for the changes to take place
- earthlng has a uBO filter which will fix this
```
github.com##div.blob-wrapper:style(overflow: visible visible !important)
```

**Comment by Thorin-Oakenpants** [comment]
Yeah that happens to me as well, for probably the last year+ - I have no idea when it started happening

STR:
- PS: using a github dark theme
- https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js
- if I just click on a line number, or even just click in the text itself, I get this
- ![blankityblankblank](https://user-images.githubusercontent.com/16656956/54857759-f656e100-4cf8-11e9-9227-cd8df2e216ef.png)

Interestingly enough .. while grabbing this screenshot and switching between that tab and this, the text reappears sometimes, depends on how fast you switch back I think, some sort of repainting, IDK

My solution has always been
- click the edit button (because I have edit rights)
- on other repos, click the raw button (which loses all syntax coloring etc, but I don't need to do this very often

I suppose we should nail down what causes this

**Comment by AMihail1** [comment]
Having to sift through with syntax is mildly annoying - would love to get to the bottom of this. I have errors on my console on the page if that would provide any help?

**Comment by earthlng** [comment]
Same here. I tried the troubleshooter but it didn't fix the problem. At least that eliminates a bunch of prefs as possible culprits. IDK if it has anything to do with a pref at all or if it's just a bug in Firefox at the moment. However, I found a workaround with an uBlock Origin custom filter that works for me:
```
github.com##div.blob-wrapper:style(overflow: visible visible !important)
```

**Comment by crssi** [comment]
This one is tricky and must be a FF bug.

Its hard to pinpoint, but **it looks like** it happens only when both of those are set to `true`:
``` js
user_pref("layers.acceleration.disabled", true);
user_pref("privacy.resistFingerprinting", true);
```

If any of those or both are set to `false`, this doesn't happen.

But, I can be mistaken. :smile_cat: 


Can anyone set
``` js
user_pref("layers.acceleration.disabled", false);
```
and try to reproduce?

Cheers

**Comment by Thorin-Oakenpants** [comment]
> and try to reproduce?

I have both `layers` and `RFP` true. I set layers as false (did not restart) and I still get the problem.

**Comment by AMihail1** [comment]
I have RFP off and acceleration on since the 1st post.

**Comment by crssi** [comment]
> I have both layers and RFP true. I set layers as false (did not restart) and I still get the problem.

Crap. Its inconsistent, also here looks like it depends of scrolling velocity, if its too low, then everything is OK.
But I cannot reprodurce with:
``` js
user_pref("layers.acceleration.disabled", false;
user_pref("privacy.resistFingerprinting", true);
```

Will play more.

**Comment by Thorin-Oakenpants** [comment]
> also here looks like it depends of scrolling velocity

My steps to reproduce don't include any scrolling. And after my comment about other repo's, I can't reproduce at all, e.g https://github.com/ghacksuserjs/TorZillaPrint/blob/master/js/screen.js - without going to edit mode, I can scroll, click lines, all sorts - but the user.js page here, every time it blanks

**Comment by Thorin-Oakenpants** [comment]
FF66.0.1
- Create a vanilla profile
- Go to https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js , bookmark it
- click on the user.js text, scroll like fuck
- Results: everything is normal
- go to about:config
- change `layers.acceleration.disabled` to `true`
- **RESTART** Firefox
- go to your bookmark
- click on the user.js text, scroll like fuck
- Results: it gets blanked
