### ISSUE TITLE
[user_pref("app.normandy.user_id"] <UID> remain set

### ISSUE THREAD

**Issue by 5t0es** [ghacksuserjs/ghacks-user.js#680]
While normandy is disabled by other prefs, that one left us with an actual <UID> still being sets (in `user_pref("app.normandy.user_id"` )
Could it potentially be used against us in some way? 
Wouldn't it be safer to empty it ("") ?

**Comment by Thorin-Oakenpants** [comment]
Why would Mozilla "use it" against anyone. It's not a weapon. It's just a UUID for when/if any normandy telemetry gets sent. Feel free to clear it, but normandy is already disabled.

Not necessarily aimed at OP, but can we stop the over-paranoia.

---

Definitely not aimed at OP, just a rant.

One of the top ten site referrals for here is a nutcase BS article that gives Firefox a red hot SPYWARE tag and then proceeds to use selected parts of this repo to prove that point, providing their own shitty list of prefs (from here) - e.g ignoring all the facts that a balanced view takes into account - such as the fact that there are no issues with using google's safebrowsing blocklists, and instead disable them all and put people at risk.

Same with librefox, which hasn't done anything since last year, after copying everything from here, bastardizing the product, disabling everything possible, and then trying to stick MY name on it. It's a piece of shit (and a lot of really silly decisions in other areas as well, not just some prefs).

All of this is starting to negatively affect how we're seen. Reddit, for some reason, seems to hate this repo. 4 days ago someone posted a link here for someone who was asking about prefs: he lost his FF profile and couldn't remember all his tweaks. Another poster innocently pointed here as a source for information .... and the post was removed by mods. I can see it in the google cached view and not on reddit.

If you don't trust Mozilla, then stop using their products.

end of rant

**Comment by Thorin-Oakenpants** [comment]
PS: for the record, I don't even have that pref, because normandy has never run in my FF profile

**Comment by Thorin-Oakenpants** [comment]
PPS: sorry for being cranky

**Comment by earthlng** [comment]
@5t0es I don't have "app.normandy.user_id" set either. I'm pretty sure if you reset it, it won't get set again with the user.js in place

**Comment by Thorin-Oakenpants** [comment]
Just FYI: In your profile, **with Firefox closed**, you can delete everything in
- `profile/storage/permanent/chrome`

This `chrome` folder holds a lot of crap and leftovers. It will regenerate data if it is needed. Mine had 20 sqlites and corresponding subfolders. I looked in a lot of them (the sqlites) and they were empty but referred to things like crf, shield, etc. Once I restarted, I got 4 sqlites back. I guess the rest were trash that never got cleaned out.

**make sure FF is closed**

PS: you can also wipe the `storage/indexeddb...` folder if you want - it gets recreated. Your startupCache can also be wiped (this gets rebuilt every time you add/remove extensions and do updates - it will also regenerate when you delete it. All contents of `profile/safebrowsing/` can also be wiped and they will auto-update in time (within a hour or so I think). Often with all the SB changes over time, you will probably have some dead files in there.

**Comment by SjoerdV** [comment]
Just to be sure I added this bit to my user-overrides.js (and run the updater). So these identifiers will be reset every time I start the browser
```
//  Start - Sanitize identifiers
user_pref("app.normandy.user_id", "");
user_pref("security.sandbox.content.tempDirSuffix", "");
user_pref("toolkit.telemetry.cachedClientID", "");
user_pref("browser.contextual-services.contextId", "");
user_pref("browser.newtabpage.activity-stream.impressionId", "");
user_pref("dom.push.userAgentID", "");
//  End - Sanitize identifiers
```

**Comment by Thorin-Oakenpants** [comment]
why sanitize them? telemetry is already disabled, push notifications require subscriptions, activity stream is disabled, etc.

**Comment by SjoerdV** [comment]
The question you should ask would be: why are these identifiers regenerated at all, while the setting controlling them is already set to disabled... So I will stick with my suggestion, anybody can make up their own minds, thank you! Please remove the label 'invalid', because that's representing a subjective view IMHO.

**Comment by Thorin-Oakenpants** [comment]
> why are these identifiers regenerated at all

who F cares if they're not used in AF and they're not even a privacy concern .. but the answer to that is that they are required at runtime - would be a pretty shit code if it couldn't handled nulls/undefined
