### ISSUE TITLE
deeskushun: privacy.trackingprotection.cryptomining.enabled

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#683]
this showed up in 66 i think? anybody know how it works? is it a hard-coded protection, or does it rely on lists, or both?

in `browser.safebrowsing.provider.mozilla.lists` i see...

`base-cryptomining-track-digest256,content-cryptomining-track-digest256`

more prefs...

```
urlclassifier.features.cryptomining.blacklistTables
urlclassifier.features.cryptomining.whitelistTables
```

**Comment by Thorin-Oakenpants** [comment]
tables... so it's using a list .. which would get updated from time to time .. like all the other TP lists, and it's just part of the options in Tracking Protection .. here's a pic from Nightly

![TPstuff](https://user-images.githubusercontent.com/16656956/55562684-05b83000-56e4-11e9-8ddd-d26f4c742e70.png)

**Comment by atomGit** [comment]
that's what i figured, but i was a little curious whether it's using only a list(s) of domains(?) or if some of the detection is hard-coded ... doesn't seem to make much sense to me to depend entirely on lists for detecting JS miners

**Comment by beerisgood** [comment]
@atomGit , @Thorin-Oakenpants 
https://github.com/privacytoolsIO/privacytools.io/issues/809#issuecomment-479865486

browser.safebrowsing.provider.mozilla.lists:
`
base-track-digest256,mozstd-trackwhite-digest256,content-track-digest256,mozplugin-block-digest256,mozplugin2-block-digest256,block-flash-digest256,except-flash-digest256,allow-flashallow-digest256,except-flashallow-digest256,block-flashsubdoc-digest256,except-flashsubdoc-digest256,ads-track-digest256,social-track-digest256,analytics-track-digest256,base-fingerprinting-track-digest256,content-fingerprinting-track-digest256,base-cryptomining-track-digest256,content-cryptomining-track-digest256,fanboyannoyance-ads-digest256,fanboysocial-ads-digest256,easylist-ads-digest256,easyprivacy-ads-digest256,adguard-ads-digest256
`

**Comment by beerisgood** [comment]
So i guess it's safe to activate?

**Comment by KOLANICH** [comment]
it's better to use ublock. IDK why mozilla has this functionality built-in.

**Comment by atomGit** [comment]
there's at least several coin miner lists that uBlock can use - [here's one](https://github.com/hoshsadiq/adblock-nocoin-list)

and yes, i would tend to agree that it's better to use uB than enabling the FF list

**Comment by Thorin-Oakenpants** [comment]
As a default for gazillion of Firefox users, it's all good (especially when they enable it all by default). Only 0.0001% of users are tech savvy wizard savant sneaky bastards like you lot

> IDK why mozilla has this functionality built-in instead of just bundling ublock or an own fork of ublock

Because ... nothing to do, nothing to see, just works .. is the best setup for the default everyday end user. And they don't have to rely on thousands of volunteers to maintain a "sane" list, instead, for business reasons and "reliability", they have a contract.

I say "sane" and "reliable" because FF's idea of tracking here is very different to what you or I might think. I'm not an expert, but Francois kinda explained it once, that they are two "list parts", including some sub- and cross- domains (I think) - so it's not just a basic list, but a curated one.

Also, they wouldn't want to run it thru an extension, but internally where it has more options etc.

PS: don't get me wrong, I think uBO is far superior, but it's too complicated for the average user. Look at Opera, they too have a "simple" adblocker on by default as well. Indicates blockage, and you can click to turn it on/off per site. Anything harder than that, and 95% of users would freak out.

**Comment by Atavic** [comment]
Cryptomining lists: they use https://github.com/disconnectme/disconnect-tracking-protection 

*base-cryptomining-track-digest256*: domains in the Cryptomining category

*content-cryptomining-track-digest256*: placeholder list, currently empty.
Intended to whitelist cryptomining domains (for some reason).

**Comment by earthlng** [comment]
FYI this is the list they use

https://github.com/mozilla-services/shavar-prod-lists/blob/master/disconnect-blacklist.json

source: https://m.wiki.mozilla.org/Security/Tracking_protection#Lists

**Comment by Thorin-Oakenpants** [comment]
https://webtap.princeton.edu/blog/ (while it's still at the top)

Part of the topic, April 12, 2019 by Steven Englehardt
> OpenWPM has a new home at Mozilla. After graduating in 2018, I joined Mozilla’s security engineering team to work on strengthening Firefox’s tracking protection. We’re committed to ensuring users are protected from tracking by default. To that end, we’ve migrated OpenWPM to Mozilla, where it will remain open source to ensure researchers have the tools required to discover privacy-infringing practices on the web. We are also using it ourselves to understand the implications of our new anti-tracking features, to discover fingerprinting scripts and add them to our tracking protection lists, as well as to collect data for a number of ongoing privacy research projects.

**Comment by Atavic** [comment]
*Automated Discovery of Privacy Violations on the Web* (PDF) is about OpenWPM:
https://senglehardt.com/pages/publications.html
