### ISSUE TITLE
privacy.trackingprotection.fingerprinting.enabled

### ISSUE THREAD

**Issue by beerisgood** [ghacksuserjs/ghacks-user.js#684]
What about "privacy.trackingprotection.fingerprinting.enabled" ?

From https://github.com/privacytoolsIO/privacytools.io/issues/808

**Comment by Thorin-Oakenpants** [comment]
Maybe @earthlng has something to say about this, if he does, then he can re-open. IDK where the F he vanishes to for six weeks, but I'm left holding the bag, all on my own. "Pants the Lonely Bagman" they call me now... *sigh*

---

Some background

It's not so bad now that we're into ESR60+. Prior to that there were very valid reasons the live version was always better for ESR52+ users - so much tweaking/changing and fixes and additions of old prefs etc as we really checked things out. And users were waiting out the Quantum release rather than ride the bumpy trains. And doing (integrated ESR + stable) got harder and harder. But now we don't have to worry about it. ESR users can use the archived FF60 release.

But, back then, when we (E and me) discussed a TP list change, this issue came up. Different pref values for different releases. It's why we decided to comment out pref `0422` and add a `[WARNING]`

```
 * [WARNING] We don't recommend enforcing this from here, as available block lists can change
```

--

But now we're just concerned with stable, which is good, because this TP stuff is changing every release. And Mozilla are changing their minds on bits and pieces of it all the time, if you follow the tickets as they try things in Nightly etc.

Honestly, **I'm not interested in keeping up with it all**. Whatever FF do as a default is just fine, and they will ramp it up - they have said so. Otherwise the end-user has a UI. Other than that, we push uBO in several places. Anyone who gets this far in reading this user.js will know about uBO (or they are living under a rock)

It also looks a bit messy - it looks like you have to have custom settings in order to use these? IDK, not interested in figuring it all out, only for it to change per release.

PS: here is a banana :banana:
