### ISSUE TITLE
2429: Wrong default for 66.0.3

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#694]
2429 shows default as true, but it is false for FF 66.0.3.

```
/* 2429: enable (limited but sufficient) window.opener protection [FF65+]
 * Makes rel=noopener implicit for target=_blank in anchor and area elements when no rel attribute is set ***/
user_pref("dom.targetBlankNoOpener.enabled", true); // [DEFAULT: true]
```

**Comment by Thorin-Oakenpants** [comment]
Hmmm .. I wonder if they rolled it back. Thanks, will investigate

**Comment by Thorin-Oakenpants** [comment]
dom.targetBlankNoOpener.enabled

65.0.2: false
66.0.3: false
67.0b11: true

We're on 67-alpha now in the user.js, so I'll leave it in but add the item as a todo in the diffs for 66->67

I won;t waste my time looking to see if was true then rolled back. Wouldn't surprise me that it was at the last second or something, since it's just a pref change

**Comment by Thorin-Oakenpants** [comment]
geeze ... https://github.com/ghacksuserjs/ghacks-user.js/commit/c2034617f0dcef095dc4eda7741b10c8e0dce380 - I added the default info **specifically** for FF67+ . I wondered what the hell was gong on
