### ISSUE TITLE
resistFingerprinting appears to make windows size weird and unique

### ISSUE THREAD

**Issue by sezanzeb** [ghacksuserjs/ghacks-user.js#704]
resistFingerprinting set to true: 
![with_screen](https://user-images.githubusercontent.com/28510156/56814829-81168880-682f-11e9-9b8c-0b261fc7bee5.png)

set to false:
![without_screen](https://user-images.githubusercontent.com/28510156/56814838-84aa0f80-682f-11e9-84e0-75a34f3187ee.png)

Should resistFingerprinting be turned on and is there a way to avoid this problem

tested with panopticlick

**Comment by Atavic** [comment]
Do you have some big taskbar as a some launcher? You get an unfortunate screen size with RFP:

> bits of identifying information
> one in x browsers have this value

A solution is to set maxInnerWidth and maxInnerHeight:
https://github.com/ghacksuserjs/ghacks-user.js/issues/449#issuecomment-399765829

It's under **4502**:
https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js#L1633

**Comment by Thorin-Oakenpants** [comment]
### issue 1: you're doing it wrong

When RFP = false, Panopticlick is getting your actual **screen** size. When RFP = true, it is getting your browser's inner window. Go [here](https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#screen) and see all the measurements (screen, available screen, outer  window, inner window, etc). This is what RFP is protecting you from - making sure all the measurements are reporting the same as your inner window.

RFP not only does that, but also sets the size of **NEW** windows to 1000 wide x 1000 max high (and reduced by 100s if not enough height available). **Just toggling the pref to true will not resize your existing window(s)** .. and by the look of it, you are maximized

### issue 2: you're reading it wrong

This is pasted from a reply I did [here](https://www.ghacks.net/2019/04/24/firefox-not-remembering-the-last-window-size-this-may-fix-it/#comments)

> I’ll try to keep this short. At the end of the day, due to the nature of sites like Panopticlick, AmIUnique etc, the results are tainted. The reasons for this are:
> 
> – they interest and attract people who are interested in privacy (usually with tweaks and extensions etc), so it’s not representative of the “real world”. For example FF’s RFP hash for a 10×10 white canvas is one in 6.73 browsers. That’s almost 15%. That’s over double Firefox’s entire worldwide stats on all platforms. That’s not to say that extensions don’t also use this, but most of them by default fake randomly, and extensions aren’t even used that much (what was that figure? half of FF users have less than 2 extensions or non at all?). This is probably the best example, as canvas produces probably the highest entropy – you’re basically always unique, so it’s the first thing EVERYONE tries to beat – cogito ergo sum: now the results are so far off real world, they actually disportionately poison the overall result.
> – results are tainted by repeat visits of said users, constantly trying to tweak their setups
> – the datasets are small: that’s not the sites’ fault (yes half a million is small)
> – the datasets can be outdated with old information, e.g user agents. Panopticlick only recently changed to a last 45 days (which is a good move), but this then plays into a smaller sampling (see previous point)
> – the tests are outdated or limited
> – some large scale real world tests in the last year confirm all of this
> – PS: That’s not to say they are useless, they are great for seeing what your browser returns.
> 
> There’s a disconnect here from users understanding that while you might be in a pool of 1% of users (e.g say Tor Browser users), that the pool is massive. And what drives FP resistance is tightening up the bucket you are in – by enforcing the FP to be the same. Math is your friend. Lowering entropy (instead of raising it randomly, which just adds “information paradoxes” and breakage) is your friend. There is no point in hiding your browser (Firefox vs chrome), or OS (major platform) or UA as all they do is create more entropy (if trying to raise entropy randomly this is not an issue). And each spoof adds entropy in its own right, not just an overall “is this user using anti-FP’ing). Let’s say you spoof your OS and they can tell you’re not from the TCP/IP stack – that’s entropy. Lets say you spoof your browser from FF66 to FF60, that’s more entropy, and so on. It’s not more entropy when it’s enforced on a set of users. It is more entropy if you look at it worldwide.

So ... one, you didn't let RFP apply its resizing on new windows because you had only just flipped it, and two you're maximized which defeats the purpose, and three, panopticlick etc is a load of bollocks

**Comment by Thorin-Oakenpants** [comment]
PS: Just so you can all shit your pants a little .. imagine what data FB has and can work with when it gets 1+ billion unique visitors/accounts a month (and many of those users over multiple devices), and now imagine how far ahead of the curve they are with anti-FP'ing researchers. I shall refer to their face recognition algorithms as a test case for you.

**Comment by sezanzeb** [comment]
k thanks
