### ISSUE TITLE
Images are broken, like imgur etc

### ISSUE THREAD

**Issue by ErikSteiner** [ghacksuserjs/ghacks-user.js#705]
Images are broken although the images can be viewed by following the link.

So this is the site with the two broken images. You are able to right click the images and select "show graphics" (I use Firefox in German, so I don't know the right naming). I can then see the images. I verified that this is an issue of the user.js by resetting my Firefox. Visiting the site vanilla showed me the images, but when I closed FF, droped the user.js and started it again, they were broken again.

The website: [LINK](https://minecraft.curseforge.com/projects/map-controllers?gameCategorySlug=mc-mods&projectID=274404)
My slightly altered user.js: [LINK2](https://pastebin.com/uBuZLyw5)
![broken](https://user-images.githubusercontent.com/2684018/56837602-87762600-686a-11e9-8f67-5f1a08b03642.PNG)

One of those two pictures:
![636039358080536200](https://user-images.githubusercontent.com/2684018/56837855-7974d500-686b-11e9-962d-b35ff92e6a5c.png)

**Comment by earthlng** [comment]
Hi,

it's because of
```js
/* 1241: disable insecure passive content (such as images) on https pages ***/
user_pref("security.mixed_content.block_display_content", true);
```

How do I know? Always check the console first!
In this case, right-click the missing image and select "copy image location", then open the browser console (Hamburger menu>Web Developer>Browser Console or Ctrl+Shift+J) and paste the image location into the search field and you'll see the error message
`Blocked loading mixed display content “http://dccg.herokuapp.com/...`

**Comment by KOLANICH** [comment]
>I use Firefox in German, so I don't know the right naming

https://blog.mozilla.org/l10n/2019/04/02/changing-the-language-of-firefox-directly-from-the-browser/

**Comment by ErikSteiner** [comment]
Nice guys, thank you for the hint. I am pretty new to this security thing in Firefox. Thank you for your help!

**Comment by Thorin-Oakenpants** [comment]
I'm in the process of reviewing a few prefs that "break" web content, and making sure we have a `[SETUP`* tag on them. This is one of those prefs. Passive content (e.g images) isn't a "security" issue, just a tracking one - i.e the information that your browser requested it is in the clear (not HTTPS) and thus everyone can see it.

HTTP is on a slow road to deprecation, and it's a shame that it takes so long. But with something like over half of the top 1M Alexa sites using HTTPS, and growing, you should see less breakage moving forward. But IDK, because while sites themselves now encrypt (1st party: i.e in your case `minecraft.curseforge.com`) so they don't get scary looking icons in the urlbar about not being secure, they're not necessarily bothered with 3rd party. Another reason why I like this pref, is that a lot of tracking and advert domains are HTTP and reluctant to spend any money or time on it (see numerous stories about how hard it was for sites like techdirt or arstechnica to switch to HTTPS) - that said, all you need for killing of ad networks is uBlock Origin.
