### ISSUE TITLE
Advice on installing user.js on Waterfox or Icecat

### ISSUE THREAD

**Issue by 480gh8q0hg08** [ghacksuserjs/ghacks-user.js#720]
Hi I'm trying to apply the user.js file to either Waterfox or Icecat, and it seems that when I put it in the root directory of the profile, and restart firefox, nothing changes in the about:config settings.  

Anyone know why that is the case? 

(I'm on linux if that matters)

**Comment by claustromaniac** [comment]
Wild guess: that's not your actual profile (see #660). Assuming those forks aren't too different from Firefox, you should be able to go to `about:profiles` and find your profile folder from there.

**Comment by Thorin-Oakenpants** [comment]
you can go to about:support and about the 8th item listed is your profile directory, regardless of being portable or not

**Comment by Thorin-Oakenpants** [comment]
**I do not support forks**. I'm not entirely sure what Waterfox is based on, 56 I think. For a start, everything that was deprecated from 57->60 is now gone from the user.js, but those deprecated since 61 are still there in the deprecated section. And if you get an old archived release, say 56: you'll find it's not as good a quality as now, e.g changes to HTTP2.

Probably your best bet is to get the current version, grab the deprecated stuff from the open sticky issue no. 123 where I archived them, add in the deprecated stuff you need. That would still leave you with prefs set that don't exist (they won;t hurt), but also with prefs that might not be have been fully ready to turn on in 56.

Anyway .. I don;t support forks. Have fun
