### ISSUE TITLE
I can't install addons

### ISSUE THREAD

**Issue by BerberBerthold** [ghacksuserjs/ghacks-user.js#721]
After installing the user.js file (placing it into my profile folder) I can't install any addons, it says "The addon downloaded from this site could not be installed because it appears to be corrupt" whenever I try to install any addon.  I used a fresh profile.

I read your documentation (the wiki) and looked into the user.js file.  I am very new to this so maybe I am missing something important.

**Comment by crssi** [comment]
It is not user.js problem.
There is a massive problem at Mozilla with their verification system:
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047

**Comment by Thorin-Oakenpants** [comment]
Here is your solution: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
** ^^ Try that first.**
- does not apply to Android, unsure about some Linux packages
- does not apply to old FF versions, e.g if you are using anything pre FF60

If you are using ESR60, Dev or Nightly, then go to about:config and set `xpinstall.signatures.required` to false, and close and restart Firefox. This will need allow you to use the extensions, and at some stage they will release an application update

If you are using FF60-66, then try

However, that won't work if you have disabled all the normandy prefs. This is what I did. Do it at your own risk (I did this with a 2 hr copy of my profile that hadn't been affected).
- NOTE: not for older versions of FF (e.g. pre FF60. I have only done this to my FF66 profile)
- Close FF
- :exclamation: Backup your profile
- Open a different browser, e.g chrome or whatever, and download and save this xpi
   * https://storage.googleapis.com/moz-fx-normandy-prod-addons/extensions/hotfix-update-xpi-intermediate@mozilla.com-1.0.2-signed.xpi
- Open Firefox
- go to about:addons
- click on the little cog wheel and select "install addon from file" and install the xpi you downloaded
- one done, close Firefox
- go to your `profile/extensions` folder and delete the xpi since it is now finished with (you can't remove it from about:addons as it does not show)
- Open Firefox

This xpi adds the new temporary cert which isn't expired
