### ISSUE TITLE
Problem with addons after recent signature debacle and it's hotfixes: After update that's supposed to fix the issue = still not working

### ISSUE THREAD

**Issue by LtqxWYEG** [ghacksuserjs/ghacks-user.js#722]
Hi,

after todays update the issue should be fixed, but not for me. **Therefore I assume it has to be the user.js that breaks or prevents the hotfix from working.** And that's the reason why I ask here. You know the user.js.

I tried changing these setting in the user.js in order make studies work, but to no avail:
app.normandy.enabled
app.normandy.run_interval_seconds
app.normandy.first_run
datareporting.healthreport.uploadEnabled
datareporting.policy.dataSubmissionEnabled
app.shield.optoutstudies.enabled

That seemed to at least make it receive the studies:
hotfix-update-xpi-signing-intermediate-bug-1548973•Active
hotfix-reset-xpi-verification-timestamp-1548973•Complete

So now I have the hotfixes AND the new update installed, but it still doesn't work.

Anything else I can try?

**Comment by Thorin-Oakenpants** [comment]
The only thing that this user.js does that could affect it, is that we had disabled normandy and telemetry - you need to enable telemetry in order to get studies. Sp I would assume you reset those as well?

If you received the studies then it should have worked. Did you restart Firefox? Do the studies show as completed in about:studies?

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

> We’re aware that some users are reporting that their extensions remain disabled with both studies active. We’re tracking this issue on Bugzilla in bug 1549078

Firefox 66.0.4 is now officially out. Just update

**Comment by Thorin-Oakenpants** [comment]
FWIW, I manually applied the hotifx and it worked for me with all normandy and telemetry disabled. I didn't change any of my prefs - so the prefs don;t prevent the hotfix from being applied
