### ISSUE TITLE
dom.IntersectionObserver.enabled = false breaks Reddit Enhancement Suite (back/forward buttons)

### ISSUE THREAD

**Issue by Emetophobe** [ghacksuserjs/ghacks-user.js#737]
With Reddit Enhancement Suite and  "dom.IntersectionObserver.enabled" set to false the back/forward button at the bottom of every sub reddit disappears completely. When set to true the buttons re-appear and work as intended (after a page reload).

Setting "dom.IntersectionObserver.enabled" to false also breaks the neverending reddit scroll feature. That seems like expected behaviour though if the Intersection Observer API is disabled. https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API:

* Lazy-loading of images or other content as a page is scrolled.
* Implementing "infinite scrolling" web sites, where more and more content is loaded and rendered as you scroll, so that the user doesn't have to flip through pages.

**Comment by crssi** [comment]
If I visit [https://www.reddit.com/r/Enhancement/](https://www.reddit.com/r/Enhancement/) the "inifnite scrolling" works just fine with `dom.IntersectionObserver.enabled = false`

**Comment by crssi** [comment]
I have found another.

With `dom.IntersectionObserver.enabled = false` open [https://bugzilla.mozilla.org/show_bug.cgi?id=1555317](https://bugzilla.mozilla.org/show_bug.cgi?id=1555317), pay attention to comment 6,7 and 8... there are missing screenshots.

Set `dom.IntersectionObserver.enabled = true` and reload upper sample link, pay attention to comment 6,7 and 8... there are visible screenshots as they should be.

@Thorin-Oakenpants Can you comment... if we block ADs with uBO and such, is then `2426` a problem if set to `true`?
I am thinking, but all dark in my mind. Already too late here.

Cheers

**Comment by Thorin-Oakenpants** [comment]
FWIW, it is default true in TB, but that's only because they haven't gotten around to [investigating it](https://trac.torproject.org/projects/tor/ticket/26606)

Yes, it is true that you control most damage by controlling your third party connections, JS, etc - but the user.js can't make assumptions about what extensions or MO (modus operandi) end users use

But if you read the MDN, this API is an easier and more reliable way to determine stuff, than older methods. Clearly it is getting some uptake - e.g by determining whats visible to initiate lazy-loading, infinite scrolling, etc - as pointed out by OP. As for the breakage in bugzilla, you can still view the image - but this wouldn't be the case everywhere.

It's also trivial to detect if the API is enabled or not = yet another FP'ing bit.

The question for me comes down to, does it actually leak anything new, or can be used to bypass any other protections. I'm not sure. I don't particularly see pixel level detection as a problem: only sub-pixel, which this may leak - I would need to build a test.

See that bugzilla .. sitting on it for 11 months, reminds me of [this one](https://trac.torproject.org/projects/tor/ticket/26607) which they also sat on for 10 months until I pointed with a simple test, that it did leak

IANAE, but I don't really see this being used in the wild for FPing: and if ad companies abuse it, well fuck em, this API is not how you beat adverts or corporate surveillance. So yeah, I would be inclined to disable it if it gives you problems.

**Comment by Thorin-Oakenpants** [comment]
there's also [source](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry) an `IntersectionObserverEntry.time` value that needs to be checked that it is covered by RFP

**Comment by Thorin-Oakenpants** [comment]
It also can use timers to build browsing profiles: https://jsfiddle.net/api/mdn/

When an element is in view, the timer for that element increments. This is more in the realm of behavioral FP'ing. Not even sure if it's useful in this way. Keyboard is (how fast you type, or repeated typos: e.g I have a habit of using `;` instead of `'` cuz I am a shit typist). And while KB analysis would be universal, this "visibility" one would depend on each page.

**Comment by crssi** [comment]
Thank you @Thorin-Oakenpants.
Note: upper link `https://jsfiddle.net/api/mdn/` leads to 404.

Cheers :heart:

**Comment by Thorin-Oakenpants** [comment]
I suspect that this can leak sub-pixels since it uses clientRec

**Comment by Thorin-Oakenpants** [comment]
There's also a Resize Observer API in 68+: https://bugzilla.mozilla.org/show_bug.cgi?id=1272409

**Comment by Thorin-Oakenpants** [comment]
Subpixels can already be detected via other means (assuming this can even do that), and this API doesn't seem to leak anything extra AFAICT - you could use older (sometimes less-reliable) methods in dom. Given more uptake with it over the web since FF55 = more breakage, I'm inclined to make the pref inactive and leave at default like TB
