### ISSUE TITLE
toolkit.telemetry.cachedClientID keeps repopulating since Firefox 67

### ISSUE THREAD

**Issue by roviavas** [ghacksuserjs/ghacks-user.js#739]
On Firefox 66 and older versions, `toolkit.telemetry.cachedClientID` would not show up with telemetry disabled (by policies.json.).
However, after upgrading to 67, Firefox keeps setting `toolkit.telemetry.cachedClientID` to a UUID-like string. Resetting or setting it to an empty string does not help. It just repopulate the next day.
I have also tried modifying other telemetry-related entries, but cannot find the way to stop it.
Any idea?

**Comment by claustromaniac** [comment]
Apparently, Firefox now resets the pref if the value is invalid.

https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/app/ClientID.jsm#232-240

**Comment by Thorin-Oakenpants** [comment]
If you're not sending any telemetry data back then it doesn't matter

**Comment by claustromaniac** [comment]
> then it doesn't matter

Is there any point in keeping that pref around then? I'm asking more out of curiosity than anything else.

**Comment by Thorin-Oakenpants** [comment]
Oh, I didn't realize it was in the user.js - got confused with some other `id` pref someone else mentioned several weeks ago

**Comment by Thorin-Oakenpants** [comment]
FWIW, my `toolkit.telemetry.cachedClientID` is blank. Been on 67, now 67.0.1, for, IDK, 6 days or so. Loads of restarts.

Where is it getting set from? A system add-on?

**Comment by claustromaniac** [comment]
> Where is it getting set from? A system add-on?

A function in the ClientID module itself is resetting the pref. Are there any errors in your console when you launch Firefox that may be related to that? Something in your setup must be preventing that code from running somehow... I can try to dig a bit more but it will take a while

**Comment by Thorin-Oakenpants** [comment]
fuk, just did a big edit in my last post

**Comment by Thorin-Oakenpants** [comment]
This is what Nightly does - it's a nilla profile, with just the user.js overwriting the pref
![console](https://user-images.githubusercontent.com/16656956/59054488-56364000-8883-11e9-9e7a-661233706427.png)

**Comment by claustromaniac** [comment]
I think what's going on is simply that you already had that empty clientID cached, and the function was simply retrieving it from disk, see here

https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/app/ClientID.jsm#220-229

If you reset the pref in your FF67 profile and restart, Firefox will most likely end up resetting the pref again over and over afterwards.

**Comment by Thorin-Oakenpants** [comment]
I'll have to fuck around in 68. Because nightly keeps resetting the option to send telemetry. I disabled that and the id got removed. But now I can't replicate that and instead got trumpy's cofffeeeeeeeefeeee

`c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0`

**Comment by Thorin-Oakenpants** [comment]
Actually `c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0` seems to be a generic string they use

**Comment by Thorin-Oakenpants** [comment]
Jesus, what a mess

Nightly sometimes resets the UI to send telemetry, the one in Privacy & Security> Data Collection and Use > Allow Nightly to send techincal....

With the option unchecked on startup, the pref doesn't exist (despite the user.js) but then manifests after about a minute: and gets set consistently to `c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0`, turn the UI telemetry option on, and it gets set to a unique string, uncheck it and you get Trumps `cofefe` again.

If anyone cares to dig deeper, then test it in 67 or 68, not nightly. BTW, nightly is my only installed version: all the others are portable. I've tried various things,. such as removing all telemetry traces (saved pings), clearing the startupcache, wiping the permanent chrome idbs (which get recreated) - it has nothing to with them

**Comment by claustromaniac** [comment]
> and instead got trumpy's cofffeeeeeeeefeeee

You only complain because you're getting ☕️ instead of :beer:

FWIW, the cached ID is stored in `profile_dir/datareporting/state.json`. Restricting write access to that file does not prevent Firefox from generating a new ID on restart, but it prevents it from writing it to disk, meaning your client gets a new ID on every restart.

**Comment by Thorin-Oakenpants** [comment]
OK, so here's some MOAR stuff.

The pref does not exist, and the toolkit.telemetry does not set it

Pic1: immediately after starting
![MOAR-console](https://user-images.githubusercontent.com/16656956/59056232-46b8f600-8887-11e9-9cbd-3e36174ce2c2.png)

but after about a minute, it gets "shows" as reset at the exact same time the `info` appears -> view-source:resource://services-settings/remote-settings.js

Pic 2: about a minute later
![MOAR-console2](https://user-images.githubusercontent.com/16656956/59056382-9697bd00-8887-11e9-83f6-9dfc58735a4a.png)

Of course that might just be when the pref change is picked up to display to about:config - but nah, cuz I see pref changes happen in real time, so I don't think that's it.

End of the day, go play in a non nightly, I think

**Comment by Thorin-Oakenpants** [comment]
all yours

**Comment by Thorin-Oakenpants** [comment]
I can't even reproduce in 68. In a nilla profile, I added the entire user.js. Restarted, checked, waited, checked the UI options for telemetry were all unchecked .. waited, checked the pref - closed. Redid it three times. The pref remains blanks

OP says he gets it in 67 - I don't. I can't even get it in a new 68.

**Comment by claustromaniac** [comment]
Telemetry is not optional on Nightly. Maybe it can be disabled with policies.json, but I wouldn't bet on that.

https://blog.nightly.mozilla.org/2018/06/27/protecting-your-privacy-in-firefox-pre-release/

You say the pref doesn't reset for you, but you are getting the same error as I, so the code for resetting the pref is running on your end too.

I'll look into this later.

**Comment by claustromaniac** [comment]
I have a few minutes for this... My first link above:

https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/app/ClientID.jsm#232-240

That is meant to make sure the value is a **string**, and only reset the pref if not. That is outright weird, because `""` is a string (and empty one, but a string). Why the hell is this condition...
```js
    if (Services.prefs.prefHasUserValue(PREF_CACHED_CLIENTID) &&
        Services.prefs.getPrefType(PREF_CACHED_CLIENTID) != Ci.nsIPrefBranch.PREF_STRING)
```
returning true on launch?... I'm gonna test a few things...

**Comment by claustromaniac** [comment]
OK... I didn't test shit yet. I mean, I did, but I only tested ONE thing, and it wasn't all that important. I kept digging in the source code though, and AFAICT this pref is only used as a cache presumably to avoid repeat reads from disk, but also apparently for some comparisons. When FF launches it looks for the file I mentioned above, reads the Client ID property there, and sets the value of this pref afterwards. The delay you mentioned is intentional, and explained [here](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/app/TelemetryController.jsm#661-663).

I can keep digging later, but TBH, it's already looking like a waste of time, because the pref ends up in two places: `prefs.js` (and I still don't know why they keep saving this pref in that file - maybe they're in the transition to stop doing that, or they don't care) and `state.json` (which is beyond the reach of this project). So far I'm not seeing any reason to keep this pref in the user.js.

**Comment by openffchrome** [comment]
i'm using
pref("browser.newtabpage.activity-stream.impressionId", "");

in my firefox.cfg and it's alway clean.

**Comment by roviavas** [comment]
> FWIW, the cached ID is stored in `profile_dir/datareporting/state.json`. 

I didn't have a datareporting folder in my old profile (I made a backup before upgrading). Yet somehow there is a `datareporting/state.json` in my current profile and the creation date is exactly the date I upgraded to Firefox 67.

I'm not sure why it got created after upgrading. I will delete that folder and see if it will be recreated after some time.

**Comment by claustromaniac** [comment]
> I will delete that folder and see if it will be recreated after some time.

It will be recreated the next time you restart Firefox.

**Comment by claustromaniac** [comment]
@openffchrome `pref()` doesn't do the trick on my end, but `lockPref()` does. At least that's better than messing with `datareporting/state.js`...

**Comment by claustromaniac** [comment]
Actually, it doesn't matter if the value of `toolkit.telemetry.cachedClientID` is `""` or not, because the ClientID module still has the ID it reads from `state.js` stored in the `_clientID` property at runtime, and accesses it from there. The most that can be done is to prevent Firefox from saving the ID to disk, which causes it to generate a new different ID for each session. Now the question is, is this worth documenting?

**Comment by Thorin-Oakenpants** [comment]
Not sure why nobody seems to understand that **my** FF67 (portable) is not setting a new value on any restarts. So there is clearly a way to block it entirely. I've usually use my browser in 4 or 5 hrs lots at a minimum. I left it running for since I was last here. Checked it (blank), closed, restarted, checked (still blank) and so on. **The `log.jsm 679` line is never fired**

Here's a little flowchart for everyone (it's humor, roll with it: not saying anyone fucked up)
![DYFWI](https://user-images.githubusercontent.com/16656956/59080347-c2429380-88d7-11e9-8d1c-97afc8327243.jpg)

**Comment by Thorin-Oakenpants** [comment]
FWIW, I have a `datareporting/state.json` last modified 28-May-2019 (with a valid id). I wonder what's so different about my setup.

**Comment by Thorin-Oakenpants** [comment]
And now FF reset it - you guys put a pox on me. I was fine until the whole saga was brought up and I experimented :sigh:

**Comment by Thorin-Oakenpants** [comment]
Some reading for :cat2: 
- [FF44](https://bugzilla.mozilla.org/show_bug.cgi?id=1186488) - [diff](https://bugzilla.mozilla.org/attachment.cgi?id=8663535&action=diff)

PS: [This](https://bugzilla.mozilla.org/show_bug.cgi?id=1353106#c2) is from 2 years ago
> This cached clientId gets created when Telemetry initializes....

I'm not sure what they changed in 67 - I've looked at all 67 fixed Telemetry bugs, I've searched, I used mercurial. But I find it strange that I don;t seem to trigger this, except now that its been brought to my attention, it changed once in "24" hrs, and never on a restart. Know what else checked once every 24 hrs? That intermediate cert check for extensions - totally jumping the gun here - but any bugs stemming from that, e.g to strengthen how they can push a rapid fix, might not be public yet. 

Anyway, I've set my state.json id to a blank string and will see what happens in the next 24 hrs. But I think this is the wrong approach. Telemetry needs to initiate in order to do it, and I don't seem to trigger that (at least not on a start)

**Comment by roviavas** [comment]
You are right. It's back again.

I also tried deleting state.json, locking the datareporting folder, resetting every pref with a timestamp as its value, and restarting Firefox.
Then I got this error.
```
Unix error 1 during operation open on file /path/to/profile/datareporting/state.json (Operation not permitted) RemoteSettingsComponents.jsm:23
    notify resource://services-settings/RemoteSettingsComponents.jsm:23
```
And a new ID was generated.

**Comment by claustromaniac** [comment]
> **The `log.jsm 679` line is never fired**

That's not as important as I first thought. It's just meant to ensure the value of the pref is a string, and if it's not a string it clears the pref (to nothing). The check for actual validity is the [`isValidClientID()`](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/app/ClientID.jsm#45-48) function, that is called from `getCachedClientID()` and [`updateClientID()`](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/app/ClientID.jsm#325-335), which is in turn called from [`_doLoadClientID()`](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/app/ClientID.jsm#148-179).

> It seems to happen when `app.update.lastUpdateTime.services-settings-poll-changes` is updated.

I'd say that's a coincidence. `services.settings.poll_interval` is used for [remote settings](https://dxr.mozilla.org/mozilla-central/source/modules/libpref/init/all.js#2695-2696). [RemoteSettings.srt](https://dxr.mozilla.org/mozilla-central/source/services/common/docs/RemoteSettings.rst#3-7)

Let me summarize to you what I've gathered, in english (or something close to english):
- The client id (the string itself) is **only** generated/rebuilt around 1 minute after Firefox starts. The delay is intentional to allow the client to load fully (briefly explained [here](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/app/TelemetryController.jsm#661-663)).
- Once generated, it is saved to disk (in `state.json`) and the **pref** is set to the same value.
- The **pref** exists solely in case the ID needs to be read anytime before telemetry fully initializes (which happens after around 1 min, as previously stated). I wasn't sure of this, but I am now after reading [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1353106#c2) (thanks :jeans: for the link). The pref is read immediately on launch from `prefs.js`. This is why the pref is called **cached**ClientID.

I'm sorry to spoil the fun, but AFAIK this pref has always been relevant only during that minute after startup. It exists to fulfill that specific role. Setting it to "" in earlier versions only prevented Firefox from sending a unique ID during that first minute of runtime. Firefox still had a unique ID stored in `state.json` back then.

The key difference with versions prior to 67 is that Firefox now checks the ID for validity, and generates a new ID if invalid (empty string is now considered invalid), but this is done after that 1-min delay. Before then, Firefox merely clears the pref if its value is invalid (but doesn't repopulate it until telemetry fully initializes). This explains the console error (it's logged by the check that clears the pref) and why the pref is set to a unique ID after the delay.

The pref alone should be nearly useless nowadays. I still didn't get around to testing how different clients behave though, I gathered all of this reading and doing a few tests in my main profile. I don't have a clue why the pref does not or did not get set to a new ID for you guys after full telemetry initialization, but as I explained here, the pref itself is not that important because it is only relevant for that first min of runtime.

**Comment by roviavas** [comment]
I don't think it's a coincidence.

In `resource://services-settings/RemoteSettingsComponents.jsm`:
```
ChromeUtils.defineModuleGetter(this, "RemoteSettings",
  "resource://services-settings/remote-settings.js");
```

In `resource://services-settings/remote-settings.js`:
```
ChromeUtils.defineModuleGetter(this, "UptakeTelemetry",
                               "resource://services-common/uptake-telemetry.js");
```

In `resource://services-common/uptake-telemetry.js`:
```
ChromeUtils.defineModuleGetter(this, "ClientID",
                               "resource://gre/modules/ClientID.jsm");
```

Finally, in `resource://gre/modules/ClientID.jsm`:
```
XPCOMUtils.defineLazyGetter(this, "gDatareportingPath", () => {
  return OS.Path.join(OS.Constants.Path.profileDir, "datareporting");
});

XPCOMUtils.defineLazyGetter(this, "gStateFilePath", () => {
  return OS.Path.join(gDatareportingPath, "state.json");
});

const PREF_CACHED_CLIENTID = "toolkit.telemetry.cachedClientID";
```

**Comment by claustromaniac** [comment]
Slightly OT:

:jeans:, where you aware of this...? (emphasis mine)

>`toolkit.telemetry.enabled`
>
>    If `unified` is off, this controls whether the Telemetry module is enabled. It can be set or unset via the Preferences dialog in Firefox for Android (Fennec). If `unified` is on, this is locked to `true` if `MOZ_UPDATE_CHANNEL` is `nightly` or `aurora` or `beta` or `default` (which is the default value of `MOZ_UPDATE_CHANNEL` for developer builds). Otherwise it is locked to `false`. **This controls a diminishing number of things and is intended to be deprecated, and then removed.**

https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/internals/preferences.html

**Comment by claustromaniac** [comment]
> I don't think it's a coincidence.

*Coincidence* is not the right word. I meant to say that the fact that those things seem to correlate by observation does not mean that the code for generating/storing/reading the ID depends on or is affected by those prefs you mentioned.

BTW, the lazy getters `gDatareportingPath` and `gStateFilePath` in `resource://gre/modules/ClientID.jsm` in that code you pasted are used to get the path to the `datareporting/state.json` file.

**Comment by Thorin-Oakenpants** [comment]
was I aware of that? Nope? **All greek to me** (that's slang for WTF does that mean). As long as the all telemetry can be disabled (despite the growing number of prefs) then I'm happy.

So, 24 hrs was a good guess, since the default is 86400 seconds. FWIW, I wouldn't mess with that, for all I know it's used for other purposes: and not worth while investigating. I for one do not like messing with timers in FF.

https://github.com/ghacksuserjs/ghacks-user.js/issues/739#issuecomment-499508615
> If you're not sending any telemetry data back then it doesn't matter

So I guess we can remove the pref from the js, since it's 1) redundant and 2) useless. Right?

**Comment by claustromaniac** [comment]
> As long as the all telemetry can be disabled (despite the growing number of prefs) then I'm happy.

I was pointing out that they intend to deprecate and eventually remove `toolkit.telemetry.enabled`, which sucks, because I imagine the number of prefs needed to fully disable telemetry will skyrocket when that happens.

> So I guess we can remove the pref from the js, since it's 1) redundant and 2) useless. Right?

I leaned toward removing it, at first, but personally, I'd just leave it there for now. Maybe we should just point out that it is only relevant before telemetry initializes fully (and link to sources), as a FYI. IDK, up to you.

**Comment by Thorin-Oakenpants** [comment]
Pros
- one less pref is always good

Cons
- people will cry and earthlng will have a hernia

**Comment by claustromaniac** [comment]
Thanks for reporting this, @roviavas
