### ISSUE TITLE
Is it possible to change the letterbox background color?

### ISSUE THREAD

**Issue by GIPeon** [ghacksuserjs/ghacks-user.js#747]
I've tried fiddling with `browser.display.background_color` but without success. 
Any suggestion? Thanks!

**Comment by Okamoi** [comment]
Failing an `about:config` solution, I would use `userChrome.css` with

```css
.browserStack {
  background-color: rgb(0, 0, 0) !important;
}
```

**Comment by GIPeon** [comment]
Brilliant! 
Looking around for docs on `userChrome.css` I found this ([source](https://www.userchrome.org/how-create-userchrome-css.html)):

> (6) Set Firefox to look for userChrome.css at startup (updated 5/24/2019)
> 
> To make startup faster for most users, Firefox 69 will no longer look for this file automatically. You need to tell it to look. Here's how:
> 
> - In a new tab, type or paste about:config in the address bar and press Enter/Return. Click the button accepting the risk.
> - In the search box above the list, type or paste `userprof` and pause while the list is filtered. If you do not see anything on the list, please ignore the rest of these instructions. You can close this tab now.
> - Double-click the `toolkit.legacyUserProfileCustomizations.stylesheets` preference to switch the value from false to true.
> 
> That change should take effect on your next startup.

Are there any RFP side effects using `userChrome.css` customisations?

**Comment by Okamoi** [comment]
The chrome is inaccessible to websites, so the only things they should be able to detect are modifications to the size of the viewport, or the viewport/window ratio. But that is covered by `privacy.resistFingerprinting` in windowed mode, and Letterboxing in maximized and full screen mode.

So I'd say it's safe. `userContent.css` would be the detectable kind, as it allows to let's say change Github's background color to pink and add blackjack and hookers animated gifs. Github might notice.

The downside of `userChrome.css` is that you need to update it yourself when it breaks, which happens every now and then as Firefox updates and the properties targetted by `userChrome.css` change. Maybe 3 times a year ? Depends on how many rules you have. If you only use this one, you should be fine for quite some time, assuming the graphical appearance of the Letterboxing feature is stable. (Which I'm not sure it is.)

**Comment by crssi** [comment]
@Okamoi 

> 
> 
> Failing an `about:config` solution, I would use `userChrome.css` with, for a black background:
> 
> ```css
> .browserStack {
>   background-color: rgb(0, 0, 0);
> }
> ```

Interestingly the canvas is immediately repainted into white color, when opening a new tab, when a new tab is set to be blank page, even the class is still .browserstack.

**Comment by Okamoi** [comment]
Yeah it's not surprising that using such a generic class would have side effects, but I don't know another way to target the "Letterbox area". Anything that uses the CSS class `browserStack` is going to get a custom coloured background unless or until it specifies its own colour.

To experiment with shit like that it's best to use a separate profile and explore the chrome with developer tools (two checkboxes must be ticked at the bottom of the advanced parameters section of the tools, and then a "special" version must be opened with CTRL+ALT+SHIFT+I)

**Comment by crssi** [comment]
> is going to get a custom coloured background unless or until it specifies its own colour

True, that is why a flickering happens, where the `!important` should prevent that. :disappointed:

**Comment by GIPeon** [comment]
@crssi yes I can confirm the flickering without `!important`.  
Also I wanted to add a border around the browser box and testing with [TorZillaPrint](https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#screen) I can see that the border is read by the fingerprint data (2px less in widthxheight).

**Comment by WellOrientedLlama** [comment]
That's because the border increases the size of the Letterboxing area and reduces the inner window. If you want a border on the edges of the Firefox window, I guess `box-shadow: inset 0px 0px 0px 2px #000066;` would do dark blue one. It might look funny when the letterboxing area gets smaller than the shadow, as the content area will sit above the shadow.

`!important` doesn't prevent flickering on `about:blank` here, it seems that the content area sometimes starts smaller, gets painted (white, in `about:blank`), and then resized to the whole screen and painted larger.

**Comment by Thorin-Oakenpants** [comment]
While there are some issues still to be dealt with in LB (letterboxing) that leak metrics (such as a new window can grab the inner window measurements **before** LB resizes the viewport: e.g think of a user in a maximized state), one of the other tickets is that the state of the viewport sizes can be detected *as you resize* - but that doesn't really leak anything, it just shows you resized you browser and the protection transitioned from e.g `1000x1000` to `1200x1000` because you wanted more width: edit: see [1556014](https://bugzilla.mozilla.org/show_bug.cgi?id=1556014). You can see this in TZP's css media results in real time. The constant checking/repainting is the jittery bit I guess, and right now it's not fast enough!! (see my example of the new window leak: edit: [1556016](https://bugzilla.mozilla.org/show_bug.cgi?id=1556016)).

> That's because the border increases the size of the Letterboxing area and reduces the inner window

Yeah, don't fuck with that shit. It's a banana skin waiting to happen. Firefox does not officially support userChrome, userContent. As per your example, you caused the wrong viewport and became unique

As for the color (I guess that's browserStack: thanks Llama: I did try and find an element a few times via Browser toolbox) I'm just going to ignore it. Instead, personally, I use a 1600x900 static inner window size (I use an extension, as this also fixes the inner window sizing issues that have persisted since FF57: the one where toolbar causes height to be out by various degrees of a few pixels depending on platform and theme density, and even installed themes from AMO).

Also, this is super low priority for Tor Uplift, but the intent was to make it a bit more user friendly by making the LB color dark in full screen mode. Maybe they can tie the LB color to the theme (dark/light/default) as well as black in FS (e.g watching netflix and having a white glaring background would suck).

If all your answers have been addressed, feel free to close this

**Comment by GIPeon** [comment]
Thank you @WellOrientedLlama @Thorin-Oakenpants , yea I gave up with borders and just changed the BG color.

> I use a 1600x900 static inner window size (I use an extension, as this also fixes the inner window sizing issues that have persisted since FF57: the one where toolbar causes height to be out by various degrees of a few pixels depending on platform and theme density, and even installed themes from AMO).

Little OT and I don't know if this is related, I can see on [TorZillaPrint#screen](https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#screen) that my `viewport` is 1383x700 being my window 1400x700, is there anything I should check for the scroll bar "gap"? Is it relevant?

Thank you!

**Comment by Thorin-Oakenpants** [comment]
You don't need to do anything. This is normal. The scrollbars (vertical, horizontal) are always detract from the inner window: i.e viewport = innerwindow - scrollbar(s). This is normal. Using math it is simple to detect your scrollbar width (at 100% zoom) and this reveals your OS. Yours is 17 pixels which means you are using Windows. If you do anything to mess with this, you only end up being unique when combined with other metrics which also say you are Windows. This is called an `Information Paradox` and is added entropy (i.e you wouldn't have that entropy if you didn't lie, or at least plausibly lie)

Note: scrollbars do not have to be on the inner window, they can also be used and measured in other elements, such as text areas, iframes, etc.

**Comment by Thorin-Oakenpants** [comment]
@GIPeon https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#useragent  look at the `[scrollbar width] os` result. Zoom in and out and rerun the section and enjoy. Imagine if you changed that measurement by lying: and now look at some of the other results in that section that tell me you're on windows: that's the Information Paradox at work.

**Comment by GIPeon** [comment]
I see, all this details when stacked up are truly a behemoth to wrangle with, very interesting thank you! If none want's to add more this issue can be closed!

Fun fact: I wondered if scroll bar width changes between Windows OS versions, apparently not. IE, chrome and FF, it's always 17px wide. But on Win10 Edge browser, the scroll bar is 12px. 
Source: https://codepen.io/sambible/post/browser-scrollbar-widths

**Comment by claustromaniac** [comment]
> This is called an `Information Paradox`

Pretty sure [black holes](https://en.wikipedia.org/wiki/Black_hole_information_paradox) don't have much to do with entropy :trollface: 

(just messing around, but do read that if you're into physics)

**Comment by Thorin-Oakenpants** [comment]
> Fun fact: I wondered if scroll bar width changes between Windows OS versions

Not in Firefox, and it is trivial to detect your real browser. It does change with zoom (and not entirely sure if DPI does anything). So knowing the sizes per zoom level for Firefox => I now know your real OS (i.e Windows vs Mac etc: **not** windows 7 vs windows 10 (although that could happen: e.g different linux distros can produce different results). At the end of the day, it is not the OS that is important, the actual pixel values = the entropy

**Comment by Thorin-Oakenpants** [comment]
https://old.reddit.com/r/FirefoxCSS/comments/c7t8cc/need_help_with_userchromecss_new_method_of/

```css
#tabbrowser-tabpanels{
  background-color: rgb(46,54,69) !important;
}
```

**Comment by LegitLlama** [comment]
^This is the better one to use. That's where the actual default white-ish colour is set and it's a CSS ID rather than a class.

```css
#tabbrowser-tabpanels  {
  background-color: unset !important;
}
```

`unset` should enforce the theme background color, meaning it will change automatically as you change theme. It worked well for my theme at least, but the default light and dark themes looked surprising on Windows 7 ! I got the OS color and transparency on the whole letterbox area. With the lowest color intensity setting (from customization through a right click on the desktop), it basically let me see my wallpaper.

**Comment by Thorin-Oakenpants** [comment]
Here's what I'm using. The color matches my group speed dial background

```cs
/* about:newtab and about:blank
 * also remove white flash: see https://bugzilla.mozilla.org/1488384
 * also colors the letterboxing */
#browser vbox#appcontent tabbrowser,
#content,
#tabbrowser-tabpanels,
browser[type=content-primary],
browser[type=content] > html {
	background: #0f0f0f !important;
}
```

**Comment by crssi** [comment]
^^ this maybe works at your config, since you are using dialer and you are messing with it.
But normally it doesn't work.

General solution... you need both:

**userChrome.css**
``` css
#tabbrowser-tabpanels{
  background-color: rgb(46,54,69) !important;
}
```

**userContent.css**
``` css
@-moz-document url("about:home"),url("about:blank"),url("about:newtab"),url("about:privatebrowsing") {
  body{ background-color: rgb(46,54,69) !important }
}
```

Cheers

**Comment by Thorin-Oakenpants** [comment]
IDK ...works just fine on Tor Browser without a userContent

**Comment by Thorin-Oakenpants** [comment]
FYI
- downstream, done: https://trac.torproject.org/projects/tor/ticket/32220
- upstream, don't hold your breath: https://bugzilla.mozilla.org/show_bug.cgi?id=1594455
