### ISSUE TITLE
Linted updater.sh with Shellcheck

### ISSUE THREAD

**Issue by tyler-public** [ghacksuserjs/ghacks-user.js#753]
Hi,

I've run `updater.sh` through shellcheck and fixed the problems it reported, I'm working on making the `updater.sh` run with `/bin/sh` and be POSIX compliant, but that's going to take more time.

https://gist.github.com/iamtpage/1936f4373c2f5a2bc01d95ac58e8d426

Thank you so much for the work on this project, hopefully this will be of use

**Comment by claustromaniac** [comment]
At a first glance it looks good to me. Would you like to submit a pull request? If not, I can submit one myself. Still, when we can, we should at least test this first to make sure it works well for everyone. @earthlng's outdated VM is (or used to be?) especially fussy.

I'm summoning @overdodactyl in advance. (🐦, can you still flap those wings?)

**Comment by iamtpage** [comment]
I'd like to have someone else test this before talking about merging it in. I've tested all functionality except for the updating part (since updating would overwrite the linted shell script with the original)

**Comment by earthlng** [comment]
Hi!

thanks for contributing here, mate!

I've never heard of shellcheck, which tbh doesn't mean much because I haven't worked with a lot of linux/mac scripting for while, but is that some kind of defacto standard in shell script linting?
I mean, is this just about "style" or did the script not actually work for you without these changes?

> Would you like to submit a pull request? If not, I can submit one myself.

Yes, someone please submit a pull request so that we can work on it there. I've already spotted a mistake in our current script thanks to this but also something that I believe is not quite right. A PR makes it a lot easier to comment on and change each line where necessary. Thanks

**Comment by iamtpage** [comment]
For shell scripts, shellcheck tends to be the "defacto standard" for linting and syntax checking. It is a bit of a mix of "best coding styles" and best practices for preventing things like undefined behavior, common mistakes, etc.

I'll open a PR for the BASH version, then once it's fixed I'll open another for the POSIX compliant one

**Comment by earthlng** [comment]
Thanks for the explanation and for opening the PR. We'll get to it hopefully soon but the next FF release is out in a couple day and we'll have to get that done first. I also don't want to change too much (or really anything) before @overdodactyl gets involved here because the script is kinda his baby.

**Comment by overdodactyl** [comment]
Thanks for the pings and sorry I've been totally MIA as of lately.  I'll take a look at the PR this weekend :)

**Comment by Thorin-Oakenpants** [comment]
any chance of getting this sorted out?

**Comment by Thorin-Oakenpants** [comment]
@overdodactyl .. wots up bro? Did you find yourself a nice partner to settle down with and build a nest, or something? .. bump

**Comment by atomGit** [comment]
could somebody please take a look at [this](https://github.com/HorlogeSkynet/thunderbird-user.js/issues/1)

i tweaked the updater.sh script so it can work for both firefox and t-bird, but i'm out of my element

since the user.js project for t-bird is up and running again, and since i'd like to see the updater script work for both, i wonder if you fellas might consider adopting my idea

**Comment by Thorin-Oakenpants** [comment]
I'll just assume this is abandoned then after seven months
