### ISSUE TITLE
Suggestion: media.autoplay.allow-muted: false

### ISSUE THREAD

**Issue by GIPeon** [ghacksuserjs/ghacks-user.js#756]
Am I the only one terribly annoyed by autoplay videos? Even more with muted videos?
Don't shove me your damn muted video ads!! /rantoff

Anyway after some digging I found that this nice little tweak can stop _even_ muted videos. :mute:  
Do you think it's a valuable suggestion for the user media section?

`media.autoplay.allow-muted: false`

**Comment by crssi** [comment]
Never landed on such site, or filters that I use on uBO are doing a great job.

Do you care to share a sample URL?

Thank you and cheers

**Comment by GIPeon** [comment]
@crssi I guess any news site or whatever, I use uBO in my every day use in a sort of advanced _easy mode_. Also my definition of "ad" video is quite broad, basically anything that autostart without consent, so many first party videos do end in this group. :ban:

**Comment by crssi** [comment]
^^ I still have trouble to find any site with that behavior. Do you mind, please, to share one sample anyway.

Thank you and cheers

**Comment by GIPeon** [comment]
Hei yea I guess any news website has this kind of issue, if you are interested the page that triggered my "that's enough" moment is [this](https://www.techwalla.com/13717336/this-smart-notebook-uses-pen-and-paper-and-its-endlessly-reusable).

**Comment by earthlng** [comment]
> Am I the only one terribly annoyed by autoplay videos?

2030 combined with 2031 should prevent (non-muted?) autoplay, doesn't it? Do you not use these 2 prefs?

It's possible that `media.autoplay.allow-muted=true` overrides those 2 prefs IF the audio/video is muted but I'm not sure.

I'm not opposed to adding this pref but note that it will get removed in FF69 and replaced with an additional value for 2030

**Comment by Thorin-Oakenpants** [comment]
My first thoughts were

- why do we even have autoplay prefs in the main section?
- they don't do anything AFAIK for privacy, anonymity, tracking
- they *might* indirectly do something for anti-FPing and security
- these probably technically belong in the personal section
- moving large **multi-line** prefs `2030` `2031` `2032` to personal is messy AF
- these are probably quite popular prefs (note `2030` + `2032` we are just enforcing defaults)
- **if** we were to add this mute pref, then I would only do it if we put the others in personal

> but note that it will get removed in FF69

Sucks for ESR. Adding it just for v68 seems like a waste of time

So IDK what to do now? I guess the first question to answer is where do they belong?

**Comment by GIPeon** [comment]
@earthlng 
> 2030 combined with 2031 should prevent (non-muted?) autoplay, doesn't it? Do you not use these 2 prefs?

Unfortunately I _do use them_, but this intended behavior [according to Mozilla](https://blog.mozilla.org/firefox/block-autoplay/) (emphasis is mine):

> ## Block autoplaying content automatically
> 
> If you find yourself on a site that autoplays video or audio Firefox will now stop the autoplay before it can start. If you’d like to hear or see it, just click on the play button to watch it. It’s easy to do and makes noisy sites mind their manners. If you’re on Facebook, Twitter or another social media site, they tend to automatically mute video content. **Block Autoplay won’t stop the video from playing and instead the video will play without sound as the sites intend them to**. 

So yea, if the video is set as muted the video will play anyway. Fun fact: according to this [HN thread](https://news.ycombinator.com/item?id=19077748), it's because of video gifs. 😒

@Thorin-Oakenpants 
> So IDK what to do now? I guess the first question to answer is where do they belong?

Indeed as you stated is more a personal setting, still I think it can actually help with some privacy and fingerprinting (I guess, I'm no expert) because I think that if the video is not played, the video file is not pulled from the server (which could be on a CDN), instead a "poster" image should be displayed (ofc also this could be on a CDN). This should be the case in a pure HTML5 implementation of the `<video>` element, dunno if this would be the same with a JS player.

**Comment by Thorin-Oakenpants** [comment]
my guess would be that logically the thumbnail/placeholder and video reside on the same server since one generates the other: if different servers, then probably the same same owner: cogito ergo sum: either way you connected to the third party

**Comment by earthlng** [comment]
> Sucks for ESR. Adding it just for v68 seems like a waste of time

If we add it now and move it to 9999 later then ESR users can still see/use it.
It will also serve as a reminder for us that there will be a new value for 2030 in FF69 (unless we already want to add that info now.)

> why do we even have autoplay prefs in the main section?

IMO it's okay to have some "general annoyances" prefs. Not everything has to be just about privacy/security.

>  I guess the first question to answer is where do they belong?

the MEDIA section is exactly where I would expect to find these prefs.
I don't really like the Personal section that much because at one point we decided that everything in there is inactive by default. And the format is different too which limits the amount of information/explanations etc that we can put there.

**Comment by Thorin-Oakenpants** [comment]
personal section has several purposes
- if we're going to say to users, here, change all this stuff for privacy, anonymity, security etc .. then we should **only** change things that relate to that
- otherwise they do not belong: but yes, they are fucking useful, so an inactive personal section of things people like us, who tinker with prefs **a lot** find them useful, then, ~~hell yeah~~ FukYeah™, lets share that info
- its also less prefs for end users to look at (unless they want to)

There is no way in hell I want to break that arrangement. Yes, it means I end up with more in my overrides: I mean who doesn't block a lot of the warnings, whats new, recommendations stuff etc? But that's an end-user choice, not ours to enforce on people.

> Not everything has to be just about privacy/security.

That's what the personal section is for. See the argument above. Otherwise we have would have situations like this
- `user`: why did you disable the warning on quit? I rely on that and you just caused me to lose 20 open tabs of research I hadn't bookmarked, which took me 4 hours to find ... because I accidentally hit ctrl-Q. Fuck you guys!
- `us`: well, umm .. fuck, sorry .. there's no legitimate reason we should do that given our mission statement. it's actually all earthling's fault .. here's his personal email account .... :trollface: 

----

So the question is: does disabling autoplay do anything for privacy, security etc?

**Comment by earthlng** [comment]
I can't think of anything that disabling autoplay does for privacy or security but it shits on advertisement videos and the like. Don't know if that's reason enough for you to keep it active and in the Media section.

**Comment by Thorin-Oakenpants** [comment]
> Don't know if that's reason enough for you to keep it active

two of the (current) three are at default. The gesture one at default knows you're already on the site and is probably the better default for most users: although I only tested on YT in a nilla, and I actually don't watch any video in my main FF, period.

at worst, it's one override

---

they could just slot straight into personal. the only thing I don't like about that is that they're verbose and require multi-lines. Adding the mute one for one release is no problem. Had a play and it's a bit messy: below is one with some info removed

```js
/* HTML5 AUTOPLAY */
   // user_pref("media.autoplay.allow-muted", false); // blah blah
   // user_pref("media.autoplay.default", 1); // [FF63+]
      // 0=Allowed, 1=Blocked (2=Prompt - removed in FF66)
      // [SETTING] Privacy & Security>Permissions>Block websites from automatically playing sound
   // user_pref("media.autoplay.enabled.user-gestures-needed", false); // disable if you interacted with the site [FF66+]
   // user_pref("media.block-autoplay-until-in-foreground", true); // disable audio autoplay in non-active tabs [FF51+]
```

**Comment by Thorin-Oakenpants** [comment]
@GIPeon  does this have anything to do with it: https://old.reddit.com/r/firefox/comments/cfuoa2/i_cant_unmute_webms/

**Comment by GIPeon** [comment]
I don't know, AFAICT I'd say no. The guy here is reporting problems with videos having no sound no matter what. 

Basically my point is just to have this option suggested/listed to prevent videos on page to autoplay *even* when set as muted by the website, since FF by default *allow* muted videos to autoplay .

**Comment by crssi** [comment]
^^ IMHO, this is for user to decide... so for user-overrides.js. I vote to stay as it is now in ghacks user.js

Cheers

**Comment by earthlng** [comment]
```js
/* 2033: disable autoplay for muted videos [FF63+] ***/
   // user_pref("media.autoplay.allow-muted", false);
```
