### ISSUE TITLE
Need help, tweaked my mozilla.cfg + can't login to email-provider.

### ISSUE THREAD

**Issue by cokeflash** [ghacksuserjs/ghacks-user.js#769]
Hi there!

I tweaked my mozilla.cfg for "Security/Performance..."

I think I had disabled some stuff that is needed for login to websites (email-provider)

Can you please look into my mozilla.cfg?

I attached it.
[mozilla.cfg.txt](https://github.com/ghacksuserjs/ghacks-user.js/files/3478155/mozilla.cfg.txt)

Which values must I enable to can login into my email-provider?
I reverted a few javascript values to 'default' back. That did not help.
When I click on the Login-button, nothing happens.

Thanks for your time.

**Comment by crssi** [comment]
No one can/will check the truckload preference dump and resolve problem where only you can do it for your needs.

That is why @Thorin-Oakenpants has made very good [Troubleshooting](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting) instruction section in the Wiki.

But... for start I would change:
``` js
lockPref("privacy.firstparty.isolate", true);
```
to:
``` js
lockPref("privacy.firstparty.isolate", false);
```

Cheers

**Comment by Thorin-Oakenpants** [comment]
2181 prefs listed. Sorry, but this is way beyond what we do or recommend.

**Comment by Thorin-Oakenpants** [comment]
Create a new profile (no extensions, no tweaking). Test you can login to your email. If you can, then add the user.js from here and restart Firefox. Can you still login? If you can, then it's not our problem. If you can't (i.e it is a ghacks user.js pref) then you need to [troubleshoot](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting) <-- use that link

Some cross domain logins can be an issue with FPI: due to how they use a evercookie type flow (e.g using google accounts to log into youtube). crssi already suggested `privacy.firstparty.isolate`. Be aware that some prefs *may* require a firefox restart (not saying this one does, just that some do)

I have no idea what email service you're trying to log into, what authentication is used etc. If it's a ghacks user.js pref that is causing an issue, then you should be able to work it out in about 5 or 6 tests using the halving method (read that link). I can't do it for you - all I can do is guess.
