### ISSUE TITLE
YouTube autoplaying

### ISSUE THREAD

**Issue by privacyguy123** [ghacksuserjs/ghacks-user.js#777]
...then pausing itself at exacttly 1 second. What setting is causing this?

**Comment by Thorin-Oakenpants** [comment]
I don't use youtube sorry.

Have you tried the troubling wiki page? i.e have you tested the user.js in a new profile with no extensions, and tried to narrow it down?

**Comment by Thorin-Oakenpants** [comment]
In a new profile, FF68, I added the ghacks user.js  (and restarted) and went to YT's home page and searched for some Taylor Swift. So admittedly, I had already interacted with the site.

I picked this [this video](https://www.youtube.com/watch?v=Dkk9gvTmCXY) (for the TayTay fans, honest) and the urlbar indicator told me I had blocked autoplay on YT, Good. I clicked play, and the video worked flawlessly.

AFAICT the user.js is not necessarily your problem. You need to be a bit more specific in your issue. Do you mean the video (on youtube and not as an embedded third party?) doesn't autoplay, but when you click play it starts and then stops? Or do you mean it doesn't autoplay (i.e you see a split second of it and it stops?). What happens if you click pause (if needed) and then play again? What version of FF are you using?

Feel free to reopen when you have steps to reproduce

**Comment by Thorin-Oakenpants** [comment]
Loaded Firefox again, sanitized (all persistent web data cleared) and went directly to the video

The video placeholder shown indicated a 6 seconds long video: some sort of ad I think. After, I guess 6 seconds, that got replaced by the magnificent TayTay video image (also not autoplaying)

Here's a pic
![TayTay](https://user-images.githubusercontent.com/16656956/63573584-399dd000-c575-11e9-8c22-ae7e5dd4d98f.png)

See in the urlbar there is an icon indicating that autoplay is off. If this is your issue, then change the site permission from `block` to `allow`. Note the video below where it hasn't even tried to play: the playlength is at zero. Clicking play works fine for me.

Good luck
