### ISSUE TITLE
Q: why aren't stickies sticky? (notabug)

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#779]
i noticed on other github repo's that sticky threads are all displayed in a nice grid/thumbnail layout at the top of the issues which makes it easier to find them - why isn't that the case here?

ex: https://github.com/firefox-devtools/debugger/issues

**Comment by Thorin-Oakenpants** [comment]
huh? I see one `pinned` item. Looks like you can pin 3 items across the top. Hate those things: I want to see the friggin issues. The purpose of pinned items would be to draw attention to them

stickies is just a label: to indicate that they're not issues/bugs that need to be solved and closed. Additionally, I keep the issues under 25 open issues most of the time - this one page: everything is viewable in one hit.

I don;t see the problem here

**Comment by atomGit** [comment]
i'm thinking sticky as in a forum post where the sticky post is always on top - that's just me

now go get a keyboard remapping program and remap **;** to **'** so you quit typing "don;t" ... i don't know why, but i do that all the time myself

**Comment by Thorin-Oakenpants** [comment]
well, to be fair, they are sticky .. they stick to the bottom of the list 😬
