### ISSUE TITLE
Moz Extensions: Site Deployment Checker + Application Update Service Helper

### ISSUE THREAD

**Issue by grauenwolfe** [ghacksuserjs/ghacks-user.js#79]
Does anyone have information on the new 'Site Deployment Checker' Extension? I've found only a vague, "politician type" answer with a Bug report:

> ...this system addon is used by mozilla to look into the integrity of its critical infrastructure like the download page by looking at real world data of certificates in use there (bug 1346017).

![ff-ext](https://cloud.githubusercontent.com/assets/25858089/24841946/2e1fafde-1d55-11e7-9bc5-617823cb7fd3.jpg)

While I'm at it, what the scoop on 'Application Update Service Helper'? I keep all auto-update stuff disabled so I can manually check when needed. Does this interfere with anything yet?

**Comment by earthlng** [comment]
Hi, I usually remove all the system-addons from my system after each update. Never had a problem with that. The Site Deployment Checker is already old news soon. It [causes Firefox to connect 18 Mozilla hosts once and send a telemetry ping](https://bugzilla.mozilla.org/show_bug.cgi?id=1346017#c32) but 5 days ago they wrote "We need to start backing this out of all trees" which has already been done for [FF53](https://bugzilla.mozilla.org/show_bug.cgi?id=1353789).
Since it builds on the telemetry ping stuff, if you have that disabled you never sent any pings (most likely)
With the AUS-Helper I think they sometimes update/change prefs without needing to release a new FF minor version. I remember reading that it does not update anything unless the App update is set to automatically download & install. So no this should not interfere with anything in your case.

**Comment by zymase** [comment]
Same as earthlng : I remove all the system-addons from my system after each update, that is, I backup their folder ("features") then empty that folder. Never encountered the slightest issue.

I read earthlng's description with interest as I never knew what exactly this system add-on performed, but I recall having read that it implied, once again, telemetry.

For those running CCleaner that application also disabling add-ons, system add-ons included.

By the way : I thought latest Firefox version(s) included system add-ons in its about:addons (Add-ons Manager) page. Never tested that since I always eradicate those so called "system add-ons". Anyone tested?

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1231202

Over a year now, and no f**king change for something so simple. I doubt they will ever do anything about it, because they do not want to. It's like resource://URIs .. 5 years and counting .. or windows.name .. 87 years and counting

**Comment by crssi** [comment]
I wrote a few days ago that I don't trust even firefox, which makes me sad. :(

**Comment by grauenwolfe** [comment]
Thanks for the suggestions.

I'm comfortable removing built-in extensions but I've only done this with the Pocket extension as you can see in the screenshot, but I also make sure to remove all 'Pocket' entries found in extensions.json, CodeResources, prefs, etc.

So what all do you guys remove? Just AUS Helper and Site Deployment Checker? Surely you don't remove e10s Multi-process? 

I have no idea exactly what Web Compat is unless it's for upcoming WebExtensions. If that's the case then there isn't any purpose for it being installed yet.

**Comment by Thorin-Oakenpants** [comment]
I remove all of it .. 100%. I'm not e10s yet due to 5 extensions (3 with and 2 without the multiprocess flag). I think the e10s was/is only used for the e10s rollout. I've never had any issues with removing the entire lot, so far.

**Comment by zymase** [comment]
@grauenwolfe you can safely remove/disable all system add-ons, but if removed do keep them backuped. Restoring a system add-on back in its _features_ folder and restarting Firefox will have it immediately taken in charge by Firefox. You can always try. Backup Backup Backup (as "Tora Tora Tora" with Pearl Harbor) and be free to experiment. Not one system add-on here.

**Comment by crssi** [comment]
Damn, I feel stupid now. :)
In which folder are those extensions? I would just like to be sure.
Would that be %appdata%\Mozilla\Extensions?

**Comment by zymase** [comment]
> If you compare yourself with others,
> you may become vain or bitter,
> for always there will be greater and lesser persons than yourself.

Desiderata -- written by Max Ehrmann in the 1920s --

Ii feel stupid myself quite often so then I remember the above extract.

The folder containing Firefox's system add-ons is
[Mozilla Firefox iinstal folder]\browser\features\

I pain to manage short answers!

**Comment by crssi** [comment]
Thank you @zymase 
Do you might to know what is [Mozilla Firefox iinstal folder]\browser\extensions ?

**Comment by zymase** [comment]
`[Mozilla Firefox iinstal folder]\browser\extensions ?`
That's reserved for Firefox, I never saw there anything else than Firefox's install xpi for whatever it means.
Good question though.

**Comment by earthlng** [comment]
> Do you might to know what is [Mozilla Firefox iinstal folder]\browser\extensions ?

`{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi` is the Firefox default theme

**Comment by earthlng** [comment]
@zymase, nice quote there, thanks for that :)

@grauenwolfe

> I have no idea exactly what Web Compat is unless it's for upcoming WebExtensions.

Last time I checked it was an empty xpi file that did exactly nothing. Atm it's somehow not possible anymore to extract those xpi files, at least on Windows. Maybe it still works on Linux - I will have to check.

**Comment by gr8gnd4r** [comment]
@earthlng:

how to extract .xpi contents:

1. on windows, copy the .xpi file to a temp directory
2. rename extension to .zip
3. extract contents (using windows)

web compat says: Urgent post-release fixes for web compatibility. [but
looks empty]

**Comment by zymase** [comment]
FYI and to whom it may concern, the **_Bandizip_** application handles xpi natively so no need to rename a xpi file's extension to zip.

**Comment by earthlng** [comment]
Thanks @gr8gnd4r
I must have changed the default handler for zip files recently and didn't notice that "Open" was not using Windows Explorer anymore and tried to open it with 7zip instead which failed.

**Comment by earthlng** [comment]
> web compat says: Urgent post-release fixes for web compatibility. [but looks empty]

yep, still the same as last time I checked, only a bunch of empty functions:

bootstrap.js (the only file in webcompat@mozilla.org.xpi other than the install.rdf)
```js
"use strict";
function startup() {}
function shutdown() {}
function install() {}
function uninstall() {}
```

**Comment by earthlng** [comment]
<em:name>Application Update Service Helper</em:name>
<em:description>Sets value(s) in the update url based on custom checks.</em:description>

It basically changes the `%OS_VERSION%` in `app.update.url` based on some checks for CPU and WebSense.
Probably best to leave this extension in the default folder for people that use the built-in update mechanism.
