### ISSUE TITLE
clean up / enhance: 0707: DoH

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#790]
currently
```js
/* 0707: disable (or setup) DNS-over-HTTPS (DoH) [FF60+]
 * TRR = Trusted Recursive Resolver
 * 0=off by default, 1=race (removed in FF69), 2=TRR first, 3=TRR only,
 * 4=race for stats but always use native result (removed in FF69), 5=explicity off
 * [WARNING] DoH bypasses hosts and gives info to yet another party (e.g. Cloudflare)
 * [1] https://www.ghacks.net/2018/04/02/configure-dns-over-https-in-firefox/
 * [2] https://hacks.mozilla.org/2018/05/a-cartoon-intro-to-dns-over-https/ ***/
   // user_pref("network.trr.mode", 0);
   // user_pref("network.trr.bootstrapAddress", "");
   // user_pref("network.trr.uri", "");
```

I think we should get this up to date

Some pointers
- The ghacks link is old and limited
- There is now a UI for some of this which we can add in
- There are new prefs as well
- maybe add something like: https://www.privacytools.io/providers/dns/#icanndns

Note: This is not something I want to enforce on anyone: it will (probably) stay inactive. I haven't really followed it, but there are pros and cons to both sides, not to mention lots of other variables (such as what are you using at an OS/network level). But it does need a good update

Suggestions?

**Comment by ema-pe** [comment]
Hi, [this article](https://blog.mozilla.org/futurereleases/2019/09/06/whats-next-in-making-dns-over-https-the-default/) says Mozilla will gradually activate DoH for US users in late September. The article also says that Firefox will give an opportunity to opt out.

I do not have an opinion about DoH, but I am sure to disable it for now. I think that you should insert two different points of view, like [this article](https://ungleich.ch/en-us/cms/blog/2019/09/11/turn-off-doh-firefox/).

**Comment by Thorin-Oakenpants** [comment]
just a note: https://trac.torproject.org/projects/tor/ticket/30753 .. keep in mind that Tor Browser is a different model

**Comment by Thorin-Oakenpants** [comment]
article: https://blog.technitium.com/2019/09/analyzing-dns-over-https-and-dns-over.html

**Comment by rusty-snake** [comment]
### What do the other user.js's
pyllyukko user.js:
```
// PREF: Trusted Recursive Resolver (DNS-over-HTTPS) (disabled)
// https://wiki.mozilla.org/Trusted_Recursive_Resolver
//user_pref("network.trr.mode",					0);
```
[privacy-handbuch user.js](https://www.privacy-handbuch.de/download/user.js)
```
user_pref("network.trr.resolvers", '[{ "name": "Cloudflare", "url": "https://mozilla.cloudflare-dns.com/dns-query" },{ "name": "SecureDNS", "url": "https://doh.securedns.eu/dns-query" },{ "name": "AppliedPrivacy", "url": "https://doh.appliedprivacy.net/query" },{ "name": "Digitale Gesellschaft (CH)", "url": "https://dns.digitale-gesellschaft.ch/dns-query" }, { "name": "Quad9", "url": "https://dns.quad9.net/dns-query" }]'); 
```

**Comment by Thorin-Oakenpants** [comment]
What version did FF plan to flip the pref for US users?

**Comment by Atavic** [comment]
I'd say from version 62.

>DoH support has been added to Firefox 62 to improve the way Firefox interacts with DNS.

https://blog.nightly.mozilla.org/2018/06/01/improving-dns-privacy-in-firefox/

**Comment by Thorin-Oakenpants** [comment]
nvm - it's not per release, it's staged and already happening (I assume FF69+ users only)

https://blog.mozilla.org/futurereleases/2019/09/06/whats-next-in-making-dns-over-https-the-default/

> We plan to gradually roll out DoH in the USA starting in late September. Our plan is to start slowly enabling DoH for a small percentage of users while monitoring for any issues before enabling for a larger audience. If this goes well, we will let you know when we’re ready for 100% deployment.

**Comment by Thorin-Oakenpants** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1573840

**Comment by Thorin-Oakenpants** [comment]
So, no one cares? I though a few of you wanted more prefs added, at least I got the impression @earthlng did from his comments in the last few diffs.

It could certainly do with better refs, adding a [SETTING] tag, changing the value to 5, and I was thinking of making it active

Speak up, or I'll just do it and refuse to ever discuss DoH again

**Comment by KOLANICH** [comment]
IMHO - If one wants encrypted dns requests, he probably should use https://github.com/DNSCrypt/dnscrypt-proxy

**Comment by rusty-snake** [comment]
> changing the value to 5, and I was thinking of making it active

Sounds good. It would prevent that all your (Browser) DNS-traffic is send to cloudflare.

**Comment by Thorin-Oakenpants** [comment]
It's not about what layer of the network it should be at (app, os, lan etc), and its not about cloudflare: it's about whether it should be opt-in or opt-out. And there's no right answer. My logic is that users of this repo are maybe likely to use  a VPN which means you should use the VPNs DNS. Or users of this repo are maybe more likely to already have a solution (e.g dnscrypt). And for a lot of people (hello non-Americans), they don't have asshole ISPs like comcast etc (which is why Firefox is only rolling it out to US users AFAIK).

So, aside from not having your ISP redirect shit or apply blocks, I'm just looking at this from a privacy standpoint: and as far as I can tell, you click a link (we do no pre-fetching of any sort), and the end result is the ISP gets this info only.

I'll have to go re-read shit, and TBH I'm tired of it all. Maybe I'll do this next year.

**Comment by earthlng** [comment]
You got the impression that I wanted more DoH prefs added? I don't remember ever saying anything to that effect.

Anyhow, I'm always in favor of adding more quality links and setting the default value to 5 also SGTM but I'd keep the pref inactive because IMO it should be up to each user to decide whether they want DoH enabled or not.
The users in the US that get DoH enabled as part of the staged rollout are shown a notification prompt where they can opt-out and for everyone else DoH is still default-disabled so no need to force-disable it for everyone IMO.

**Comment by Thorin-Oakenpants** [comment]
> You got the impression that I wanted more DoH prefs added?

Nevermind then. It's just the vibe I get from the nudges in diffs, and the initial addition of it, to add DoH prefs

There's been a few things I do **not** want to do, because it can be subjective and/or hard to maintain and/or it's already done elsewhere to death and/or it's in a constant state of change as it matures and/or it all ends up on myself to follow up on and make changes (excluding the occasional comment and wisdom from the odd person). So fuck it, less work for me.

Examples
- search engines: a wiki page/ sticky (several issues about this shit) and changing some default prefs etc
- tracking protection: no pressure from anyone: I ripped it out of my own volition and thank F I did given the plethora of changes each release as it has moved from TP to ETP and more to come. It has a UI guys :)
- DoH: same argument as ETP

> are shown a notification prompt where they can opt-out

Ahh, cool. I've been on the fence for a long time, but that makes sense, and thus tips me back over to inactive.

So yeah
* [ ] clean up the references
* [ ] change to 5
* [ ] `SETTING` tag: note the UI is still a work in progress and there are open bugzillas
* [ ] description: we need to do something better here: for example: what if you're in the US and this is flipped on you (but you didn't understand it and said yes), but you use a VPN. What happens?
* [ ] Do we add a `SETUP` tag ?

I just feel the description is a bit naff. There's pros as well. But I don't want to write a book.

Class! Prepare a PR! or discuss!

**Comment by rusty-snake** [comment]
@Thorin-Oakenpants two thing
1. what about adding `network.dns.skipTRR-when-parental-control-enabled` commente here (see FF70 diffs)
2. > You could do this at the OS level instead; e.g. DNSCrypt.

This is a bit confusing, because DNSCrypt is another protocol to encrypt DNS-Traffic.

**Comment by Thorin-Oakenpants** [comment]
IDK. I don't even want this shit in the user.js since it's a user choice and has a UI. We don't have a big pile of proxy prefs in the user.js, do we. And I sure as hell personally don't care about this one. 14 lines for one pref. I'd rather rip it out and be done with it. Since I'm the one that seems to maintain everything, I think I might just do that.

**Comment by Thorin-Oakenpants** [comment]
> This is a bit confusing, because DNSCrypt is another protocol to encrypt DNS-Traffic

But it does the same thing, which is my point: "makes DNS lookups encrypted" and "can prevent DNS hijacking or manipulation" - right?

Anyway. That's my draft. You guys fix it up (and hurry up), or I'll rip it out

**Comment by rusty-snake** [comment]
There is a lot more interesting `network.trr.*` stuff.

> and has a UI

But
1. it is a bit hidden (End of about:preferences > Button > PopUp > Scroll down)
2. The UI sets it to **2** not 3, thats a potential leak of DNS traffic.

---
Or rip it out if you want.

**Comment by Thorin-Oakenpants** [comment]
don't get your panties in a twist - the tag is used to filter for changes to the user.js / wiki

**Comment by earthlng** [comment]
removing useful information is an awesome enhancement ;)

**Comment by Thorin-Oakenpants** [comment]
Thanks for adding a `:)` but please don't troll me

I agree that the loss of information is not what I wanted.

But it's not that fucking important: Any change by Mozilla is (currrently) limited to US (if that changed it would affect the reasoning), and since that change is prompted, users are not at risk of "unwanted" change. It's only a possible "uninformed" change at worst (I'm sure users of this repo can use search engines or click Firefox's learn more links)

With regards to quality of information: either we do it properly (not using outdated links, and not incomplete: there are a lot more prefs and other issues such as ESNI or whatever it is). So in that regard, removing it as unmaintained, incomplete, and outdated **is** an enhancement.

If someone wants to create and maintain a quality DoH section (and re-invent the wheel that a thousand articles and websites already provide), and cover all bugs as it gets polished and UI changes ... then be my guest. I do not have time for it.

I proposed changes, and asked for help (I am not an expert on DoH) for almost 2 months and no-one fucking helped. What did you expect me to do.


Here's my smiley --->  :)

**Comment by earthlng** [comment]
That's not trolling - just voicing my disagreement using sarcasm to highlight the fact that removing information is not an enhancement.

Look, you opened this issue to "clean up / enhance" 0707 so clearly the burden is on you. Nobody asked for any changes or said anything about 0707 being outdated, incomplete or whatever.
Then you weren't satisfied with the responses you got and decided to just remove it instead of just closing the issue which is what you should've done.
Even if the information were outdated, which it wasn't, that's still better than no information at all.
It listed the 3 most essential prefs as well as all the available values and that's all that's really needed for someone to either force-disable TRR or set it up the way they want.

You also said that it has a UI to which @rusty-snake responded, and rightfully so, that the UI is fucking useless (my words ;) because it sets the mode to 2 and has no option to use mode 3.
Fe. the other day we had a guy report an issue with TRR and if he didn't know about mode 3 and just used the UI instead, he might have ended up under the impression that he's now using TRR while in reality it would've just fallen back to native resolution - because the UI is fucking shit!
Now, IDK how he learned about mode 3 but I'd like to think that he probably saw it in the user.js - before you ripped it out :)

> and re-invent the wheel that a thousand articles and websites already provide

that's just a shitty excuse. If that were a criteria we could probably remove 50% of the user.js because articles get written about pretty much everything. I mean, why provide any links at all if users could just google it, right?! sorry but that's just stupid

> 14 lines for one pref.

We're at somewhere around 1800 lines and I couldn't care less if we ended up at 4k lines.
This is supposed to be a (if not "the most") "comprehensive" user.js template, right? So who the fuck cares about # of lines.

> asked for help ... and no-one fucking helped.

you said that before - "So, no one cares?" - after 2 people already replied! That's not exactly encouraging collaboration. Why should anyone contribute anything if you just disregard/ignore what they say?

And similarly, I really, really, REALLY don't like your threats! like "Do something or else ...!", fe

> That's my draft. You guys fix it up (**and hurry up), or I'll rip it out**

When I saw that I just said fuck it, let him do whatever the fuck he wants, I'm outta here. That was until you added the enhancement label at which point I just couldn't resist to say *something*

ps. if a smiley makes this blunt criticism any better or less offending, here you go ... :)

**Comment by Thorin-Oakenpants** [comment]
No I'm not offended. And yes, I know you're not trolling - it just hit a nerve. And no (in my mind) I'm not threatening, that's me practically begging for some help - I won't do that anymore - ask for help, moan, or "threaten"

And, yes, I appreciate all the help that is given.

No, I don't want to leave this out (loss of information). And I realize the issue with value 3. But the item itself didn't even cover that. And I do not believe the ghacks link is good enough (it is outdated: too many things have changed under the hood: my words in op "The ghacks link is old and limited"). And there are always trr/doh changes or new prefs each release. I see them and in my head I go "fuck it". And the DoH section hasn't changed since it was added (except for value 5 being added or something), so I *think* it's incomplete. I just can't deal with it mate: so I *think* what we had was a bit crap, and I *think* it's unmaintained. I don't know what to do.

> that the UI is fucking useless

Yes. It is quite useless. And there are tickets in to add more fields and options to it: which I have mentioned numerous times.

Anyway, we're just going to go around in circles. I can't do it. But anyone else is free to draft something up, and maintain it.

Anyway, feel free to speak bluntly: I find it way easier. I'm not offended that way. Whereas cryptic/snide remarks get my goat up.

Apologies. Hope you now know where I stand on this.
