### ISSUE TITLE
Switch to ESR 68.x / Question about User.js

### ISSUE THREAD

**Issue by bitpixl** [ghacksuserjs/ghacks-user.js#802]
So with the latest news that Mozilla is planning to implement more 'functionality' in Firefox every 4 weeks starting next year, I've decided to switch to ESR releases from now on.

I'm going to use the latest ESR (68.x) and want to be sure I'm configuring the User.js correctly.

in section 4600 theres the following note:
>IF you DO NOT use RFP or are on ESR... then turn on each ESR section below

I'm not sure how to read this. I assume ESR 68.x has RFP, so if I leave it enabled then 4600 can be skipped even though the note says  "or are on ESR"?

And in section 9999 I only re-enable the FF68 and ESR68.x part and that should be it right?

Thanks in advance.

**Comment by earthlng** [comment]
4600 is at this point mostly there for non-RFP users.
If you look at it, you can see that everything is tagged and grouped by version. It starts at FF55+ and the last item in 4600 at the moment is tagged `FF67+`, meaning that if you use FF68 ESR **with RFP enabled**, you don't need any of these.
But you still need to keep an eye on our changelogs for things that we move to 4600 if mozilla implement a new feature in RFP for newer versions than FF68+. In that case (because we probably won't change the grouping format in 4600) you'll need to add that/those prefs to your overrides unless they also backport that specific change to ESR. Since RFP is currently still mostly worked on for the Tor Browser it's very likely that they'll backport those things to ESR but you may want to check in each case.

> And in section 9999 I only re-enable the FF68 and ESR68.x part and that should be it right?

yes but you may still want to check the **inactive** prefs in that ESR68 section for things that you may want to activate, like for example currently there's `disable autoplay for muted videos`

I hope that helps but if not, just ask again :)

**Comment by Thorin-Oakenpants** [comment]
It's a bit tricky, but essentially you should be ok using the live user.js with ESR if you flip the bits. We don't tend to remove anything if it's still used in ESR (or the removal is fine in both ESR and stable).

I would prefer users just use the archived 68 release. But yeah, in ESR68 you would change
- `/* ESR68.x still uses all the following prefs`
- to `// ESR68.x still uses all the following prefs`

In section 4600, there is nothing in there to flip for ESR68: so you don't have to worry about that for now. That section header is a bit messy. There are no ESR sections in it. Leave this ticket open as my reminder to fix that.

When RFP in future, applies something and it has a corresponding pref that is no longer needed (or alters the RFP fingerprint), then I'm not sure what I'll do: I think it will be a very rare occurrence. I will probably  just say ESR users should add an override. That way non-RFP users only have to change one char.

**Comment by Thorin-Oakenpants** [comment]
> because we probably won't change the grouping format in 4600) you'll need to add that/those prefs to your overrides unless they also backport that specific change to ESR

holy fuck ... earlthing and I agreed on something /jk

**Comment by bitpixl** [comment]
Thanks for the answers and great tip about using the archived 68 user.js release, didnt think of that and will make it even easier to maintain. One other thing, I read ESR still gets security updates and stability fixes. Could this potentially include new about:config entries that aren't included in the archived 68 user.js? IF so, would you update the archived user with an updates version?

**Comment by Thorin-Oakenpants** [comment]
The archived versions don't get updates

**Comment by bitpixl** [comment]
Ok, even then I still think it's better to use the matching version user.js based on @earthlng comment about things possibly being moved to 4600 on the live user.js.

**Comment by Thorin-Oakenpants** [comment]
got this covered in #801
