### ISSUE TITLE
browser.sessionhistory.max_entries [1511813]

### ISSUE THREAD

**Issue by rusty-snake** [ghacksuserjs/ghacks-user.js#808]
Mozilla Firefox for Fedora 69.0.1 (64-Bit)

### Steps to Reproduce

* create a new profile
* add the user.js to it
* start firefox with the new profile
* open a few sites in the same tab
* open the console and look for `history.length`
* open http://browserspy.dk/document.php and look for: Number of pages visited in History

### actual result

`history.length` grow over 10

### expected result

`history.length` can not get higher then 10

**Comment by earthlng** [comment]
Wow, good find, thanks!

I searched bugzilla and found [1511813](https://bugzilla.mozilla.org/show_bug.cgi?id=1511813) which was reported 10 months ago. If their regression window is correct, the pref is apparently broken since FF61.

**Comment by Thorin-Oakenpants** [comment]
I'll poke someone at Mozilla on this later. Meanwhile (I haven't tested it yet: and I have questions), should we add a note that this has been broken since FF61?

**Comment by rusty-snake** [comment]
Workaround would be CanvasBlocker or https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts#small_orange_diamond-conceal-historylength.

**Comment by Thorin-Oakenpants** [comment]
Sure. Not sure exactly what CB does, but that userscript is "security by obscurity" (plus it's detectable). So I don't want to go there and add too much crap to the user.js - I'd rather just get it fixed so history is actually limited

**Comment by earthlng** [comment]
> should we add a note that this has been broken since FF61?

sounds good but ~we~ *you* should probably test/confirm that FF61 is actually the version that broke it.
I'd also add the link to https://bugzilla.mozilla.org/1511813 so that we can easily check in future versions whether the bug got fixed

**Comment by Thorin-Oakenpants** [comment]
well fuck ... which one of you degenerates bricked the test page 🐘 

> Warning: require_once(Cache/Lite.php): failed to open stream: No such file or directory in /home2/gemal/public_html/inc/gsite.php on line 10
> 
> Fatal error: require_once(): Failed opening required 'Cache/Lite.php' (include_path='.:/opt/php54/lib/php') in /home2/gemal/public_html/inc/gsite.php on line 10

**Comment by Thorin-Oakenpants** [comment]
https://thorin-oakenpants.github.io/testing/history_length.html

**Comment by Thorin-Oakenpants** [comment]
OK - I pinged someone I know at Mozilla

**Comment by Thorin-Oakenpants** [comment]
Makes you wonder if anything else in [here](https://hg.mozilla.org/integration/mozilla-inbound/rev/6cffa8738ca53d246a39536d18a0c19b8c602e37) that was removed in early prefs got broken

**Comment by Thorin-Oakenpants** [comment]
The pref being broken is one issue. The other is, and I want to clarify this, what exactly is the threat here? AFAIK the actual history entries can't be read (right?), so what does it matter if you allow up to 10 or up to 50? For whatever reason we added this, it may no longer be relevant. Also, I read something about history states (push etc) the other day (wish I could find it again) in a new bugzilla.

In order to push the bugzilla forward, I need some proof that this affects privacy or something: otherwise they might as well just remove the pref, and it'll languish in P5-land

**Comment by Thorin-Oakenpants** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/history
> For security reasons the History object doesn't allow the non-privileged code to access the URLs of other pages in the session history, but it does allow it to navigate the session history.

**Comment by Thorin-Oakenpants** [comment]
I can't find anything that this pref does that helps privacy, security, anonymity, etc. I've done a buttload of google-fu'ing... I'll recap what I found, know

- it doesn't control overall history, it's only used for per tab history, so it does nothing to stop visited links or other history attacks
- it doesn't control anything to do with session restore tab-history (there's a separate pref default 10 items for that): and we don't do SR, the files are deleted on close
- a number of sites seem to think it helps control memory: e.g. if a history entry in the tab is discarded it frees up memory: maybe, seems like a logical thing. But that doesn't fit our purpose. I also think that this may have changed: e.g. Firefox most likely has other means to free up memory when required. I was trying to find the origins of the pref, but seems like it's been around since Firefox 1 or something
- it could help with shoulder surfers if the user clicks and holds the back button: but I'm done with that: breaking functionality to cater for end-user in-session behavior (all that shoulder surfer stuff: e.g we don't block the urlbar dropdown, we're not doing this for the same reason)

So, I see no reason to even keep this pref in the user.js. I will remove it.

@earthlng

**Comment by Thorin-Oakenpants** [comment]
Also, just for your info: https://bugzilla.mozilla.org/show_bug.cgi?id=1515073  .. they're going to shut down the history api abuse

**Comment by Thorin-Oakenpants** [comment]
> Edit: I had a feeling that TB at some stage might have reset the figure to 1 or something if the TLD or eTLD+1 changed, so I did a test. Nope. Maybe it was someone else (JoDoNym probably).

Maybe i was thinking about windows.name: I should test that in TB

**Comment by Thorin-Oakenpants** [comment]
pref removed in AF v69, so removing answered label
