### ISSUE TITLE
revisit 4602: dom.enable_resource_timing

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#813]
Keep an eye on what gk does with this

https://trac.torproject.org/projects/tor/ticket/27268#comment:18
>  With RFP set, all of these timestamps will be clamped/jittered. Additionally, RFP has the behavior of setting `dom.enable_performance` to false (so you don't need to set that pref.)
> 
> However RFP does not have the same behavior for `dom.enable_resource_timing` - so you may want to disable that explicitly.

**Comment by earthlng** [comment]
AFAICT I think he's wrong and `dom.enable_resource_timing` is fully covered by RFP.

According to [this](https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API) you always start a resource timing with some form of `performance.getEntriesByType("resource")` and that returns an empty array if either RFP is enabled or `dom.enable_resource_timing` is set to false.

Yes, RFP doesn't exactly have the behavior of disabling the pref like it does for `dom.enable_performance` but that's irrelevant because it instead hooks into `getEntriesByType` and returns an empty array instead of the list of resources available for timing.

I'd ping Tom but I forgot his GH handle, again ;)
Can you add him to the list of contributors or something so that his GH name comes up by typing `@t` ?

**Comment by Thorin-Oakenpants** [comment]
https://github.com/search?q=tomritter&type=Users  ... you have two choices :)  but you know ... if you really cared, you'd remember his name 😀  @tomrittervg

**Comment by Thorin-Oakenpants** [comment]
closing this: I do not have the time (no pun intended) and I'm keeping an eye on TB anyway
