### ISSUE TITLE
"Enhanced Tracking Protection"

### ISSUE THREAD

**Issue by privacyguy123** [ghacksuserjs/ghacks-user.js#818]
I see it just got updated in FireFox 70 today - is there any benefit/drawback to having these settings on/off vs the changes already made in the user.js?

![image](https://user-images.githubusercontent.com/50337995/67315768-22d91280-f4ff-11e9-8104-4e338e4cd28b.png)

On top of this I have addons like uBlock, Decentraleyes & CanvasBlocker running - is this overkill?

**Comment by Thorin-Oakenpants** [comment]
> On top of this I have addons like uBlock, Decentraleyes & CanvasBlocker running

make sure you're using **uBlock Origin** and not `uBlock`

---

I removed all the TP (now called ETP) entries several (four?) releases ago as it was going to go through lots of changes (defaults, prefs, new lists, UI changes, methodology, etc) and get ramped up and turned on by default. And I do not have the time to keep track of it all, and I trust that FF's defaults are just fine as they ramp it up. And there's a UI for end-users. I don't need to do anything.

Mozilla have had to start small and monitor breakage, because it will affect all users, and they can't have people using Firefox and suddenly going, aww fuck, it's broken, and running off to use chrome. But each release they ramp it up. Things like crypto and fingerprinters go from default off to default on, and from options for only in PB Mode to all modes (see in your picture above how TP is the only item that has a PB mode setting). Social media trackers list is already default enabled now. There will be more. The lists are getting expanded (e.g for example OpenWPM is always being worked on as to how they detect fingerprinters etc: e.g. by going deeper than the landing page on crawls, but moving from 3rd party only to include 1st party).

Depending on what type is being blocked, I'm not sure if a block here is as effective as e.g. uBlock Origin etc. They're only going to block the "tracking" side of things - e.g. images (ads) may still show, AFAIK. So "cookies" is one thing, and TP is another: they're two different items in the options: and I'm not 100% sure on how they handle them.

Whatever you do, It can't hurt. As long as one source blocks something (Firefox, uBlock Origin, uMatrix) then it gets blocked. So you might get some benefit from a **custom** ETP in TP/cookies, but it depends on your uBO config (and how exactly Firefox handles their side).

e.g
- uBO you block `example.com` as a 3rd party site
- Firefox might block cookies from `example.com` as a 3rd party but allow images and css from it: again, I am not sure on the exact difference between cookies vs TP (but I have an idea, but they could easily change it)

**The only setting we have in the user.js** is the one for cookies, which we set to block all 3rd party. This is item `2701` in the user.js. Clearly blocking `all 3rd party` is better than just blocking `cross-site & social`. This also flips your setting from standard to custom.

The only other item you could harden is to change TP from PB windows to all windows. But that will happen anyway, as Firefox ramp this up.

PS: blocking cookies on a domain also blocks that domain's ability to use localStorage, sessionStorage, indexedDB, service worker cache etc. Some of that may change, and it gets complex and the rules change a little for session cookies (that may change as well) and in PB mode. And 1st party vs 3rd party rules are different. It's complex. But for now they seem to have tied everything back to cookies as a master switch per domain under a quota management

**Comment by Thorin-Oakenpants** [comment]
^^ tl;dr ?  Do what you like :) Standard (default) is fine. The user.js already changes it to custom by changing the cookie setting. We would also expect most users of this repo to have uBO, so we're happy to let TP just be in PB (private browsing) and Firefox will change that anyway, when they are ready.

**Comment by Thorin-Oakenpants** [comment]
Here's them "ramping it up" - https://blog.mozilla.org/blog/2019/10/22/the-illusion-of-choice-and-the-need-for-default-privacy-protection/

I mean look at that graph ... in a few months you're going to look at that miniscule 450 billion and realize that's what gets blocked in a week, then a day. They're only just starting

**Comment by privacyguy123** [comment]
Thanks for the in depth reply!
