### ISSUE TITLE
user-overrides.js: Override Ghacks value with Firefox default value

### ISSUE THREAD

**Issue by eggplanting** [ghacksuserjs/ghacks-user.js#821]
Hi,

could someone tell me if it is possible to set a value from Ghacks user.js back to the default value via user-overrides.js?

I don't want to set a static value, since a Firefox update could make changes.
This is exactly what your wiki tells under "Changes to default values": https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.2-Applying-Your-Changes

For example, I tried to set following value to the defaults:
user_pref("privacy.sanitize.sanitizeOnShutdown", true); // Ghacks user.js
user_pref("privacy.sanitize.sanitizeOnShutdown",); // user-overrides.js

This didn't work. Is there some way around this, which is not documented so far?
Probably there is some way to comment out the user.js entry entirely, via user-overrides.js?

**Comment by Thorin-Oakenpants** [comment]
```js
user_pref("privacy.sanitize.sanitizeOnShutdown",)
```

You need to apply a value - see [working with a user.js](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview#small_orange_diamond-working-with-a-userjs)

> Preferences must follow Mozilla's syntax which is `user_pref("prefname", value);`. Note that the preference name must be wrapped in quotation marks, and do not forget the semi-colon at the end. The value must also be wrapped in quotation marks, but only if it is a string

so you need
```js
user_pref("privacy.sanitize.sanitizeOnShutdown", false);
```

I don't use an overrides.js : that's for you to use as a master list / backup copy: I also don't use the updater ( @earthlng and @claustromaniac and @overdodactyl worked all that out ) so I'm not 100% sure how it works.

I **think** if you use the updater it grabs the new version and then appends your overrides.js to the end of the user.js. Long story short: **all** your changes need to end up in the user.js file - because Firefox only parses that one file

```js
//blah blah master copy from ghacks.js
//end of ghacks

// special eggplant overrides
user_pref("privacy.sanitize.sanitizeOnShutdown", false); 
```

**Comment by rusty-snake** [comment]
The Windows updater script supports commenting `user_pref`, but the linux not.

**Comment by eggplanting** [comment]
Thanks together, rusty-snake pointed me to my solution! :)
