### ISSUE TITLE
Broken icons?

### ISSUE THREAD

**Issue by privacyguy123** [ghacksuserjs/ghacks-user.js#824]
Anybody know which setting is affecting these buttons being able to load?

![image](https://user-images.githubusercontent.com/50337995/67685901-c60daa00-f98d-11e9-812d-3c865aabcf8e.png)

**Comment by rusty-snake** [comment]
Which site?

I have often seen something like that if `svg.disabled = true`.

**Comment by Thorin-Oakenpants** [comment]
Those are `ligatures` - see https://github.com/FirefoxBar/HeaderEditor/issues/46 - It is caused by `browser.display.use_document_fonts` 

You have two options
- get the extension dev to code around it
- log a bugzilla that the pref should not apply to extensions (not sure if it will get any priority as the pref is rarely used) - but who knows, some of these are trivial bits of code: example that svg pref not applying to extensions - for years it lingered, but then gk from tor project opened a ticket and it was done with 2 or 3 days

**Comment by Thorin-Oakenpants** [comment]
That is an extension, right?

**Comment by privacyguy123** [comment]
These are icons on a website page - seems strange the fonts option affects it but you are right, yes.

**Comment by Thorin-Oakenpants** [comment]
Most websites these days use downloadable fonts for lots of reasons: the main one being that they need conformity and reliability across browsers/platforms

Font fingerprinting is pretty high up the list in terms of entropy - you would most likely be unique if a script dug deep enough.

But here's the thing: **if** a script ... you can drastically reduce the attack surface by blocking most 3rd party scripts (e.g uBO, uMatrix, and of course enabling the fingerprinters tracking protection). So up to you if you want to override that pref

And, how many sites screw up icons like this, depends on the user experience. I never see those ligatures, but I do see [tofu](https://en.wikipedia.org/wiki/Tofu_(disambiguation), but it's usually pretty clear what the button does when you hover over it and read the URL, but that's my user-story, not yours.

**Comment by Thorin-Oakenpants** [comment]
pref was made inactive in AF v82, and since AF v91 has been under a `DON'T BOTHER` section, hence changing the labels
