### ISSUE TITLE
wiki: Cookie Controller tutorial

### ISSUE THREAD

**Issue by Atavic** [ghacksuserjs/ghacks-user.js#83]
- user.js gives a disallow all for cookies and hints at Cookie Controller addon for allowing specific sites where one has to login.

- Improve the Wiki, add info into Scripts and Appendix about addons setup (Cookie Controller, uBlock) to give a complete solution with user.js

For Cookie Controller:

Install Cookie Controller by iann. Once installed, a new item appears under Tools menu. Select it and under _Settings for Toggle states_ check _Force "off" state at start_ then be sure that _Session only_ is checked.

From here, you can CTRL- or middle- click to set a temporary exception for a page you may find problematic. If the temporary exception solved your problem, you can click on _Cookies allowed for `<site domain>` only as a 1st party_.

**Comment by Thorin-Oakenpants** [comment]
So this is not about the user.js, but a wiki suggestion? I don't want to reinvent the wheel ... but I have ideas for the wiki (we already have a uBo and uMatrix scripts section to build on), with more how to's/tutorials: such as a super simplified uBo + uMatrix default settings for hardened mode bwteeen them (earthlng & I use a different approach which is worth noting), not to mention these working with NS. Not sure about cookie controller - will it become a WebExtension? The user.js with default deny-all cookies, still allows cookie control under site permissions, so an add-on isn't strictly necessary.

**Comment by zymase** [comment]
Concerning cookies management in Firefox I'd seriously consider another add-on approach than that of _Cookie Controller_, a nice add-on but requiring the user's intervention. It's just more elaborated but the concept is old.

I plead for the [Self-Destructing Cookies](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/) Firefox add-on. it handles not only cookies but the user's Dom Storage as well, cleaning both unless the site has been set as an exception (Privacy/History/Accept cookies from sites/Exceptions/allow) by the user. It can as well clear the caches at a defined interval. This is the must IMO concerning Firefox cookies. It's so logical. Allow cookies (still block 3rd-partie cookies though) and have them wiped when you close a non-whitelisted site. Et voila. No fuss, nothing to do, let it roll.

**Comment by earthlng** [comment]
https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/

> Gets rid of a site's cookies and LocalStorage as soon as you close its tabs.

> Version 0.4.12
> add-ons can't monitor sites' LocalStorage usage in e10s mode

---

> It can as well clear the caches at a defined interval.

same as uMatrix

> have them wiped when you close a non-whitelisted site

same as uMatrix

> No fuss, nothing to do, let it roll.

I'm not against recommending this addon but uMatrix users don't need an another addon for Cookie handling AFAIK. I could be wrong of course so please correct me if I am

**Comment by zymase** [comment]
_uBlock Origin_ is already considered by many users as too complicated and _uMatrix_ even more.
Moreover _uMatrix_ is not cookie specifically oriented.
Also, if _uMatrix_ is an argument then it is towards _Self-Destructing Cookies_ as _Self-Destructing Cookies_ is towards _Cookie Controller_. At the end no intention here else than to propose, and I am proposing in the area of cookie management since this is the topic of this thread.

Is _Cookie Controller_  e10-compatible? I know it's not a Webextension at this time. And besides it's been said and written here that versions of Firefox considered are last release and coming one. So I'm not considering november 2017 and Firefox 57 but only Firefox 52 and 53.

**Comment by earthlng** [comment]
> since this is the topic of this thread

afaik this topic was created by @Atavic to outline a possible _How-To for Cookie Controller_ for the wiki.

[Appendix B: Firefox Add ons](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B:-Firefox-Add-ons#small_orange_diamond-recommended-add-ons] - Self-Destructing Cookies is already listed

**Comment by earthlng** [comment]
Tom, I appreciate your input but this is not the right issue to place your disagreements about an addon recommendation. If you feel strongly about SDC being better than CC, it would be great if you write up a tutorial/how-to article explaining why it's better and your recommended way to use/config SDC, etc. (with some nice images and stuff) We can host the article here and link to it in the Appendix B.
You're the master of addons around here anyway (70+ addons, right?) :)

**Comment by crssi** [comment]
Just commenting the current debate.
First, explaining myself: I am looking to FF settings from the non-experienced users eyes (like my folks, etc.).
There are quite a lot of sites that doesn't work as intended when cookies are blocked, so I am here on @zymase modus operandi, which is somehow reversed logic from @earthlng and @Thorin-Oakenpants.
I am allowing all cookies, even 3rd party for a session time being, and letting SDC destroy them after.
This works very good for any non-computer expert user.
For 1 or 2 sites I can set SDC not to destroy cookies after where this is needed.

**Comment by Atavic** [comment]
Call me nostalgic, but [self-destructing-cookies](https://addons.mozilla.org/firefox/addon/self-destructing-cookies/) addon is just one of those that will stay in a legacy FF install.

@earthling I generally propose to include some quick how-to instructions in the wiki.

e.g  Add uBlock set-up and suggest the [Blocking mode: hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode).

**Comment by zymase** [comment]
I have the feeling @earthlng and @Thorin-Oakenpants are becoming omnipotent, rigid with pseudo category rules which have no meaning. Little village chiefs.

Bye. I'll manage by myself and share elsewhere. Far too sectarian here.

**Comment by Thorin-Oakenpants** [comment]
Not sure what I'm supposed to do with that? Am I meant to change the user.js cookie preference and espouse the virtues of another add-on? One that is not e10s. The user.js actually says to use site permissions OR an extension - and the extension was an example, not an order. Why am I being blasted over this, after 2 years of it being there?

The default `deny-all` (with granular control) is what this user.js has been about since day one. It's consistent. It is also a better methodology IMO. For example, imagine PB mode where you have no control over cookies (with any add-on) - all cookies persistent until the session ends (but in user.js mode they are blocked). Or imagine normal mode but you have 50 tabs open... all with cookies (in user.js mode they are all blocked).

Whether a user wants to use whitelisting (deny-all) or blacklisting (default self-destruct) is their choice. It's one setting in the user.js out of over 400. The user.js is a template.

As for SDC vs CC: that's up to the end-user. CC is e10s (which may be enforced in 12 weeks come FF55), and SDC is not. CC also handles local dom storage, just to clear that up. CC is also set and forget, voila and all that. BOTH are listed in the recommended add-ons. What more am I supposed to do?

Personally, I think cookies are over-rated. Except for where I need to login, I have no issues with any sites not accepting cookies. Hence why I use whitelisting (grand total of about 8 cookies allowed as 1st party, that's it - about 8 more as session only). I am, of course, but one user. For me I find only allowing up to 16 cookies ever is a hell of a better option that allowing everything. Both SDC and CC would still require me to whitelist. These 16 cookies I can still delete them via the UI interface, via CC settings, via CCleaner etc. Why wrote and store for any period thousands of cookies, 99% of which you don't need to? IMO it just creates more "attack" surface.

However, it's an end-user choice. Hell, use both in different profiles for all I care.

===
Not even sure why this topic was created (or worded like it is). I for one will NOT be doing any tutorials for the wiki on non e10s add-ons. I will do/consider non WebExtension, as ESR will be around for a long time. But truth be told, I do not want to re-invent the wheel (maybe we could to point to articles like 12bytes and uBo/uMatrix's own wiki pages to help end users - just add then as bullet points under each add-on). The add-ons suggestions are going to undergo a lot of change as e10s is enforced, then WE only, and a lot of potential extensions get ported (or work out of the box) from the chrome store, not to mention the devs of our current add-ons, such as NS, gorhill, SmartReferer etc working on WE versions. So I'm also kind of loathe to do anything for a while until the smoke clears a little.

**Comment by Thorin-Oakenpants** [comment]
@Atavic If you want to write a tutorial for CC, go for it. Either create a wiki page on your fork for us to look at, or just type it up in here

**Comment by crssi** [comment]
I must completely disagree with the latest post of @zymase.
I would not take it personally, its might just be someones the "those days in the month". :)
And the truth is that SDC is not "future compliant" (I hope the author will do something about it).

@Thorin-Oakenpants and @earthlng, you are champs, and please, don't get distracted with similar posts.
I also have a few differences in my user.js version, but those I am keeping in queue for a debate for the light version, when it comes. :)

**Comment by earthlng** [comment]
> I have the feeling @earthlng and @Thorin-Oakenpants are becoming omnipotent, rigid with pseudo category rules which have no meaning. Little village chiefs.
> 
> Bye. I'll manage by myself and share elsewhere. Far too sectarian here.

Jeez, I don't even know what I wrote that caused such a strong reaction?! I already feel like walking on egg-shells and am trying my best not to offend anyone around here. I'm sorry Tom (@zymase)
I guess you/he only read the less than ideal title (which btw was chosen by Atavic, Tom) and took offense when I told you/him that this issue is not really about a discussion for Cookie addons. (?)
And Pants didn't even respond to your comments, Tom, so it's totally unfair to include him/her in your accusations.
We are indeed omnipotent around here but I don't think we are unreasonable. We try to keep the issues clean and not going offtopic, and not having the same discussions over and over again in different issues.
This whole thing is about prefs first and foremost and the rest is just bonus material that we (well, mostly Pants) try to write up to help others.
We have "official" issues/stickies and everyone is free to create new issues to their heart's content.
If we don't moderate the tickets to a certain degree, it will all become much less useful very quick.
We are trying our best here so please give us some slack, we're only human and same as everyone else we also have bad days sometimes.

Bye, I guess

**Comment by Atavic** [comment]
Ghacks user.js is a template. OK on that. Wiki suggests addons, then leaves no hints at how to set them up. On the opening post I say what to do, once CC is installed, to set cookies preferences up as user.js does. Nothing more, nothing less.
