### ISSUE TITLE
ciphers

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#839]
I'd like to strip out the ciphers BS. At  the end of the day, there is no need for someone to disable any of them: they should leave it up to Mozilla and their experts to decide when to deprecate something

At the very least this
```
   Note that your cipher and other settings can be used server side as a fingerprint attack
   vector, see [1] (It's quite technical but the first part is easy to understand
   and you can stop reading when you reach the second section titled "Enter Bro")

   Option 1: Use defaults for ciphers (1260's). There is nothing *weak* about these, but
             due to breakage, browsers can't deprecate them until the web stops using them
   Option 2: Disable the ciphers in 1261, 1262 and 1263. These shouldn't break anything.
             Optionally, disable the ciphers in 1264.

   [1] https://www.securityartwork.es/2017/02/02/tls-client-fingerprinting-with-bro/
```

can be changed to
```
   Note that your cipher and other settings can be used in server side fingerprinting
```

We could even not have that and just change this
```
/** CIPHERS [see the section 1200 intro] ***/
```

to 
```
/** CIPHERS [don't fuck with these, u morons] ***/
```

@earthlng : please advise

**Comment by Thorin-Oakenpants** [comment]
^^ bump

**Comment by TomasGutierrez0** [comment]
Mozilla is planning to [disable support for TLS 1.0 and 1.1](https://blog.mozilla.org/security/2018/10/15/removing-old-versions-of-tls/) in march 2020. It would be pointless to disable TLS 1.0 and 1.1 ciphers if later they are going to be disabled anyway.

I don't know if Firefox disables them by default or not but user.js should disable null ciphers as it only authenticates but doesn't encrypt the connection which is a security problem.

**Comment by Thorin-Oakenpants** [comment]
^^ yup, that's already noted, and the prefs are inactive (commented out)

```js
/* 1202: control TLS versions with min and max
 * 1=TLS 1.0, 2=TLS 1.1, 3=TLS 1.2, 4=TLS 1.3
 * [WARNING] Leave these at default, otherwise you alter your TLS fingerprint ....
```

What I'm talking about here is trimming fat and keeping things as simple as possible

**Comment by earthlng** [comment]
To me that's useful information because it highlights the prefs (among all the other `security.ssl3.*` prefs) that should ideally be disabled by default but still aren't.

And nobody is forced to read the link in [1] but those who want to know more have a good starting point.

Instead of just removing it and forget about it, having it in the file could prompt some people (or we could maybe even ask people) to create github accounts and go vote on some of these bugs and/or create new bugs to pressure mozilla into some action.
fe. https://bugzilla.mozilla.org/show_bug.cgi?id=1367617 is about one of those prefs and even Chrome disabled it some 3 years ago while mozilla is apparently still too busy creating new firefox logos every couple months and designing new stupid cutesy dragons (or whatever the fuck these things are supposed to be) on all their error/warning pages and shit like that.

Like, how hard can it be to toggle a few prefs and see how it goes?! All the other browsers have already done it a long time ago:

> Looks like Chrome bumped the minimum DH key size, so we probably can too.

^^ [source](https://bugzilla.mozilla.org/show_bug.cgi?id=1367617#c1) (posted 3 years ago!)

> Other browsers completely disable DH.

^^ [source](https://bugzilla.mozilla.org/show_bug.cgi?id=1367617#c9) (posted "last year")

1367617: opened 3 years ago - last activity: "last year" - progress after 3 years: zero!

**Comment by Thorin-Oakenpants** [comment]
Not saying to remove the actual ciphers. And the link is fine I guess, but then I can't make that line much simpler. I just wanted to simplify the FP aspect, and not list option 2. All I want to say is don't fucking change these cuz 1: FP and 2: almost zero risk: i.e was a warning in the actual cipher subsection.

I'm just trying to reduce walls of text to make the js more palatable.

---

I read some of those cipher bugzillas about 6 months ago and wondered why they're taking so long. Surely they have them in their telemetry (but I just now read some open bugzillas on improving the the telemetry to distinguish some ciphers, so who knows)

- [1367617](https://bugzilla.mozilla.org/show_bug.cgi?id=1367617) - Increase minimum DH key size in TLS handshakes to 2048 bits
- [1227524](https://bugzilla.mozilla.org/show_bug.cgi?id=1227524) - Establish deprecation date for 3DES
- [1496639](https://bugzilla.mozilla.org/show_bug.cgi?id=1496639) - Establish deprecation date for DHE cipher suites in Firefox
- [1227522](https://bugzilla.mozilla.org/show_bug.cgi?id=1227522) - Establish deprecation date for CBC cipher suits
   * ^^ I have NFI if this is still relevant

---

> busy creating new firefox logos every couple months and designing new stupid cutesy dragons

Lols. Yeah. their UX department must be overstaffed. They should trim that and shift resources to engineering :) Might upset all the fanboys circle jerking at reddit over them. Logo posts get a disproportionately large amount of comments: whereas something like the CSP header injection gets shadowbanned. Fuck em.

**Comment by earthlng** [comment]
re: "Not saying to remove the actual ciphers." ...

> What I'm talking about here is trimming fat (specifically the ciphers sub section)

I read that as you wanting to remove the ciphers sub section. Just removing Option 1 and 2 in the header I guess is fine.

**Comment by Thorin-Oakenpants** [comment]
Sorry about that: that was a reply to someone referencing something completely different. OP states it clearly: both rough proposals reference a ciphers section: cogito ergo sum ... so that wouldn't be getting removed

**Comment by Thorin-Oakenpants** [comment]
https://tlsfingerprint.io/ .. no sure what to make of all that :)

**Comment by Thorin-Oakenpants** [comment]
PR: https://github.com/ghacksuserjs/ghacks-user.js/pull/844
