### ISSUE TITLE
Branches for Aurora/Developer and Nightly channels

### ISSUE THREAD

**Issue by ArchangeGabriel** [ghacksuserjs/ghacks-user.js#85]
Hi there,

And first of all, thanks for this great work!

One thing that might be interesting is providing branches for the other release channels. For Aurora/Developer, I think this is just shifting workload ahead: normally, this branch could just be merged into master when moving to Beta.

Regarding Nightly, it’s probably more demanding, because changes might happen everyday.

**Comment by Thorin-Oakenpants** [comment]
We plan on doing "lite/relaxed" and "hardened" (although this is pretty much hardened already) and maybe "social media not sure if we call it that" (allow service workers/svg/gmp's etc for popular sites like youtube, street view, netflix etc) branches for use in profiles. We will probably also do an ESR branch due to 57 dropping XUL - to give users more time to transition to WE.

We get diffs from earthlng ready to work on as soon as they are available. It's usually around 10-15 prefs each release, and beta users can refer to that in the meantime. Might be a bit too much work (for now) to cover actual branches for these, especially nightly.

**Comment by earthlng** [comment]
> Might be a bit too much work (for now) to cover actual branches for these, especially nightly.

Yeah definitely. We would need to do diffs for each channel and new version, and we can barely finish the stable diffs in a reasonable time due to lack of contributors. Atm it feels like I'm doing them alone tbh

**Comment by positr0nic** [comment]
@ArchangeGabriel Aurora is dead now with the release of FF stable 53

**Comment by Thorin-Oakenpants** [comment]
Nightly is problematic and aurora is now killed off. Not exactly sure where developer sits. Will keep these branch ideas in mind for when we expand to ESR and other preset templates.

**Comment by fmarier** [comment]
> Nightly is problematic and aurora is now killed off. Not exactly sure where developer sits.

Dev edition used to be based off of aurora, now it will be based off of beta.
