### ISSUE TITLE
browser.contentblocking.category blocks ETP prefs

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#862]
``` js
/* 2701 */
user_pref("network.cookie.cookieBehavior", 1);
```
is ignored, unless
``` js
user_pref("browser.contentblocking.category", "custom");
```

`browser.contentblocking.category` is missing in user.js  and thus set by default to `standard`.
ATM user must manually change in GUI to `custom`.

Cheers

**Comment by Thorin-Oakenpants** [comment]
if you change your cookie behavior to 1, the custom setting is automatically applied. Try it on a new profile.

**Comment by crssi** [comment]
No, it is not. 
I have tried with a new profile before posting an issue 😉 .
Maybe this is new to latest FF.

**Comment by Thorin-Oakenpants** [comment]
Lemme do some tests: I have ESR60, ESR68, FF60-FF73 portables with practically vanilla profiles all here as my test suite

**Comment by crssi** [comment]
Its not only the latest FF, it looks like FF 70 also.

**Comment by Thorin-Oakenpants** [comment]
I cannot replicate

🐧 info for reference: network.cookie.cookieBehavior
 * 0=Accept cookies and site data
 * 1=(Block) All third-party cookies
 * 2=(Block) All cookies
 * 3=(Block) Cookies from unvisited websites
 * 4=(Block) Cross-site and social media trackers (FF63+) (default FF69+)

🐧 Tests / STR

**FF71-73 (default 4)**
- tab1: about:preferences#privacy = standard
- tab2: about:config change pref to `1`
- tab1: **automagically changes to custom** - change it back to standard
- tab2: about:config change pref to `2`
- tab1: **automagically** changes to custom
- not going to test 0 or 3
- Interestingly, if you reset the pref (in about:config), it stays in custom mode (even after a restart) even though nothing is different. This might be by design and is immaterial IMO: it's just cosmetic.

**ESR68 (default = 0)
- results with `1` and `2` **and** `4`
- they all **automagically** change to custom

**Comment by earthlng** [comment]
Prefs in about:config are (often) tied to a prefs-observer which then does things like "automatically" change this thing to "custom" etc. But that's not (or not always) the case when a pref is applied from a user.js.
So I guess the STR would be to let the user.js apply the cookie pref and then check if the GUI correctly changed to custom

**Comment by Thorin-Oakenpants** [comment]
I'll let someone else test it: I need sleep. But it's still cosmetic and we don't want to add `browser.contentblocking.category` to the user.js

**Comment by crssi** [comment]
Here is the video: https://www.dropbox.com/s/at740nllocidetp/ffvideo.mp4?dl=0

Windows 10 up-to-date, FF 71 x64.

**Comment by crssi** [comment]
You can also simply test with your working profile (where u have user.js).
Change to `Standard`... restart FF. Is should be `Custom`, due to user.js, but it persist to `Standard`.

**Comment by Thorin-Oakenpants** [comment]
BTW: your video didn't show the value of the pref you were adding, but we'll assume it was not `4` :) 

It's just cosmetic. You can fix it manually - just click custom and restart the browser. Adding `browser.contentblocking.category` is a bit messy. The UI might confuse people - I'll have to re-check exactly what is shown to determine what to do here.

**Comment by Thorin-Oakenpants** [comment]
good lord I need some sleep

I *think* (99% sure) that we can just enforce `browser.contentblocking.category` = custom
 - when in custom display, the info displayed is **always correct** (i.e what is being blocked = exactly what the prefs are) - it doesn't matter if the configuration matches the default standard setup
   * see my point about "Interestingly, if you reset the pref (in about:config), it stays in custom mode (even after a restart) even though nothing is different."
 - when not in custom display and we end up with crssi's situation, the info displayed is incorrect (i.,e it says it is only blocking "cross site and tracking cookies" when in really it could be blocking all cookies)

So the only way to ensure the blocking info is correct is to enforce custom

@earthlng Does this sound right to you?

**Comment by Thorin-Oakenpants** [comment]
PPS: Thanks crssi 💋

**Comment by crssi** [comment]
> BTW: your video didn't show the value of the pref you were adding, but we'll assume it was not `4` :)

Not needed, since it shows that I have started a clean vanilla profile, and then I have used user.js, which enforces `1`. 😉 

>     i.,e it says it is only blocking "cross site and tracking cookies" when in really it could be blocking all cookies

I have think off that it might be only GUI fckdup, but in reality it is not blocking as long as it is `Standard`... I have tested it over `https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled`

> I _think_ (99% sure) that we can just enforce `browser.contentblocking.category` = custom

I will enforce it in my overrides if its not enforced by user.js.

> PPS: Thanks crssi 💋

least I can do ❤️

**Comment by rusty-snake** [comment]
FFX: 73; new profile.

`browser.contentblocking.category` is a hidden pref. If it is unset (not in user.js/prefs.js) and `user_pref("network.cookie.cookieBehavior", 1);` is in the user.js `browser.contentblocking.category` becomes `custom`. If it is set, it is not touched.

**Comment by earthlng** [comment]
At first I wasn't able to reproduce it ie I put a user.js with the cookie pref = 1 into a new profile, started FF and the category was correctly set to custom.
BUT once you change it to "standard", it sticks!
What I think is happening is that initially on FF start the user.js is correctly applied but then at some point FF sees .category=standard and resets all the relevant contentblocking prefs including the cookiebehavior.
I tested FF71 and todays Nightly and it's the same behavior in both. Ideally we should let mozilla know and get this fixed upstream but until then, yes I think we should enforce the category pref to custom.

Thanks @crssi, good find!

@Thorin-Oakenpants would you mind opening a ticket? thank you ;)

**Comment by Thorin-Oakenpants** [comment]
open a ticket where? at moz?

**Comment by Thorin-Oakenpants** [comment]
> At first I wasn't able to reproduce it ie I put a user.js with the cookie pref = 1 into a new profile, started FF and the category was correctly set to custom. BUT once you change it to "standard", it sticks!

Well fuck. Cuz after I confirmed it happening [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/862#issuecomment-566144574), when I went to recheck [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/862#issuecomment-566177233) I couldn't reproduce (and yeah, it was on the same profile I had used earlier: my practically nilla 71 test portable), but I thought it might be because I was so fucking tired. The cookie behaviour pref wasn't being applied, which was alarming - and I aimed to come back to it. Now it makes sense when you said **and resets all the relevant contentblocking prefs including the cookiebehavior.**

**Comment by crssi** [comment]
Looks like your approach to new profile might be different to mine.
STR:
1. Close FF
2. Delete FF profile folders, that is %appdata%\Mozilla\Firefox
3. Start FF, so profile folder with initial files are created.
4. Close FF
5. Add user.js into profile folder
6. Start FF... there is `Standard` instead of `Custom`, despite the value `1` in the user.js

Here it is reproducible every single time.

Cheers

**Comment by Thorin-Oakenpants** [comment]
> Here it is reproducible every single time.

Yeah, but that doesn't reproduce the problem that earthlng wants me to lodge with mozilla. 

I tested it twice (on the same profile). My test suite of portables are vanilla profiles with a user.js already there with some tweaks. So I simply used the existing user.js to add one line - which actually confirmed it. So the test wasn't flawed in the first test (luckily because ETP had never been changed: as earthlng found out: he had trouble reproducing), And the subsequent test I did on the ETP modified profile, showed it getting stuck in standard including the actual cookie setting.

Due to the two different results, like earthlng, I would have dug deeper.

----

@earthlng How would you frame this issue for mozilla: since you're the one with the exact STR? Is this also an enterprise policy option?

**Comment by Thorin-Oakenpants** [comment]
> but then at some point FF sees .category=standard and resets...

I guess resetting the pref also fixes this: you could use that in the STR to show it was the problem.

In cfg ... `pref()`, `user_pref()`, `sticky_pref()` and `lockPref()` .. I though there was a clear_pref or something?

---

FYI: OT: [reddit link](https://old.reddit.com/r/firefox/comments/ebbqqu/userjs_prefs_parse_error_unknown_keyword_error_in/)

**Comment by earthlng** [comment]
> open a ticket where? at moz?

yes. Pretty please ... :)

> Looks like your approach to new profile might be different to mine.

correct, I didn't do 3 + 4 in your STR. In step 3 the category gets set to "standard" and apparently once that's set, it sticks.
If you do 5 before 3, it'll correctly set the category to custom.

It's easier to test with FF portable because you can just create an empty "profile" folder under "Data" and put the user.js in there before you start FF for the 1st time with that profile.

If you want to test it your way, you can do 1, 2 + 3 to let FF create the randomly named profile folder, then delete everything in there, put the user.js in and then start FF again.

**Comment by Thorin-Oakenpants** [comment]
> you can just create an empty "profile" folder under "Data" and put the user.js in there before you start FF for the 1st time with that profile

But I reproduced without an empty profile. In fact my profile (portable 71) is was week old and had been opened dozens of times, including going to the options UI. Hope you weren't saying an empty profile was required in STR?

**Comment by crssi** [comment]
You don't need and empty profile.
Just change to `Standard` and restart FF. It will stay in standard and will not block 3rd party cookies, despite the value `1` in user.js

**Comment by earthlng** [comment]
The main issue is that once `browser.contentblocking.category` is set to `standard` (either manually or otherwise), all those ETP prefs are no longer honored when set from a user.js. ("no longer honored" = I'm pretty sure they get initially applied during startup but then later reset when FF sees .category="standard")
And it's not the UI page itself that does the resetting, it happens during startup

**Comment by earthlng** [comment]
AFAICT, in FF71 the affected ETP prefs are all of these:

- network.cookie.cookieBehavior
- privacy.trackingprotection.pbmode.enabled
- privacy.trackingprotection.enabled
- privacy.trackingprotection.socialtracking.enabled
- privacy.trackingprotection.fingerprinting.enabled
- privacy.trackingprotection.cryptomining.enabled

**Comment by earthlng** [comment]
Since `network.cookie.cookieBehavior` is the only pref out of those that we still have in the user.js, IMO we can just add the category pref to 2701 and keep it there until after the next ESR gets released, assuming they'll fix the issue by then.

**Comment by earthlng** [comment]
FYI ESR 68.3.0 has the same problem.

**Comment by Thorin-Oakenpants** [comment]
> The main issue is that once browser.contentblocking.category is set to standard (either manually or otherwise), all those ETP prefs are no longer honored when set from a user.js. ("no longer honored" = I'm pretty sure they get initially applied during startup but then later reset or overwritten when FF sees .category="standard")

^^ This. 

> And it's not the UI page itself that does the resetting, it happens during startup

Yes. In my test about 24 hrs ago, the cookie behavior pref wasn't applied. I'd start FF, go straight to about:config and check

**Comment by Thorin-Oakenpants** [comment]
> The main issue is that once browser.contentblocking.category is set to standard (either manually or otherwise)

I don't think this is quite true anymore. A brand new profile sets this to standard. Anyway, I'm pinging the moz guys

**Comment by earthlng** [comment]
> I don't think this is quite true anymore.

why not?

The main problem is when someone applies the user.js to a profile with ETP=standard, the cookie pref won't get set

**Comment by Thorin-Oakenpants** [comment]
nvm

**Comment by Thorin-Oakenpants** [comment]
FYI: hidden some comments to make for easier reading by moz engineers

**Comment by Thorin-Oakenpants** [comment]
FYI: I've passed this info onto someone at Mozilla - up to them to forward it to someone to consider and deal with it

**Comment by Thorin-Oakenpants** [comment]
FYI: [1607249](https://bugzilla.mozilla.org/show_bug.cgi?id=1607249) - Enterprise is not affected (which was what I was worried about), but outside of runtime is - e.g. user.js.

This is a WONTFIX which I don't fully understand (is user.js not supported? is it unofficial? not AFAIK). At the time, they made sure enterprise was OK but didn't think of all the methods, which I find really frustrating.

But we have our own undocumented fix - too bad for all those ignorant of this situation. The only conclusion I can draw from this, is that user.js (and cfg etc) are second class citizens and no longer supported or even considered (especially now Enterprise Policies exist)
