### ISSUE TITLE
Window Size Gets Cropped When Maximized - Firefox ESR

### ISSUE THREAD

**Issue by desmonk** [ghacksuserjs/ghacks-user.js#864]
When window gets maximized, the inner window remains cropped. This is similar to Tor Browser. Can we adjust this?

**Comment by crssi** [comment]
Not, if you are using RFP.
Also I would recommend not to. 
You can better use some chrome adjusting to change that nasty white border. 😉

**Comment by Thorin-Oakenpants** [comment]
see [this](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.3-Implementation#small_orange_diamond-at-a-bare-minimum) ... and scroll down and spot the info about **letterboxing** .. and read the info in the user.js about pref no `4504`

If letterboxing (LB) is disabled, you still have all your screen/window/chrome metrics protected as the inner window ones. The reason LB exists is so that when people resize (accidently, maximize, go full-screen, etc) the "inner window" snaps into preset sizes so as to provide as few buckets as possible.

Another way to work around this is to disable LBing, go to https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#screen and maximize: this will tell you your real inner window dimensions when maximized. Then you can set up some preset sizes in the `dimensions` pref listed in `4504`. But be aware that this is a list of all accepted sizes, so you would to cover a bit of a spectrum

e.g: LB off
- my full screen Firefox inner window is `2560 x 1439`
- my maximized Firefox inner window is `2560 x 1282`
- my new window size (on start, or new window) in Firefox with RFP is `1600x900`
- I also want to cater for the findBar which is `37`pxs (just toggle ctrl-F on the test page and so some basic math)
- I would also like a few more options to allow for non-maximized and smaller sizes

So I might set my `privacy.resistFingerprinting.letterboxing.dimensions` as;
- `2560x1439, 2560x1402, 2560x1282, 2560x1245, 1600x900, 1600x863, 1000x900, 1000x863, 600x600`
- i.e fullscreen, fullscreen with findbar, maximized, maximized with findbar, my default on open (I use pref 4502), my default with findbar, something smaller ... and a lower range

But I'm kinda against this. The pref is only there for testing, and not guaranteed to exist forever. The easiest thing for you is to just disable LBing if you can't live with it or your threat model doesn't call for it.

**Comment by Thorin-Oakenpants** [comment]
PS: the LBing margins will be patched to match your theme, and the LB'ed content will be attached to the top (rather than the center). This is https://bugzilla.mozilla.org/show_bug.cgi?id=1594455

And .. FYI: -> https://bugzilla.mozilla.org/show_bug.cgi?id=1601040

**Comment by crssi** [comment]
> Although once you get used to it, LB is fucking great :)

😄 It was driving me nuts for first few hours, changed the color of it and after I don't even notice it.

**Comment by Thorin-Oakenpants** [comment]
I never see it, because I don't deviate from my 1600x900 (except the findbar which is infrequent)
