### ISSUE TITLE
FF site exeptions/pinning tabs/Facebook-containers questions.

### ISSUE THREAD

**Issue by fu8765** [ghacksuserjs/ghacks-user.js#874]
1) I had to "unfortunately" comment out all the cookie removals sections, as i wish to keep logins for some sites.

however, looking at the documentation here "https://github.com/ghacksuserjs/ghacks-user.js/issues/350", I found"
Cookies [1]

    pref: network.cookie.cookieBehavior=2 (block all) (2701)
        use FF site exceptions (allow eg for logins, allow for session eg for sites that require them to work)

Is it possible to disable cookies, and allow some specific sites to set them? If so. how?
right now, I'm using cookie autodelete for a similar purpose.

2) how can I re-enable the ability to pin tabs?

3) Does first party isolation allows me to keep facebook logged in, but my information invisible from facebook trackers on other sites? or do I need containers to do so.. just want to make sure facebook is as isolated as possible.

Thank you. love your work Thorin

**Comment by Thorin-Oakenpants** [comment]
That's how I do it. Deny all, and allow site exceptions for 5 sites for logins, and about 8 other sites as session only, so they work. You may get different mileage - but be prepared for sites breaking with no cookie permissions: cookies control everything: localStorage, IDB, service workers cache: so some sites wet themselves

---

So the first thing I would do is decide if you're going to keep FPI on or off (that's the `privacy.firstparty.isolate` pref), because basically everything is related to Origin Attributes (FPI, containers, private browsing mode)

**A**: with Firefox closed, I delete (or rename as a backup file)
- `cookies.sqlite`
- `webappstore.sqlite`
- in `/storage/default/` remove anything not a `moz-extension...` folder.
- `permissions.sqlite`
- everthing in the `cache`

and/or **B**: 
- running Firefox's Ctrl-Shift-Del, select all time, and clear `cache`, `cookies`, `offline web data`, `site permissions`

In other words, start with a clean slate for permissions and all persistent local web data. Doing both A/B (besides the cache cleaning) is redundant, but sometimes there can be problems with orphaned data, and a manual approach is nice. Also, you may want to backup the permissions file so you can see what you have in there later.

---

All of that was optional: I just think it's better to start with clean data

Set cookies to always be denied for all sites: `network.cookie.cookieBehavior` = `2`, make sure cookies are not deleted on close.

to make site exceptions/permissions: e.g.
- go to GitHub, click on the padlock in the urlbar, click on the right arrow on the right, click on more information -> now you have the `page info` dialog. Or you can right click on an empty area of the webpage and select `View Page Info`
- click the permissions tab, for cookies, uncheck `use default` and select `Allow`
- refresh the github page, login - the cookie is allowed and will never get wiped

Do the same if you need a cookie for a site to work, but use `Allow for Session` and it will get removed when you close the browser.

You can see all your cookie permissions under about:preferences#privacy > cookies and site data > manage permissions: here's what mine looks like: the entire lot: e.g I allow a cookie for imdb for session else it breaks, same for imgur (otherwise albums break: lots of redditers use this and I often need to see the picture to know what they're talking about). I allow a tor project cookie as session, so it doesn't auto-log me in. I allow github as always, so I'm always auto-logged in.

![example](https://user-images.githubusercontent.com/16656956/72123561-926dd980-3359-11ea-99b7-a24848dab40d.png)

That's it: simple as: no need to worry about cookie auto delete (which is not effective and can leave orphaned data behind). The cookie permissions here will not protect you from repeat visits to the same first party in the same session - but if you regularly close your browser (like I do), then session cookies are wiped.

**Comment by Thorin-Oakenpants** [comment]
No idea about pinning tabs, I don't use it. I can right click on a tab right now and I see a menu entry for `Pin tab` (I didn't click it) - so I'm not sure what you mean. Maybe someone else can answer it and/or you can be a little more specific

**Comment by Thorin-Oakenpants** [comment]
> Does first party isolation allows me to keep facebook logged in, but my information invisible from facebook trackers on other sites? or do I need containers to do so.. just want to make sure facebook is as isolated as possible.

FPI will isolate the data (such as cookies, localStorage etc) per domain. e.g
-  A: `facebook.com` loads `facebook.com` stuff
-  B: `foo.com` loads `facebook.com` stuff
-  C: `bar.com` loads `facebook.com` stuff

Without FPI or containers (or a one off private browsing mode), those three lots of `facebook.com` stuff would all be **one and the same**: so at point A, at facebook.com, you log in, they have your facebook ID tied to your account. And at points B and C they can directly tie in your website traffic to your account - because of your facebook ID. Even if you weren't logged in (no site A), the tracking would still tie all the data together (B+C+D...etc)

But if you isolate it, then sites B + C + D etc can never access site A's data.. and in fact B + C + D etc can never talk to each other either. For containers, this is not the case: it might "contain" site A to it's own container, but every other site outside a container can be shared (B+C etc). But temporary containers can do this.

Also be aware that probably isn't really enough. FPI might isolate cookies etc, but it doesn't stop the first party (site B) telling the third party (facebook, site A) you came to visit. Site A is still being connected to. Your best best is block facebook.com and other FB domains on all sites but allow them on facebook.com - eg. in uBlock Origin.

Maybe someone else can explain it better. There's lot of variables here, so lots of solutions

**Comment by fu8765** [comment]
any option in user.js that we can do cookies per session as default? that would avoid a lot of breakage at the cost of privacy, but having first party isolate should protect.

something similar to cookie autodelete, but that it works 100%?

**Comment by fu8765** [comment]
> Also be aware that probably isn't really enough. FPI might isolate cookies etc, but it doesn't stop the first party (site B) telling the third party (facebook, site A) you came to visit. Site A is still being connected to. Your best best is block facebook.com and other FB domains on all sites but allow them on facebook.com - eg. in uBlock Origin.

hmm, if site B has facebook tracking.. but I logged in on facebook with FPI.
site B shouldnt have my account, unless I log into it.. correct?

**Comment by Thorin-Oakenpants** [comment]
> hmm, if site B has facebook tracking.. but I logged in on facebook with FPI.
> site B shouldnt have my account, unless I log into it.. correct?

If you login to facebook.com then you are obviously using an account = unique id. Without FPI/containers then facebook's cookie can be used on other sites = which means that the unique id is directly linked to that web site visit.

If you don't log into FB, it still sets a cookie etc (you might not even log in but still have persistent local data that identifies your account) .. or it's a `shadow profile`. That profile will still directly link all your web traffic (for sites that use FB as a third party).

Site B doesn't necessarily know anything - FB is doing the tracking, not site B.

---

This is but one form of tracking - e.g. your IP can still link your traffic - e.g you're on FB on one tab, on site B on another which loads isolated FB third party stuff. FB can probably tie the two together.

Just block all FB data as third party except on FB

**Comment by Thorin-Oakenpants** [comment]
> I like your idea about blocking all cookies by default and then exempting selected ones.

But that's what you asked
> Is it possible to disable cookies, and allow some specific sites to set them? If so. how?

---

> isn't there an option in user.js that can remove cookies and site data when you close the tab

No. That's what extensions are for, but there are long standing issues with clearing data due to API and other technical shortcomings (e.g. you can't clear IDB entries by host).

e.g. Cookie Auto-Delete
- you open a siteA.com
- siteA.com sets a cookie, some localStorage and an IDB entry
- the IDB entry contains a tracking uuid
- you close the tab
- CAD removes the cookie and the localStorage, but cannot remove the IDB data
- you think you're protected should you change IPs and revisit, but you're not
- there can also be issues with orphaned persistent data: because the cookie no longer exists, Firefox's internals may not be able to properly sanitize or even display siteA's persistent data

**Comment by fu8765** [comment]
> 
> 
> > hmm, if site B has facebook tracking.. but I logged in on facebook with FPI.
> > site B shouldnt have my account, unless I log into it.. correct?
> 
> If you login to facebook.com then you are obviously using an account = unique id. Without FPI/containers then facebook's cookie can be used on other sites = which means that the unique id is directly linked to that web site visit.
> 
> If you don't log into FB, it still sets a cookie etc (you might not even log in but still have persistent local data that identifies your account) .. or it's a `shadow profile`. That profile will still directly link all your web traffic (for sites that use FB as a third party).
> 
> Site B doesn't necessarily know anything - FB is doing the tracking, not site B.
> 
> This is but one form of tracking - e.g. your IP can still link your traffic - e.g you're on FB on one tab, on site B on another which loads isolated FB third party stuff. FB can probably tie the two together.
> 
> Just block all FB data as third party except on FB

Thanks for the response Thoring.
I think we misunderstood each other.
Not looking for an FPI alternative.
I just wanted to confirm how FPI works, and whether having FB cookie means, i won't be tracked by 3rd party sites (with cookies at least) is this how it's supposed to work?

**Comment by fu8765** [comment]
> 
> 
> No idea about pinning tabs, I don't use it. I can right click on a tab right now and I see a menu entry for `Pin tab` (I didn't click it) - so I'm not sure what you mean. Maybe someone else can answer it and/or you can be a little more specific

What happens is when you pin a tab, you can then close the browser.. and when you reopen, the tab is still there pinned..
this is useful for things like whatsapp web, slack, gmail. etc. that you use all the time.

with the user.js applies, after I reopen the browser, the pinned tab is no longer there.

**Comment by Thorin-Oakenpants** [comment]
It is probably something to do with session restore: but we don't disable that AFAIK. Or it could be part of history. Try those

**Comment by Thorin-Oakenpants** [comment]
Pinned tabs use session restore, which we disable
```js
/* 0102: set START page (0=blank, 1=home, 2=last visited page, 3=resume previous session)
 * [NOTE] Session Restore is not used in PB mode (0110) and is cleared with history (2803, 2804)
 * [SETTING] General>Startup>Restore previous session ***/
user_pref("browser.startup.page", 0);
```

So if you want SR then you will need to use an override
