### ISSUE TITLE
Use sticky_pref() instead of user_pref()

### ISSUE THREAD

**Issue by woky** [ghacksuserjs/ghacks-user.js#878]
I'm reading through the vast wiki and I've just stumbled upon https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.1-Resetting-Inactive-Prefs-%5BScripts%5D, which recommends for my taste quite ugly (as in fragile and unreliable) workarounds for removed/commented prefs. The article is 100% accurate, but after a bit of googling I discovered `sticky_pref()` function at https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences.

When I use `sticky_pref()` in `user.js`, the setting in `about:config` looks as if it was at its default value, which is however the value set in `user.js`. Moreover, the setting isn't copied to `prefs.js` on browser exit.

I'm not familiar with details, but it looks to me like using `sticky_pref()` in `user.js` solves the _reset_ problem completely in elegant way, making the cleanup scripts unnecessary.

Why do you use `user_pref()`?

EDIT: Well, it seems that this exact behavior in relation to `user.js` is not documented at all in the aforementioned Mozilla wiki. However, it works in  68 ESR nad 72.

**Comment by Thorin-Oakenpants** [comment]
the user.js is a **per profile** mechanism and it is important for users to be able to distinguish modified preferences in about:config: the old interface has a column for Status (e.g. `modified`), and the new interface you can spot them by the `reset` or `delete` icons

IANAE on this stuff, but sticky sounds like it's more useful in autoconfig. I'm also not willing to trust the sticky prefs won't be deprecated like `lockPref` (in 67+ you have to use `pref("name", value, locked)` instead )

And I'm also not willing to test that every pref works this way - I know in the past that some prefs couldn't be set using the lock mechanism, and who's to say that sticky doesn't also have the same problem

**Comment by earthlng** [comment]
Hi,

> However, it works in 68 ESR and 72

you're right but that's not how sticky prefs are supposed to work. The sole purpose of sticky_pref is that the value should always get written to prefs.js. Apparently that's currently not the case when they're used in a user.js but should we really rely on that? What if they decide to fix that or even worse, decide to ignore sticky_prefs in user.js files?

Yes, atm sticky_prefs would solve the **reset** problem in an elegant way but it would come with its own problems:
1. as Pants already mentioned, the modified prefs wouldn't be easily distinguishable in about:config.
2. temporarily renaming the user.js to test/debug something that might need a restart would no longer be possible
3. it would completely break our troubleshooter script because there would be no way to detect the user-set prefs.

We document every single pref change/removal in our changelogs and people who don't want to use the prefsCleaner and/or scratchpad cleanup scripts can just manually reset the necessary prefs based on the changelog

**Comment by woky** [comment]
> you're right but that's not how sticky prefs are supposed to work. The sole purpose of sticky_pref is that the value should always get written to prefs.js. Apparently that's currently not the case when they're used in a user.js but should we really rely on that? What if they decide to fix that or even worse, decide to ignore sticky_prefs in user.js files?

You're totally right about that. I I not forget, I'll open a report on bugzilla to get more info about current behavior in relation to `user.js` and whether devs plan to commit to it.

I've modified ghack's `user.js` to use `sticky_pref()` and everything I've search for in `about:config` so far had the default value from `user.js`.

> 1. as Pants already mentioned, the modified prefs wouldn't be easily distinguishable in about:config.
> 3. it would completely break our troubleshooter script because there would be no way to detect the user-set prefs.

I feel that these two points, mainly the first one, are not issues at all, since power users using `user.js` shouldn't really be confused by what's in `about:config`.

But I'm not disagreeing at all. I just wanted to get your feedback on `sticky_pref()` and you pretty much confirmed what I thought, i.e. that the current _nice_ behavior is undefined and hence unreliable in future. I'm total beginner in `user.js` world and the wiki mentions that I should customize the ghacks `user.js` to my linking anyway, so that's what I'm going to do. :-)

**Comment by earthlng** [comment]
> the current nice behavior is undefined and hence unreliable in future

if that's the behavior you want, you can use `pref()` which changes the default value without writing it to prefs.js
