### ISSUE TITLE
Reporting API

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#879]
- [FF65+](https://bugzilla.mozilla.org/show_bug.cgi?id=1492036)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Reporting_API)
- [Tor 32701](https://trac.torproject.org/projects/tor/ticket/32701)
- [example of leak: 1507280](https://bugzilla.mozilla.org/show_bug.cgi?id=1507280)

Maybe set these as false?
- `dom.reporting.enabled`
- `dom.reporting.header.enabled`

Is this similar to CSP reports (e.g which you can block in uBO)?

As for the bugzilla example, if you're using an en-US build you should be fine. But I have no real idea about this API, who uses it, how data is triggered, and if it can leak more than just a locale. Totally lost with al this shit: Feature Policy, CSP, CORS, CO-OP, ANAGRAM, ANACHRONISM, ANARCHY etc

Anyone with any constructive enlightment may enter and comment....

Note, the Reporting API being enabled/disabled is/should-be fingerprintable, but who cares. FPing generally comes last after closing possible leaks

**Comment by Thorin-Oakenpants** [comment]
- ESR68, FF65-72, Dev73 = default `false`
- Nightly 74 = default `true` (`dom.reporting.enabled` only, not headers)

So I guess it's just starting to ride the trains

**Comment by KOLANICH** [comment]
>Ian Clelland (Google Inc.) 
>Mike West (Google Inc.)
>Ilya Grigorik (Google Inc.)
>Paul Meyer (Google Inc.)

What else could you expect if the ones designing the standard have conflict of interests and Mozilla has to conform because with a few percent of users the company has no other choice?

Of course this should be disabled. But the problem is that Mozilla started making its (anti)features undisableable. I guess eventually the most of `.+\.(dis|en)abled` `about:config` entries will be eliminated.

**Comment by Thorin-Oakenpants** [comment]
> Of course this should be disabled.

I'm asking what it does -  I can't follow everything :) Until I understand WTF it is, I have no idea if it's an issue

**Comment by earthlng** [comment]
We discussed them in the FF65 diff but ultimately decided to ignore them because they were default-false at that point.
Yes this is similar to CSP reports but now they can also observe and process them with JS.
And it's not just for CSP violations but will eventually report all kinds of things, see fe "Such information can include:" in the MDN you linked.

I assume they'll add a UI option before/when they enable it because the spec is quite explicit about that ie the line quoted by KOLANICH

**Comment by gwarser** [comment]
> I assume they'll add a UI option before/when they enable it because the spec is quite explicit about that ie the line quoted by KOLANICH

I wouldn't be so sure, this quote should also apply to CSP and there is no switch for it in UI.

**Comment by Thorin-Oakenpants** [comment]
I don't know if the flip in Nightly has been on for some time (I only have 74 with which to check), so my question would be do we wait for this to turn up in diffs to action, or disable them now in the user.js - e.g. thinking of Dev/Beta users here

**Comment by Thorin-Oakenpants** [comment]
OT: just posting here for @gorhill since he might be interested in the discussion

https://trac.torproject.org/projects/tor/ticket/30570#comment:16

> However, uMatrix buckets browser resources slightly differently than NoScript. For instance, with vanilla uMatrix to support blocking web fonts we would need to block css entirely. uMatrix also does not seem to support blocking WebGL at all. So while we get the rules-engine that we want, we do end up losing some security/privacy by not being able to block things by default as granularly (or at least in the same way) as the current version of Tor Browser.

I'm not sure that the web fonts comment is true...

**Comment by gorhill** [comment]
> However, uMatrix buckets browser resources slightly differently than NoScript. For instance, with vanilla uMatrix to support blocking web fonts we would need to block css entirely

He is right, it's an accurate assessment. There is a long standing opened issue about this: <https://github.com/gorhill/uMatrix/issues/263>. I lean toward providing a per-scope switch for font rather than a new column just for font given how much horizontal space is limited in the matrix, but I never ended up deciding what I should do. It could be a per-scope switch in the UI, but a rule-based syntax internally so that one could manually create rules for `font`.

**Comment by earthlng** [comment]
> I wouldn't be so sure, this quote should also apply to CSP and there is no switch for it in UI.

yeah, I'm a bit too optimistic sometimes :)
