### ISSUE TITLE
Extension's access to cookies

### ISSUE THREAD

**Issue by zdat** [ghacksuserjs/ghacks-user.js#880]
Is there anything in the user.js file that could be stopping uMatrix accessing cookies?

I have everything configured to keep cookies based on exceptions, so I would like if uMatrix can delete the inactive ones after X amount of time without having to restart my browser. They aren't being deleted though and are remaining in about:preferences#privacy > Cookies and Site Data > Manage Data...

Thanks. Here is what I am checking in uMatrix:

![firefox_2020-01-13_03-53-36](https://user-images.githubusercontent.com/59732143/72232324-5edcba80-35b8-11ea-96a0-3d34e47c7d51.png)

**Comment by Thorin-Oakenpants** [comment]
Maybe ask at https://old.reddit.com/r/uMatrix/new/ ?

I do not use this feature. @gwarser knows lots - but my first question would be are you **sure** that you tested **session** cookies, because that's what the info says

Secondly, the `cookies and site data` **may** not be updated in a timely fashion (async arbitrary timing, but it's getting better), I know in the past you can to close and reopen the preferences page. Or you could use the storage inspector

**Comment by earthlng** [comment]
> Is there anything in the user.js file that could be stopping uMatrix accessing cookies?

First-Party-Isolation

**Comment by zdat** [comment]
Thanks guys. Wont be needing this option any more.

I'm using Cookie AutoDelete now. Has all the options I could want for managing cookies, really is much better than the one built into Firefox.

Don't think I need containers with FPI enabled, so I should be set in terms of managing and isolating cookies.
