### ISSUE TITLE
Disable indexedDB in Firefox 72+

### ISSUE THREAD

**Issue by RustyBurton** [ghacksuserjs/ghacks-user.js#884]
Hello.

Starting with version FF 72, mozilla removed the ability to change state indexedDB (false/true). But maybe there was some posibility to do it ? She did similar with preference **app.update.enabled** in past. But the opportunity remained to disable updates through policies.json. Maybe something similar remains for indexedDB? Please tell me if there is something in FF72+. I need ANY WAY to do this. I'm desperate.

**Comment by KOLANICH** [comment]
Why do you need it?

1. If you want to prevent websites from using it, you can use a webextension hooking and replacing the API. But it is fingerprintable.
2. If you want to prevent webextensions ... I remember that thay have reimplemented localStorage for tuem upon IndexedDB.
3. But I still dislike the decision to remove any pref from about config. We need more control, not less.

**Comment by RustyBurton** [comment]
I need that the browser itself, extensions and websites to think that indexedDB disabled. As it was before when **user_pref("dom.indexedDB.enabled", false);**  still existed.

**Comment by Thorin-Oakenpants** [comment]
The short answer is no. This user.js actually **enforced** that pref as true since it caused problems within FF itself (or at least did), and with extension data (or at least did) and that it's also a pretty blunt instrument to control something: it's not very granular. Far better solutions exist

---

The long answer:

If you use PB Mode, IDB is not available

Another option is that you control local persistent web storage by controlling cookies - i.e block cookies through Firefox's site permissions, and you block localStorage, sessionStorage, IDB and more. However that isn't for everyone: i.e default block then whitelist

You can also just clear all IDB data on close

You can also use FPI and that way all data is isolated. But within the same session it's not: so you can use Temporary Containers in a hardened config.

You don't **NEED** to disable IDB, what you *want* is to control web sites and mitigate your threat. And just what is your threat here? Don't answer that, it's rhetorical. But for example, Tor Browser don't need to worry about adverts or cookies, etc, because they have FPI, and for 99% of people, that's all you need
