### ISSUE TITLE
privacy.resistFingerprinting.letterboxing

### ISSUE THREAD

**Issue by zdat** [ghacksuserjs/ghacks-user.js#889]
Maybe a stupid question but I was wondering if there's anything (add-on, anything) that I can use that hides the true resolution (inner window) of my browser, instead of setting "privacy.resistFingerprinting.letterboxing", true.

**Comment by Thorin-Oakenpants** [comment]
No. Because elements can be measured (and other means) - you can lie about screen, and outer window sizes .. but not inner - not successfully

**Comment by qazip** [comment]
This is really bad, because having changed only the following from the default ghacks' user.js:
```
user_pref("privacy.clearOnShutdown.history", false); // Browsing & Download History
user_pref("browser.formfill.enable", true);
user_pref("privacy.resistFingerprinting.letterboxing", false); // White section around webpages
```

My fingerprint becomes unique in panopticlick. Just those 3 settings. In fact, it's probably just the letterboxing one since the value for screen size/depth is as follows:

Screen Size and Color Depth           17.46           180168.0           1918x979x24

**Comment by crssi** [comment]
^^ is it just the **WHITE** border that bothers you about letterboxing?

**Comment by qazip** [comment]
Hum, it's not the fact that it's white, it's the fact that it's there and that the webpage is thus smaller.

**Comment by crssi** [comment]
I am asking because it did bother me, until I have changed the color from white to something darker. 😉

**Comment by Thorin-Oakenpants** [comment]
`1918x979x24` <-- you are maximized on a 1920x1080 monitor (and letterboxing is turned off, as you said) - so what did you expect? Firefox is correctly reporting your inner window measurements = that's RFP being used. You are meant to stick to the default new window sizes (like Tor Browser), but that's not really all that practical - hence LBing which rounds your values in various steps = less buckets.

Do not read anything into the numbers or entropy given by sites like Panopticlick: they are tainted and flawed

**Comment by qazip** [comment]
Oh, I was actually using the entropy on Panopticlick as a deciding variable. I was changing:

- layout.css.devPixelsPerPx;
- Zoom level;
- Letterboxing;

To minimize the entropy on panopticlick. It really sucks that even changing the default zoom level ruins everything. In my case, if I want to not be "nearly unique" on panopticlick, the text needs to be nearly unreadable lol.

**Comment by Thorin-Oakenpants** [comment]
go [here](https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#screen)

Values are updated in real time if you zoom or resize on desktop. This is purely reporting values back: no entropy or bits guessing.

With RFP on, all your values should be the same: screen, available screen, outer, inner, viewport (less any scrollbar width). As you zoom or resize they **all** change. The matchmedia ones will the same integer part but may provide some decimal places depending on your devicePixelRatio

Now turn on letterboxing and resize, and the values will snap into set sizes (it uses different steps at different sizes at, but generally it's 100's in height and 200's in width)

I personally get confused over DPI vs devicePixelRatio (e.g. Retina, android phones, hiDPI?)  vs setting system sizes (e.g Windows Ease of Access settings) vs something simple like zoom: and I have no real idea **what** exactly that css pref is doing

> To minimize the entropy on panopticlick

Don't: The entropy is practically all BS - I can give you 10 good reasons why it's rubbish, but I don't want to do that for the 20th time.

You control most FPing by controlling third party scripts = e.g. use FF's in-build "fingerprinters" (on by default - it's in about:preferences#privacy ETP section), and something like uBlock Origin.
 
As a fallback, and scripst can be first party, you use RFP which protects against most scripts and the most common methods in the wild. Most scripts have stuck with the same techniques and data for years - e.g. using fpjs2 or something. There are other, newer FPing techniques - and the other one not covered by RFP is basic font FPing.

Don't worry too much about it. If someone wanted to **really** FP you - you'd be unique. And even with RFP and locking down fonts and using CanvasBlocker for things like textMetrics and domrect and audio etc - you'll still be pretty much unique.

RFP: feel free to zoom, but RFP will reset **new** tabs/windows at 100%. Zooming while on a site doesn't give anything away. Everyone would be the same: e.g we're all at 1000x1000, we all zoom to 133% and we all report  750x750. Big deal. Also zooming occasionally would make that FP unstable (because scripts can't easily know your actual zoom level: it's hard to do and they can't be bothered)

**Comment by qazip** [comment]
@Thorin-Oakenpants, thank you so much for this thoughtful reply, really. I am grateful you took the time to write that!

I have decided to use the ghacks user.js with only the below modifications:

```
user_pref("privacy.clearOnShutdown.history", false); // Browsing & Download History
user_pref("browser.formfill.enable", true);
user_pref("keyword.enabled", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true); // [FF68+] allow userChrome/userContent
user_pref("toolkit.cosmeticAnimations.enabled", false); // [FF55+]
user_pref("layout.css.devPixelsPerPx", "1.15");
```

So, I'll stick with Letterboxing for now. Hopefully my modifications are not too bad and won't seriously hit my privacy.

**Comment by Thorin-Oakenpants** [comment]
> layout.css.devPixelsPerPx  -> 1.15

Is that for usability reasons - e.g eyesight?

**Comment by qazip** [comment]
> > layout.css.devPixelsPerPx  -> 1.15
> 
> Is that for usability reasons - e.g eyesight?

Yes. My eyesight is good, however I don't feel comfortable reading small text. Without that (and without zooming in on every single page), the text is way too small for me.

This fingerprinting stuff is really hard. I noticed that on some sites the font is all messed up (webclient, rss reader, etc etc), so I set "browser.display.use_document_fonts = 1" and I immediately become unique on panopticlick. Damn. Guess I'll live with messed up fonts.

**Comment by Thorin-Oakenpants** [comment]
`browser.display.use_document_fonts` = `1` (default) is fine for usability. Don't worry too much about the fingerprinting. If you can't live with missing icon glyphs and a very limited set of fonts (and your mileage will differ depending on your default fonts: e.g. what language pack you use, what OS you are on), then reset it to default. **Your** internet needs to be usable **for you**

**Comment by Thorin-Oakenpants** [comment]
RFP = on, LB = on, issue (regardless of RFP/LB): text is too small

possible solutions: is RFP/LB still working as expected

---

`layout.css.devPixelsPerPx` = `1.15`

The browser opened and **everything** was 15% bigger, and the inner window opened at 1000x1000 (even though it's actually using 1150 : i.e 15% more). Depending on how much actual screen you have, you will end up with 1000x600 or x700height or x800 etc. And everything is still the same (i.e the four green dots in my test). Don't worry about the css *min* values or decimals in matchmedia results.

If you get letterboxing (unused space on the top and bottom) on new windows, that's because of annoying bugs with the toolbar etc. The letterboxing protects you somewhat by severely limiting the combinations of width/height you gave provide. Thats good. Just drag your window slightly taller to reduce so much wasted space

So I don't see any issues with this as a solution for you: except that it enlarges everything (pictures included). The real bonus here is that it doesn't affect measurements: e.g. you default font sizes are as expected, and so on: RFP works, LBing works .. elements getting measured still work (i.e expected values) and so on.

---

What I haven't tried yet is the option to just enlarge text
![zoom](https://user-images.githubusercontent.com/16656956/80190875-750d0480-8604-11ea-995a-461d41d795c5.png)

That's a pic from Nightly: and there are tickets in/closed/open (lost track) about how the zoom is meant to be disabled or a warning/note when RFP is on: that zoom is reset on new tabs. But I don't know without testing: because this is a default value, not a per site setting. This is also not the pref from above. And then there's the text only option. So zoom at 115% and check text only.

I might get around to testing this. But if you're happy with that layout pref, then use that. It's seems like a more solid solution, at first glance

**Comment by Thorin-Oakenpants** [comment]
@dngray if you have time... [Reddit PTIO question](https://old.reddit.com/r/privacytoolsIO/comments/gj34q0/is_it_safe_to_set_a_default_zoom_on_torbrowser_if/)

The answer is i the above post: set `layout.css.devPixelsPerPx` = `1.15` (for a 15% increase) .. this method will at least not affect any FPing methods that I know of re sizes of elements, window, screen, font, zoom values etc
