### ISSUE TITLE
Wiki: Conceal window.name has syntax error

### ISSUE THREAD

**Issue by quistor** [ghacksuserjs/ghacks-user.js#890]
Look like Conceal window.name script from https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts) has error which doesn't allow to enable it.
Error located in:
` // @exclude     /^https://www\.google\.com/recaptcha/api2/(?:anchor|frame)\?.+$/`

According to it, template for excluding link is incorrectly done. Script manager ask it to follow pattern of `/^(https?|wss?file|ftp|\*):\/\/(\^*|\*.[^*/]+|[^*/]+)\/.*$/` 

I am attaching error message
![error](https://user-images.githubusercontent.com/52989169/74123486-e3762500-4bc6-11ea-95b8-45a3b44462e4.png)

Steps to reproduce rather simple:
- Install script manager(tested with last version of Firemonkey and Tapermonkey)
- Copy script from wiki page
- Save script
- try to enable it

**Comment by Thorin-Oakenpants** [comment]
looking an [old revision](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts/88b689279abf3e140ba08e0f9813feca3d7ccd86) of that wiki page

this is what used to be in the script
```js
if(/^https:\/\/www\.google\.com\/recaptcha\/api2\/(?:anchor|frame)\?.+$/.test(window.location.href)&&/^I[0-1]_[1-9][0-9]+$/.test(_window.name))
```

@earthlng wrote `version 2.0`, so I'll let him sort this out. This isn't my area, so I'd be useless anyway :) Thanks for reporting

**Comment by earthlng** [comment]
That script wouldn't work with Firemonkey even if I changed that exclude line because FM doesn't support exportFunction(). I'm not familiar with Tampermonkey.
The script works fine with Greasemonkey but it's still easily detectable. I only wrote it because Pants felt that it's better than nothing but then he removed all his comments and now we're left with a subpar userscript and no explanation why it exists in the 1st place.
If you want a more robust window.name protection you can use CanvasBlocker.

**Comment by Thorin-Oakenpants** [comment]
I'm done with it - I'd rather delete it

It was a very messy page that needed a cleanup. Then we had new script versions, and we had FM being discussed .. I tried to do the comment thing: pointing out detection (IANAExpert), pointing out that the end user needs to make sure the script works in **their** choice of ext, pointing out all the alternatives (CB etc). I also listed FM, VM, and GM on the ext wiki page. On the scripts page I even starting listing a `works with` for each script - but all I got was negative comments, over a month.

I've wipe my hands of it when I stripped down to two scripts and nothing else - clean AF  - and no extension mentioned, and no script extensions in the extensions wiki page - no more arguments,. no more waiting for months for consensus - job done.

PS: I'd rather remove the scripts page - it's two scripts now and other solutions exist - but because @earthlng wrote two scripts, I'll leave it there - but fucked if I'm going to waste my time for more criticism

/end rant ❤️ 🍺 🍻 🐐 😴 

I've edited the top line to say "tested in GM only"

**Comment by earthlng** [comment]
I removed the window.name script from the wiki page

**Comment by Thorin-Oakenpants** [comment]
Why? The script works. The onus is on users to test the script (if it isn't GM). I'd rather it was put back (not everyone uses CanvasBlocker as an alternative). Please advise

**Comment by earthlng** [comment]
Before you edited your previous comment you said you'd rather remove that whole page. ??

Yes the script obviously works or I wouldn't have posted it but it only offers the most basic level of protection, is still easily detectable and a site can still get the window.name if it looks in the right place. 
Why provide a half-baked userscript when there are better ways to get real window.name protection, like CB or hardened TC ?!
AFAIK you can use CB and disable everything except the window.(name|opener) protection if you like. CB's window.opener uses a different method than my script but the end-result is probably the same

In the other issue you said you had problems with the window.opener script and that it didn't run correctly at document-start but never followed up or figured out why that was the case.
If that's indeed still an issue (for some people) then that turns a more elaborate script like the window.name one from mostly useless to potentially dangerous!

**Comment by Thorin-Oakenpants** [comment]
> and a site can get the window.name if it looks in the right place

OK. Didn't know that. So, good, one less script and less shit for me/you to deal with 👍 

Although we could just state that it's not perfect and only offers some protection - but fuck all that shit: been down that road of TMI

---

Yes, I don't want any scripts page TBH. I think the potential banana skins are legion (also another reason I removed TM/VM/FM from the extensions list)

**Comment by Thorin-Oakenpants** [comment]
> In the other issue you said you had problems with the window.opener script and that it didn't run correctly at document-start but never followed up or figured out why that was the case.

You closed the issue, which was my way of reminding myself. But I decided I didn't have time to work out why, and I'm using your extension: so in the end I'm not affected and I'm getting very selfish (no fucks given) and decided that it's not my problem. If you want me to troubleshoot why it fails in my FF setup, then open a ticket to remind me, and do it: for all I know the cause could be a common combo

**Comment by earthlng** [comment]
> If you want me to troubleshoot why it fails in my FF setup

that'd be great. I'll open that other issue again which served as your reminder
