### ISSUE TITLE
Add note on extension scope to 1.3 Implementation as default breaks system-wide extensions

### ISSUE THREAD

**Issue by martin21** [ghacksuserjs/ghacks-user.js#898]
Thank you for your great work!

So I did the recommended things and read the README and the Implementation guide. And still broke three of my extensions installed as Debian `webext-*`-Packages. And it took me quite a while to fix cause at first I searched user.js for `addon` but only found

```
/** EXTENSIONS ***/
/* 2660: lock down allowed extension directories
 * [SETUP-CHROME] This will break extensions, language packs, themes and any other
 * XPI files which are installed outside of profile and application directories
 * [1] https://mike.kaply.com/2012/02/21/understanding-add-on-scopes/
 * [1] archived: https://archive.is/DYjAM ***/
user_pref("extensions.enabledScopes", 5); // [HIDDEN PREF]
user_pref("extensions.autoDisableScopes", 15); // [DEFAULT: 15]
/* 2662: disable webextension restrictions on certain mozilla domains (also see 4503) [FF60+]
 * [1] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1384330,1406795,1415644,1453988 ***/
   // user_pref("extensions.webextensions.restrictedDomains", "");
```
after I searched for `extensions`. Before that I tried various other extension related settings that did not help

Of course, if you think that only very few people are affected, feel free to skip that suggestion, but unlike noted in issue #503 there is no WARNING in the comments for this settings either.

For other users of extensions packaged by Linux distributions, here is the override snippet I use:

```
/** EXTENSIONS ***/
/* 2660: lock down allowed extension directories */
user_pref("extensions.enabledScopes", 13); // [HIDDEN PREF]
user_pref("extensions.autoDisableScopes", 2); // [DEFAULT: 15]
```

I pondered whether to use extensions distribution as Debian packages several times. But with currently four browsers – Firefox and Chromium for two users – it means the difference between updating once or four times. However I am aware that I usually do not receive updates as often as would be good. I may ditch Chromium as with version 80 I read it limits uBlock Origin. Then it would be just two browsers to take care off. But same goes with different profiles. With system wide addons they are always just there.

**Comment by Thorin-Oakenpants** [comment]
hey @martin21 - I haven't forgotten this - I should get to it next week

**Comment by martin21** [comment]
Hi @Thorin-Oakenpants. Thanks for letting me know. There is no urgency in this.

**Comment by Thorin-Oakenpants** [comment]
https://mike.kaply.com/2012/02/21/understanding-add-on-scopes/
> 1 (SCOPE_PROFILE)
> 2 (SCOPE_USER)
> 4 (SCOPE_APPLICATION)
> 8 (SCOPE_SYSTEM)

---

I am not very Linux knowledgeable

- enabledScopes
   - user.js is `5` (profile, application)
   - you added `8` to allow for system scope -> `13`
   - that seems right
- autoDisableScopes
   - user.js is `15` (the lot)
   - you changed this to `2` - why does this need changing?
   - what is the default in your Linux FF (just reset it in about:config to check) - it's 15 in windows. I can't imagine the default at 15 breaks anything and that this doesn't need to be changed

It seems, to me at least, that enabled overrides disabled. I'm clearly missing something here, because if that were the case, the disabled pref is redundant: and that surely can't be true

@earthlng

**Comment by Thorin-Oakenpants** [comment]
note: we could probably also make autoDisabledScopes inactive - needs some thought and checkin'

**Comment by earthlng** [comment]
enabled doesn't override disabled, they control 2 different things. enabledScopes controls the locations from where XPIs are allowed/read and autoDisableScopes controls whether extensions from those locations are auto-disabled initially. If a location is not excluded from autoDisableScopes then I believe users are prompted whether they want to enable those extensions when they're first installed in their profiles.

OP had a problem finding the relevant item when searching for "addon" instead of "extension".
Squeezing the word "addon" somewhere in there should solve that.

**Comment by Thorin-Oakenpants** [comment]
> and that surely can't be true

As I said, I was missing something. But **now** it makes sense after reading your comment - loading that scope vs enabling/disabling that by default (if that scope is allowed/read).

But in a sense, enabled does override autoDisabled - i.e if the scope is not enabled, then autoDisabled is not applied for that scope - that's what I was getting at.

---

Maybe I need to take a break... anyway, I **think** we could make autoDisabled = inactive. And I still don't see why OP needed to change it to `2` - at most he should have subtracted `8` and used `7` if it caused prompts? I think `2` creates less "security" (prompt fallback?) - in which case we should leave it active and enforce `15` - IDK, don't really care either way

^^ but if you think we could improve that (active state, better info in the user.js, etc) then re-open (I'm going to close this)

---

add-on : 10 instances
   - 8 are "system add-ons" (what we choose to call that shit), 1 is a menu item, 1 is an URL
addon: 19 instances <-- all in URLs or pref names
extension: 61 instances

Addon is a legacy term - they are called extensions. Yes, "addon" is used in about:addons and prefs due to legacy naming (including the hamburger menu: A for add-on) - but the term is extensions. Not a single use of the word `addon` is used anywhere except prefs or URLs. Why should I break that rule.

Adding `addon` isn't the answer. `2660` already has a setup tag - searching for `[setup` will find you the problem. And if you used `setup-chrome` you'd get there even quicker - this is exactly why I created the tag in the first place: for non-website related stuff

closing

**Comment by martin21** [comment]
Dear Thorin-Oakenpants, I did not really understand what `autoDisableScopes` actually really does and just thought I invert it. Thus when I use

`user_pref("extensions.enabledScopes", 13);`

and `extensions.autoDisableScopes` by default is 15, I just do 15-13 = 2 and be done with it.

Now after actually completely reading the reference from `user.js`¹ and understanding that extensions installed on user request are by default not disabled, *no matter* what is in `extensions.autoDisableScopes` I see that 15-7 = 8 is safer, even when I have some process install an extension into the user directory without asking me first, I surely have a deeper issue as I don't see that any free software application on Linux would ever be supposed to do that. I again wonder why browsers have become so complicated, needed not one but two settings to control how it treats extensions.

That said, as quite some webext packages in Debian are highly outdated, especially important ones like uBlock Origin – and quite Debian bug reports about them are lingering for extended amounts of time I may just pull the plug and install them all from addons.mozilla.org. I wanted to keep the amount of software I install by other means than the systems package management to a minimum, but apparently with some things this does not work very well at the moment.

About the terms: I never received any communication from Mozilla within the browser that addons is an outdated term. So as a user how would I be supposed to know? If its outdated for the sake of consistency, they should change it everywhere. But well, that is something for Mozilla to consider.

[1] Understanding Add-on Scopes

https://mike.kaply.com/2012/02/21/understanding-add-on-scopes/
