### ISSUE TITLE
user.js in Firefox Beta

### ISSUE THREAD

**Issue by desk7** [ghacksuserjs/ghacks-user.js#901]
Can this guide be used also with Firefox beta? Is it possible to block all telemetry and other stuff only in Firefox stable or also in beta version? In the beta version is some telemetry always enabled and not editable?

Thanks

**Comment by Thorin-Oakenpants** [comment]
Yes, you can use this with Beta or Developer (up to 4weeks / 1 version ahead) or Nightly (8 weeks / 2 versions ahead) - but just be aware that any changes in those releases might not be "covered" until we do a new release - see the [changelogs](https://github.com/ghacksuserjs/ghacks-user.js/issues?utf8=✓&q=is%3Aissue+label%3Achangelog) (they're getting less full of changes)

Each release the number of changes are becoming a lot less now that Mozilla have been able to  move a more rapidly with XUL out the way. And they're now on a 4 week rapid release cycle, so even less changes. And the user.js is pretty much solid and awesome AF so no need for edits/tinkering from us much anymore

As far as you're concerned
- anything we change about existing stuff: 95% is just cosmetic otherwise, big deal
- anything in the user/js that gets deprecated doesn't matter: i.e you still apply the pref but it does nothing
- new: getting rare for us to add things, as most new Firefox stuff seems to be open specs and good choices

So yeah, go for it, just be aware that you're up to 4 weeks (beta/dev) behind - possibly missing out on one or two potential prefs we add/change - not a big deal

**Comment by Thorin-Oakenpants** [comment]
As for telemetry: AFAIK you're covered by the user.js - only Nightly *has/had* some enforcement.

Don't mistake telemetry / studies / pingcenter with valid external calls such as:
- firefox update checks etc
- recommendations
- lockwise / monitor
- sync / accounts
- submiting (user sent) crash reports
- etc

Telemetry is not bad: what they collect is not significant except to the developers, and none of it contains PII (personally identifiable information).
