### ISSUE TITLE
Lost html5 functionality for Netflix

### ISSUE THREAD

**Issue by begrey1** [ghacksuserjs/ghacks-user.js#903]
Tried changing a bunch of settings. I tailored the user.js to my liking, but I couldn't figure out which setting is screwing with my Netflix html5 in browser. 

Also, which setting can fix the sound/video stopping when I switch tabs?

**Comment by Thorin-Oakenpants** [comment]
Have you only just applied the user.js (with some changes)? Did you look at the `[SETUP` tags?

```
/* 1825: disable widevine CDM (Content Decryption Module)
 * [SETUP-WEB] if you *need* CDM, e.g. Netflix, Amazon Prime, Hulu, whatever ***/
user_pref("media.gmp-widevinecdm.visible", false);
user_pref("media.gmp-widevinecdm.enabled", false);

/* 1830: disable all DRM content (EME: Encryption Media Extension)
 * [SETUP-WEB] if you *need* EME, e.g. Netflix, Amazon Prime, Hulu, whatever ***/
user_pref("media.eme.enabled", false);
```

You need to add them to your overrides as true

**Comment by Thorin-Oakenpants** [comment]
> Also, which setting can fix the sound/video stopping when I switch tabs?

search for the word `autoplay` -> 2030. I don't play media, so I'm not 100% sure if this is the pref  on stopping auto-muting tabs with no focus

Also 2031 (at false) might be handy to flip to true: what it does (when true) is that if you allowed a video on say YouTube, then subsequent YouTube videos no longer prompt/block because you already physically interacted with the site - I think this is session only

**Comment by Thorin-Oakenpants** [comment]
marking as invalid: OP didn't RTM (or even reply back)
