### ISSUE TITLE
Extension ClearURLs reloads each 15 seconds

### ISSUE THREAD

**Issue by Pilford** [ghacksuserjs/ghacks-user.js#906]
After updating FF to v74 I noticed a small issue with the extension ClearURLs. It reloads each 15 seconds. You can see an annoying flickering each time. Go for instance to the options of the extension: Ctrl+Shift+A. The tab Options closes after 15 seconds.

If you delete the file user.js everything is OK. I checked all sections and I figured out the bad boy:

user_pref("security.OCSP.require", true);

If you change true to false the reload is gone. However, I have no idea if it harms to make this change.

**Comment by Thorin-Oakenpants** [comment]
> user_pref("security.OCSP.require", true);

That's interesting, but I think is a red herring - the real issue is how ClearURLs handles not getting an update

---

@gwarser FYI 

I also got this, but in 73. It's to do with when the rules get updated. I emailed Kevin. Also see https://gitlab.com/KevinRoebert/ClearUrls/-/issues/428

![ext](https://user-images.githubusercontent.com/16656956/76677220-9c16f600-65c3-11ea-9616-52c4b7f59d92.gif)

In my case, **network is not disabled**. 
In my case, **security.OCSP.require = false**
In my case
- I went to `about:debugging#/runtime/this-firefox` and looked up the ClearURLs' Internal UUID
- I went to my profiles `storage/default` dir and there was no IDB data for the extension
- I removed the extension, restarted, added extension - problem persisted
- may be incidental, but after a couple of option changes (e.g. badge color) and save/reloads, it created an IDB entry and the problem went away

So gwarser shows with no network, there is a side effect. You showed that with OSCP failing, there is the same side effect. I showed that (for whatever reason) when the IDB data is missing, it shows the same side effect (and can't seem to recover: even though it has base rules).

The ball is in Kevin's hands

**Comment by Thorin-Oakenpants** [comment]
^^ @KevinRoebert .. fyi

**Comment by KevinRoebert** [comment]
@Pilford:

> After updating FF to v74 I noticed a small issue with the extension ClearURLs. It reloads each 15 seconds. You can see an annoying flickering each time. Go for instance to the options of the extension: Ctrl+Shift+A. The tab Options closes after 15 seconds.
> 
> If you delete the file user.js everything is OK. I checked all sections and I figured out the bad boy:
> 
> user_pref("security.OCSP.require", true);
> 
> If you change true to false the reload is gone. However, I have no idea if it harms to make this change.

`openssl.exe s_client -connect kevinroebert.gitlab.io:443 -status` outputs:
`OCSP response: no response sent`.

So it is true that GitLab Pages does not support OSCP. I will contact GitLab support and ask if this can be activated.

**Comment by KevinRoebert** [comment]
https://gitlab.com/gitlab-org/gitlab-pages/-/issues/364

**Comment by KevinRoebert** [comment]
@Pilford @Thorin-Oakenpants Could you please try again in version 1.16.0?

**Comment by Thorin-Oakenpants** [comment]
I'm not sure I can. I updated to 1.16, copied by FF portable as a master, closed, renamed the relevant`profile/storage/moz-extension+++UUID` folder (to simulate it being missing), and restarted

Without digging further, it seems like all my extensions broke. My speed dial landing page didn't load, another extension's toolbar button's page action wouldn't populate - clearURLs page action was blank of data (just titles showing) and it says something like "oophs something went wrong"

I closed and deleted the contents of `profile/startupCache' but nothing changed

That was just a quick test, and I'm not sure what happens if I replicate that, but then disable clearURLs - I can't see how one extension would affect others - so it must be some sort of sanity test of web ext data by Firefox? IDK

**Comment by Thorin-Oakenpants** [comment]
^^ the good news: in that test, ClearURLs instantly created a new IDB data set - but the size was way off (I'll have to replicate to report the sizes: but my working size is 56kb and the new one was stalled at 4kb or something) which might be a symptom of the whole extension thing falling over

**Comment by gwarser** [comment]
> closed, renamed the relevant`profile/storage/moz-extension+++UUID` folder (to simulate it being missing), and restarted

You should not leave it in storage folder, move it somewhere else. (Firefox storage is very fragile).

**Comment by Thorin-Oakenpants** [comment]
> You should not leave it in storage folder, move it somewhere else. (Firefox storage is very fragile)

👍 Excellent - never thought of that (just renaming in the past has worked for me)

So I repeated the test, this time I deleted the IDB data (while closed). On restart clearURLs recreated the IDB data: the size is identical: I assume this is using the bundled base ruleset in 1.16 and no updates to it are needed/available

**Comment by Pilford** [comment]
Problem is fixed. Thanks!

**Comment by Thorin-Oakenpants** [comment]
^^ I don't think the updating is fixed re OCSP: but the symptoms might be. Which means you might find clearURLs deactivates itself? with a warning? IDK exactly what the logic is here re updates and the canary etc. Testing with 1.16 there wouldn't be any new updates to get, and the gitlab ticket for OCSP is still open.

**Comment by KevinRoebert** [comment]
> ^^ I don't think the updating is fixed re OCSP: but the symptoms might be. Which means you might find clearURLs deactivates itself? with a warning? IDK exactly what the logic is here re updates and the canary etc. Testing with 1.16 there wouldn't be any new updates to get, and the gitlab ticket for OCSP is still open.

That's right. I have "soothed" the symptoms for now. There is nothing I can do about the missing OCSP stapling. We'll have to wait for GitLab to confirm that. I also enabled GitHub Pages (https://kevinroebert.github.io/ClearUrls/data/data.min.json), they have OCSP stapling, but GitHub can't automatically get the hash files generated by GitLab CI ;(

**Comment by Thorin-Oakenpants** [comment]
closing this: Kevin has any refinements (and gwarser to remind him) for any further improvements

Thanks Kevin: regarding OSCP, and sorry if I haven't re-looked up the release changes - but I assume if the update fails, then the user is alerted to the fact? That is the ext stays loaded, but had a red badge/warning? Can you detect off-line mode (gwarser's issue) vs other failures (e.g you can ping but can't get an update therefore it's OSCP?) to be more specific in the alert/notice?

Anyway, thanks for soothing the symptoms :kiss:
