### ISSUE TITLE
Question about 1203: security.ssl.disable_session_identifiers

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#907]
What does mean, if I set `security.ssl.disable_session_identifiers` to `false`?
I do not use FPI, but I am using TC in Auto mode.

Just for info: I have cases where I need to use USB Token with client certificate, but it doesn't work when `1203` is set to `true`.

Thank you a lot
Cheers

**Comment by rusty-snake** [comment]
I suggest to set `security.ssl.disable_session_identifiers` to `false` if you 
 - use auto TC and/or FPI 
 - `privacy.clearOnShutdown.cache` (IIRC)
 - `network.cookie.cookieBehavior` 0 or 4

because
 - better performance (no continuous renegotiation of the ssl session)
 - no real privacy improvement since you are already identifiable
 - restart / cpd / new container reset this

**Comment by crssi** [comment]
I though so too, but better to ask than be sorry. 😄 

Thank you @rusty-snake  for clarification.
