### ISSUE TITLE
privacy.resistFingerprinting.letterboxing, false | Bug?

### ISSUE THREAD

**Issue by zdat** [ghacksuserjs/ghacks-user.js#908]
Was messing around with the letterboxing pref and test sites (AmIUnique, Panopticlick). I noticed something strange.

With the user.js inserted into a stock firefox and `privacy.resistFingerprinting.letterboxing, false` (letterboxing disabled), the detected screen/window heights are reduced by 74 pixels.

Example (tested with AmIUnique & Panopticlick, tested 2 different screen resolutions w/ maximized windows):

- Stock Firefox
Screen w/h is detected as 1920x1080, available w/h is detected as 1920x1040.
- User.js inserted, `privacy.resistFingerprinting.letterboxing, false`
Screen w/h is detected as 1920x1006, available w/h is detected as 1920x966; both reduced by 74 pixels.

Is this a bug? With letterboxing disabled it _should_ be the same as stock firefox, no? This is surely making people who disable letterboxing more fingerprintable than they need to be?

**Comment by Thorin-Oakenpants** [comment]
- LB'ing only controls the **inner window**
- to protect **outer window**, **screen** and **available screen**, you need RFP (which then reports those the same as the inner window)

Panopticlick is measuring screen, so LBing is immaterial

**Comment by zdat** [comment]
>* LB'ing only controls the **inner window**

Ok so if I disable letterboxing my inner window measurement should be the same as a stock firefox, right? It's not. The height is 74 pixels less.

>* to protect **outer window**, **screen** and **available screen**, you need RFP (which then reports those the same as the inner window)

RFP is not reporting these as the same when letterboxing is disabled. It's 74 pixels less than a stock firefox though.

Can you test this or help me understand better?

**Comment by zdat** [comment]
Oh... the outer window is being protected with RFP, but the inner window is exposed which is why it's giving weird numbers? Honestly I can't quite get my head around it at the moment.

**Comment by crssi** [comment]
What happens when you start brand new profile + ghacksuser.js? Are the results the same?

**Comment by Thorin-Oakenpants** [comment]
> my inner window measurement should be the same as a stock firefox, right

WTF is a stock Firefox? There is no such thing. The **inner window is always exactly what it is** - no-one lies about it, because things need to rely on it to display properly (and there are too many ways to get measure it, and if you play with it you just break things). LBing adjusts the inner window to a different size, but the actual inner window measurements are exactly what they are

> Ok so if I disable letterboxing ... The height is 74 pixels less.

WTF are you measuring? Are you maximized? Are you full-screen? Are you windowed? Is RFP on? The height of **what** is 74 pixels less .. than  the height of **what**?

I can't make any sense of what you're asking, because you're not giving precise instructions or enough detail. Just use TZP to see what affects what: it updates in real time
