### ISSUE TITLE
Firefox does not focus when opening links from other applications.

### ISSUE THREAD

**Issue by arksunix** [ghacksuserjs/ghacks-user.js#915]
I can not find the setting responsible for this. Before installing ghacks-user.js, when I clicked on a link in another application, I was automatically switched into Firefox and the desired page opened there. Now I must to switch to a window with Firefox and manually open the tab that appears. This is very annoying, how can I change this? I tried to create a clean profile and there works as I need. I tried to disable all add-ons, this did not help. The console is empty. I am using Firefox 74.0 and Arch Linux with bspwm. _Sorry for my English, I am using Google Translate_.

**Comment by Thorin-Oakenpants** [comment]
There shouldn't be anything in the user.js that changes your default application for various types: e.g html links - that said, I'm not very knowledgeable about Linux, let alone Arch

This is my best guess: default application settings: I'm sure you're pretty technically competent  - go to  Options/Settings > General .. what does it say about Firefox being your default browser?

here's mine on windows
![default](https://user-images.githubusercontent.com/16656956/77980593-2e730580-72f7-11ea-840e-17fa981916e6.png)

Now mine is a portable version and is actually set as the default, but Firefox doesn't know that because the default app is not firefox.exe but a launcher executable. That shouldn't be the case for you on Linux

On Linux, just make sure that Firefox is set as your default (however you do that in Linux). You don't need the "always check if Firefox is your default" - it's just a check - but if you want it on, it's the pref numbered `0101`

Other than that, since it seems to be a pref: the easiest way to find the cause is the binary method of [troubleshooting](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting#small_orange_diamond-manual-troubleshooting)

**Comment by Thorin-Oakenpants** [comment]
I'm also having a hard time understanding exactly what the issue is.

- In another app you click a link
- before
   - firefox would open, or if already open, would get focus, and the link would open in a new tab
- now
  - nothing happens? no messages from Arch OS?
  - you then have to select Firefox (if open) and then what? How do you open the link - copy it from the other application and paste it to a new tab?
  - or do you mean it's already opened, but doesn't have focus? Is it Firefox is not focused, or the tab you just opened the new link in is not selected and is a background tab?

**Comment by atomGit** [comment]
very recently a change was made to FF to the handlers/file associations - where before all file types were associated to different programs/commands, now it appears some stuff is associated with the system handler - you can find this in preferences -> general -> applications

i suspect your problem might lie there rather than in prefs/user.js

i run Manjaro (Arch for dummies) and i don't have the problem

try renaming handlers.json and restart FF - if that doesn't work, then you may have another problem similar to what happened to me before in which case i'll try to help further

**Comment by atomGit** [comment]
WAIT A MINUTE - are you saying that firefox loads the link but just does not come to the foreground? if that's the case, then what is `browser.tabs.loadDivertedInBackground` set to?

**Comment by Thorin-Oakenpants** [comment]
^^ Yeah, unfortunately it's not fully clear exactly what the problem is: but the user.js doesn't have that pref. Reading OP for the fourth time, it certainly sounds like he means the tab doesn't open in the foreground (and/or Firefox doesn't get focus, which would be an OS thing I guess)

**Comment by arksunix** [comment]
> WAIT A MINUTE - are you saying that firefox loads the link but just does not come to the foreground? if that's the case, then what is `browser.tabs.loadDivertedInBackground` set to?

Yes that's it. Thank you very much. The problem was not in user.js, but in user-overrides.js. This is strange because I checked all the settings in this file and changed them for myself (I took user-overrides.js from 12bytes). Now I am ashamed because of my carelessness, sorry guys.

**Comment by atomGit** [comment]
hehe - looks like it's all my fault :)
sorry pants
