### ISSUE TITLE
FYI: dom.IntersectionObserver.enabled = false = images not loading

### ISSUE THREAD

**Issue by Just-me-ghacks** [ghacksuserjs/ghacks-user.js#919]
Images on a popular website in my country don't load with `user_pref("dom.IntersectionObserver.enabled", false);`

AFAIK it's a very bad idea to enable this API. I will keep it disabled and only flip it when I need that particular site.

Not sure if we need [SETUP-WEB] tag for easier troubleshooting.

Pants, let me know if you want to have a look at the URL.

**Comment by rusty-snake** [comment]
What i thought so far was that switching off this api does not help a lot, because websites can get this information in other ways.

**Comment by crssi** [comment]
I guess its not worth to enable and set to false, otherwise Pants and E wouldn't disabled it.

**Comment by Thorin-Oakenpants** [comment]
FYI it can also break extensions: such as uBOs panel
- see `https://github.com/uBlockOrigin/uMatrix-issues/issues/235` 

It's inactive for a reason. Because it breaks stuff. It doesn't need a setup tag, because it's inactive. And it helps websites detect positioning (rather than use old hacky methods).

I left it in the user.js for those who want to harden, and as a reminder to myself (I have local test I've been working on) but at the end of the day, there's nothing here AFAICT (that can't be gotten other ways) or that it leaks anything not available anywhere else.

And there's a Tor ticket still open about it (but I doubt anything will ever be done to investigate it, it's been three years - and it seems zero risk) - the answer is to disable JS if your threat model calls for it

**Comment by iWARR** [comment]
Just leave my setting here:

```
// 2426 : Intersection Observer API = [ Enabled ]
/*			The visibility and position of target DOM elements relative to an intersection root.
	[NOTE] 		Websites can use this API to recognize an ad blocking activity down to a pixel level.
	[WARNING]	DON'T DISABLE THIS!
			• This will hardly break showing preview tiles on eShops, devianart.com, etc.
			• This can break extensions, such as uMatrix panel.
			• In the past it also produced a numerous crashes.
	[1]		https://github.com/ghacksuserjs/ghacks-user.js/issues/919
	[2]		https://developer.mozilla.org/docs/Web/API/Intersection_Observer_API
	[3]		https://w3c.github.io/IntersectionObserver/
	[4]		https://bugzilla.mozilla.org/1243846     */
//	user_pref("dom.IntersectionObserver.enabled", false);
```
