### ISSUE TITLE
Firefox 75.0 - AS top sites can still populate urlbar dropdown

### ISSUE THREAD

**Issue by desk7** [ghacksuserjs/ghacks-user.js#922]
Firefox 75.0 introduced a new "feature": Top sites now appear when you select the address ([here](https://www.mozilla.org/en-US/firefox/75.0/releasenotes/))

So, I suggest to add the pref:
`user_pref("browser.newtabpage.activity-stream.default.sites", "");`
to avoid sites to appear.

**Comment by Thorin-Oakenpants** [comment]
Go to about:preferences#home and untick Top Sites

I tested in a vanilla FF75 (haven't even loaded a web page). The activity stream (AS) landing page has some pre-loaded top sites like youtube, etc. Clicking in the urlbar auto-shows theses.

Still using AS as the home page - by unchecking top sties as a display item, they no longer show in the urlbar dropdown.

```js
/* 0105: disable Activity Stream stuff (AS)
 * AS is the default homepage/newtab in FF57+, based on metadata and browsing behavior.
 *    **NOT LISTING ALL OF THESE: USE THE PREFERENCES UI**
 * [SETTING] Home>Firefox Home Content>...  to show/hide what you want ***/
```

What I need to test is when the newtab/home-page set to something else (blank page, extension controlled), does the urlbar show "top sites"

**Comment by Thorin-Oakenpants** [comment]
> What I need to test is when the newtab/home-page set to something else (blank page, extension controlled), does the urlbar show "top sites"

The answer is yes

**Comment by Thorin-Oakenpants** [comment]
Actually, I'm not sure if this is the right way to go about it: re-opening

- what populates "top sites" - I mean it's not a static default list - I'm assuming this is driven by history
- users may very well **want** their top sites as suggestions
- there is another option `browser.urlbar.openViewOnFocus` which I have Q's about
   - is that just on "focus" and doesn't stop the listing of top sites when you start typing
   - what happens when you click the dropdown arrow
   - the pref will probably be removed, but I'd have to check

I also don't see this as a privacy, security, tracking, FPing issue: it's a user choice - but it does fit with a shoulder-surfers aspect (e.g. 0850s).

Anyone with any spare time, please feel free to investigate

**Comment by Thorin-Oakenpants** [comment]
OK, `browser.urlbar.openViewOnFocus`, will be removed, see [1627989](https://bugzilla.mozilla.org/show_bug.cgi?id=1627989)

I guess OP's pref would be the long term solution. I wonder how it works when you have your own top sites: do the default ones falls off if unused? What happens when you clear history - do the default one's pop back up? Rhetorical, not really interested TBH.

Top Sites has nothing to do with the objective of this user.js: not a privacy, FPing, tracking, security concern. Closing

**Comment by Thorin-Oakenpants** [comment]
@desk7 .. see #967
