### ISSUE TITLE
[Informational] fix resistfingerprinting & youtube video white bottom half

### ISSUE THREAD

**Issue by bitpixl** [ghacksuserjs/ghacks-user.js#924]
It seems as of today [april 10th 2020] Youtube is projecting a white bar on the bottom half of youtube video's if you have "privacy.resistFingerprinting" set to "true". (tyvm google...)

I spotted a fix on [reddit](https://www.reddit.com/r/firefox/comments/fy6l1z/youtube_borked_with_new_firefox/fmytbrw/) and thought it might be useful to post the fix (requires UBO) here as well.

Add this filter to Ublock Origin: `www.youtube.com##.ytp-gradient-bottom`

I suspect this will be quickly fixed with updated filter lists, so feel free to remove/close if it's out of scope.

**Comment by atomGit** [comment]
i noticed this yesterday and thought it was my 'make the whole damn web dark and stop bloody blinding me or else' add-on

thanks for the tip

for those using CSS injection add-on (Stylus) ...
```css
/* fat white bar on bottom half of videos on mouse-over, pause */
.ytp-gradient-bottom {
    display: none;
}
```
bonus tip...
to disable YT's "polymer" which is slow as hell and apparently uses a depreciated API because they hate Firefox, you can do this with some sort of redirect add-on (Redirector)...
```
 Description: YouTube disable polymer 
Example URL: https://www.youtube.com/watch/?v=somevideo
Include pattern: https:\/\/www\.youtube\.com\/(?!.*disable_polymer=true$)(.*\?.*)
Redirect to: https://www.youtube.com/$1&disable_polymer=true
Pattern type: Regular Expression
```

**Comment by theltalpha** [comment]
Hallo! Thank you, @bitpixl! I was going crazy about this for one hour because I thought I accidentally hit some shortcut on the keyboard. Good to know I am not alone. I tried the uBlock Origin solution, but it does not work for me. I am not sure if I am applying this correctly: I copy www.youtube.com##.ytp-gradient-bottom and paste it on a line in the "My filters" tab of the uBlock Origin settings. Then I click on "Apply changes". But the white bottom on Youtube is still there, even when closing and restarting Firefox. Am I applying the fix in a wrong way or do you have any other idea why this isn't working for me?

**Comment by bitpixl** [comment]
@theltalpha I'n not sure why it's not working on your end, maybe you can try putting that line at the top of the "my filters" tab/list or try with a fresh profile with just user.js+ubo? If you keep having problems I think it's probably best asking in the reddit link I posted or maybe try the UBO forums.

**Comment by gwarser** [comment]
@theltalpha make sure cosmetic filtering is enabled on YT (eye icon in uBO popup).

**Comment by theltalpha** [comment]
> @theltalpha make sure cosmetic filtering is enabled on YT (eye icon in uBO popup).

That was it! I had globally de-activated cosmetic filtering as per [12bytes' uBlock Origin Suggested Settings](https://12bytes.org/articles/tech/ublock-origin-suggested-settings) and activated it now as per site setting for Youtube. Excellent, thank you!

**Comment by gwarser** [comment]
> I had globally de-activated cosmetic filtering as per [12bytes' uBlock Origin Suggested Settings](https://12bytes.org/articles/tech/ublock-origin-suggested-settings)

What is the point?

**Comment by atomGit** [comment]
from the uBO pop-up...

> Generic cosmetic filters are those cosmetic filters which are meant to apply on all web sites.
> 
> Though handled efficiently by uBlock₀, generic cosmetic filters may still contribute measurable memory and CPU overhead on some web pages, especially for large and long-lived ones.

**Comment by gwarser** [comment]
@atomGit unrelated, this filter is "specific" - it works specifically on `www.youtube.com`.

**Comment by atomGit** [comment]
with Stylus you can apply css per domain also - i do it this way only because i don't want to enable cosmetic filtering in uBO which, in turn, enables those filters in all the filter lists that one uses that includes cosmetic filters

that said, i don't actually know whether the performance hit is less with css injection or not - i never tested

**Comment by Thorin-Oakenpants** [comment]
FF nilla (nightly if you must know), set RFP on, restarted for good measure, no extensions and loaded up some TayTay
- https://www.youtube.com/watch?v=Dkk9gvTmCXY - Taylor Swift: You Need to Calm Down
- everything works as expected, no white canvas overlay BS
- see https://bugzilla.mozilla.org/show_bug.cgi?id=1628947 

Still, it's not hard to detect RFP (even if canvas wasn't a tell-tale 10x10 white) and penalize users - not that I'm saying that's why google did it - maybe it was an A/B test ... 👌 👃 (my attempt at saying fuck knows (nose) using emojis)

That reddit poster recommending turning off RFP was a joke. They do the same thing for people asking about why their version says 68 and they can't install an extension from AMO ... instead of telling them how to bypass it, etc.

Closing. Speak up if I missed anything

**Comment by gwarser** [comment]
> That reddit poster recommending turning off RFP was a joke. They do the same thing for people asking about why their version says 68 and they can't install an extension from AMO ... instead of telling them how to bypass it, etc.

They are just tired by people asking the same thing every few days again and again.

**Comment by Thorin-Oakenpants** [comment]
> They are just tired ~~by~~ of people asking the same thing every few days again and again

They should know better. Anyway .. who enjoyed the TayTay vid?

**Comment by TerekMoL** [comment]
When Firefox works with pref privacy.resistFingerprinting:true it opens the browser in the window 1000x891. Because of this, youtube displays the video player as in theatrical mode (but this is not):

<details> <summary> Screenshot </summary>

![arg](https://user-images.githubusercontent.com/67173311/85200196-d4c21c00-b2e4-11ea-92e8-d772f5eb4d1f.jpg)

</details>

Is there any way to do so it would be displayed as in old youtube layout?

<details> <summary> Screenshot </summary>

![arg2](https://user-images.githubusercontent.com/67173311/85200247-469a6580-b2e5-11ea-939f-f1675c30a8d6.jpg)

</details>

**Comment by atomGit** [comment]
you can override that part of RFP globally with `privacy.resistFingerprinting.letterboxing`, which is what i do, but this makes one more susceptible to fingerprinting

if you want a youtube specific solution, i suppose you could try one of the many youtube add-ons or, perhaps better (safer), write your own CSS in userContent.css

**Comment by TerekMoL** [comment]
> you can override that part of RFP globally with `privacy.resistFingerprinting.letterboxing`, which is what i do, but this makes one more susceptible to fingerprinting

I dont want to messup with privacy.resistFingerprinting. I am already used to it.

> if you want a youtube specific solution, i suppose you could try one of the many youtube add-ons or, perhaps better (safer), write your own CSS in userContent.css

Not one of the addons did not help. I searched the whole AMO. CSS script does not exist either. I tried to write my own but I didn't succeed. So far, I have rewritten the code of one of the addons and use this last method to view youtube in old layout. But this is a matter of time until google blocks it. :(

**Comment by atomGit** [comment]
just for kicks you could try disabling whatever YT add-on you're using and load [this](https://www.youtube.com/watch?v=FVwtTrlPSSk&disable_polymer=true) video and see what happens - appended to the URL is the `&disable_polymer=true` parameter ... if that works for you, you can use a [redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/) add-on to make that permanent

**Comment by atomGit** [comment]
let me also throw this in here in case it might be of interest...

[Privacy Redirect](https://addons.mozilla.org/en-US/firefox/addon/privacy-redirect/)

the problem with the Invidious instances is that they aren't always reliable - instances come and go or can take a long time to load or don't always work with certain videos, but it does offer a substantial privacy boost

**Comment by TerekMoL** [comment]
Im used before script like this:

```
var url = window.location.href;
if (url.indexOf("disable_polymer") === -1) {
  if (url.indexOf("?") > 0) {
    url += "&";
  } else {
    url += "?";
  }
  url += "disable_polymer=1";
  window.location.href = url;
}
```
Not work properly anymore. Now i have addon that just change useragent for youtube only. Works fine. For now. But already need to look for a replacement with normal polymer displaying.

Privacy Redirect addon use invidio.us site with youtube links only. This is not privacy at all. Video is still uploaded from google servers.

**Comment by atomGit** [comment]
the default method for viewing YT videos with Privacy Redirect bypasses youtube.com, so it is better for privacy since all the tracking/JS from youtube is avoided, however you still have to connect to google to get the video

if you enable proxy mode, then you bypass both youtube and google, however i really don't recommend that unless you donate to the service since this adds a lot to bandwidth costs

but yes, either way, the Invidious instances are sometimes slow and less than reliable
