### ISSUE TITLE
5000: browser.altClickSave

### ISSUE THREAD

**Issue by desk7** [ghacksuserjs/ghacks-user.js#929]
I suggest to add the following  to PERSONAL section:
`user_pref("browser.altClickSave", true);`

The preference browser.altClickSave controls whether clicking a link while holding the alt key starts the download of that link.

See **Save Focused Link** in https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

**Comment by Thorin-Oakenpants** [comment]
I'd rather not keep adding things to personal - especially when it comes to modifier keys (alt/shift/control/command) since RFP could possibly cause issues. I'm wary of ending up with having to deal with issues like the one mentioned in `2402` - where that pref and middlemouse and autoscroll combined sent @gwarser on a  [mission](https://bugzilla.mozilla.org/1528289)

Also, have you checked the behavior would be the same on all platforms - I see the link has options to view the shortcuts per platform and version. That's another thing I'm wary of now: cross platform differences.

BTW, that's a great link 👍  .. I just added it to the [Wiki References](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B---References)

**Comment by rusty-snake** [comment]
> The preference browser.altClickSave controls whether clicking a link while holding the alt key starts the download of that link.

Linux same behaviour.

**Comment by gwarser** [comment]
> Linux: same behaviour.

For me it interferes with window dragging shortcut.

**Comment by rusty-snake** [comment]
KDE? Only if you move the mouse or already when you click?

**Comment by gwarser** [comment]
KDE Manjaro, cursor changes to drag arrows (cross) on click. Can be different on clean system - I recall changing some prefs related to this.

**Comment by Thorin-Oakenpants** [comment]
I checked the various OS options on the link, and for that pref they all indicated the behavior is exactly what the pref is called on all platforms. But that's never the full story: as evidenced by gwarser. And our users are likely to fiddle with prefs. So, yeah, closing - I can do without any potential issues - great link though - I should use more of them
