### ISSUE TITLE
Comprehensive referer testing tool

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#934]
The current referer testing tool in Appendix A does not properly check the JavaScript referer.

I found a tool that does:  http://www.zeigen.com/refer/

Do you know of any tools that check both the HTTP and the JavaScript referers?

**Comment by rusty-snake** [comment]
browserleaks check both, but on different pages.

HTTP: https://browserleaks.com/ip
JS: https://browserleaks.com/javascript

**Comment by Gitoffthelawn** [comment]
@rusty-snake Thanks.  Showing both on a single page would be better, and their HTTP test doesn't indicate no referer explicitly... you just have to notice that it's missing from the headers.   Do you happen to know of any others?

**Comment by geeknik** [comment]
https://www.darklaunch.com/tools/test-referer looks useful-ish.

**Comment by rusty-snake** [comment]
@geeknik this test for different types (css, image, ...) the HTTP-Referer. @Gitoffthelawn is looking for a tool that supports JS and HTTP referer on one page (same-origin or cross-origin) as I get.

**Comment by Thorin-Oakenpants** [comment]
FYI: [1601496](https://bugzilla.mozilla.org/show_bug.cgi?id=1601496) .. watch the gif .. but I can't replicate (vanilla Nightly)

**Comment by Thorin-Oakenpants** [comment]
> The current referer testing tool in Appendix A does not properly check the JavaScript referer.

note: practically vanilla profile, no extensions, nightly

When I search for "zeigen's referrer test" in google and click the link for http://www.zeigen.com/refer/ - the page tells me the `document.referer` is `https://www.google.com/`

When I search for "dark launch test referer headers" in google and click the link for https://www.darklaunch.com/tools/test-referer - I get the same results as if I just pasted the link into a new tab. **But I wasn't expecting this page to tell me that** - or is it meant to, otherwise it isn't broken?

Call me thick, but I've never been interested in headers and referers: but I just don't quite "get" that dark launch page. It says `form`, `image`, `script` and `javascript` but all I see is 4 tests: two "links" (whatever that means) and two "forms". Then are four test buttons you can click (excluding the one at the top to retest all). What's the difference? I don't see any images? So fucking confusing (to the layman: count me in that bracket)

**Comment by FatOrangutan** [comment]
>When I search for "zeigen's referrer test" in google and click the link for `http://www.zeigen.com/refer` - the page tells me the document.referer is `https://www.google.com/`

That page is showing you the referer that was sent when you requested the document `http://www.zeigen.com/refer/`.

>When I search for "dark launch test referer headers" in google and click the link for `darklaunch.com/tools/test-referer` - I get the same results as if I just pasted the link into a new tab. But I wasn't expecting this page to tell me that - or is it meant to, otherwise it isn't broken?

That page isn't showing you how you arrived at that page. Each of the 4 black boxes on that page is an iframe, and each iframe displays the header sent when requesting that particular iframe.

**Comment by Thorin-Oakenpants** [comment]
^^ That's my point. Dark Launch is not meant to be showing you what Zeigen does, but OP says Dark Launch is **broken** in this regard and then links to Zeigen as one that does work: quote me "But I wasn't expecting this page to tell me that" - so that was all aimed at OP :)

As for the 4 black boxes = 4 iframes, I get that. But where are the `images`, `scripts`, `javascripts`, `forms`. Sure, I see two things labeled forms, but the rest is confusing

**Comment by FatOrangutan** [comment]
> As for the 4 black boxes = 4 iframes, I get that. But where are the images, scripts, javascripts, forms. Sure, I see two things labeled forms, but the rest is confusing

I didn't know the answer to that, which is why I had deleted my comment. Seems like you had already received it by then though :)

**Comment by Thorin-Oakenpants** [comment]
@FatOrangutan Ahh, OK. I get all comments sent to my email when they are posted. When I replied, your message was actually still here on github - i.e I don't "see" deleted posts.

As for my question about dark launch, I might just invoke Cunningham's Law
