### ISSUE TITLE
2608 is now false by default

### ISSUE THREAD

**Issue by WhyNotHugo** [ghacksuserjs/ghacks-user.js#950]
> /* 2608: disable remote debugging
>  * [1] https://trac.torproject.org/projects/tor/ticket/16222 ***/
> user_pref("devtools.debugger.remote-enabled", false);

Looks like the default for this setting (on Firefox 76.0.1) is `false`, so it's not really needed on Firefox 76+ (might be worth adding a comment for that).

**Comment by Thorin-Oakenpants** [comment]
Yeah. It hasn't been true since at least FF60, if ever. Not entirely sure why we have it active - probably to ensure a reset state between restarts

@earthlng what are your thoughts? We can add a `// [DEFAULT: false]`, but I think we could also make it inactive: if someone is using remote debugging, then they probably don't need us resetting it.

**Comment by earthlng** [comment]
> probably to ensure a reset state between restarts

that's my understanding as well.

FYI it's not just for remote debugging but also to get access to the "Browser Toolbox" and the "Browser Content Toolbox".

IDK if there's actually a risk of someone remotely accessing one's FF though.
Since it's default false it doesn't hurt to forcibly set it (back) to false on every FF startup.
If we don't have it active then we might as well remove it completely. I'd just add the default tag.

**Comment by geeknik** [comment]
> IDK if there's actually a risk of someone remotely accessing one's FF though.

Zero as long as `devtools.debugger.force-local` remains set to `true` which is [the default](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_Desktop) for this very reason.

**Comment by Thorin-Oakenpants** [comment]
Mine was true in my nightly :) But stuffed if I could actually get a connection to my Firefox .. that was about 6 months ago, so "there was this one time, at pants camp ... and it got left on" .. so yeah. 

Now that I think of it, it was that FF68 incompatibility with 69+ - which is #943  (I wanted the console when running scripts on android for debugging purposes) which @hunkjazz mentioned. I wonder how much longer before preview hits stable

**Comment by WhyNotHugo** [comment]
Thanks! :)
