### ISSUE TITLE
[correction] 'extensions.autoDisableScopes' defaults to 11 on linux

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#960]
... or at least Arch/Manjaro it does

**Comment by rusty-snake** [comment]
Fedora has 0 as default :confused: .

For Arch I point you to that PKGBUILD line:
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/firefox#n166

**Comment by atomGit** [comment]
oh, if that's being set in pkgbuild than it could potentially be different for every distro???

if that's the case than maybe a note should be added to 'extensions.autoDisableScopes' to inform that 15 is a Windows default

**Comment by Thorin-Oakenpants** [comment]
This is like #952 - arch blanked a hidden pref -> issues. AFAIK, the `Firefox` default for all OSes is 15 (i.e if you get the linux build directly from Mozilla and unpack it) - if I get time, I can check my VMs

Sure, I get that Linux distros package their own, and they modify stuff (that's what prefs are for). Potentially every pref has this same issue.

We've had this convo before, which is why `2660` has a `[setup-chrome]` tag. So I'm not sure what anyone expects me to do here

**Comment by atomGit** [comment]
> AFAIK, the Firefox default for all OSes is 15 (i.e if you get the linux build directly from Mozilla and unpack it)

that makes obvious sense - i didn't think of that

not sure if you wanted this closed so i'll leave it up to you

**Comment by Thorin-Oakenpants** [comment]
leave it open, I might get around to checking my Linux VMs where I have hundreds of unpacked FF's lying around

**Comment by rusty-snake** [comment]
FWIW: Fedora uses this overrides. The most are removed (in the last 10 years!) from firefox, but this appera on about:conifg.

<details><summary> firefox-redhat-default-prefs.js </summary>

```javascript
pref("app.update.auto",                     false);
pref("app.update.enabled",                  false);
pref("app.update.autoInstallEnabled",       false);
pref("general.smoothScroll",                true);
pref("intl.locale.matchOS",                 true);
pref("intl.locale.requested",               "");
pref("toolkit.storage.synchronous",         0);
pref("toolkit.networkmanager.disable",      false);
pref("offline.autoDetect",                  true);
pref("browser.backspace_action",            2);
pref("browser.display.use_system_colors",   true);
pref("browser.download.folderList",         1);
pref("browser.link.open_external",          3);
pref("browser.shell.checkDefaultBrowser",   false);
pref("network.manage-offline-status",       true);
pref("extensions.shownSelectionUI",         true);
pref("ui.SpellCheckerUnderlineStyle",       1);
pref("startup.homepage_override_url",       "");
pref("browser.startup.homepage",            "data:text/plain,browser.startup.homepage=https://start.fedoraproject.org/");
pref("browser.newtabpage.pinned",           '[{"url":"https://start.fedoraproject.org/","title":"Fedora Project - Start Page"}]');
pref("geo.wifi.uri", "https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY%");
pref("media.gmp-gmpopenh264.provider.enabled",false);
pref("media.gmp-gmpopenh264.autoupdate",false);
pref("media.gmp-gmpopenh264.enabled",false);
pref("media.gmp-gmpopenh264.enabled",false);
pref("plugins.notifyMissingFlash", false);
/* See https://bugzilla.redhat.com/show_bug.cgi?id=1226489 */
pref("browser.display.use_system_colors", false);
pref("layers.use-image-offscreen-surfaces", false);
/* Allow sending credetials to all https:// sites */
pref("network.negotiate-auth.trusted-uris", "https://");
pref("spellchecker.dictionary_path","/usr/share/myspell");
/* Disable DoH by default */
pref("network.trr.mode",                    5);
/* Enable per-user policy dir, see mozbz#1583466 */
pref("browser.policies.perUserDir",         true);
pref("browser.gnome-search-provider.enabled",true);
```

</details>

**Comment by Thorin-Oakenpants** [comment]
```
pref("browser.startup.homepage", ...
pref("browser.newtabpage.pinned", ...
```

I hate shit like that. They're already using your OS. Just add a bookmark

**Comment by 4ut0-M-4t** [comment]
Ubuntu/Lubuntu/Xubuntu version is shipped with `extensions.autoDisableScopes = 3`, while TB defaults to `0`.

**Comment by Thorin-Oakenpants** [comment]
TB disabledScopes at 0 seems a bit odd (been that value since at least ESR60). I know acat had to change enabledScopes from 1 to 5, like we did (this was due to a change in FF68 that broke system xpis: e.g. the built in dark theme, built in search engines lost icons, etc)

So if I understand that correctly, TB
- doesn't default deny: they allow all scopes by default - i.e they don't autoDisable anywhere: value 15
- whitelists some scopes at `5`
   - `1` profile scope
   - `4` application scope: extensions directory where the executable is located

That doesn't make sense: @acatarineu

**Comment by atomGit** [comment]
TB defaults to 11 in my case (Manjaro, possibly Arch as well)

**Comment by acatarineu** [comment]
> TB disabledScopes at 0 seems a bit odd (been that value since at least ESR60). I know acat had to change enabledScopes from 1 to 5, like we did (this was due to a change in FF68 that broke system xpis: e.g. the built in dark theme, built in search engines lost icons, etc)
> 
> So if I understand that correctly, TB
> 
>     * doesn't default deny: they allow all scopes by default - i.e they don't autoDisable anywhere: value `0`
> 
>     * whitelists some scopes at `5`
>       
>       * `1` profile scope
>       * `4` application scope: extensions directory where the executable is located
> 
> 
> That doesn't make sense: @acatarineu
> 
> edit: but it also doesn't make sense if they had issues and had to change from 1 to 5? IDK :headspin:

My understanding is that setting `extensions.enabledScopes = 5` is already default denying the scopes that are not profile or application, in the sense that these locations should not be even scanned for addons. With that, I'm not sure we need to set `extensions.autoDisableScopes` to a value other than 0. We could probably set it to `~(SCOPE_USER | SCOPE_APPLICATION)`, but I don't think it would have any effect, given that we have `extensions.enabledScopes = 5`.

**Comment by Thorin-Oakenpants** [comment]
@acatarineu 

This is what I don't understand...
- https://mike.kaply.com/2012/02/21/understanding-add-on-scopes/
   - > `extensions.autoDisableScopes` was introduced in Firefox 8 as part of the effort to crack down on third-party add-ons. It is used to specify the locations from which add-ons will be **disabled by default. The default value for this preference is 15** which means that add-ons are disabled by default in all locations. You may wonder how this works, since the user’s profile directory is one of those locations. **Add-ons are only disabled by default if they were not explicitly installed by the user**. So if an external application places an add-on into the user’s profile directory, it is disabled by default. 

That article is from 2012, Mike Kaply is now at Mozilla, and something may have changed
- the [default](https://dxr.mozilla.org/mozilla-central/search?q=autoDisableScopes&redirect=false) for desktop and mobile seems to be `15`, so TB must have overriden it at some stage for some reason
- why would TB set this as `0` and open up the ability for a third party to side-load an extension?
- IANAE, but side-loading may not be an issue anymore

I still can't access the new tracker, but it's only been 10 days since my email to admin, so sorry for poking at you from here :)

**Comment by acatarineu** [comment]
@Thorin-Oakenpants 

This should be the ticket where it was changed https://trac.torproject.org/projects/tor/ticket/4427. As I expected, setting `extensions.autoDisableScopes = 15` breaks TB bundled extensions (noscript, https-everywhere), since their xpi's are put in the user profile so that they are installed first time on browser startup. We could probably set it to 14, or we could ship the extensions differently (e.g. system addons) and use the default for `extensions.autoDisableScopes` and `extensions.enabledScopes = 4`. But again, AFAIK with the current TB preferences, the only way a third party may be able to side-load an extension is by putting the xpi in the TB profile folder (or modifying TB itself), which means a quite powerful attacker.

> I still can't access the new tracker, but it's only been 10 days since my email to admin, so sorry for poking at you from here :)

Yeah, I think they are still checking the permission system before opening gitlab to external users.

**Comment by rusty-snake** [comment]
> AFAIK with the current TB preferences, the only way a third party may be able to side-load an extension is by putting the xpi in the TB profile folder (or modifying TB itself), which means a quite powerful attacker.

:+1:, if an attacker can add extensions to the TB-profil, he has write access to you to TB. So you are lost anyway.
