### ISSUE TITLE
ui.prefersReducedMotion

### ISSUE THREAD

**Issue by wvxwxvw** [ghacksuserjs/ghacks-user.js#971]
Twice in a document with different values. First it is enabled, and then, according to the instructions for non-RFP users, it is disabled.

**Comment by Thorin-Oakenpants** [comment]
Correct. It's disabled as part of RFP because that comes before the one in RFP alts: so it makes no sense to put it in the 5000's, inactive, and ask users to add it as an override: so it's enabled active be default and does not affect fingerprinting (due to RFP)

But if a user decides to disable RFP and instead they turn on the RFP Alts section, then the second value is applied last, and the fingerprinting is still covered

[how a user.js works](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview#small_orange_diamond-what-is-it-what-does-it-do-and-why-would-i-want-one)
> It parses the `user.js` in the order it is written, i.e if the same preference is listed twice with two different values, the last one will be applied last

**Comment by rusty-snake** [comment]
> /* 4520: disable chrome animations [FF77+] [RESTART]

Where is the FPing/Security?

**Comment by Thorin-Oakenpants** [comment]
Are you asking how PRM is fingerprintable (it is), or why it's included when all the other prefs not in 5000s have some sort of privacy/security/anti-tracking/anti-FPing aspect and this one doesn't?

**Comment by rusty-snake** [comment]
I'm wondering why we need to disable animations for firefox. There is no security issue and I don't see the FPing (as long as RFP is used).

**Comment by Thorin-Oakenpants** [comment]
Because Mozilla tied a chrome setting to a web setting

The pref is already covered by RFP, but if we enforce it as `1` (which leaks with no RFP) then no-one will need to add it **as an override** to disable the megabar etc, which means anyone who then needs to flip on RFP Alts is not compromised

capisce?

**Comment by crssi** [comment]
@Thorin-Oakenpants Is there anything you have not think of at all? 😄 ❤️

**Comment by Thorin-Oakenpants** [comment]
> @Thorin-Oakenpants Is there anything you have not think of at all? 😄 ❤️

I forgot my mom's birthday once .. she's never let me live it down ... 47 years and counting .. `*sigh*`
