### ISSUE TITLE
discussion: sync

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#98]
here's what we currently have

```js
/* 0380: disable sync [SETUP] ***/
user_pref("services.sync.enabled", false); // (hidden pref)
/* 0381: disable WebExtension sync
 * [1] https://wiki.mozilla.org/WebExtensions/chrome.storage.sync ***/
user_pref("webextensions.storage.sync.enabled", false);
user_pref("webextensions.storage.sync.serverURL", "");
```

First of all, we should add [SETUP] to 0381. Now lets talk about this. These settings are useless unless the user has set up an account for syncing. I'm not saying remove them, but lets consider deactivating them.

Also, WE syncing can be used to sync more than just extension preferences. IMO, it can be used by developers to track users across devices.

Class discuss!

**Comment by kaliostro2** [comment]
As for me, it's best to leave it as it is. Those who use synchronization do not even have an idea of the existence of ghack-user.js. Any attempt to leak the data must be terminated. Is not this the philosophy of the project?

**Comment by Thorin-Oakenpants** [comment]
I agree @kaliostro2 . Syncing is bad enough (I know you can choose what to sync, but eek, all your bookmarks in the cloud, among other things - some people have no idea, and others are OK with that). But it really only happens if a user sets up sync. For those who do, the user.js should be more user friendly - because clearly they wanted and chose sync. We shouldn't just then break that choice they made.

Nothing will sync if you don't have a sync account, so deactivated is fine for everyone who doesn't have a sync account (which would be most people using this user.js and setting up hardened versions etc) - so no harm no foul making them deactivated. If you do have a sync account, then currently it just disrupts/breaks syncing and upsets people.

IDK .. whatever I do, I upset people :) I'm now tempted to leave it activated so people learn! :) Wonder what earthlng says

**Comment by earthlng** [comment]
[Remove **services.sync.enabled** preference - VERIFIED FIXED in Firefox 47](https://bugzilla.mozilla.org/show_bug.cgi?id=1213094)

but it's still used at least once [here](https://dxr.mozilla.org/mozilla-central/source/services/fxaccounts/FxAccountsManager.jsm#622)

Either keep 0380 until the code gets cleaned up, then move it to deprecated/removed, or move it already because it's not "supposed" to do anything anymore anyway.
As for the other ones, they definitely don't fit under 0300 because it's not "auto-phoning home".
Because the "phoning home" only happens for users who "clearly they wanted and chose sync"
Due to the controversy maybe we should (if we want to keep it) move it to the Personal Settings.
I'd say commented out so it won't break parts of Sync by default, and the more privacy interested users are more likely to read the user.js in detail and can un-comment it if they feel inclined to do so.
If we wanted to make sure Sync will never do anything we should also be looking at other prefs fe. `services.sync.engine.*` but since we're not doing that (yet?), the 2 prefs feel a bit out of place.

**Comment by RoxKilly** [comment]
@Thorin-Oakenpants  wrote:
> But it really only happens if a user sets up sync. For those who do, the user.js should be more user friendly - because clearly they wanted and chose sync. We shouldn't just then break that choice they made.

@earthlng wrote:
> maybe we should (if we want to keep it) move it to the Personal Settings.
I'd say commented out so it won't break parts of Sync by default, and the more privacy interested users are more likely to read the user.js in detail and can un-comment it

These perfectly match my opinion. Agreed.

**Comment by Thorin-Oakenpants** [comment]
I ~~am~~ was tempted to set up a sync section - i..e create an account and map the UI to about:config and add anything else relevant, most likely as all inactive. The section header would contain a short description. But now I can't be bothered. It's all so common sense (people *should* know what they're doing). Also, @earthlng said sync is being overhauled/changed (unless I misread that).

I'd rather remove them, maybe stick em on the to watch list, and forget about it

**Comment by earthlng** [comment]
> Also, @earthlng said sync is being overhauled/changed (unless I misread that)

you misread that. Idk where you think I said that. I know nothing about Sync except for what I wrote above

**Comment by Thorin-Oakenpants** [comment]
FYI: WE syncing has been archived to items to keep an eye on
