### ISSUE TITLE
Could not parse ASRouter preference

### ISSUE THREAD

**Issue by eleius** [ghacksuserjs/ghacks-user.js#992]
I see this is the console when Firefox starts:

`Could not parse ASRouter preference. Try resetting browser.newtabpage.activity-stream.asrouter.providers.snippets in about:config.`

I have this in the Activity Stream (`0105b`) section:

```
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.asrouter.providers.snippets", "");
```

Using Firefox 79.0-1 in Arch Linux with default ghacks' user.js file.

**Comment by eleius** [comment]
Sorry, had deprecated ASRouter leftovers in my prefs file.

**Comment by eleius** [comment]
I thought the error was caused by stale entries in my prefs.js, but after deleting it and also redownloading user.js I still see that message.

**Comment by Thorin-Oakenpants** [comment]
that seems good
![good](https://user-images.githubusercontent.com/16656956/90256383-2b575c80-de35-11ea-9030-6d532c3800b7.png)

I just tried on Nightly: it's enough to just flip the providers pref and watch the error happen. Even with `browser.startup.page` = `0` (blank page: 0102)

I don't get this at all in my main FF as I used an extension to load a different start/home page: so AS never kicks in

Just ignore the error. Otherwise, anyone feel free to confirm that just parsing the providers doesn't do anything (outbound)

**Comment by Thorin-Oakenpants** [comment]
`{"id":"snippets","enabled":true,"type":"remote","url":"","updateCycleInMs":14400000}` seems to work

**Comment by Thorin-Oakenpants** [comment]
not sure how to put `"` into a string... probably `\` escapes. It seems as if it needs at least one set
- `{"":""}` is the smallest I can seem to get it

**Comment by Thorin-Oakenpants** [comment]
```js
user_pref("browser.newtabpage.activity-stream.asrouter.providers.snippets", "{\"\":\"\"}");
```

**Comment by guser-sudo** [comment]
@Thorin-Oakenpants 
This works for me: `user_pref("browser.newtabpage.activity-stream.asrouter.providers.snippets", "{}");`
Numbers and non-empty strings seem to be ok, too. Letters are not.

**Comment by Thorin-Oakenpants** [comment]
could have sworn I tried that .. just tested and yup, looks good. I'll do a commit
